# 2AFC Constant-Stimuli Psychophysics Analysis

This notebook analyzes a two-alternative forced-choice (2AFC) constant-stimuli experiment, following the relevant perception-analysis structure used by Farajian & Nisky: count matrices of comparison-standard stiffness differences, logistic psychometric curves, PSE, and JND.

**Raw data rule:** set `DATA_ROOT` to the main data folder. The notebook treats it as read-only and writes all outputs to `OUTPUT_ROOT`.

**Important fitting rule:** the raw `answer` column is **not** used directly for fitting. Each trial is first converted into `response_comparison_greater` after determining whether the comparison stimulus was object 1 or object 2.

**Added for this experiment:** success/correctness is analyzed separately from the psychometric response, including answer duration (`time_to_answer`) and fatigue/learning proxies (trial order, elapsed time, first-vs-second half, and early/middle/late bins) per participant and across participants.

## 0. Configuration

Edit `DATA_ROOT`. Keep `OUTPUT_ROOT` outside the raw data folder.

In [1]:
from pathlib import Path
import sys
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Works whether Jupyter's current directory is the project root, analysis/, or this folder.
CWD = Path.cwd()
if (CWD / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD
elif (CWD / "analysis" / "psychophysics_analysis" / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD / "analysis" / "psychophysics_analysis"
elif (CWD / "psychophysics_analysis" / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD / "psychophysics_analysis"
else:
    raise FileNotFoundError("Could not locate twoafc_psychophysics.py. Open the notebook from the project root, analysis/, or analysis/psychophysics_analysis/.")
sys.path.insert(0, str(ANALYSIS_DIR))
import twoafc_psychophysics as pf

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

# Main read-only results folder: P* are pilots, E* are experiment participants.
DATA_ROOT = Path(r"C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\expiriments_results")

# Separate output location. Do not place this inside DATA_ROOT.
OUTPUT_ROOT = ANALYSIS_DIR / "results"
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

STANDARD_FALLBACK = 85.0          # used only as fallback/tie-break anchor
STANDARD_ABS_TOLERANCE = 0.75     # tolerance for classifying the inferred standard
FIG_DPI = 160

# Optional manual column overrides if automatic detection needs help.
# Example: {"object_1_value": "object_1_stiffness", "answer": "answer"}
MANUAL_COLUMN_OVERRIDES = {}

print("ANALYSIS_DIR:", ANALYSIS_DIR.resolve())
print("DATA_ROOT:", DATA_ROOT)
print("OUTPUT_ROOT:", OUTPUT_ROOT.resolve())
if str(DATA_ROOT) == "PUT_MAIN_DATA_FOLDER_HERE":
    print("?? Set DATA_ROOT before running the analysis cells.")

ANALYSIS_DIR: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics_analysis
DATA_ROOT: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\expiriments_results
OUTPUT_ROOT: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics_analysis\results

## 1. File discovery and loading

One folder per subject is expected under `DATA_ROOT`. The code searches each subject folder recursively for files named exactly `answers.csv` only, then saves a discovery audit table.

In [2]:
pf.validate_paths(DATA_ROOT, OUTPUT_ROOT)

file_discovery_summary = pf.discover_answer_files(DATA_ROOT, OUTPUT_ROOT)
pf.save_csv(file_discovery_summary, OUTPUT_ROOT, "file_discovery_summary.csv")
display(file_discovery_summary.head(30))

combined_raw_imported_data = pf.load_selected_subject_csvs(file_discovery_summary)
pf.save_csv(combined_raw_imported_data, OUTPUT_ROOT, "combined_raw_imported_data.csv")
display(combined_raw_imported_data.head())
print("combined raw shape:", combined_raw_imported_data.shape)

,subject_id,subject_folder,candidate_rank,candidate_score,selected,source_file,source_file_name,n_answer_csv_candidates,n_total_csv_files_in_subject_folder,selection_warning
0,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,260,
1,E10,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
2,E11,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,274,
3,E12,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,273,
4,E2,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,266,
5,E3,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,274,
6,E4,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
7,E5,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,276,
8,E6,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,273,
9,E7,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,273,
10,E8,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,274,
11,E9,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,273,
12,P1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1.0,37.0,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,264,
13,P2,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,NaN,NaN,False,,,0,255,no exact answers.csv file found
14,P3,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,NaN,NaN,False,,,0,255,no exact answers.csv file found
15,טספים משני,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,NaN,NaN,False,,,0,0,no exact answers.csv file found

,subject_id,_subject_folder,_source_file,_source_file_name,_row_in_source,timestamp,pair_number,object_1_finger,object_1_stiffness,object_2_finger,object_2_stiffness,time_to_answer,answer
0,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,0,2026-05-09T16:42:37.905766,1,pinky,125,pinky,85,5.438098,0
1,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,2026-05-09T16:43:09.191703,2,pinky,45,pinky,85,3.965589,0
2,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,2,2026-05-09T16:43:41.424086,3,pinky,25,pinky,85,2.604255,1
3,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,3,2026-05-09T16:44:29.923436,4,pinky,165,pinky,85,2.336992,0
4,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,4,2026-05-09T16:44:55.500089,5,pinky,85,pinky,145,2.118856,1

combined raw shape: (3448, 13)

## 2. Column detection and validation

Detects object values, object fingers, answer, reaction time, trial index, timestamp, and optional block columns. Review the detection table; if needed, set `MANUAL_COLUMN_OVERRIDES` above and rerun.

In [3]:
detected_columns, column_detection_details = pf.detect_columns(combined_raw_imported_data, MANUAL_COLUMN_OVERRIDES)
print(json.dumps(detected_columns, indent=2, ensure_ascii=False))
pf.save_csv(column_detection_details, OUTPUT_ROOT, "column_detection_details.csv")
display(column_detection_details.groupby("target").head(5))

missing_required = [k for k in ["object_1_value", "object_2_value", "answer"] if not detected_columns.get(k)]
if missing_required:
    raise RuntimeError(f"Missing required detected columns: {missing_required}. Add MANUAL_COLUMN_OVERRIDES and rerun.")

{
  "object_1_value": "object_1_stiffness",
  "object_2_value": "object_2_stiffness",
  "object_1_finger": "object_1_finger",
  "object_2_finger": "object_2_finger",
  "answer": "answer",
  "reaction_time": "time_to_answer",
  "trial_index": "pair_number",
  "timestamp": "timestamp",
  "block": null
}

             target              column          normalized  score  manual
0    object_1_value  object_1_stiffness  object_1_stiffness     23   False
1    object_1_value  object_2_stiffness  object_2_stiffness      9   False
2    object_1_value     object_1_finger     object_1_finger      6   False
3    object_1_value      _row_in_source       row_in_source      0   False
4    object_1_value        _source_file         source_file      0   False
8    object_2_value  object_2_stiffness  object_2_stiffness     23   False
9    object_2_value  object_1_stiffness  object_1_stiffness      9   False
10   object_2_value     object_2_finger     object_2_finger      6   False
11   object_2_value      _row_in_source       row_in_source      0   False
12   object_2_value        _source_file         source_file      0   False
16  object_1_finger     object_1_finger     object_1_finger     24   False
17  object_1_finger     object_2_finger     object_2_finger     10   False
18  object_1_finger  object_1_stiffness  object_1_stiffness      8   False
19  object_1_finger      _row_in_source       row_in_source      0   False
20  object_1_finger        _source_file         source_file      0   False
24  object_2_finger     object_2_finger     object_2_finger     24   False
25  object_2_finger     object_1_finger     object_1_finger     10   False
26  object_2_finger  object_2_stiffness  object_2_stiffness      8   False
27  object_2_finger      _row_in_source       row_in_source      0   False
28  object_2_finger        _source_file         source_file      0   False
32           answer              answer              answer     10   False
33           answer      time_to_answer      time_to_answer      2   False
34           answer      _row_in_source       row_in_source      0   False
35           answer        _source_file         source_file      0   False
36           answer   _source_file_name    source_file_name      0   False
40    reaction_time      time_to_answer      time_to_answer     13   False
41    reaction_time      _row_in_source       row_in_source      0   False
42    reaction_time        _source_file         source_file      0   False
43    reaction_time   _source_file_name    source_file_name      0   False
44    reaction_time     _subject_folder      subject_folder      0   False
48      trial_index         pair_number         pair_number      8   False
49      trial_index      _row_in_source       row_in_source      0   False
50      trial_index        _source_file         source_file      0   False
51      trial_index   _source_file_name    source_file_name      0   False
52      trial_index     _subject_folder      subject_folder      0   False
56        timestamp           timestamp           timestamp      8   False
57        timestamp      _row_in_source       row_in_source      0   False
58        timestamp        _source_file         source_file      0   False
59        timestamp   _source_file_name    source_file_name      0   False
60        timestamp     _subject_folder      subject_folder      0   False
64            block      _row_in_source       row_in_source      0   False
65            block        _source_file         source_file      0   False
66            block   _source_file_name    source_file_name      0   False
67            block     _subject_folder      subject_folder      0   False
68            block         pair_number         pair_number      0   False

## 3. Trial cleaning and canonicalization

Protocol rows and invalid/ambiguous trials are flagged and saved separately. Valid trials receive `response_comparison_greater` for fitting.

Examples:
- standard object 1, comparison object 2 ? response is 1 when `answer == 1`.
- standard object 2, comparison object 1 ? response is 1 when `answer == 0`.

In [4]:
inferred_standard_value, standard_inference_table = pf.infer_standard_value(combined_raw_imported_data, detected_columns, STANDARD_FALLBACK)
print(f"Inferred standard/reference value: {inferred_standard_value:g}")
pf.save_csv(standard_inference_table, OUTPUT_ROOT, "standard_value_inference.csv")
display(standard_inference_table.head(10))

combined_clean_trials, combined_flagged_trials = pf.canonicalize_trials(
    combined_raw_imported_data,
    detected_columns,
    standard_value=inferred_standard_value,
    standard_tolerance=STANDARD_ABS_TOLERANCE,
)
pf.save_csv(combined_clean_trials, OUTPUT_ROOT, "combined_clean_trials.csv")
pf.save_csv(combined_flagged_trials, OUTPUT_ROOT, "combined_flagged_trials.csv")

print("Clean trials:", combined_clean_trials.shape)
display(combined_clean_trials.head())
print("Flagged trials:", combined_flagged_trials.shape)
display(combined_flagged_trials.head())

Inferred standard/reference value: 85

   candidate_value  count  n_unique_partners  distance_from_fallback  standard_score
0               85   3448                 14                     0.0        1.350000
1               70    360                  1                    15.0        0.120033
2              100    320                  1                    15.0        0.108432
3               25    416                  1                    60.0        0.108150
4              145    416                  1                    60.0        0.108150
5              130    360                  1                    45.0        0.101283
6               40    360                  1                    45.0        0.101283
7              115    320                  1                    30.0        0.099057
8               55    320                  1                    30.0        0.099057
9               65     96                  1                    20.0        0.040342

Clean trials: (3448, 30)

,subject_id,source_file,source_file_name,row_in_source,trial_index_raw,timestamp,block_raw,object_1_value,object_2_value,object_1_finger_raw,object_2_finger_raw,object_1_finger,object_2_finger,standard_value,standard_side,comparison_side,comparison_value,standard_finger,comparison_finger,finger_condition,raw_answer,answer_code,response_comparison_greater,reaction_time,protocol_marker,finger_warning,excluded_from_fit,flag_reason,global_trial_order,answer_chose_object_2
0,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,0,1,2026-05-09T16:42:37.905766,NaN,125,85,pinky,pinky,P,P,85.0,object_2,object_1,125.0,P,P,P,0,0,1,5.438098,False,,False,,1,0.0
1,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,2,2026-05-09T16:43:09.191703,NaN,45,85,pinky,pinky,P,P,85.0,object_2,object_1,45.0,P,P,P,0,0,1,3.965589,False,,False,,2,0.0
2,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,2,3,2026-05-09T16:43:41.424086,NaN,25,85,pinky,pinky,P,P,85.0,object_2,object_1,25.0,P,P,P,1,1,0,2.604255,False,,False,,3,1.0
3,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,3,4,2026-05-09T16:44:29.923436,NaN,165,85,pinky,pinky,P,P,85.0,object_2,object_1,165.0,P,P,P,0,0,1,2.336992,False,,False,,4,0.0
4,E1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,4,5,2026-05-09T16:44:55.500089,NaN,85,145,pinky,pinky,P,P,85.0,object_1,object_2,145.0,P,P,P,1,1,1,2.118856,False,,False,,5,1.0

Flagged trials: (0, 0)

Empty DataFrame
Columns: []
Index: []

## 4. Block and finger detection

Finger labels are normalized to `I`, `M`, `R`, `P`. Block order is inferred from changes in `finger_condition` within each subject.

In [5]:
combined_clean_trials, block_order_summary = pf.add_block_numbers(combined_clean_trials)
pf.save_csv(combined_clean_trials, OUTPUT_ROOT, "combined_clean_trials.csv")
pf.save_csv(block_order_summary, OUTPUT_ROOT, "block_order_summary.csv")
display(block_order_summary.head(30))
display(pd.crosstab(combined_clean_trials["subject_id"], combined_clean_trials["finger_condition"]))

   subject_id  block_number finger_condition  first_global_trial_order  n_trials_in_block
0          E1             1                P                         1                 64
1          E1             2                I                        65                 64
2          E1             3                R                       129                 64
3          E1             4                M                       193                 64
4         E10             1                I                         1                  3
5         E10             2                M                         4                  3
6         E10             3                R                         7                  3
7         E10             4                P                        10                  3
8         E10             5                R                        13                 64
9         E10             6                P                        77                 64
10        E10             7                M                       141                 64
11        E10             8                I                       205                 64
12        E11             1                I                         1                  3
13        E11             2                M                         4                  3
14        E11             3                R                         7                  3
15        E11             4                P                        10                  3
16        E11             5                M                        13                 64
17        E11             6                R                        77                 64
18        E11             7                I                       141                 64
19        E11             8                P                       205                 64
20        E12             1                I                         1                  3
21        E12             2                M                         4                  3
22        E12             3                R                         7                  3
23        E12             4                P                        10                  3
24        E12             5                I                        13                 64
25        E12             6                M                        77                 64
26        E12             7                P                       141                 64
27        E12             8                R                       205                 64
28         E2             1                I                         1                 64
29         E2             2                M                        65                 64

finger_condition   I   M   P   R
subject_id
E1                64  64  64  64
E10               67  67  67  67
E11               67  67  67  67
E12               67  67  67  67
E2                64  64  64  64
E3                67  67  67  67
E4                67  67  67  67
E5                67  67  67  67
E6                67  67  67  67
E7                67  67  67  67
E8                67  67  67  67
E9                67  67  67  67
P1                64  64  64  64

## 5. Success/correctness coding and Farajian-style count matrices

Psychometric fitting uses `response_comparison_greater`. Success-rate analysis asks a different question: did the participant choose the physically stiffer stimulus? This cell adds `correct_response`, signed stiffness deltas, elapsed time, participant group (`pilot`/`experiment`), and fatigue/order proxies.

In [6]:
combined_success_trials = pf.add_success_and_time_columns(combined_clean_trials)
pf.save_csv(combined_success_trials, OUTPUT_ROOT, "combined_success_trials.csv")

farajian_style_input_by_subject_finger = pf.make_farajian_style_psychometric_input(combined_success_trials, ["subject_id", "finger_condition"])
farajian_style_input_group_by_finger = pf.make_farajian_style_psychometric_input(combined_success_trials, ["finger_condition"])
pf.save_csv(farajian_style_input_by_subject_finger, OUTPUT_ROOT, "farajian_style_input_by_subject_finger.csv")
pf.save_csv(farajian_style_input_group_by_finger, OUTPUT_ROOT, "farajian_style_input_group_by_finger.csv")

display(combined_success_trials[[
    "subject_id", "subject_group_label", "finger_condition", "global_trial_order",
    "signed_stiffness_delta", "response_comparison_greater", "correct_response",
    "reaction_time", "elapsed_minutes", "session_half", "fatigue_tertile"
]].head(20))
display(farajian_style_input_by_subject_finger.head(30))

,subject_id,subject_group_label,finger_condition,global_trial_order,signed_stiffness_delta,response_comparison_greater,correct_response,reaction_time,elapsed_minutes,session_half,fatigue_tertile
0,E1,experiment,P,1,40.0,1,1.0,5.438098,0.000000,first_half,early
1,E1,experiment,P,2,-40.0,1,0.0,3.965589,0.521432,first_half,early
2,E1,experiment,P,3,-60.0,0,1.0,2.604255,1.058639,first_half,early
3,E1,experiment,P,4,80.0,1,1.0,2.336992,1.866961,first_half,early
4,E1,experiment,P,5,60.0,1,1.0,2.118856,2.293239,first_half,early
5,E1,experiment,P,6,-20.0,0,1.0,2.327784,2.727673,first_half,early
6,E1,experiment,P,7,20.0,0,0.0,2.093581,3.195846,first_half,early
7,E1,experiment,P,8,-80.0,0,1.0,2.462920,3.594276,first_half,early
8,E1,experiment,P,9,-20.0,1,0.0,2.181055,3.914480,first_half,early
9,E1,experiment,P,10,-40.0,0,1.0,1.959361,4.133198,first_half,early
10,E1,experiment,P,11,40.0,0,0.0,2.337371,4.649966,first_half,early
11,E1,experiment,P,12,-60.0,0,1.0,2.033647,4.902001,first_half,early
12,E1,experiment,P,13,60.0,1,1.0,2.043150,5.367080,first_half,early
13,E1,experiment,P,14,-80.0,0,1.0,2.221571,5.682127,first_half,early
14,E1,experiment,P,15,80.0,0,0.0,1.977363,5.863720,first_half,early
15,E1,experiment,P,16,20.0,1,1.0,2.167818,6.375758,first_half,early
16,E1,experiment,P,17,80.0,1,1.0,1.885467,6.689241,first_half,early
17,E1,experiment,P,18,40.0,1,1.0,2.251210,7.201379,first_half,early
18,E1,experiment,P,19,-20.0,0,1.0,2.525690,7.813393,first_half,early
19,E1,experiment,P,20,-60.0,0,1.0,1.996843,8.093006,first_half,early

,subject_id,finger_condition,delta_comparison_minus_standard,delta_standard_minus_comparison,n_comparison_greater,n_trials,p_comparison_greater,n_correct,success_rate,mean_reaction_time,standard_value,comparison_value,signed_stiffness_delta
0,E1,I,-80.0,80.0,0,8,0.000,8.0,1.000,1.926551,85.0,5.0,-80.0
1,E1,I,-60.0,60.0,0,8,0.000,8.0,1.000,1.916106,85.0,25.0,-60.0
2,E1,I,-40.0,40.0,0,8,0.000,8.0,1.000,1.904801,85.0,45.0,-40.0
3,E1,I,-20.0,20.0,3,8,0.375,5.0,0.625,2.360614,85.0,65.0,-20.0
4,E1,I,20.0,-20.0,7,8,0.875,7.0,0.875,2.116333,85.0,105.0,20.0
5,E1,I,40.0,-40.0,8,8,1.000,8.0,1.000,2.122745,85.0,125.0,40.0
6,E1,I,60.0,-60.0,8,8,1.000,8.0,1.000,1.941267,85.0,145.0,60.0
7,E1,I,80.0,-80.0,8,8,1.000,8.0,1.000,1.909946,85.0,165.0,80.0
8,E1,M,-80.0,80.0,0,8,0.000,8.0,1.000,2.078783,85.0,5.0,-80.0
9,E1,M,-60.0,60.0,0,8,0.000,8.0,1.000,1.923015,85.0,25.0,-60.0
10,E1,M,-40.0,40.0,0,8,0.000,8.0,1.000,1.841338,85.0,45.0,-40.0
11,E1,M,-20.0,20.0,1,8,0.125,7.0,0.875,2.009057,85.0,65.0,-20.0
12,E1,M,20.0,-20.0,4,8,0.500,4.0,0.500,2.033851,85.0,105.0,20.0
13,E1,M,40.0,-40.0,7,8,0.875,7.0,0.875,2.246047,85.0,125.0,40.0
14,E1,M,60.0,-60.0,8,8,1.000,8.0,1.000,2.172738,85.0,145.0,60.0
15,E1,M,80.0,-80.0,8,8,1.000,8.0,1.000,1.718983,85.0,165.0,80.0
16,E1,P,-80.0,80.0,0,8,0.000,8.0,1.000,2.185750,85.0,5.0,-80.0
17,E1,P,-60.0,60.0,0,8,0.000,8.0,1.000,2.130883,85.0,25.0,-60.0
18,E1,P,-40.0,40.0,1,8,0.125,7.0,0.875,2.382405,85.0,45.0,-40.0
19,E1,P,-20.0,20.0,1,8,0.125,7.0,0.875,2.279986,85.0,65.0,-20.0
20,E1,P,20.0,-20.0,5,8,0.625,5.0,0.625,3.325073,85.0,105.0,20.0
21,E1,P,40.0,-40.0,6,8,0.750,6.0,0.750,2.750131,85.0,125.0,40.0
22,E1,P,60.0,-60.0,7,8,0.875,7.0,0.875,2.095257,85.0,145.0,60.0
23,E1,P,80.0,-80.0,7,8,0.875,7.0,0.875,2.392429,85.0,165.0,80.0
24,E1,R,-80.0,80.0,0,8,0.000,8.0,1.000,1.713534,85.0,5.0,-80.0
25,E1,R,-60.0,60.0,0,8,0.000,8.0,1.000,1.843864,85.0,25.0,-60.0
26,E1,R,-40.0,40.0,0,8,0.000,8.0,1.000,2.145764,85.0,45.0,-40.0
27,E1,R,-20.0,20.0,0,8,0.000,8.0,1.000,1.822736,85.0,65.0,-20.0
28,E1,R,20.0,-20.0,6,8,0.750,6.0,0.750,1.766011,85.0,105.0,20.0
29,E1,R,40.0,-40.0,7,8,0.875,7.0,0.875,2.173778,85.0,125.0,40.0

## 6. Quality-control summaries

Flags suspicious cases without silently deleting more data: missing/invalid rows, trial counts per value/finger, non-monotonic curves, apparent error rate, RT outliers, side bias, standard-side bias, and related warnings.

In [7]:
qc_summary = pf.make_qc_summary(combined_clean_trials, combined_flagged_trials)
pf.save_csv(qc_summary, OUTPUT_ROOT, "qc_summary.csv")
display(qc_summary)

,subject_id,finger_condition,n_clean_trials,n_stimulus_levels,min_trials_per_value,median_trials_per_value,side_bias_p_chose_object2,standard_side_p_object2,apparent_error_rate,rt_outlier_count,monotonic_violations,spearman_r,non_monotonic_flag,qc_warnings,n_flagged_rows
0,E1,I,64,8,8,8.0,0.500000,0.500000,0.062500,2,0,0.951190,False,,0
1,E1,M,64,8,8,8.0,0.468750,0.500000,0.093750,5,0,0.969782,False,,0
2,E1,P,64,8,8,8.0,0.484375,0.500000,0.140625,7,0,0.981981,False,,0
3,E1,R,64,8,8,8.0,0.484375,0.500000,0.046875,5,0,0.932227,False,,0
4,E10,I,67,8,8,8.0,0.432836,0.492537,0.134581,3,0,0.970077,False,,0
5,E10,M,67,8,8,8.0,0.477612,0.507463,0.104278,2,0,0.988024,False,,0
6,E10,P,67,8,8,8.0,0.432836,0.477612,0.089127,4,0,0.951876,False,,0
7,E10,R,67,8,8,8.0,0.537313,0.507463,0.104724,6,0,0.951876,False,,0
8,E11,I,67,8,8,8.0,0.477612,0.492537,0.180481,6,0,0.963925,False,,0
9,E11,M,67,8,8,8.0,0.477612,0.507463,0.135918,4,1,0.951503,True,non_monotonic_curve,0
10,E11,P,67,8,8,8.0,0.432836,0.477612,0.090018,4,0,0.843435,False,,0
11,E11,R,67,8,8,8.0,0.417910,0.507463,0.164439,1,1,0.874267,True,non_monotonic_curve,0
12,E12,I,67,8,8,8.0,0.537313,0.492537,0.179590,4,0,0.783189,False,,0
13,E12,M,67,8,8,8.0,0.537313,0.507463,0.194296,1,1,0.927778,True,non_monotonic_curve,0
14,E12,P,67,8,8,8.0,0.492537,0.477612,0.238859,3,0,1.000000,False,,0
15,E12,R,67,8,8,8.0,0.462687,0.507463,0.269162,4,1,0.790433,True,non_monotonic_curve,0
16,E2,I,64,8,8,8.0,0.453125,0.500000,0.265625,5,0,0.815374,False,,0
17,E2,M,64,8,8,8.0,0.453125,0.500000,0.234375,4,1,0.926562,True,non_monotonic_curve,0
18,E2,P,64,8,8,8.0,0.500000,0.500000,0.062500,5,1,0.906687,True,non_monotonic_curve,0
19,E2,R,64,8,8,8.0,0.406250,0.500000,0.125000,4,0,0.932954,False,,0
20,E3,I,67,8,8,8.0,0.582090,0.492537,0.195633,2,2,0.747042,True,non_monotonic_curve,0
21,E3,M,67,8,8,8.0,0.447761,0.507463,0.194742,5,1,0.915729,True,non_monotonic_curve,0
22,E3,P,67,8,8,8.0,0.552239,0.477612,0.209893,3,0,0.951876,False,,0
23,E3,R,67,8,8,8.0,0.492537,0.507463,0.151070,5,1,0.724267,True,non_monotonic_curve,0
24,E4,I,67,8,8,8.0,0.373134,0.492537,0.372995,1,0,0.718576,False,high_apparent_error_rate,0
25,E4,M,67,8,8,8.0,0.492537,0.507463,0.329768,1,0,0.790433,False,,0
26,E4,P,67,8,8,8.0,0.507463,0.477612,0.253119,1,1,0.850315,True,non_monotonic_curve,0
27,E4,R,67,8,8,8.0,0.507463,0.507463,0.312834,3,2,0.682647,True,non_monotonic_curve,0
28,E5,I,67,8,8,8.0,0.477612,0.492537,0.179590,3,1,0.891631,True,non_monotonic_curve,0
29,E5,M,67,8,8,8.0,0.462687,0.507463,0.119430,7,0,0.927105,False,,0
30,E5,P,67,8,8,8.0,0.492537,0.477612,0.060606,4,0,0.938591,False,,0
31,E5,R,67,8,8,8.0,0.567164,0.507463,0.075312,3,1,0.822473,True,non_monotonic_curve,0
32,E6,I,67,8,8,8.0,0.492537,0.492537,0.165775,7,0,0.902708,False,,0
33,E6,M,67,8,8,8.0,0.537313,0.507463,0.165775,6,1,0.932954,True,non_monotonic_curve,0
34,E6,P,67,8,8,8.0,0.477612,0.477612,0.134581,8,0,0.970077,False,,0
35,E6,R,67,8,8,8.0,0.402985,0.507463,0.149287,4,0,0.898220,False,,0
36,E7,I,67,8,8,8.0,0.522388,0.492537,0.105169,3,0,0.969782,False,,0
37,E7,M,67,8,8,8.0,0.388060,0.507463,0.134135,4,0,0.981981,False,,0
38,E7,P,67,8,8,8.0,0.373134,0.477612,0.209447,3,0,0.934148,False,,0
39,E7,R,67,8,8,8.0,0.507463,0.507463,0.284759,3,2,0.690476,True,non_monotonic_curve,0
40,E8,I,67,8,8,8.0,0.582090,0.492537,0.195187,7,0,0.927105,False,,0
41,E8,M,67,8,8,8.0,0.567164,0.507463,0.254456,6,0,0.976190,False,,0
42,E8,P,67,8,8,8.0,0.582090,0.477612,0.120321,6,0,0.878310,False,,0
43,E8,R,67,8,8,8.0,0.641791,0.507463,0.211230,6,0,0.975900,False,,0
44,E9,I,67,8,8,8.0,0.492537,0.492537,0.164884,5,0,1.000000,False,,0
45,E9,M,67,8,8,8.0,0.507463,0.507463,0.074866,1,1,0.883852,True,non_monotonic_curve,0
46,E9,P,67,8,8,8.0,0.477612,0.477612,0.135472,2,0,0.963925,False,,0
47,E9,R,67,8,8,8.0,0.492537,0.507463,0.149733,3,0,0.734993,False,,0
48,P1,I,64,8,8,8.0,0.625000,0.500000,0.187500,4,1,0.871576,True,non_monotonic_curve,0
49,P1,M,64,8,8,8.0,0.500000,0.500000,0.093750,3,0,0.848625,False,,0
50,P1,P,64,8,8,8.0,0.468750,0.500000,0.062500,3,0,0.963624,False,,0
51,P1,R,64,8,8,8.0,0.437500,0.500000,0.125000,0,0,0.951876,False,,0

## 7. Psychometric aggregation

Aggregates valid trials into binomial counts: `comparison_value`, `n_trials`, `n_comparison_greater`, and observed probability.

In [8]:
psychometric_input_by_subject_finger = pf.make_psychometric_input(combined_clean_trials, ["subject_id", "finger_condition"])
pf.save_csv(psychometric_input_by_subject_finger, OUTPUT_ROOT, "psychometric_input_by_subject_finger.csv")
display(psychometric_input_by_subject_finger.head(30))

   subject_id finger_condition  comparison_value  n_trials  n_comparison_greater  p_comparison_greater   mean_rt  standard_value
0          E1                I               5.0         8                     0                 0.000  1.926551            85.0
1          E1                I              25.0         8                     0                 0.000  1.916106            85.0
2          E1                I              45.0         8                     0                 0.000  1.904801            85.0
3          E1                I              65.0         8                     3                 0.375  2.360614            85.0
4          E1                I             105.0         8                     7                 0.875  2.116333            85.0
5          E1                I             125.0         8                     8                 1.000  2.122745            85.0
6          E1                I             145.0         8                     8                 1.000  1.941267            85.0
7          E1                I             165.0         8                     8                 1.000  1.909946            85.0
8          E1                M               5.0         8                     0                 0.000  2.078783            85.0
9          E1                M              25.0         8                     0                 0.000  1.923015            85.0
10         E1                M              45.0         8                     0                 0.000  1.841338            85.0
11         E1                M              65.0         8                     1                 0.125  2.009057            85.0
12         E1                M             105.0         8                     4                 0.500  2.033851            85.0
13         E1                M             125.0         8                     7                 0.875  2.246047            85.0
14         E1                M             145.0         8                     8                 1.000  2.172738            85.0
15         E1                M             165.0         8                     8                 1.000  1.718983            85.0
16         E1                P               5.0         8                     0                 0.000  2.185750            85.0
17         E1                P              25.0         8                     0                 0.000  2.130883            85.0
18         E1                P              45.0         8                     1                 0.125  2.382405            85.0
19         E1                P              65.0         8                     1                 0.125  2.279986            85.0
20         E1                P             105.0         8                     5                 0.625  3.325073            85.0
21         E1                P             125.0         8                     6                 0.750  2.750131            85.0
22         E1                P             145.0         8                     7                 0.875  2.095257            85.0
23         E1                P             165.0         8                     7                 0.875  2.392429            85.0
24         E1                R               5.0         8                     0                 0.000  1.713534            85.0
25         E1                R              25.0         8                     0                 0.000  1.843864            85.0
26         E1                R              45.0         8                     0                 0.000  2.145764            85.0
27         E1                R              65.0         8                     0                 0.000  1.822736            85.0
28         E1                R             105.0         8                     6                 0.750  1.766011            85.0
29         E1                R             125.0         8                     7                 0.875  2.173778            85.0

## Psychometric fitting setup

The notebook attempts Wichmann-lab `psignifit` first when available and compatible. If not, it prints installation guidance and uses the scipy logistic fallback on physical stimulus values.

In [9]:
PSIGNIFIT_AVAILABLE, PSIGNIFIT_STATUS = pf.check_psignifit_available()
print(PSIGNIFIT_STATUS)
if not PSIGNIFIT_AVAILABLE:
    print("Optional psignifit install example: pip install psignifit")
    print("Continuing with scipy logistic fallback fits.")

psignifit import succeeded (version=unknown)

## 8. Subject x finger psychometric fits

In [10]:
pse_jnd_by_subject_finger = pf.fit_conditions(psychometric_input_by_subject_finger, ["subject_id", "finger_condition"], PSIGNIFIT_AVAILABLE)
pf.save_csv(pse_jnd_by_subject_finger, OUTPUT_ROOT, "pse_jnd_by_subject_finger.csv")
display(pse_jnd_by_subject_finger)

,subject_id,finger_condition,fit_method,pse,jnd,x25,x75,slope_at_pse,lapse_rate,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,deviance,aic,psignifit_status,neg_log_likelihood,mu,scale,comparison_min,comparison_max
0,E1,I,scipy_logistic_fallback,76.134600,11.955487,64.179112,88.090087,0.022973,0.000000,0.000000,0.000000,ok,,64,8,2.103563,26.716898,psignifit_failed: 'dict' object has no attribu...,9.358449,76.134600,10.882353,5.0,165.0
1,E1,M,scipy_logistic_fallback,100.433106,14.025326,86.407781,114.458432,0.019583,0.000000,0.000000,0.000000,ok,,64,8,1.585911,32.732911,psignifit_failed: 'dict' object has no attribu...,12.366456,100.433106,12.766402,5.0,165.0
2,E1,P,scipy_logistic_fallback,95.744883,23.034181,74.670052,120.738415,0.012402,0.103729,0.000000,0.103729,ok,,64,8,1.065465,52.761129,psignifit_failed: 'dict' object has no attribu...,22.380565,91.600232,17.825773,5.0,165.0
3,E1,R,scipy_logistic_fallback,98.969443,9.999349,88.970095,108.968792,0.027467,0.000000,0.000000,0.000000,ok,,64,8,1.426814,24.452499,psignifit_failed: 'dict' object has no attribu...,8.226250,98.969443,9.101800,5.0,165.0
4,E10,I,scipy_logistic_fallback,85.485339,18.482478,67.692312,104.657267,0.015084,0.053352,0.000000,0.053352,ok,,67,8,3.577245,57.442304,psignifit_failed: 'dict' object has no attribu...,24.721152,83.720544,15.640064,25.0,145.0
5,E10,M,scipy_logistic_fallback,76.408379,10.956600,66.048269,87.961470,0.025650,0.073351,0.000000,0.073351,ok,,67,8,2.023803,45.845003,psignifit_failed: 'dict' object has no attribu...,18.922502,74.984541,8.974936,25.0,145.0
6,E10,P,scipy_logistic_fallback,76.111447,10.284597,66.118064,86.687257,0.027001,0.041839,0.000000,0.041839,ok,,67,8,2.805090,40.597968,psignifit_failed: 'dict' object has no attribu...,16.298984,75.337657,8.854687,25.0,145.0
7,E10,R,scipy_logistic_fallback,91.198310,12.626983,78.242692,103.496657,0.021971,0.038783,0.038783,0.000000,ok,,67,8,3.571906,43.998930,psignifit_failed: 'dict' object has no attribu...,17.999465,92.079956,10.919673,25.0,145.0
8,E11,I,scipy_logistic_fallback,100.143312,22.519514,77.623798,122.662826,0.012196,0.000000,0.000000,0.000000,ok,,67,8,6.568184,62.471803,psignifit_failed: 'dict' object has no attribu...,27.235901,100.143312,20.498145,25.0,145.0
9,E11,M,scipy_logistic_fallback,102.464535,16.626594,85.837940,119.091129,0.016519,0.000000,0.000000,0.000000,ok,,67,8,6.581874,50.483281,psignifit_failed: 'dict' object has no attribu...,21.241640,102.464535,15.134178,25.0,145.0
10,E11,P,scipy_logistic_fallback,89.276946,8.462783,81.108955,98.034521,0.033674,0.126783,0.043163,0.083620,ok,,67,8,4.187324,46.049942,psignifit_failed: 'dict' object has no attribu...,19.024971,88.677087,6.468894,25.0,145.0
11,E11,R,scipy_logistic_fallback,77.527960,20.438941,60.837719,101.715602,0.014974,0.169900,0.000000,0.169900,warning,high_lapse_estimate,67,8,12.258814,67.112133,psignifit_failed: 'dict' object has no attribu...,29.556066,72.014622,13.278342,25.0,145.0
12,E12,I,scipy_logistic_fallback,99.080021,15.142921,82.629853,112.915694,0.019714,0.210072,0.142336,0.067737,ok,,67,8,4.347802,67.416483,psignifit_failed: 'dict' object has no attribu...,29.708241,100.960769,9.927935,25.0,145.0
13,E12,M,scipy_logistic_fallback,88.208987,23.832144,64.376842,112.041131,0.011524,0.000000,0.000000,0.000000,ok,,67,8,10.128906,65.407361,psignifit_failed: 'dict' object has no attribu...,28.703681,88.208987,21.692953,25.0,145.0
14,E12,P,scipy_logistic_fallback,79.417359,29.488631,54.112663,113.089926,0.010049,0.146560,0.000000,0.146560,ok,,67,8,1.992043,76.034834,psignifit_failed: 'dict' object has no attribu...,34.017417,72.269571,20.605087,25.0,145.0
15,E12,R,scipy_logistic_fallback,99.059287,2.543650,96.515638,101.602937,0.141405,0.400000,0.200000,0.200000,warning,high_lapse_estimate,67,8,5.583625,86.504783,psignifit_failed: 'dict' object has no attribu...,39.252392,99.059287,1.060784,25.0,145.0
16,E2,I,scipy_logistic_fallback,127.537831,57.687435,84.665163,200.040034,0.005682,0.200000,0.000000,0.200000,warning,high_lapse_estimate,64,8,5.045570,68.958291,psignifit_failed: 'dict' object has no attribu...,30.479146,110.682029,32.997175,5.0,165.0
17,E2,M,scipy_logistic_fallback,104.664995,37.123544,77.075186,151.322274,0.008830,0.200000,0.000000,0.200000,warning,high_lapse_estimate,64,8,6.340367,62.708737,psignifit_failed: 'dict' object has no attribu...,27.354368,93.817796,21.234642,5.0,165.0
18,E2,P,scipy_logistic_fallback,85.395022,1.353256,84.191734,86.898246,0.214408,0.125001,0.000000,0.125001,ok,,64,8,7.499956,32.113290,psignifit_failed: 'dict' object has no attribu...,12.056645,85.107502,0.999431,5.0,165.0
19,E2,R,scipy_logistic_fallback,86.463226,18.541485,68.854161,105.937132,0.015127,0.068724,0.000000,0.068724,ok,,64,8,4.905562,46.132231,psignifit_failed: 'dict' object has no attribu...,19.066115,84.199878,15.307351,5.0,165.0
20,E3,I,scipy_logistic_fallback,95.298505,3.951440,92.100437,100.003318,0.083597,0.288236,0.088236,0.200000,warning,high_lapse_estimate,67,8,8.732656,70.628787,psignifit_failed: 'dict' object has no attribu...,31.314394,94.641084,2.076063,25.0,145.0
21,E3,M,scipy_logistic_fallback,88.844106,20.592652,71.268510,112.453814,0.015581,0.283840,0.096630,0.187210,warning,high_lapse_estimate,67,8,4.444238,71.640896,psignifit_failed: 'dict' object has no attribu...,31.820448,85.968424,11.307180,25.0,145.0
22,E3,P,scipy_logistic_fallback,72.761544,13.041011,63.069608,89.151630,0.025136,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,1.719832,66.227911,psignifit_failed: 'dict' object has no attribu...,29.113956,68.951066,7.459450,25.0,145.0
23,E3,R,scipy_logistic_fallback,97.510145,2.011058,95.978606,100.000722,0.163144,0.229414,0.029414,0.200000,warning,high_lapse_estimate,67,8,5.918345,56.585678,psignifit_failed: 'dict' object has no attribu...,24.292839,97.004588,1.122971,25.0,145.0
24,E4,I,scipy_logistic_fallback,90.107096,68.577193,3.918525,141.072912,0.004780,0.200000,0.200000,0.000000,warning,high_lapse_estimate,67,8,4.870331,93.513670,psignifit_failed: 'dict' object has no attribu...,42.756835,110.144798,39.226109,25.0,145.0
25,E4,M,scipy_logistic_fallback,100.405091,59.176022,56.426122,174.778166,0.005539,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,6.468752,86.333377,psignifit_failed: 'dict' object has no attribu...,39.166689,83.114335,33.848645,25.0,145.0
26,E4,P,scipy_logistic_fallback,67.487502,13.161314,55.271778,81.594406,0.026195,0.371968,0.171968,0.200000,warning,high_lapse_estimate,67,8,11.881133,79.354448,psignifit_failed: 'dict' object has no attribu...,35.677224,66.953144,5.981868,25.0,145.0
27,E4,R,scipy_logistic_fallback,64.871072,40.316516,34.908280,115.541313,0.008131,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,10.140076,88.936007,psignifit_failed: 'dict' object has no attribu...,40.468003,53.090912,23.061021,25.0,145.0
28,E5,I,scipy_logistic_fallback,74.156439,16.219440,62.102329,94.541209,0.020210,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,3.717869,64.348854,psignifit_failed: 'dict' object has no attribu...,28.174427,69.417250,9.277509,25.0,145.0
29,E5,M,scipy_logistic_fallback,79.734283,10.009254,70.212222,90.230731,0.029095,0.176568,0.064280,0.112288,ok,,67,8,1.491188,55.697146,psignifit_failed: 'dict' object has no attribu...,23.848573,78.911128,7.051370,25.0,145.0
30,E5,P,scipy_logistic_fallback,95.481125,4.355292,91.382067,100.092651,0.064670,0.078101,0.000000,0.078101,ok,,67,8,1.616624,30.921286,psignifit_failed: 'dict' object has no attribu...,11.460643,94.880173,3.538277,25.0,145.0
31,E5,R,scipy_logistic_fallback,72.212751,1.343640,71.011431,73.698710,0.215274,0.121214,0.000000,0.121214,ok,,67,8,2.784630,38.654964,psignifit_failed: 'dict' object has no attribu...,15.327482,71.934801,1.001128,25.0,145.0
32,E6,I,scipy_logistic_fallback,90.872111,18.388433,77.206030,113.982896,0.017826,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,7.323401,56.805795,psignifit_failed: 'dict' object has no attribu...,24.402898,85.499160,10.518171,25.0,145.0
33,E6,M,scipy_logistic_fallback,92.805421,18.546062,78.779058,115.871183,0.017440,0.195468,0.000000,0.195468,warning,high_lapse_estimate,67,8,3.627828,55.766794,psignifit_failed: 'dict' object has no attribu...,23.883397,87.424574,10.852156,25.0,145.0
34,E6,P,scipy_logistic_fallback,79.750529,14.033256,67.106772,95.173283,0.020524,0.115677,0.000000,0.115677,ok,,67,8,3.488021,53.533995,psignifit_failed: 'dict' object has no attribu...,22.766997,76.964700,10.587437,25.0,145.0
35,E6,R,scipy_logistic_fallback,70.208626,1.139961,69.209269,71.489191,0.262869,0.191519,0.040001,0.151518,warning,high_lapse_estimate,67,8,5.880156,56.834183,psignifit_failed: 'dict' object has no attribu...,24.417092,69.999212,0.754271,25.0,145.0
36,E7,I,scipy_logistic_fallback,91.936133,14.343369,77.830582,106.517319,0.019267,0.025600,0.000000,0.025600,ok,,67,8,3.257815,45.066229,psignifit_failed: 'dict' object has no attribu...,18.533114,91.272099,12.634400,25.0,145.0
37,E7,M,scipy_logistic_fallback,83.202911,16.346954,66.855957,99.549864,0.016801,0.000000,0.000000,0.000000,ok,,67,8,4.565482,48.953838,psignifit_failed: 'dict' object has no attribu...,20.476919,83.202911,14.879638,25.0,145.0
38,E7,P,scipy_logistic_fallback,69.808712,1.084816,68.974559,71.144191,0.302632,0.240000,0.040000,0.200000,warning,high_lapse_estimate,67,8,3.881006,65.670700,psignifit_failed: 'dict' object has no attribu...,28.835350,69.552246,0.600000,25.0,145.0
39,E7,R,scipy_logistic_fallback,71.961418,21.334004,56.106221,98.774229,0.015365,0.200000,0.000000,0.200000,warning,high_lapse_estimate,67,8,9.955112,84.252362,psignifit_failed: 'dict' object has no attribu...,38.126181,65.727794,12.203036,25.0,145.0
40,E8,I,scipy_logistic_fallback,95.075141,20.183940,75.968281,116.336161,0.013917,0.072163,0.000000,0.072163,ok,,67,8,6.823572,59.078555,psignifit_failed: 'dict' object has no attribu...,25.539277,92.492930,16.566954,25.0,145.0
41,E8,M,scipy_logistic_fallback,90.593895,29.091189,63.486592,121.668971,0.009729,0.087766,0.000000,0.087766,ok,,67,8,5.307857,73.125874,psignifit_failed: 'dict' object has no attribu...,32.562937,86.111108,23.224703,25.0,145.0
42,E8,P,scipy_logistic_fallback,91.345337,13.034957,79.124288,105.194203,0.021647,0.081898,0.000000,0.081898,ok,,67,8,5.246463,46.178830,psignifit_failed: 'dict' object has no attribu...,19.089415,89.463753,10.518494,25.0,145.0
43,E8,R,scipy_logistic_fallback,107.108595,21.754379,87.175834,130.684593,0.013121,0.102536,0.000000,0.102536,ok,,67,8,2.705128,58.895441,psignifit_failed: 'dict' object has no attribu...,25.447720,103.235422,16.876356,25.0,145.0
44,E9,I,scipy_logistic_fallback,94.666162,19.038070,75.242854,113.318993,0.014537,0.030813,0.030813,0.000000,ok,,67,8,2.046667,58.255374,psignifit_failed: 'dict' object has no attribu...,25.127687,95.725233,16.650342,25.0,145.0
45,E9,M,scipy_logistic_fallback,70.798844,0.757291,70.095602,71.610184,0.374360,0.090909,0.000000,0.090909,ok,,67,8,4.542948,37.640694,psignifit_failed: 'dict' object has no attribu...,14.820347,70.678236,0.601025,25.0,145.0
46,E9,P,scipy_logistic_fallback,104.535246,8.336825,95.871228,112.544878,0.033469,0.055745,0.055745,0.000000,ok,,67,8,3.529621,43.419295,psignifit_failed: 'dict' object has no attribu...,17.709648,105.366085,7.028534,25.0,145.0
47,E9,R,scipy_logistic_fallback,70.763099,1.462205,69.568309,72.492719,0.214711,0.221818,0.040000,0.181818,warning,high_lapse_estimate,67,8,2.822706,59.147657,psignifit_failed: 'dict' object has no attribu...,25.573829,70.440207,0.875986,25.0,145.0
48,P1,I,scipy_logistic_fallback,65.000022,2.615906,62.508996,67.740809,0.118447,0.281251,0.125001,0.156250,warning,high_lapse_estimate,64,8,3.714481,64.912851,psignifit_failed: 'dict' object has no attribu...,28.456425,64.868275,1.514155,5.0,165.0
49,P1,M,scipy_logistic_fallback,71.340865,6.345050,64.886991,77.577090,0.045127,0.143978,0.081459,0.062519,ok,,64,8,4.604484,45.715137,psignifit_failed: 'dict' object has no attribu...,18.857569,71.550646,4.739932,5.0,165.0
50,P1,P,scipy_logistic_fallback,85.001967,14.487994,70.513972,99.489961,0.018957,0.000000,0.000000,0.000000,ok,,64,8,2.376749,31.430756,psignifit_failed: 'dict' object has no attribu...,11.715378,85.001967,13.187541,5.0,165.0
51,P1,R,scipy_logistic_fallback,97.908060,16.660839,80.638758,113.960437,0.016727,0.052380,0.052380,0.000000,ok,,64,8,4.657138,44.801500,psignifit_failed: 'dict' object has no attribu...,18.400750,99.470591,14.119713,5.0,165.0

## 9. Subject-level pooled-across-fingers fits

In [11]:
psychometric_input_subject_pooled = pf.make_psychometric_input(combined_clean_trials, ["subject_id"])
pse_jnd_subject_pooled = pf.fit_conditions(psychometric_input_subject_pooled, ["subject_id"], PSIGNIFIT_AVAILABLE)
pf.save_csv(psychometric_input_subject_pooled, OUTPUT_ROOT, "psychometric_input_subject_pooled.csv")
pf.save_csv(pse_jnd_subject_pooled, OUTPUT_ROOT, "pse_jnd_subject_pooled.csv")
display(pse_jnd_subject_pooled)

,subject_id,fit_method,pse,jnd,x25,x75,slope_at_pse,lapse_rate,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,deviance,aic,psignifit_status,neg_log_likelihood,mu,scale,comparison_min,comparison_max
0,E1,scipy_logistic_fallback,92.751105,16.133410,76.834679,109.101499,0.017109,0.021017,0.000000,0.021017,ok,,256,8,1.196932,127.496952,psignifit_failed: 'dict' object has no attribu...,59.748476,92.137074,14.298771,5.0,165.0
1,E10,scipy_logistic_fallback,83.359156,15.124147,68.506649,98.754943,0.018283,0.027586,0.000000,0.027586,ok,,268,8,1.351860,169.335032,psignifit_failed: 'dict' object has no attribu...,80.667516,82.605130,13.286198,25.0,145.0
2,E11,scipy_logistic_fallback,91.276812,19.734667,73.033640,112.502975,0.014398,0.094971,0.000000,0.094971,ok,,268,8,13.365992,212.697433,psignifit_failed: 'dict' object has no attribu...,102.348716,88.003108,15.541081,25.0,145.0
3,E12,scipy_logistic_fallback,86.310487,30.259179,58.050249,118.568607,0.009411,0.108884,0.014388,0.094496,ok,,268,8,4.314183,280.130583,psignifit_failed: 'dict' object has no attribu...,136.065292,82.077221,23.481753,25.0,145.0
4,E2,scipy_logistic_fallback,93.505649,26.300164,73.959656,126.559985,0.012464,0.200000,0.000000,0.200000,warning,high_lapse_estimate,256,8,4.484356,202.255295,psignifit_failed: 'dict' object has no attribu...,97.127648,85.820954,15.043676,5.0,165.0
5,E3,scipy_logistic_fallback,88.362440,20.665340,72.425479,113.756159,0.015890,0.243115,0.043115,0.200000,warning,high_lapse_estimate,268,8,8.902961,251.547259,psignifit_failed: 'dict' object has no attribu...,121.773630,83.568484,11.396541,25.0,145.0
6,E4,scipy_logistic_fallback,79.159069,55.787617,37.698326,149.273560,0.005876,0.200000,0.000000,0.200000,warning,high_lapse_estimate,268,8,8.698299,333.788509,psignifit_failed: 'dict' object has no attribu...,162.894255,62.858378,31.910480,25.0,145.0
7,E5,scipy_logistic_fallback,82.496303,12.152137,71.610148,95.914423,0.023881,0.132312,0.008429,0.123883,ok,,268,8,3.505009,180.824410,psignifit_failed: 'dict' object has no attribu...,86.412205,80.107709,8.922492,25.0,145.0
8,E6,scipy_logistic_fallback,85.019546,16.254613,71.496096,104.005321,0.018689,0.173628,0.008859,0.164769,warning,high_lapse_estimate,268,8,15.507435,207.759848,psignifit_failed: 'dict' object has no attribu...,99.879924,80.948101,10.660671,25.0,145.0
9,E7,scipy_logistic_fallback,75.125729,16.649231,62.752203,96.050666,0.019688,0.200000,0.000000,0.200000,warning,high_lapse_estimate,268,8,3.843211,232.801115,psignifit_failed: 'dict' object has no attribu...,112.400558,70.260958,9.523349,25.0,145.0
10,E8,scipy_logistic_fallback,95.580336,21.595907,75.610443,118.802258,0.013155,0.094699,0.000000,0.094699,ok,,268,8,12.182931,221.744819,psignifit_failed: 'dict' object has no attribu...,106.872410,92.007391,17.015752,25.0,145.0
11,E9,scipy_logistic_fallback,89.323986,17.048463,73.050578,107.147503,0.016414,0.063175,0.000000,0.063175,ok,,268,8,2.150862,191.596065,psignifit_failed: 'dict' object has no attribu...,91.798033,87.405368,14.203970,25.0,145.0
12,P1,scipy_logistic_fallback,83.846320,18.806377,64.907015,102.519770,0.014940,0.089252,0.049228,0.040024,ok,,256,8,1.135709,176.761901,psignifit_failed: 'dict' object has no attribu...,84.380950,84.154326,15.238623,5.0,165.0

## 10. Group-level fits by finger

Pools all valid trials across subjects within each finger condition.

In [12]:
psychometric_input_group_by_finger = pf.make_psychometric_input(combined_clean_trials, ["finger_condition"])
pse_jnd_group_by_finger = pf.fit_conditions(psychometric_input_group_by_finger, ["finger_condition"], PSIGNIFIT_AVAILABLE)
pf.save_csv(psychometric_input_group_by_finger, OUTPUT_ROOT, "psychometric_input_group_by_finger.csv")
pf.save_csv(pse_jnd_group_by_finger, OUTPUT_ROOT, "pse_jnd_group_by_finger.csv")
display(pse_jnd_group_by_finger)

,finger_condition,fit_method,pse,jnd,x25,x75,slope_at_pse,lapse_rate,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,deviance,aic,psignifit_status,neg_log_likelihood,mu,scale,comparison_min,comparison_max
0,I,scipy_logistic_fallback,89.936426,24.475073,67.922611,116.872758,0.011959,0.157683,0.027241,0.130442,ok,,862,14,8.955702,775.650718,psignifit_failed: 'dict' object has no attribu...,383.825359,85.664768,17.344725,5.0,165.0
1,M,scipy_logistic_fallback,87.625573,21.529539,68.015256,111.074334,0.013304,0.108315,0.000642,0.107672,ok,,862,14,15.802793,696.220214,psignifit_failed: 'dict' object has no attribu...,344.110107,83.641777,16.514843,5.0,165.0
2,P,scipy_logistic_fallback,86.915452,19.038980,68.904651,106.982612,0.014758,0.072870,0.000000,0.072870,ok,,862,14,9.789935,631.521441,psignifit_failed: 'dict' object has no attribu...,311.760721,84.456833,15.608335,5.0,165.0
3,R,scipy_logistic_fallback,84.574860,22.138518,65.757432,110.034467,0.013561,0.168587,0.012481,0.156106,warning,high_lapse_estimate,862,14,22.560353,743.415631,psignifit_failed: 'dict' object has no attribu...,367.707815,79.385262,14.870151,5.0,165.0

## 11. Group-level all-pooled fit

In [13]:
all_pooled_trials = combined_clean_trials.copy()
all_pooled_trials["group"] = "all_pooled"
psychometric_input_group_all_pooled = pf.make_psychometric_input(all_pooled_trials, ["group"])
pse_jnd_group_all_pooled = pf.fit_conditions(psychometric_input_group_all_pooled, ["group"], PSIGNIFIT_AVAILABLE)
pf.save_csv(psychometric_input_group_all_pooled, OUTPUT_ROOT, "psychometric_input_group_all_pooled.csv")
pf.save_csv(pse_jnd_group_all_pooled, OUTPUT_ROOT, "pse_jnd_group_all_pooled.csv")
display(pse_jnd_group_all_pooled)

,group,fit_method,pse,jnd,x25,x75,slope_at_pse,lapse_rate,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,deviance,aic,psignifit_status,neg_log_likelihood,mu,scale,comparison_min,comparison_max
0,all_pooled,scipy_logistic_fallback,87.233766,22.092733,67.229083,111.414549,0.013026,0.117492,0.003681,0.113811,ok,,3448,14,17.693769,2836.6474,psignifit_failed: 'dict' object has no attribu...,1414.3237,83.050418,16.6739,5.0,165.0

## 12. Subject-average group analysis

Computes subject-level probabilities first, then averages subjects so each subject has equal weight. This complements trial-pooled group fits.

In [14]:
subject_average_group_by_finger = pf.subject_average_psychometric(combined_clean_trials, ["finger_condition"])
subject_average_group_all = pf.subject_average_psychometric(combined_clean_trials.assign(group="all_subject_average"), ["group"])
pf.save_csv(subject_average_group_by_finger, OUTPUT_ROOT, "subject_average_group_by_finger.csv")
pf.save_csv(subject_average_group_all, OUTPUT_ROOT, "subject_average_group_all_pooled.csv")
display(subject_average_group_by_finger.head(30))

   finger_condition  comparison_value  n_subjects  mean_p_comparison_greater  sem_p_comparison_greater  total_trials  standard_value
0                 I               5.0           3                   0.041667                  0.041667            24            85.0
1                 I              25.0          13                   0.038462                  0.021856           104            85.0
2                 I              40.0          10                   0.111111                  0.054935            90            85.0
3                 I              45.0           3                   0.083333                  0.041667            24            85.0
4                 I              55.0          10                   0.150000                  0.040825            80            85.0
5                 I              65.0           3                   0.333333                  0.110240            24            85.0
6                 I              70.0          10                   0.222222                  0.040572            90            85.0
7                 I             100.0          10                   0.625000                  0.052705            80            85.0
8                 I             105.0           3                   0.750000                  0.072169            24            85.0
9                 I             115.0          10                   0.687500                  0.027951            80            85.0
10                I             125.0           3                   0.791667                  0.150231            24            85.0
11                I             130.0          10                   0.822222                  0.044444            90            85.0
12                I             145.0          13                   0.875000                  0.049029           104            85.0
13                I             165.0           3                   0.750000                  0.144338            24            85.0
14                M               5.0           3                   0.041667                  0.041667            24            85.0
15                M              25.0          13                   0.000000                  0.000000           104            85.0
16                M              40.0          10                   0.055556                  0.024845            90            85.0
17                M              45.0           3                   0.041667                  0.041667            24            85.0
18                M              55.0          10                   0.162500                  0.059073            80            85.0
19                M              65.0           3                   0.250000                  0.072169            24            85.0
20                M              70.0          10                   0.288889                  0.041243            90            85.0
21                M             100.0          10                   0.662500                  0.059073            80            85.0
22                M             105.0           3                   0.625000                  0.190941            24            85.0
23                M             115.0          10                   0.800000                  0.046398            80            85.0
24                M             125.0           3                   0.791667                  0.083333            24            85.0
25                M             130.0          10                   0.766667                  0.048148            90            85.0
26                M             145.0          13                   0.923077                  0.022550           104            85.0
27                M             165.0           3                   0.875000                  0.125000            24            85.0
28                P               5.0           3                   0.000000                  0.000000            24            85.0
29                P              25.0          13                   0.009615                  0.009615           104            85.0

## 13. Order-effect analysis

Summarizes fatigue/order effects across trial number and inferred block order.

In [15]:
order_effects_summary, order_effects_binned = pf.compute_order_effects(combined_clean_trials)
pf.save_csv(order_effects_summary, OUTPUT_ROOT, "order_effects_summary.csv")
pf.save_csv(order_effects_binned, OUTPUT_ROOT, "order_effects_binned.csv")
display(order_effects_summary)

,subject_id,finger_condition,n_trials,first_half_p_comparison_greater,second_half_p_comparison_greater,first_half_mean_rt,second_half_mean_rt,spearman_response_vs_order,spearman_rt_vs_order,first_block_number
0,E1,I,64,0.531250,0.531250,2.088419,1.961172,0.022035,-0.237179,2
1,E1,M,64,0.437500,0.437500,2.200159,1.805794,-0.037511,-0.448993,4
2,E1,P,64,0.437500,0.406250,2.491971,2.393507,-0.067652,-0.292720,1
3,E1,R,64,0.437500,0.468750,1.952724,1.945272,-0.000850,-0.098077,3
4,E10,I,67,0.575758,0.382353,2.475518,2.455543,-0.211678,-0.028693,1
5,E10,M,67,0.545455,0.470588,2.792674,2.150120,-0.067924,-0.455982,2
6,E10,P,67,0.484848,0.558824,2.464267,2.213386,0.041718,-0.249820,4
7,E10,R,67,0.454545,0.500000,7.047507,2.304028,0.049443,-0.413800,3
8,E11,I,67,0.424242,0.382353,2.227676,2.010826,-0.055071,-0.038151,1
9,E11,M,67,0.393939,0.382353,2.413769,2.231409,-0.031675,-0.116450,2
10,E11,P,67,0.484848,0.441176,2.015353,2.156397,-0.085132,-0.031686,4
11,E11,R,67,0.393939,0.558824,2.177913,1.964558,0.205498,-0.393367,3
12,E12,I,67,0.515152,0.411765,2.896998,2.847132,-0.086680,0.122955,1
13,E12,M,67,0.484848,0.470588,2.549239,2.382279,-0.016996,0.183454,2
14,E12,P,67,0.545455,0.441176,2.141157,2.338480,-0.097254,0.149174,4
15,E12,R,67,0.393939,0.529412,2.036592,2.146651,0.065010,0.004390,3
16,E2,I,64,0.343750,0.250000,2.567726,2.269617,-0.086086,-0.586722,1
17,E2,M,64,0.312500,0.406250,2.162919,1.940699,0.064343,-0.428984,2
18,E2,P,64,0.437500,0.437500,2.068231,2.076746,0.015345,-0.025183,3
19,E2,R,64,0.468750,0.468750,1.954084,1.976870,-0.067799,-0.225092,4
20,E3,I,67,0.303030,0.470588,2.173875,1.808591,0.164710,-0.292242,1
21,E3,M,67,0.454545,0.441176,2.915515,2.085155,0.062082,-0.636284,2
22,E3,P,67,0.393939,0.470588,2.241085,1.986817,0.014019,-0.173557,4
23,E3,R,67,0.393939,0.352941,2.408786,2.463743,-0.057448,-0.329156,3
24,E4,I,67,0.575758,0.441176,2.348662,2.150798,-0.097254,-0.347514,1
25,E4,M,67,0.424242,0.382353,2.680343,2.291543,0.037763,-0.431040,2
26,E4,P,67,0.484848,0.588235,2.052511,2.178729,0.148595,0.270093,4
27,E4,R,67,0.515152,0.558824,2.245093,2.367553,0.047984,0.166653,3
28,E5,I,67,0.515152,0.411765,2.870846,2.372337,-0.116090,-0.304613,1
29,E5,M,67,0.545455,0.441176,2.367425,2.077270,-0.172896,-0.489903,2
30,E5,P,67,0.393939,0.470588,2.302220,2.066054,0.063864,-0.154362,4
31,E5,R,67,0.424242,0.470588,2.206107,1.988949,0.037249,-0.255886,3
32,E6,I,67,0.424242,0.352941,1.849891,1.809079,-0.107695,-0.037393,1
33,E6,M,67,0.333333,0.441176,2.232001,2.010396,0.045929,-0.498045,2
34,E6,P,67,0.393939,0.558824,2.192092,1.979040,0.115882,-0.203448,4
35,E6,R,67,0.515152,0.470588,2.081617,1.919986,0.000000,-0.121518,3
36,E7,I,67,0.454545,0.441176,1.959802,1.772815,-0.048113,-0.236132,1
37,E7,M,67,0.454545,0.558824,1.915725,1.821945,0.104973,-0.345000,2
38,E7,P,67,0.393939,0.529412,1.949758,1.880462,0.171813,-0.433275,4
39,E7,R,67,0.515152,0.323529,2.215219,2.062936,-0.143960,-0.666613,3
40,E8,I,67,0.424242,0.411765,2.311979,1.877200,-0.075109,-0.312116,1
41,E8,M,67,0.424242,0.470588,2.582536,2.005070,0.074498,0.261633,2
42,E8,P,67,0.424242,0.441176,2.344460,1.949950,0.007788,-0.371019,4
43,E8,R,67,0.272727,0.411765,2.060702,1.744142,0.154418,-0.117727,3
44,E9,I,67,0.393939,0.500000,2.126170,1.940707,0.065186,-0.437705,1
45,E9,M,67,0.424242,0.529412,1.922843,1.838990,0.060259,-0.108708,2
46,E9,P,67,0.393939,0.441176,2.201020,2.065976,0.020342,-0.262152,4
47,E9,R,67,0.454545,0.470588,1.901809,1.918938,0.074297,-0.319938,3
48,P1,I,64,0.531250,0.531250,2.566329,1.831648,-0.076274,-0.472482,1
49,P1,M,64,0.531250,0.531250,2.106116,2.191270,0.035594,-0.184478,2
50,P1,P,64,0.500000,0.500000,1.894839,6.508709,-0.035525,-0.110531,3
51,P1,R,64,0.437500,0.500000,1.848076,1.900917,0.008475,-0.034066,4

## 14. Success-rate, answer-duration, and fatigue/learning analysis

This section tests the requested psychophysics-only questions:

- Does answer duration (`time_to_answer`) relate to success?
- Does success go up or down over the session (learning vs tiredness/fatigue proxy)?
- Are the effects visible within each participant/finger and across participants?

Because no subjective tiredness scale is present in `answers.csv`, tiredness is operationalized conservatively as trial order, elapsed time, and first-vs-second-half changes.

In [16]:
success_time_fatigue = pf.compute_success_time_fatigue(combined_success_trials, ["subject_id", "finger_condition"])

success_summary_by_subject_finger = success_time_fatigue["summary"]
success_trend_slopes_by_subject_finger = success_time_fatigue["slopes"]
success_by_reaction_time_bin = success_time_fatigue["reaction_time_bins"]
success_by_order_bin = success_time_fatigue["order_bins"]
fatigue_first_second_summary = success_time_fatigue["first_second"]
between_subject_success_time_stats = success_time_fatigue["between_subjects"]
success_summary_by_subject = success_time_fatigue["subject_summary"]

pf.save_csv(success_summary_by_subject, OUTPUT_ROOT, "success_summary_by_subject.csv")
pf.save_csv(success_summary_by_subject_finger, OUTPUT_ROOT, "success_summary_by_subject_finger.csv")
pf.save_csv(success_trend_slopes_by_subject_finger, OUTPUT_ROOT, "success_trend_slopes_by_subject_finger.csv")
pf.save_csv(success_by_reaction_time_bin, OUTPUT_ROOT, "success_by_reaction_time_bin.csv")
pf.save_csv(success_by_order_bin, OUTPUT_ROOT, "success_by_order_bin.csv")
pf.save_csv(fatigue_first_second_summary, OUTPUT_ROOT, "fatigue_first_second_summary.csv")
pf.save_csv(between_subject_success_time_stats, OUTPUT_ROOT, "between_subject_success_time_stats.csv")

print("Participant-level success summary")
display(success_summary_by_subject)
print("Within participant/finger success trend slopes: positive=success improves, negative=success decreases")
display(success_trend_slopes_by_subject_finger)
print("First vs second half fatigue/learning proxy")
display(fatigue_first_second_summary)
print("Between-participant duration/time statistics")
display(between_subject_success_time_stats)

Participant-level success summary

   subject_id subject_group_label  n_trials  success_rate  mean_reaction_time  median_reaction_time  session_duration_min  mean_abs_stiffness_delta
0          E1          experiment       256      0.914062            2.104877              1.890275             66.549613                  50.00000
1         E10          experiment       268      0.891791            2.977327              2.107130             84.758794                  37.38806
2         E11          experiment       268      0.858209            2.148858              1.915955             74.676195                  37.38806
3         E12          experiment       268      0.779851            2.417485              2.131556             74.118833                  37.38806
4          E2          experiment       256      0.828125            2.127112              1.947843             87.672255                  50.00000
5          E3          experiment       268      0.813433            2.257843              1.869651             88.423661                  37.38806
6          E4          experiment       268      0.682836            2.288773              2.165501             58.798110                  37.38806
7          E5          experiment       268      0.891791            2.279084              2.030381             58.605595                  37.38806
8          E6          experiment       268      0.847015            2.008074              1.890265             58.608434                  37.38806
9          E7          experiment       268      0.817164            1.946395              1.869485             67.107354                  37.38806
10         E8          experiment       268      0.805970            2.106290              1.782065            109.001485                  37.38806
11         E9          experiment       268      0.869403            1.988834              1.894508             62.647336                  37.38806
12         P1               pilot       256      0.882812            2.605988              1.830306             78.694191                  50.00000

Within participant/finger success trend slopes: positive=success improves, negative=success decreases

,subject_id,finger_condition,n_trials,success_rate,success_vs_order_slope,success_vs_order_p_value,success_vs_order_spearman_r,success_vs_order_spearman_p,success_vs_order_direction,success_vs_global_order_slope,success_vs_global_order_p_value,success_vs_global_order_spearman_r,success_vs_global_order_spearman_p,success_vs_global_order_direction,success_vs_elapsed_slope,success_vs_elapsed_p_value,success_vs_elapsed_direction,success_vs_reaction_time_slope,success_vs_reaction_time_p_value,success_vs_reaction_time_spearman_r,success_vs_reaction_time_spearman_p,success_vs_reaction_time_direction
0,E1,I,64,0.937500,0.049038,0.641023,0.059403,0.641023,up_weak,0.198489,0.641023,0.059403,0.641023,up_weak,0.325425,0.531636,up_weak,-0.023824,7.214344e-01,-0.122300,3.356800e-01,flat
1,E1,M,64,0.906250,-0.086538,0.493965,-0.087055,0.493965,down_weak,-0.350275,0.493965,-0.087055,0.493965,down_weak,-0.503677,0.363110,down_weak,-0.039882,4.502381e-01,-0.058037,6.487291e-01,down_weak
2,E1,P,64,0.859375,0.206250,0.169189,0.173967,0.169189,up_weak,0.834821,0.169189,0.173967,0.169189,up_weak,0.659488,0.150422,up_weak,-0.007474,8.585132e-01,-0.023115,8.561355e-01,flat
3,E1,R,64,0.953125,0.007212,0.937464,0.010004,0.937464,flat,0.029190,0.937464,0.010004,0.937464,flat,0.104176,0.852754,up_weak,-0.044699,4.047679e-01,-0.066027,6.041987e-01,down_weak
4,E10,I,67,0.865672,0.010536,0.942038,0.009053,0.942038,flat,0.184522,0.398315,0.009053,0.942038,up_weak,0.210988,0.327615,up_weak,-0.223080,1.122121e-08,-0.556755,9.949817e-07,down_p_lt_0.05
5,E10,M,67,0.895522,0.318701,0.011997,0.305299,0.011997,up_p_lt_0.05,0.906174,0.000248,0.305299,0.011997,up_p_lt_0.05,0.889043,0.000251,up_p_lt_0.05,-0.139179,2.147014e-04,-0.370900,2.002714e-03,down_p_lt_0.05
6,E10,P,67,0.910448,0.213345,0.075081,0.218932,0.075081,up_weak,0.695223,0.044057,0.218932,0.075081,up_p_lt_0.05,0.670074,0.047893,up_p_lt_0.05,-0.127151,2.961297e-02,-0.216229,7.883985e-02,down_p_lt_0.05
7,E10,R,67,0.895522,0.042142,0.745668,0.040370,0.745668,up_weak,0.187918,0.717480,0.040370,0.745668,up_weak,0.261180,0.515694,up_weak,-0.000820,7.578822e-01,-0.242220,4.828359e-02,flat
8,E11,I,67,0.820896,0.021071,0.897097,0.016102,0.897097,flat,0.529156,0.096487,0.016102,0.897097,up_weak,0.576619,0.056902,up_weak,-0.134685,2.985023e-02,-0.263672,3.108838e-02,down_p_lt_0.05
9,E11,M,67,0.865672,-0.187006,0.193942,-0.160689,0.193942,down_weak,-0.744972,0.189866,-0.160689,0.193942,down_weak,-0.823859,0.181947,down_weak,-0.119510,1.352667e-02,-0.233113,5.763717e-02,down_p_lt_0.05
10,E11,P,67,0.910448,-0.102722,0.395902,-0.105412,0.395902,down_weak,-0.144337,0.445996,-0.105412,0.395902,down_weak,-0.142689,0.457158,down_weak,-0.181467,8.345357e-05,-0.283800,1.994587e-02,down_p_lt_0.05
11,E11,R,67,0.835821,0.229148,0.142127,0.181256,0.142127,up_weak,0.636140,0.151712,0.181256,0.142127,up_weak,0.576178,0.156670,up_weak,-0.188834,1.243453e-02,-0.231258,5.971163e-02,down_p_lt_0.05
12,E12,I,67,0.820896,-0.181738,0.262358,-0.138881,0.262358,down_weak,-0.640724,0.310884,-0.138881,0.262358,down_weak,-0.336941,0.436464,down_weak,-0.143945,1.050404e-05,-0.374374,1.802041e-03,down_p_lt_0.05
13,E12,M,67,0.805970,0.021071,0.900207,0.015613,0.900207,flat,0.189318,0.686572,0.015613,0.900207,up_weak,0.237069,0.594069,up_weak,-0.072767,5.926456e-02,-0.113194,3.617515e-01,down_weak
14,E12,P,67,0.761194,-0.044776,0.804750,-0.030773,0.804750,down_weak,0.053349,0.886356,-0.030773,0.804750,up_weak,0.074349,0.838776,up_weak,-0.291940,2.324959e-02,-0.249803,4.148066e-02,down_p_lt_0.05
15,E12,R,67,0.731343,-0.463565,0.011666,-0.306438,0.011666,down_p_lt_0.05,-0.518792,0.071308,-0.306438,0.011666,down_weak,-0.458915,0.114857,down_weak,0.102832,4.115192e-01,0.008706,9.442582e-01,up_weak
16,E2,I,64,0.734375,-0.021635,0.910311,-0.014363,0.910311,flat,-0.087569,0.910311,-0.014363,0.910311,down_weak,-0.070595,0.876727,down_weak,0.042089,5.994501e-01,0.058410,6.466183e-01,up_weak
17,E2,M,64,0.765625,0.036058,0.844791,0.024959,0.844791,up_weak,0.145948,0.844791,0.024959,0.844791,up_weak,0.123247,0.881197,up_weak,0.322695,1.140511e-01,0.154747,2.221066e-01,up_weak
18,E2,P,64,0.937500,0.034615,0.742167,0.041931,0.742167,up_weak,0.140110,0.742167,0.041931,0.742167,up_weak,0.131260,0.798691,up_weak,0.082984,2.760580e-01,0.164231,1.947066e-01,up_weak
19,E2,R,64,0.875000,-0.075000,0.601625,-0.066496,0.601625,down_weak,-0.303571,0.601625,-0.066496,0.601625,down_weak,-0.339889,0.669241,down_weak,0.084388,4.268446e-01,0.040921,7.481731e-01,up_weak
20,E3,I,67,0.805970,0.213345,0.201372,0.158081,0.201372,up_weak,0.351065,0.288005,0.158081,0.201372,up_weak,0.251639,0.401771,up_weak,0.012176,8.009585e-01,-0.097581,4.321126e-01,flat
21,E3,M,67,0.805970,0.176471,0.291563,0.130759,0.291563,up_weak,0.705293,0.285578,0.130759,0.291563,up_weak,0.417963,0.371033,up_weak,-0.042831,3.263446e-01,0.033178,7.898289e-01,down_weak
22,E3,P,67,0.791045,-0.250219,0.144194,-0.180337,0.144194,down_weak,-0.343160,0.201343,-0.180337,0.144194,down_weak,-0.329884,0.249271,down_weak,-0.028235,5.641637e-01,0.034169,7.836976e-01,flat
23,E3,R,67,0.850746,0.036874,0.807556,0.030322,0.807556,up_weak,0.268125,0.532575,0.030322,0.807556,up_weak,0.264871,0.478972,up_weak,-0.037127,9.654412e-02,-0.194926,1.139434e-01,down_weak
24,E4,I,67,0.626866,-0.273924,0.179530,-0.165960,0.179530,down_weak,-0.489578,0.111555,-0.165960,0.179530,down_weak,-0.483648,0.114547,down_weak,0.103420,4.023317e-01,-0.012766,9.183336e-01,up_weak
25,E4,M,67,0.671642,0.171203,0.389577,0.106822,0.389577,up_weak,0.660464,0.400538,0.106822,0.389577,up_weak,0.600893,0.397659,up_weak,-0.201942,2.777030e-02,-0.195566,1.127373e-01,down_p_lt_0.05
26,E4,P,67,0.746269,-0.142230,0.440726,-0.095774,0.440726,down_weak,-0.558744,0.293773,-0.095774,0.440726,down_weak,-0.618118,0.254528,down_weak,-0.159757,4.385274e-01,-0.177360,1.510474e-01,down_weak
27,E4,R,67,0.686567,-0.018437,0.925478,-0.011646,0.925478,flat,0.002205,0.995606,-0.011646,0.925478,flat,0.010318,0.979779,flat,-0.033111,8.151944e-01,-0.158052,2.014578e-01,down_weak
28,E5,I,67,0.820896,0.210711,0.193011,0.161021,0.193011,up_weak,0.831732,0.187136,0.161021,0.193011,up_weak,0.590933,0.188786,up_weak,-0.012452,7.329728e-01,-0.223416,6.915979e-02,flat
29,E5,M,67,0.880597,0.013169,0.923855,0.011900,0.923855,flat,0.253714,0.509137,0.011900,0.923855,up_weak,0.282232,0.392244,up_weak,0.011036,8.740607e-01,0.045222,7.163244e-01,flat
30,E5,P,67,0.940299,0.076383,0.447037,0.094463,0.447037,up_weak,0.370636,0.070406,0.094463,0.447037,up_weak,0.412239,0.052464,up_weak,-0.072102,1.100364e-01,-0.146581,2.365554e-01,down_weak
31,E5,R,67,0.925373,0.158033,0.153753,0.176212,0.153753,up_weak,0.329097,0.053192,0.176212,0.153753,up_weak,0.338276,0.063950,up_weak,-0.031527,5.331154e-01,-0.052863,6.709383e-01,down_weak
32,E6,I,67,0.835821,-0.123793,0.430507,-0.097920,0.430507,down_weak,0.405072,0.189607,-0.097920,0.430507,up_weak,0.384021,0.180919,up_weak,-0.232717,1.298076e-01,-0.160422,1.946936e-01,down_weak
33,E6,M,67,0.835821,0.100088,0.524232,0.079169,0.524232,up_weak,0.416482,0.501983,0.079169,0.524232,up_weak,0.443303,0.437850,up_weak,-0.098770,1.292939e-01,0.033334,7.888578e-01,down_weak
34,E6,P,67,0.865672,0.345040,0.014843,0.296483,0.014843,up_p_lt_0.05,0.697332,0.001379,0.296483,0.014843,up_p_lt_0.05,0.705329,0.001686,up_p_lt_0.05,0.008769,8.579028e-01,-0.074687,5.480587e-01,flat
35,E6,R,67,0.850746,0.073749,0.625906,0.060644,0.625906,up_weak,0.341728,0.425945,0.060644,0.625906,up_weak,0.352270,0.426523,up_weak,-0.119995,3.226067e-01,-0.095297,4.430169e-01,down_weak
36,E7,I,67,0.895522,0.131694,0.309023,0.126156,0.309023,up_weak,-0.019345,0.921575,0.126156,0.309023,flat,-0.034834,0.858311,down_weak,0.021439,7.958376e-01,-0.138772,2.627344e-01,flat
37,E7,M,67,0.865672,-0.134328,0.352306,-0.115425,0.352306,down_weak,-0.274202,0.343054,-0.115425,0.352306,down_weak,-0.269175,0.336662,down_weak,0.090509,7.150626e-01,-0.038475,7.572312e-01,up_weak
38,E7,P,67,0.791045,0.039508,0.819077,0.028474,0.819077,up_weak,-0.136641,0.784309,0.028474,0.819077,down_weak,-0.195558,0.659267,down_weak,-0.344725,3.078998e-01,-0.161355,1.920784e-01,down_weak
39,E7,R,67,0.716418,-0.147498,0.440191,-0.095886,0.440191,down_weak,-0.578042,0.449290,-0.095886,0.440191,down_weak,-0.598226,0.452607,down_weak,0.441909,1.044158e-01,0.229441,6.180175e-02,up_weak
40,E8,I,67,0.805970,-0.002634,0.987494,-0.001952,0.987494,flat,0.144971,0.753387,-0.001952,0.987494,up_weak,0.167430,0.603171,up_weak,-0.088905,1.082812e-01,-0.243953,4.665391e-02,down_weak
41,E8,M,67,0.746269,0.165935,0.368006,0.111737,0.368006,up_weak,0.770596,0.004961,0.111737,0.368006,up_p_lt_0.05,0.839951,0.002561,up_p_lt_0.05,-0.068793,3.242369e-03,-0.129473,2.963756e-01,down_p_lt_0.05
42,E8,P,67,0.880597,-0.097454,0.478546,-0.088063,0.478546,down_weak,-0.394245,0.478546,-0.088063,0.478546,down_weak,-0.546049,0.526215,down_weak,-0.168140,4.321302e-07,-0.242769,4.776246e-02,down_p_lt_0.05
43,E8,R,67,0.791045,0.197542,0.250433,0.142372,0.250433,up_weak,0.332799,0.341268,0.142372,0.250433,up_weak,0.067003,0.859406,up_weak,-0.001822,9.806713e-01,-0.263862,3.096251e-02,flat
44,E9,I,67,0.835821,-0.150132,0.338495,-0.118754,0.338495,down_weak,-0.098041,0.820598,-0.118754,0.338495,down_weak,0.035491,0.917796,up_weak,-0.131652,1.955503e-01,-0.066669,5.919334e-01,down_weak
45,E9,M,67,0.925373,-0.105356,0.343762,-0.117474,0.343762,down_weak,-0.128353,0.451202,-0.117474,0.343762,down_weak,-0.112391,0.512728,down_weak,-0.128732,9.042091e-02,-0.234949,5.564172e-02,down_weak
46,E9,P,67,0.865672,0.176471,0.220599,0.151636,0.220599,up_weak,0.713904,0.220599,0.151636,0.220599,up_weak,0.565555,0.162206,up_weak,-0.274064,1.658672e-03,-0.242166,4.833579e-02,down_p_lt_0.05
47,E9,R,67,0.850746,-0.184372,0.220683,-0.151609,0.220683,down_weak,-0.345629,0.258784,-0.151609,0.220683,down_weak,-0.299023,0.299740,down_weak,-0.109214,2.744974e-01,-0.121287,3.282175e-01,down_weak
48,P1,I,64,0.812500,-0.008654,0.959338,-0.006501,0.959338,flat,-0.035027,0.959338,-0.006501,0.959338,down_weak,0.271509,0.714762,up_weak,0.013658,6.086500e-01,-0.065012,6.097819e-01,flat
49,P1,M,64,0.906250,-0.092308,0.465507,-0.092859,0.465507,down_weak,-0.373626,0.465507,-0.092859,0.465507,down_weak,-0.616799,0.425376,down_weak,0.004595,8.788199e-01,-0.156700,2.162561e-01,flat
50,P1,P,64,0.937500,-0.046154,0.660809,-0.055909,0.660809,down_weak,-0.186813,0.660809,-0.055909,0.660809,down_weak,-0.197468,0.789279,down_weak,0.000424,7.972442e-01,-0.045426,7.215208e-01,flat
51,P1,R,64,0.875000,-0.020192,0.888335,-0.017903,0.888335,flat,-0.081731,0.888335,-0.017903,0.888335,down_weak,-0.165399,0.871892,down_weak,-0.282061,3.141658e-02,-0.163683,1.962204e-01,down_p_lt_0.05

First vs second half fatigue/learning proxy

,subject_id,finger_condition,mean_reaction_time_first_half,mean_reaction_time_second_half,n_trials_first_half,n_trials_second_half,success_rate_first_half,success_rate_second_half,success_rate_second_minus_first,fatigue_direction,reaction_time_second_minus_first
0,E1,I,2.088419,1.961172,32,32,0.906250,0.968750,0.062500,up_weak,-0.127246
1,E1,M,2.200159,1.805794,32,32,0.937500,0.875000,-0.062500,down_weak,-0.394365
2,E1,P,2.491971,2.393507,32,32,0.812500,0.906250,0.093750,up_weak,-0.098464
3,E1,R,1.952724,1.945272,32,32,0.937500,0.968750,0.031250,up_weak,-0.007452
4,E10,I,2.475518,2.455543,33,34,0.909091,0.823529,-0.085561,down_weak,-0.019975
5,E10,M,2.792674,2.150120,33,34,0.818182,0.970588,0.152406,up_weak,-0.642554
6,E10,P,2.464267,2.213386,33,34,0.878788,0.941176,0.062389,up_weak,-0.250881
7,E10,R,7.047507,2.304028,33,34,0.909091,0.882353,-0.026738,flat,-4.743479
8,E11,I,2.227676,2.010826,33,34,0.818182,0.823529,0.005348,flat,-0.216850
9,E11,M,2.413769,2.231409,33,34,0.909091,0.823529,-0.085561,down_weak,-0.182360
10,E11,P,2.015353,2.156397,33,34,0.939394,0.882353,-0.057041,down_weak,0.141044
11,E11,R,2.177913,1.964558,33,34,0.787879,0.882353,0.094474,up_weak,-0.213356
12,E12,I,2.896998,2.847132,33,34,0.848485,0.794118,-0.054367,down_weak,-0.049866
13,E12,M,2.549239,2.382279,33,34,0.757576,0.852941,0.095365,up_weak,-0.166960
14,E12,P,2.141157,2.338480,33,34,0.757576,0.764706,0.007130,flat,0.197323
15,E12,R,2.036592,2.146651,33,34,0.848485,0.617647,-0.230838,down_weak,0.110060
16,E2,I,2.567726,2.269617,32,32,0.781250,0.687500,-0.093750,down_weak,-0.298109
17,E2,M,2.162919,1.940699,32,32,0.750000,0.781250,0.031250,up_weak,-0.222220
18,E2,P,2.068231,2.076746,32,32,0.937500,0.937500,0.000000,flat,0.008515
19,E2,R,1.954084,1.976870,32,32,0.906250,0.843750,-0.062500,down_weak,0.022786
20,E3,I,2.173875,1.808591,33,34,0.757576,0.852941,0.095365,up_weak,-0.365284
21,E3,M,2.915515,2.085155,33,34,0.787879,0.823529,0.035651,up_weak,-0.830360
22,E3,P,2.241085,1.986817,33,34,0.848485,0.735294,-0.113191,down_weak,-0.254268
23,E3,R,2.408786,2.463743,33,34,0.848485,0.852941,0.004456,flat,0.054957
24,E4,I,2.348662,2.150799,33,34,0.727273,0.529412,-0.197861,down_weak,-0.197863
25,E4,M,2.680343,2.291543,33,34,0.636364,0.705882,0.069519,up_weak,-0.388801
26,E4,P,2.052511,2.178729,33,34,0.818182,0.676471,-0.141711,down_weak,0.126218
27,E4,R,2.245093,2.367553,33,34,0.666667,0.705882,0.039216,up_weak,0.122460
28,E5,I,2.870846,2.372337,33,34,0.787879,0.852941,0.065062,up_weak,-0.498509
29,E5,M,2.367425,2.077270,33,34,0.878788,0.882353,0.003565,flat,-0.290155
30,E5,P,2.302220,2.066054,33,34,0.909091,0.970588,0.061497,up_weak,-0.236166
31,E5,R,2.206107,1.988949,33,34,0.878788,0.970588,0.091800,up_weak,-0.217158
32,E6,I,1.849891,1.809079,33,34,0.878788,0.794118,-0.084670,down_weak,-0.040812
33,E6,M,2.232001,2.010396,33,34,0.787879,0.882353,0.094474,up_weak,-0.221604
34,E6,P,2.192092,1.979040,33,34,0.787879,0.941176,0.153298,up_weak,-0.213052
35,E6,R,2.081617,1.919986,33,34,0.848485,0.852941,0.004456,flat,-0.161630
36,E7,I,1.959802,1.772814,33,34,0.848485,0.941176,0.092692,up_weak,-0.186987
37,E7,M,1.915725,1.821945,33,34,0.909091,0.823529,-0.085561,down_weak,-0.093780
38,E7,P,1.949758,1.880462,33,34,0.787879,0.794118,0.006239,flat,-0.069296
39,E7,R,2.215219,2.062936,33,34,0.787879,0.647059,-0.140820,down_weak,-0.152284
40,E8,I,2.311979,1.877200,33,34,0.818182,0.794118,-0.024064,flat,-0.434779
41,E8,M,2.582536,2.005070,33,34,0.696970,0.794118,0.097148,up_weak,-0.577466
42,E8,P,2.344460,1.949950,33,34,0.878788,0.882353,0.003565,flat,-0.394511
43,E8,R,2.060702,1.744142,33,34,0.727273,0.852941,0.125668,up_weak,-0.316561
44,E9,I,2.126170,1.940707,33,34,0.848485,0.823529,-0.024955,flat,-0.185463
45,E9,M,1.922843,1.838990,33,34,0.939394,0.911765,-0.027629,flat,-0.083854
46,E9,P,2.201020,2.065976,33,34,0.787879,0.941176,0.153298,up_weak,-0.135044
47,E9,R,1.901809,1.918938,33,34,0.909091,0.794118,-0.114973,down_weak,0.017129
48,P1,I,2.566329,1.831648,32,32,0.781250,0.843750,0.062500,up_weak,-0.734681
49,P1,M,2.106116,2.191270,32,32,0.968750,0.843750,-0.125000,down_weak,0.085154
50,P1,P,1.894839,6.508709,32,32,0.937500,0.937500,0.000000,flat,4.613870
51,P1,R,1.848076,1.900917,32,32,0.875000,0.875000,0.000000,flat,0.052841

Between-participant duration/time statistics

                                            analysis  n_subjects     slope  linear_p_value  spearman_r  spearman_p  direction
0      between_subject_success_vs_mean_reaction_time          13  0.030218        0.645950    0.016506    0.957318    up_weak
1    between_subject_success_vs_median_reaction_time          13 -0.197718        0.182840   -0.057772    0.851296  down_weak
2    between_subject_success_vs_session_duration_min          13 -0.000073        0.953901   -0.228336    0.453061       flat
3  between_subject_success_vs_mean_abs_stiffness_...          13  0.003905        0.235305    0.390897    0.186607       flat

## 15. Finger identity across time and finger appearance order

This section addresses two additional time questions:

1. **Between fingers across time:** compare index/middle/ring/pinky success trajectories across normalized time within each finger's trials.
2. **Appearance of fingers:** compare the first, second, third, and fourth finger encountered in each participant session, independent of the anatomical finger identity.

Outputs include subject-level slopes, group time-bin curves by finger, the finger-order matrix for every participant, and paired contrasts between fingers/appearance positions.

In [ ]:
import importlib
pf = importlib.reload(pf)

finger_time_appearance = pf.compare_fingers_over_time_and_appearance(combined_success_trials)

finger_time_subject_summary = finger_time_appearance["subject_finger_summary"]
finger_time_group_bins = finger_time_appearance["group_finger_time_bins"]
finger_time_subject_bins = finger_time_appearance["subject_finger_time_bins"]
finger_appearance_order_summary = finger_time_appearance["appearance_order_summary"]
finger_by_appearance_order = finger_time_appearance["finger_by_appearance_order"]
finger_order_matrix = finger_time_appearance["finger_order_matrix"]
finger_time_slope_summary = finger_time_appearance["finger_slope_summary"]
stiffness_time_slope_summary = finger_time_appearance.get("stiffness_slope_summary", pd.DataFrame())
finger_time_slope_contrasts = finger_time_appearance["finger_slope_contrasts"]
finger_appearance_order_contrasts = finger_time_appearance["appearance_order_contrasts"]

pf.save_csv(finger_time_subject_summary, OUTPUT_ROOT, "finger_time_subject_summary.csv")
pf.save_csv(finger_time_group_bins, OUTPUT_ROOT, "finger_time_group_bins.csv")
pf.save_csv(finger_time_subject_bins, OUTPUT_ROOT, "finger_time_subject_bins.csv")
pf.save_csv(finger_appearance_order_summary, OUTPUT_ROOT, "finger_appearance_order_summary.csv")
pf.save_csv(finger_by_appearance_order, OUTPUT_ROOT, "finger_by_appearance_order.csv")
pf.save_csv(finger_order_matrix, OUTPUT_ROOT, "finger_order_matrix.csv")
pf.save_csv(finger_time_slope_summary, OUTPUT_ROOT, "finger_time_slope_summary.csv")
pf.save_csv(stiffness_time_slope_summary, OUTPUT_ROOT, "stiffness_time_slope_summary.csv")
pf.save_csv(finger_time_slope_contrasts, OUTPUT_ROOT, "finger_time_slope_contrasts.csv")
pf.save_csv(finger_appearance_order_contrasts, OUTPUT_ROOT, "finger_appearance_order_contrasts.csv")

print("Finger order matrix: which finger appeared 1st/2nd/3rd/4th for each participant")
display(finger_order_matrix)
print("Group success by finger and normalized within-finger time bin")
display(finger_time_group_bins)
print("Finger appearance-order summary")
display(finger_appearance_order_summary)
print("Finger time-slope summary")
display(finger_time_slope_summary)
print("Success slope by stiffness")
display(stiffness_time_slope_summary)
print("Paired contrasts between finger time slopes")
display(finger_time_slope_contrasts)
print("Paired contrasts between appearance-order success rates")
display(finger_appearance_order_contrasts)

## 16. Article-inspired figures adapted to this experiment: skin stretch and XY probing

The eLife article includes perception panels (psychometric curves, PSE, JND) and force/trajectory-style panels. For this experiment, the relevant substitutions are:

- **No grip force:** use the recorded skin-stretch gain/condition in **mm/m** and a skin-stretch command proxy, not grip force.
- **Probing from center in the XY plane:** use `object_x, object_y` from `tracking.csv` relative to screen center `(320, 240)`.
- **Article-style perception:** keep psychometric curves, PSE, JND, subject lines, and group average/dotted summary styling.

Important distinction: `motor_response_analisys_servo` is a separate hardware check/calibration for motor command response. This psychophysics notebook keeps the main analysis on the experiment variables that participants experienced: skin-stretch mm/m, XY probing from center, time, success, and finger/order effects.

In [ ]:
article_style_figure_paths, article_style_figure_manifest = pf.save_article_style_psychophysics_figures(
    OUTPUT_ROOT,
    combined_success_trials,
    psychometric_input_by_subject_finger,
    pse_jnd_by_subject_finger,
    finger_time_subject_summary,
    finger_appearance_order_summary,
    finger_by_appearance_order,
    preferred_subject=None,
    fig_dpi=FIG_DPI,
)
print(f"Saved {len(article_style_figure_paths)} article-style psychophysics figures")
display(article_style_figure_manifest)

## 17. Plots and saved outputs

Saves PNG figures: subject ? finger curves, group curves, all-pooled curve, PSE/JND summaries, order effects, side bias, and QC plots. Subject-specific outputs are also written under `OUTPUT_ROOT/subjects/<subject_id>/`.

In [ ]:
figure_paths = pf.save_all_figures(
    OUTPUT_ROOT,
    combined_clean_trials,
    qc_summary,
    psychometric_input_by_subject_finger,
    pse_jnd_by_subject_finger,
    psychometric_input_group_by_finger,
    pse_jnd_group_by_finger,
    psychometric_input_group_all_pooled,
    pse_jnd_group_all_pooled,
    order_effects_binned,
    FIG_DPI,
)
time_fatigue_figure_paths = pf.save_time_fatigue_figures(
    OUTPUT_ROOT,
    success_by_reaction_time_bin,
    success_by_order_bin,
    fatigue_first_second_summary,
    success_summary_by_subject,
    success_trend_slopes_by_subject_finger,
    FIG_DPI,
)
finger_time_appearance_figure_paths = pf.save_finger_time_appearance_figures(
    OUTPUT_ROOT,
    finger_time_group_bins,
    finger_appearance_order_summary,
    finger_by_appearance_order,
    finger_time_slope_summary,
    FIG_DPI,
    stiffness_time_slope_summary=stiffness_time_slope_summary,
)
figure_paths = (
    figure_paths
    + time_fatigue_figure_paths
    + finger_time_appearance_figure_paths
    + article_style_figure_paths
)
print(f"Saved {len(figure_paths)} figure files.")
display(pd.DataFrame({"figure": [str(p) for p in figure_paths]}).head(60))

pf.save_subject_level_outputs(
    OUTPUT_ROOT,
    combined_clean_trials,
    combined_flagged_trials,
    pse_jnd_by_subject_finger,
    pse_jnd_subject_pooled,
)

psychophysics_group_comparisons = pf.save_experiment_group_comparison_outputs(
    OUTPUT_ROOT,
    combined_success_trials,
    pse_jnd_by_subject_finger=pse_jnd_by_subject_finger,
    pse_jnd_subject_pooled=pse_jnd_subject_pooled,
)
motor_control_method_references = pf.motor_control_method_references()
pf.save_csv(motor_control_method_references, OUTPUT_ROOT, "motor_control_method_references.csv")

print("N_E / L_E / L_P psychophysics group summary (transparent raw values are retained in raw_values_json and plotted faded in scope figures)")
display(psychophysics_group_comparisons["psychophysics_trial_group_metric_summary"].head(80))
print("Between-group psychophysics comparisons")
display(psychophysics_group_comparisons["psychophysics_trial_between_group_metric_comparisons"].head(80))
print("ANOVA-style factor statistics: one-way and two-way screening, subject-level collapsed where needed")
display(psychophysics_group_comparisons["psychophysics_factor_statistics"].head(120))
display(psychophysics_group_comparisons["psychophysics_factor_statistics_status"])
print("Motor-control / psychophysics method references saved for later citation")
display(motor_control_method_references[["citation_key", "year", "title", "doi", "analysis_use"]])

manifest = pf.analysis_manifest(OUTPUT_ROOT)
display(manifest)
print("Figures folder:", OUTPUT_ROOT / "figures")
print("Subject output folder:", OUTPUT_ROOT / "subjects")

## Interpretation notes

- `PSE` is the physical comparison value where `P(response_comparison_greater) = 0.5`.
- `JND = (x75 - x25) / 2`, in the same units as the stimulus values.
- `farajian_style_input_by_subject_finger.csv` mirrors the Farajian/Nisky perception scripts: stimulus difference, number of comparison-stiffer responses, and total repetitions.
- `correct_response` is the success variable: 1 means the physically stiffer stimulus was selected, 0 means it was not.
- `success_vs_order_slope > 0` suggests improvement/learning over the session; `< 0` suggests possible fatigue or decline. Treat this as a proxy because no direct subjective tiredness rating is present in `answers.csv`.
- `success_vs_reaction_time_slope` and `success_by_reaction_time_bin.csv` show whether longer answer duration is associated with better or worse success.
- `finger_time_group_bins.csv` compares success across normalized time within each finger, enabling direct index/middle/ring/pinky time-course comparison.
- `finger_appearance_order_summary.csv` compares the 1st/2nd/3rd/4th finger encountered in a participant session, which tests whether finger appearance/order itself matters.
- `finger_order_matrix.csv` records which anatomical finger appeared in each order position for every participant.
- Review `fit_warning`, `qc_warnings`, `combined_flagged_trials.csv`, and the per-subject trend tables before interpreting results.
- `motor_response_analisys_servo` is treated as a separate hardware calibration/check, not mixed into the main psychophysics variables.
- Rows excluded from fitting are preserved for audit; no raw data files are modified.

- All psychophysics group outputs now include the requested scopes when available: protocol/group (`N_E`, `L_E`, `L_P`, broad `N/L/P/E`, and all participants), participant, finger, stiffness/comparison value, success/failure, sex, age group, and workspace (`N` 40x50 cm; `L` 60x60 cm).
- `comparison_over_standard`, `signed_delta_over_standard`, and `abs_delta_over_standard` normalize analog stiffness values to the trial standard while preserving original values; workspace columns document the original physical space and do not alter stimulus units.
- Scope-summary plots use faded raw/background values plus the summary bar/point so every value remains transparent behind the group statistic.
- `psychophysics_factor_statistics.csv` is an ANOVA-style screening table. For binary repeated 2AFC trials, treat it as descriptive evidence; for manuscript-level inference prefer planned psychometric model comparisons or mixed/repeated-measures models with participant as a repeated/random factor.
- `motor_control_method_references.csv` lists the motor-control and haptic psychophysics articles used to guide the analysis additions and citation trail.