# Fillterizetion: filtered `z_tracking.csv` kinematics

Standalone filtered kinematics notebook.

**Safety contract**
- Reads the raw experiment tree and existing Python analysis module only.
- Uses `z_tracking.csv` files for side-Z input; it does **not** decode/open video files.
- Writes all new CSVs and figures under `analysis/Kinematics/result_fillter/`.
- Does not edit `kinematic_analysis.ipynb`, `kinematics_analysis.py`, `analysis/Kinematics/results/`, or raw experiment folders.

The spelling `fillter` / `result_fillter` is kept intentionally to match the requested folder/tag name.

In [4]:
from pathlib import Path
import importlib
import sys
import pandas as pd
import numpy as np
from IPython.display import display


def find_analysis_dir(start: Path | None = None) -> Path:
    """Locate analysis/Kinematics from the notebook's current working directory.

    Jupyter/VS Code may start the kernel from the project root, the notebook
    folder, or an intermediate folder such as ``analysis``.  Walk upward so
    the setup cell works from any directory inside the repository.
    """
    current = (Path.cwd() if start is None else Path(start)).resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "kinematics_analysis.py").exists():
            return candidate
        nested = candidate / "analysis" / "Kinematics"
        if (nested / "kinematics_analysis.py").exists():
            return nested
    raise FileNotFoundError(
        "Could not find analysis/Kinematics/kinematics_analysis.py. "
        "Start the notebook from somewhere inside the Parallel_Heptics repository."
    )


ANALYSIS_DIR = find_analysis_dir()
analysis_dir_text = str(ANALYSIS_DIR)
if analysis_dir_text not in sys.path:
    sys.path.insert(0, analysis_dir_text)
import kinematics_analysis as ka
# Pick up edits to kinematics_analysis.py without restarting the kernel. Jupyter
# caches the first import, so without this a re-run silently uses stale code.
importlib.reload(ka)

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

# --- Raw data + selection -------------------------------------------------
# Read-only raw data root: the current Parallel_Heptics results tree (one folder
# per subject, each holding answers.csv + pair_NNN/tracking.csv + side/top camera
# mp4). This is the same root the psychophysics notebook reads.
DATA_ROOT = Path(r"C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\results")

# Choose what to analyze, mirroring the psychophysics notebook:
#   single subject  -> "N_E_1"   (or a one-element list ["N_E_1"] -> same folder)
#   a whole group   -> "N_E" / "L_E" / "N_P" / "L_P"
#   combined groups -> "L_N_E"   (= L_E + N_E)
#   only filtered folders -> "FILTER_ONLY" (or "L_E_FILTER_ONLY" for one group)
#   a hand-picked list -> ["L_E_1", "L_E_2", ...] (each subject + one custom aggregate folder)
#   every valid subject -> None
# Folders carrying a "not"/"old"/"unfinished" token are skipped automatically.
DATA_SELECTION = "L_N_E"
# True: group/cohort selections skip folders marked "filter"; False: keep every valid called subject.
# Keep this False when DATA_SELECTION is FILTER_ONLY / <GROUP>_FILTER_ONLY.
# Explicit single-subject selections are kept in both cases.
EXCLUDE_FILTER_FOLDERS = True
SELECTION_LABEL = ka.selection_output_label(DATA_SELECTION, exclude_filter_folders=EXCLUDE_FILTER_FOLDERS)

# Output tree: the subject is the primary unit. Subjects and group folders are
# top-level siblings under results/, each with csv/ and figures/ split into the
# same semantic categories (filled in by ka.organize_kinematic_results_tree at
# the end of the run):
#   results/<subject>/{csv,figures}/<category>/   <- per-subject outputs
#   results/L_E , results/N_E , results/L_N_E /{csv,figures}/<category>/  <- named groups
#   results/<custom-selection>/{csv,figures}/<category>/  <- hand-picked aggregate
# A single-subject run (string OR one-element list) produces only that one folder.
#
# results/ is NOT wiped each run. Only the folders THIS run (re)makes are cleared
# of stale content: the selected subject/group folder here, plus each selected
# subject/group folder in the discovery cell. Folders are created lazily as
# outputs are written, so an interrupted run never leaves empty shells, and
# folders from other runs are left in place. Legacy results_old is untouched.
# There is no _group_level staging folder: a single-subject selection stays in
# results/<subject>/, and group selections stay in results/<group>/ or
# results/<custom-selection>/.
FILTER_TAG = "fillter"
RESULTS_ROOT = (ANALYSIS_DIR / "result_fillter").resolve()
RUN_OUTPUT_ROOT = (RESULTS_ROOT / SELECTION_LABEL).resolve()
OUTPUT_ROOT = RUN_OUTPUT_ROOT
FILTERED_Z_TRACKING_ROOT = (RESULTS_ROOT / "filtered_z_tracking_sources" / f"{SELECTION_LABEL}_{FILTER_TAG}").resolve()

# Keep False to avoid deleting previous filtered outputs by accident. If you want
# a clean filtered rerun, set True; it clears only paths inside result_fillter.
CLEAR_PREVIOUS_FILTER_OUTPUT = False

assert RESULTS_ROOT.name == "result_fillter", RESULTS_ROOT
assert OUTPUT_ROOT.is_relative_to(RESULTS_ROOT), (OUTPUT_ROOT, RESULTS_ROOT)
assert FILTERED_Z_TRACKING_ROOT.is_relative_to(RESULTS_ROOT), (FILTERED_Z_TRACKING_ROOT, RESULTS_ROOT)
if CLEAR_PREVIOUS_FILTER_OUTPUT:
    ka.reset_output_root(RUN_OUTPUT_ROOT)
    ka.reset_output_root(FILTERED_Z_TRACKING_ROOT)
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
FILTERED_Z_TRACKING_ROOT.mkdir(parents=True, exist_ok=True)

CENTER_X = 320.0
CENTER_Y = 240.0
LOWPASS_CUTOFF_HZ = 3.0
HIGHPASS_CUTOFF_HZ = 0.10
TRAJECTORY_TIME_BINS = 50
SIDE_VIDEO_SAMPLES_PER_TRIAL = 30  # samples from filtered z_tracking.csv; no video decoding
MAX_TRACKING_TRIALS = None        # set a number for debugging only
MAX_SIDE_VIDEO_TRIALS = None      # set a number for debugging only
FIG_DPI = 160

# Filterization: per z_tracking trajectory, replace the upper 5% values with
# interpolated values and then apply a short centered rolling median (LPF-like).
UPPER_TAIL_FRACTION = 0.05
ROLLING_WINDOW_SAMPLES = 5
FILTER_VALUE_COLUMNS = tuple(getattr(ka, "Z_TRACKING_VALUE_COLUMNS", (
    "z_active_finger_lift_px",
    "z_hand_midpoint_lift_px",
    "z_thumb_lift_px",
)))

print("ANALYSIS_DIR", ANALYSIS_DIR.resolve())
print("DATA_ROOT", DATA_ROOT)
print("DATA_SELECTION", DATA_SELECTION, "->", SELECTION_LABEL)
print("EXCLUDE_FILTER_FOLDERS", EXCLUDE_FILTER_FOLDERS)
print("RUN_OUTPUT_ROOT", RUN_OUTPUT_ROOT.resolve())
print("OUTPUT_ROOT", OUTPUT_ROOT.resolve())
print("FILTERED_Z_TRACKING_ROOT", FILTERED_Z_TRACKING_ROOT.resolve())
print("FILTER_TAG", FILTER_TAG)

ANALYSIS_DIR C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics
DATA_ROOT C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\results
DATA_SELECTION L_N_E -> L_N_E
EXCLUDE_FILTER_FOLDERS True
RUN_OUTPUT_ROOT C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\result_fillter\L_N_E
OUTPUT_ROOT C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\result_fillter\L_N_E
FILTERED_Z_TRACKING_ROOT C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\result_fillter\filtered_z_tracking_sources\L_N_E_fillter
FILTER_TAG fillter

## 1b. Create filtered `z_tracking.csv` copies

This notebook writes filtered copies named `z_tracking_fillter.csv` into `result_fillter/filtered_z_tracking_sources/...`.
The raw `z_tracking.csv` files are never changed.

For each z value column, the filter:
1. Finds the 95th percentile inside that file/trajectory.
2. Marks values above that threshold as the maximum 5% spike set.
3. Replaces those spike values by interpolation.
4. Applies a short centered rolling median as a low-pass-like smoother.

The downstream side-Z loader is patched only in notebook memory so `estimate_side_video_z()` consumes these filtered CSV copies and never decodes video.

In [5]:
def _safe_relative_path(path: Path, root: Path) -> Path:
    path = Path(path).resolve()
    root = Path(root).resolve()
    try:
        return path.relative_to(root)
    except ValueError:
        return Path(ka.sanitize_name(str(path).replace(":", "")))


def fillter_z_tracking_frame(raw: pd.DataFrame) -> tuple[pd.DataFrame, list[dict[str, object]]]:
    """Filter upper-tail z spikes in one z_tracking trajectory.

    Original values are kept in `*_raw_unfilltered`; filtered values replace the
    original z columns so downstream kinematic calculations use the filtered
    trajectory.
    """
    out = raw.copy()
    out["fillter_tag"] = FILTER_TAG
    out["fillter_upper_tail_fraction"] = float(UPPER_TAIL_FRACTION)
    out["fillter_rolling_window_samples"] = int(ROLLING_WINDOW_SAMPLES or 1)
    stats: list[dict[str, object]] = []
    for col in FILTER_VALUE_COLUMNS:
        if col not in out.columns:
            continue
        values = pd.to_numeric(out[col], errors="coerce")
        valid = values.dropna()
        out[f"{col}_raw_unfilltered"] = values
        if valid.empty:
            out[f"{col}_fillter_removed_upper_tail"] = 0
            out[f"{col}_fillter_threshold_p95"] = np.nan
            stats.append({"column": col, "n_rows": len(out), "n_valid": 0, "threshold": np.nan, "n_removed": 0, "removed_fraction": np.nan})
            continue
        threshold = float(valid.quantile(1.0 - UPPER_TAIL_FRACTION))
        high_mask = values > threshold
        filtered = values.mask(high_mask).interpolate(method="linear", limit_direction="both")
        if ROLLING_WINDOW_SAMPLES and int(ROLLING_WINDOW_SAMPLES) > 1:
            filtered = filtered.rolling(int(ROLLING_WINDOW_SAMPLES), center=True, min_periods=1).median()
        out[col] = filtered
        out[f"{col}_fillter_removed_upper_tail"] = high_mask.fillna(False).astype(int)
        out[f"{col}_fillter_threshold_p95"] = threshold
        stats.append({
            "column": col,
            "n_rows": len(out),
            "n_valid": int(valid.shape[0]),
            "threshold": threshold,
            "n_removed": int(high_mask.sum()),
            "removed_fraction": float(high_mask.sum() / max(valid.shape[0], 1)),
        })
    return out, stats


def fillter_one_z_tracking_csv(raw_z_path: Path) -> tuple[Path | None, list[dict[str, object]]]:
    """Read one raw z_tracking.csv and save its filtered copy under result_fillter."""
    raw_z_path = Path(raw_z_path).resolve()
    if not raw_z_path.exists():
        return None, [{"status": "missing_z_tracking_csv", "raw_z_tracking_file": str(raw_z_path)}]
    raw = ka.read_csv_flexible(raw_z_path)
    filtered, stats = fillter_z_tracking_frame(raw)
    rel = _safe_relative_path(raw_z_path, DATA_ROOT)
    if rel.name.lower() == "z_tracking.csv":
        rel = rel.with_name("z_tracking_fillter.csv")
    else:
        rel = rel.with_name(f"{rel.stem}_fillter{rel.suffix}")
    filtered_z_path = (FILTERED_Z_TRACKING_ROOT / rel).resolve()
    assert filtered_z_path.is_relative_to(RESULTS_ROOT), filtered_z_path
    filtered_z_path.parent.mkdir(parents=True, exist_ok=True)
    filtered.to_csv(filtered_z_path, index=False)
    rows = []
    for stat in stats:
        rows.append({
            "status": "ok",
            "filter_tag": FILTER_TAG,
            "raw_z_tracking_file": str(raw_z_path),
            "filtered_z_tracking_file": str(filtered_z_path),
            "source_pair_dir": str(raw_z_path.parent),
            **stat,
        })
    return filtered_z_path, rows


def prepare_filltered_z_tracking_sources(trial_file_manifest: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, Path]]:
    """Filter selected z_tracking files and map raw pair folders to filtered pair folders."""
    rows: list[dict[str, object]] = []
    pair_dir_map: dict[str, Path] = {}
    if trial_file_manifest.empty or "side_video_file" not in trial_file_manifest.columns:
        return pd.DataFrame(), pair_dir_map
    side_files = trial_file_manifest["side_video_file"].dropna().astype(str).drop_duplicates().sort_values()
    for side_file in side_files:
        # `side_video_file` is used only as a path locator for sibling z_tracking.csv.
        # No video file is opened or decoded here.
        raw_pair_dir = Path(side_file).parent.resolve()
        filtered_z_path, stat_rows = fillter_one_z_tracking_csv(raw_pair_dir / "z_tracking.csv")
        if filtered_z_path is not None:
            pair_dir_map[str(raw_pair_dir)] = filtered_z_path.parent
        rows.extend(stat_rows)
    return pd.DataFrame(rows), pair_dir_map


FILTERED_PAIR_DIR_BY_RAW_PAIR_DIR: dict[str, Path] = {}
_ORIGINAL_LOAD_Z_TRACKING_CSV = ka._load_z_tracking_csv
_ORIGINAL_Z_TRACKING_FILENAME = getattr(ka, "Z_TRACKING_FILENAME", "z_tracking.csv")


def load_filltered_z_tracking_csv(side_video: Path) -> pd.DataFrame:
    """Notebook-local side-Z loader: read filtered z_tracking.csv only."""
    raw_pair_dir = Path(side_video).parent.resolve()
    filtered_pair_dir = FILTERED_PAIR_DIR_BY_RAW_PAIR_DIR.get(str(raw_pair_dir))
    if filtered_pair_dir is None:
        expected = FILTERED_Z_TRACKING_ROOT / _safe_relative_path(raw_pair_dir / "z_tracking.csv", DATA_ROOT)
        expected = expected.with_name("z_tracking_fillter.csv")
        return pd.DataFrame({
            "z_tracking_file": [str(expected)],
            "z_tracking_warning": ["missing_filltered_z_tracking_csv"],
            "fillter_tag": [FILTER_TAG],
        })
    # The original loader only looks for sibling z_tracking.csv; the fake mp4 path
    # is never opened. This preserves all existing z_tracking parsing behavior.
    previous_filename = getattr(ka, "Z_TRACKING_FILENAME", "z_tracking.csv")
    ka.Z_TRACKING_FILENAME = "z_tracking_fillter.csv"
    try:
        loaded = _ORIGINAL_LOAD_Z_TRACKING_CSV(Path(filtered_pair_dir) / "side_camera.mp4")
    finally:
        ka.Z_TRACKING_FILENAME = previous_filename
    if isinstance(loaded, pd.DataFrame):
        loaded["fillter_tag"] = FILTER_TAG
        if "side_z_source" in loaded.columns:
            loaded["side_z_source"] = loaded["side_z_source"].astype(str) + f":{FILTER_TAG}"
    return loaded

## 1. Discover trials and filter side-Z CSV inputs

Each selected `answers.csv` row is mapped to `pair_NNN/tracking.csv` and sibling `pair_NNN/z_tracking.csv`.
`side_camera.mp4` path metadata is used only as a folder locator by the existing manifest format; the notebook does not decode video.

In [6]:
trial_file_manifest = ka.discover_trials(
    DATA_ROOT,
    selection=DATA_SELECTION,
    exclude_filter_folders=EXCLUDE_FILTER_FOLDERS,
)
trial_file_manifest["filter_tag"] = FILTER_TAG
ka.save_csv(trial_file_manifest, OUTPUT_ROOT, "trial_file_manifest.csv")
ka.save_experiment_setup_context(OUTPUT_ROOT)

# Clean only result_fillter folders if explicitly requested. Raw data and the
# original analysis/Kinematics/results tree are never touched by this notebook.
_run_root = RUN_OUTPUT_ROOT.resolve()
_selected_subjects = sorted(
    {str(s) for s in trial_file_manifest.get("subject_id", pd.Series(dtype=str)).dropna().unique()}
)
if CLEAR_PREVIOUS_FILTER_OUTPUT:
    _owners = set(_selected_subjects) | set(ka.COMBINED_EXPERIMENT_GROUPS.get(SELECTION_LABEL, ()))
    for _owner in sorted(_owners):
        _owner_dir = (RESULTS_ROOT / ka.sanitize_name(_owner)).resolve()
        assert _owner_dir.is_relative_to(RESULTS_ROOT), _owner_dir
        if _owner_dir == _run_root or _owner_dir in _run_root.parents:
            continue
        ka.clear_output_root(_owner_dir)

z_tracking_filter_manifest, FILTERED_PAIR_DIR_BY_RAW_PAIR_DIR = prepare_filltered_z_tracking_sources(trial_file_manifest)
ka.save_csv(z_tracking_filter_manifest, OUTPUT_ROOT, "z_tracking_fillter_manifest.csv")

# Patch only this notebook's in-memory module. Existing .py/.ipynb files are unchanged.
ka._load_z_tracking_csv = load_filltered_z_tracking_csv

print("Discovered rows:", trial_file_manifest.shape)
print("Selected subjects:", len(_selected_subjects), _selected_subjects)
print("Filtered z_tracking files:", len(FILTERED_PAIR_DIR_BY_RAW_PAIR_DIR))
display(trial_file_manifest.groupby(["subject_group", "selected", "tracking_exists", "side_video_exists"], dropna=False).size().reset_index(name="n"))
display(z_tracking_filter_manifest.head(30))

Discovered rows: (10240, 27)
Selected subjects: 40 ['L_E_1', 'L_E_10', 'L_E_11', 'L_E_12', 'L_E_14', 'L_E_15', 'L_E_16', 'L_E_17', 'L_E_18', 'L_E_2', 'L_E_20', 'L_E_21', 'L_E_22', 'L_E_3', 'L_E_4', 'L_E_5', 'L_E_6', 'L_E_7', 'L_E_8', 'L_E_9', 'N_E_1', 'N_E_11', 'N_E_12', 'N_E_13', 'N_E_14', 'N_E_15', 'N_E_16', 'N_E_17', 'N_E_18', 'N_E_19', 'N_E_2', 'N_E_20', 'N_E_21', 'N_E_3', 'N_E_4', 'N_E_5', 'N_E_6', 'N_E_7', 'N_E_8', 'N_E_9']
Filtered z_tracking files: 10240

  subject_group  selected  tracking_exists  side_video_exists     n
0             L      True             True               True  5120
1             N      True             True               True  5120

,status,filter_tag,raw_z_tracking_file,filtered_z_tracking_file,source_pair_dir,column,n_rows,n_valid,threshold,n_removed,removed_fraction
0,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,475,475,16.972588,24,0.050526
1,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,475,0,NaN,0,NaN
2,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,475,0,NaN,0,NaN
3,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,384,384,16.895755,20,0.052083
4,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,384,0,NaN,0,NaN
5,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,384,0,NaN,0,NaN
6,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,392,392,15.140633,20,0.051020
7,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,392,0,NaN,0,NaN
8,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,392,0,NaN,0,NaN
9,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,336,336,19.352026,16,0.047619
10,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,336,0,NaN,0,NaN
11,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,336,0,NaN,0,NaN
12,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,349,349,18.129135,18,0.051576
13,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,349,0,NaN,0,NaN
14,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,349,0,NaN,0,NaN
15,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,394,394,19.232427,20,0.050761
16,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,394,0,NaN,0,NaN
17,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,394,0,NaN,0,NaN
18,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,419,419,17.348562,21,0.050119
19,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,419,0,NaN,0,NaN
20,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,419,0,NaN,0,NaN
21,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,289,289,18.761625,15,0.051903
22,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,289,0,NaN,0,NaN
23,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,289,0,NaN,0,NaN
24,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,452,452,22.190389,23,0.050885
25,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,452,0,NaN,0,NaN
26,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,452,0,NaN,0,NaN
27,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_active_finger_lift_px,393,393,23.840985,20,0.050891
28,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_hand_midpoint_lift_px,393,0,NaN,0,NaN
29,ok,fillter,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,z_thumb_lift_px,393,0,NaN,0,NaN

## 2. XY kinematics from tracking.csv

For every tracking sample the notebook computes location relative to center, polar orientation, LPF/HPF position components, velocity, acceleration, movement direction, radial velocity, and tangential velocity.

In [7]:
kin = ka.compute_tracking_kinematics(
    trial_file_manifest,
    center_x=CENTER_X,
    center_y=CENTER_Y,
    lowpass_cutoff_hz=LOWPASS_CUTOFF_HZ,
    highpass_cutoff_hz=HIGHPASS_CUTOFF_HZ,
    n_time_bins=TRAJECTORY_TIME_BINS,
    max_trials=MAX_TRACKING_TRIALS,
)
kinematic_samples = kin["samples"]
trial_kinematic_summary = kin["trial_summary"]          # one row per participant x pair x stiffness segment
pair_kinematic_summary = kin["pair_summary"]            # one row per recorded pair
trajectory_time_bins = kin["time_bins"]                  # time normalized within each stiffness segment

ka.save_parquet(kinematic_samples, OUTPUT_ROOT, "kinematic_samples.parquet")
ka.save_csv(pair_kinematic_summary, OUTPUT_ROOT, "pair_kinematic_summary.csv")
ka.save_csv(trial_kinematic_summary, OUTPUT_ROOT, "trial_kinematic_summary.csv")
ka.save_csv(trajectory_time_bins, OUTPUT_ROOT, "trajectory_time_bins.csv")
print("samples", kinematic_samples.shape, "stiffness trials", trial_kinematic_summary.shape, "pairs", pair_kinematic_summary.shape, "time bins", trajectory_time_bins.shape)
display(trial_kinematic_summary.head())

samples (3575955, 87) stiffness trials (20480, 108) pairs (10240, 33) time bins (1021379, 86)

,subject_id,subject_group,experiment_group,selected,source_file,run_dir,trial_index_raw,pair_dir,tracking_file,side_video_file,top_video_file,tracking_exists,side_video_exists,pair_number,object_1_finger,object_1_stiffness,object_2_finger,object_2_stiffness,finger_condition,time_to_answer_s,answer_code,comparison_value,standard_value,signed_stiffness_delta,correct_response,warning,filter_tag,tracking_warning,stiffness_value,skin_stretch_gain_mm_per_m,stiffness_segment_id,stiffness_order_in_trial,stiffness_start_time_s,stiffness_end_time_s,stiffness_start_fraction,stiffness_end_fraction,n_tracking_samples,duration_s,pair_duration_s,sampling_rate_hz,mean_x_centered_px,mean_y_centered_px,mean_x_workspace_cm,mean_y_workspace_cm,mean_r_workspace_cm,mean_r_workspace_normalized,workspace_setup,workspace_label,workspace_width_cm,workspace_height_cm,side_camera_side,participant_position_context,movement_space_context,side_camera_interpretation_note,mean_r_center_px,max_r_center_px,max_r_workspace_cm,mean_thumb_active_span_px,mean_thumb_active_span_cm,mean_hand_orientation_xy_deg,path_length_px,path_length_cm,net_displacement_px,net_displacement_cm,straightness_index,straightness_index_cm,mean_vx_px_s,mean_vy_px_s,mean_speed_px_s,max_speed_px_s,mean_vx_cm_s,mean_vy_cm_s,mean_speed_cm_s,max_speed_cm_s,mean_ax_px_s2,mean_ay_px_s2,mean_acceleration_px_s2,max_acceleration_px_s2,mean_ax_cm_s2,mean_ay_cm_s2,mean_acceleration_cm_s2,max_acceleration_cm_s2,mean_jerk_px_s3,max_jerk_px_s3,mean_jerk_cm_s3,max_jerk_cm_s3,normalized_jerk_cost,normalized_jerk_cost_cm,mean_curvature_1_px,median_curvature_1_px,mean_curvature_1_cm,median_curvature_1_cm,speed_curvature_power_law_slope,speed_curvature_power_law_intercept,speed_curvature_power_law_r2,speed_curvature_power_law_n,mean_radial_velocity_px_s,mean_abs_radial_velocity_px_s,mean_abs_tangential_velocity_px_s,mean_radial_velocity_cm_s,mean_abs_radial_velocity_cm_s,mean_abs_tangential_velocity_cm_s,dominant_movement_angle_deg,dominant_movement_angle_cm_deg,dominant_movement_direction,movement_direction_resultant_length,movement_direction_entropy_bits,mean_skin_stretch_gain_mm_per_m
0,L_E_1,L,L_E,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,13,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,True,True,13,M,115.0,M,85.0,M,2.062190,0.0,115.0,85.0,30.0,1.0,,fillter,,115.0,115.0,1,1,0.000000,6.090795,0.000000,0.554307,395,6.090795,10.988135,64.989927,-9.157982,-59.425192,-1.144748,-7.428149,9.352625,0.187052,L,L workspace (80x60 cm),80.0,60.0,right,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,74.820996,162.635709,20.329464,86.773772,10.846721,-56.394513,616.111538,77.013942,0.0,0.0,0.0,0.0,30.972569,30.186605,123.639737,272.542578,3.871571,3.773326,15.454967,34.067822,16.140267,-13.893344,609.489226,3987.902646,2.017533,-1.736668,76.186153,498.487831,48410.531716,446845.502570,6051.316464,55855.687821,1.350577e+08,1.350577e+08,0.011706,0.011706,0.093649,0.093649,-0.414951,2.799818,0.672962,263,0.0,62.351375,28.448091,0.0,7.793922,3.556011,-1.310150,-1.310150,SSE,0.014877,3.055338,115.0
1,L_E_1,L,L_E,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,13,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,True,True,13,M,115.0,M,85.0,M,2.062190,0.0,115.0,85.0,30.0,1.0,,fillter,,85.0,85.0,2,2,6.106709,10.988135,0.555755,1.000000,311,4.881426,10.988135,64.989927,-11.421103,-32.111077,-1.427638,-4.013885,6.179038,0.123581,L,L workspace (80x60 cm),80.0,60.0,right,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,49.432303,154.227214,19.278402,89.346057,11.168257,-56.500063,718.561113,89.820139,0.0,0.0,0.0,0.0,9.561001,9.375602,136.019724,278.400383,1.195125,1.171950,17.002465,34.800048,-61.256687,-10.155136,849.059672,4441.325059,-7.657086,-1.269392,106.132459,555.165632,53186.015338,442850.798477,6648.251917,55356.349810,1.838970e+08,1.838970e+08,0.014381,0.014381,0.115045,0.115045,-0.410160,2.988547,0.680633,274,0.0,80.812444,32.082642,0.0,10.101555,4.010330,-114.220433,-114.220433,SW,0.012215,3.361975,85.0
2,L_E_1,L,L_E,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,14,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,True,True,14,M,55.0,M,85.0,M,1.823390,1.0,55.0,85.0,-30.0,1.0,,fillter,,55.0,55.0,1,1,0.000000,6.137792,0.000000,0.610143,395,6.137792,10.059589,64.701886,-11.398621,-31.948865,-1.424828,-3.993608,11.709771,0.234195,L,L workspace (80x60 cm),80.0,60.0,right,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,93.678166,223.225636,27.903205,85.985478,10.748185,-63.240152,801.266792,100.158349,0.0,0.0,0.0,0.0,9.656892,11.441294,158.291053,309.342501,1.207112,1.430162,19.786382,38.667813,-14.937695,5.919789,625.584567,5123.882625,-1.867212,0.739974,78.198071,640.485328,49386.745115,656307.287300,6173.343139,82038.410913,3.497844e+08,3.497844e+08,0.009696,0.009696,0.077568,0.077568,-0.438688,2.729791,0.757633,314,0.0,57.041164,36.228143,0.0,7.130145,4.528518,-16.388466,-16.388466,SSE,0.005768,3.287154,55.0
3,L_E_1,L,L_E,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,14,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,True,True,14,M,55.0,M,85.0,M,1.823390,1.0,55.0,85.0,-30.0,1.0,,fillter,,85.0,85.0,2,2,6.152687,10.059589,0.611624,1.000000,250,3.906902,10.059589,64.701886,-1.981895,-56.017542,-0.247737,-7.002193,13.511619,0.270232,L,L workspace (80x60 cm),80.0,60.0,right,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,108.092951,166.722641,20.840330,87.167373,10.895922,-58.361915,648.536734,81.067092,0.0,0.0,0.0,0.0,43.992075,45.624880,191.077933,425.660584,5.499009,5.703110,23.884742,53.207573,43.206757,-19.772474,988.972379,4923.110570,5.400845,-2.471559,123.621547,615.388821,65786.572850,530870.997281,8223.321606,66358.874660,6.650237e+07,6.650237e+07,0.009022,0.009022,0.072172,0.072172,-0.442239,2.907898,0.611695,210,0.0,83.621922,42.998374,0.0,10.452740,5.374797,-68.538871,-68.538871,SSW,0.012931,3.006188,85.0
4,L_E_1,L,L_E,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,15,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,True,True,15,M,40.0,M,85.0,M,1.864983,1.0,40.0,85.0,-45.0,1.0,,fillter,,40.0,40.0,1,1,0.000000,4.480564,0.000000,0.602195,287,4.480564,7.440391,64.903456,-9.553811,-57.968652,-1.194226,-7.246082,12.761761,0.255235,L,L workspace (80x60 cm),80.0,60.0,right,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,102.094091,163.189646,20.398706,90.283952,11.285494,-58.568464,580.418012,72.552251,0.0,0.0,0.0,0.0,17.904535,20.136250,205.039467,305.778924,2.238067,2.517031,25.629933,38.222365,-5.200373,62.303747,1070.083521,6022.254961,-0.650047,7.787968,133.760440,752.781870,85639.210927,681663.205106,10704.901366,85207.900638,6.384354e+07,6.384354e+07,0.010056,0.010056,0.080448,0.080448,-0.403048,3.231079,0.533787,192,0.0,86.229592,64.586411,0.0,10.778699,8.073301,-74.899318,-74.899318,SSW,0.007261,3.214884,40.0

## 3. Direction, distance, and success summaries

These tables test whether movement direction, distance from center, speed, or acceleration are associated with selection accuracy.

In [8]:
summaries = ka.summarize_kinematics(trial_kinematic_summary, trajectory_time_bins)
direction_success_summary = summaries["direction_success"]
distance_success_summary = summaries["distance_success"]
subject_kinematic_summary = summaries["subject_summary"]
participant_stiffness_kinematic_summary = summaries["participant_stiffness_summary"]
stiffness_kinematic_summary = summaries["stiffness_summary"]
group_time_summary = summaries["group_time"]
stiffness_time_summary = summaries["stiffness_time"]
kinematic_group_metric_summary = summaries["kinematic_group_metric_summary"]
kinematic_group_condition_metric_summary = summaries["kinematic_group_condition_metric_summary"]
kinematic_within_group_condition_comparisons = summaries["kinematic_within_group_condition_comparisons"]
kinematic_between_group_metric_comparisons = summaries["kinematic_between_group_metric_comparisons"]
kinematic_expanded_scope_metric_summary = summaries.get("kinematic_expanded_scope_metric_summary", pd.DataFrame())
kinematic_expanded_scope_pairwise_mean_differences = summaries.get("kinematic_expanded_scope_pairwise_mean_differences", pd.DataFrame())
kinematic_expanded_scope_status = summaries.get("kinematic_expanded_scope_status", pd.DataFrame())

ka.save_csv(direction_success_summary, OUTPUT_ROOT, "direction_success_summary.csv")
ka.save_csv(distance_success_summary, OUTPUT_ROOT, "distance_success_summary.csv")
ka.save_csv(subject_kinematic_summary, OUTPUT_ROOT, "subject_kinematic_summary.csv")
ka.save_csv(participant_stiffness_kinematic_summary, OUTPUT_ROOT, "participant_stiffness_kinematic_summary.csv")
ka.save_csv(stiffness_kinematic_summary, OUTPUT_ROOT, "stiffness_kinematic_summary.csv")
ka.save_parquet(group_time_summary, OUTPUT_ROOT, "group_time_summary.parquet")
ka.save_csv(stiffness_time_summary, OUTPUT_ROOT, "stiffness_time_summary.csv")
ka.save_csv(kinematic_group_metric_summary, OUTPUT_ROOT, "kinematic_group_metric_summary.csv")
ka.save_csv(kinematic_group_condition_metric_summary, OUTPUT_ROOT, "kinematic_group_condition_metric_summary.csv")
ka.save_csv(kinematic_within_group_condition_comparisons, OUTPUT_ROOT, "kinematic_within_group_condition_comparisons.csv")
ka.save_csv(kinematic_between_group_metric_comparisons, OUTPUT_ROOT, "kinematic_between_group_metric_comparisons.csv")
ka.save_csv(kinematic_expanded_scope_metric_summary, OUTPUT_ROOT, "kinematic_expanded_scope_metric_summary.csv")
ka.save_csv(kinematic_expanded_scope_pairwise_mean_differences, OUTPUT_ROOT, "kinematic_expanded_scope_pairwise_mean_differences.csv")
ka.save_csv(kinematic_expanded_scope_status, OUTPUT_ROOT, "kinematic_expanded_scope_status.csv")

print("Direction x success per participant/stiffness")
display(direction_success_summary.sort_values(["subject_id", "stiffness_value", "finger_condition", "dominant_movement_direction"]).head(40))
print("Participant x stiffness kinematic summary")
display(participant_stiffness_kinematic_summary.head(40))
print("All participants by stiffness")
display(stiffness_kinematic_summary.sort_values("stiffness_value").head(40))

print("N_E / L_E / L_P kinematic group summary")
display(kinematic_group_metric_summary.head(80))
print("Between-group kinematic comparisons")
display(kinematic_between_group_metric_comparisons.head(80))
print("Expanded requested scopes: all, protocol, E/P, N/L, sex, age, stiffness, finger, success/failure")
display(kinematic_expanded_scope_status)
display(kinematic_expanded_scope_metric_summary.head(120))

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Direction x success per participant/stiffness

,subject_id,subject_group,experiment_group,workspace_setup,side_camera_side,participant_position_context,stiffness_value,finger_condition,dominant_movement_direction,n_trials,success_rate,mean_x_workspace_cm,mean_y_workspace_cm,mean_speed_cm_s,mean_r_workspace_cm,mean_path_length_cm,mean_x_centered_px,mean_y_centered_px,mean_speed_px_s,mean_r_center_px,mean_path_length_px
0,L_E_1,L,L_E,L,right,slightly_left,25.0,I,NNE,1,1.000000,-1.148528,-2.611585,26.629379,12.916837,75.357588,-9.188223,-20.892677,213.035030,103.334700,602.860700
1,L_E_1,L,L_E,L,right,slightly_left,25.0,I,SE,1,1.000000,-1.409438,-7.534572,31.988070,13.601124,84.240510,-11.275504,-60.276575,255.904558,108.808988,673.924076
2,L_E_1,L,L_E,L,right,slightly_left,25.0,I,SW,1,1.000000,-0.880394,-9.066423,31.113887,12.957877,79.824797,-7.043152,-72.531381,248.911098,103.663014,638.598375
3,L_E_1,L,L_E,L,right,slightly_left,25.0,I,W,2,1.000000,-0.257697,-8.157498,32.361963,12.967205,80.764452,-2.061572,-65.259987,258.895702,103.737640,646.115613
4,L_E_1,L,L_E,L,right,slightly_left,25.0,I,WSW,3,1.000000,-1.322667,-5.600028,28.510509,11.540271,72.819713,-10.581337,-44.800222,228.084074,92.322164,582.557700
5,L_E_1,L,L_E,L,right,slightly_left,25.0,M,NNE,1,1.000000,-3.984179,-8.342406,29.307770,13.782894,82.054533,-31.873436,-66.739247,234.462161,110.263150,656.436265
6,L_E_1,L,L_E,L,right,slightly_left,25.0,M,SSW,3,1.000000,1.133361,-7.562040,24.276011,13.087933,127.766697,9.066888,-60.496323,194.208089,104.703462,1022.133577
7,L_E_1,L,L_E,L,right,slightly_left,25.0,M,W,1,1.000000,0.228845,-2.058463,31.382553,12.094898,98.920082,1.830758,-16.467705,251.060428,96.759182,791.360653
8,L_E_1,L,L_E,L,right,slightly_left,25.0,M,WSW,3,1.000000,-1.506433,-5.771032,24.754577,13.270873,86.858813,-12.051464,-46.168256,198.036613,106.166981,694.870502
9,L_E_1,L,L_E,L,right,slightly_left,25.0,P,ESE,1,1.000000,1.319302,-6.272842,12.903469,6.431291,38.940475,10.554419,-50.182736,103.227750,51.450327,311.523798
10,L_E_1,L,L_E,L,right,slightly_left,25.0,P,NE,1,1.000000,2.841665,-9.475622,16.244773,11.287362,69.214262,22.733322,-75.804977,129.958180,90.298896,553.714097
11,L_E_1,L,L_E,L,right,slightly_left,25.0,P,S,1,1.000000,-8.176980,5.109658,25.780100,9.790543,62.041903,-65.415840,40.877266,206.240800,78.324346,496.335226
12,L_E_1,L,L_E,L,right,slightly_left,25.0,P,SE,1,1.000000,-0.817436,-6.159192,13.593783,6.476924,46.097824,-6.539492,-49.273539,108.750262,51.815393,368.782595
13,L_E_1,L,L_E,L,right,slightly_left,25.0,P,SSE,1,1.000000,0.728066,7.384304,22.664560,15.258332,86.676111,5.824529,59.074430,181.316478,122.066655,693.408886
14,L_E_1,L,L_E,L,right,slightly_left,25.0,P,SSW,1,1.000000,0.250669,-9.591773,24.596500,13.619979,70.925613,2.005348,-76.734180,196.771998,108.959828,567.404905
15,L_E_1,L,L_E,L,right,slightly_left,25.0,P,SW,1,1.000000,-0.925889,-7.376976,14.953916,7.445994,36.295366,-7.407112,-59.015808,119.631328,59.567954,290.362930
16,L_E_1,L,L_E,L,right,slightly_left,25.0,P,WSW,1,1.000000,0.059065,0.370013,17.421602,13.979690,132.572706,0.472519,2.960100,139.372813,111.837516,1060.581646
17,L_E_1,L,L_E,L,right,slightly_left,25.0,R,NNE,1,1.000000,7.384813,-0.284334,13.171813,7.423659,49.543771,59.078503,-2.274670,105.374503,59.389270,396.350166
18,L_E_1,L,L_E,L,right,slightly_left,25.0,R,SE,2,1.000000,10.782152,-0.362408,13.029107,10.843227,53.195667,86.257219,-2.899267,104.232859,86.745815,425.565335
19,L_E_1,L,L_E,L,right,slightly_left,25.0,R,SSE,2,1.000000,12.150263,-0.228983,15.327703,12.156587,54.814031,97.202106,-1.831863,122.621620,97.252693,438.512244
20,L_E_1,L,L_E,L,right,slightly_left,25.0,R,W,3,1.000000,12.909548,-0.471802,14.694723,12.911006,54.253396,103.276386,-3.774415,117.557781,103.288046,434.027168
21,L_E_1,L,L_E,L,right,slightly_left,40.0,I,S,3,1.000000,2.246897,-4.817510,31.206795,14.048588,136.793889,17.975178,-38.540082,249.654362,112.388704,1094.351115
22,L_E_1,L,L_E,L,right,slightly_left,40.0,I,SSE,3,1.000000,1.476324,-9.165856,32.388095,14.373274,73.578178,11.810589,-73.326845,259.104760,114.986193,588.625423
23,L_E_1,L,L_E,L,right,slightly_left,40.0,I,SSW,1,1.000000,-0.270876,-5.127102,32.603024,13.053923,75.485413,-2.167005,-41.016812,260.824190,104.431381,603.883307
24,L_E_1,L,L_E,L,right,slightly_left,40.0,I,WSW,1,1.000000,0.698349,-8.629665,26.373908,12.410312,65.353039,5.586794,-69.037321,210.991261,99.282495,522.824313
25,L_E_1,L,L_E,L,right,slightly_left,40.0,M,ESE,1,1.000000,-0.792050,-3.621350,23.879816,11.053546,76.275652,-6.336403,-28.970797,191.038527,88.428371,610.205215
26,L_E_1,L,L_E,L,right,slightly_left,40.0,M,NE,1,1.000000,-3.363085,-10.141182,20.690679,12.928237,78.810530,-26.904678,-81.129456,165.525431,103.425896,630.484236
27,L_E_1,L,L_E,L,right,slightly_left,40.0,M,S,2,1.000000,-0.991268,-4.931086,25.342128,10.766611,87.246569,-7.930141,-39.448689,202.737026,86.132885,697.972550
28,L_E_1,L,L_E,L,right,slightly_left,40.0,M,SSE,2,1.000000,-2.747699,-6.997916,28.253716,12.387426,81.167813,-21.981593,-55.983331,226.029731,99.099406,649.342501
29,L_E_1,L,L_E,L,right,slightly_left,40.0,M,SSW,1,1.000000,-1.194226,-7.246082,25.629933,12.761761,72.552251,-9.553811,-57.968652,205.039467,102.094091,580.418012
30,L_E_1,L,L_E,L,right,slightly_left,40.0,M,SW,1,1.000000,-0.268164,-11.681144,23.839990,14.208397,77.197777,-2.145315,-93.449149,190.719919,113.667176,617.582214
31,L_E_1,L,L_E,L,right,slightly_left,40.0,P,E,1,1.000000,-0.418612,8.248934,24.348779,15.404890,154.613313,-3.348894,65.991468,194.790232,123.239124,1236.906502
32,L_E_1,L,L_E,L,right,slightly_left,40.0,P,NNE,1,1.000000,-0.351214,-8.360240,18.799004,8.363147,42.284483,-2.809715,-66.881919,150.392028,66.905177,338.275866
33,L_E_1,L,L_E,L,right,slightly_left,40.0,P,SSW,2,1.000000,-0.709155,-6.506704,17.016195,6.963163,58.659441,-5.673239,-52.053629,136.129559,55.705307,469.275529
34,L_E_1,L,L_E,L,right,slightly_left,40.0,P,W,3,0.666667,0.563635,-0.875106,17.601685,9.001123,53.787214,4.509076,-7.000852,140.813482,72.008986,430.297709
35,L_E_1,L,L_E,L,right,slightly_left,40.0,P,WSW,1,1.000000,6.512959,0.220903,14.343427,16.826125,125.337083,52.103672,1.767225,114.747416,134.609000,1002.696664
36,L_E_1,L,L_E,L,right,slightly_left,40.0,R,NNE,3,1.000000,9.051355,-0.278842,18.022298,9.052801,51.834109,72.410841,-2.230740,144.178384,72.422411,414.672873
37,L_E_1,L,L_E,L,right,slightly_left,40.0,R,SE,1,1.000000,9.865172,-0.137758,17.437411,9.885441,51.056416,78.921375,-1.102065,139.499290,79.083531,408.451329
38,L_E_1,L,L_E,L,right,slightly_left,40.0,R,SSW,1,1.000000,10.014247,0.020894,16.171354,10.016393,44.321374,80.113974,0.167155,129.370832,80.131140,354.570996
39,L_E_1,L,L_E,L,right,slightly_left,40.0,R,W,3,0.666667,9.262295,-0.131410,7.917850,9.290018,53.484767,74.098358,-1.051283,63.342799,74.320145,427.878133

Participant x stiffness kinematic summary

,subject_id,subject_group,experiment_group,workspace_setup,side_camera_side,participant_position_context,stiffness_value,finger_condition,n_trials,success_rate,mean_x_centered_px,mean_y_centered_px,mean_x_workspace_cm,mean_y_workspace_cm,mean_r_workspace_cm,mean_r_workspace_normalized,mean_max_r_center_px,mean_max_r_workspace_cm,mean_thumb_active_span_px,mean_thumb_active_span_cm,mean_hand_orientation_xy_deg,mean_hand_orientation_xy_cm_deg,mean_vx_px_s,mean_vy_px_s,mean_vx_cm_s,mean_vy_cm_s,mean_speed_px_s,mean_speed_cm_s,mean_ax_px_s2,mean_ay_px_s2,mean_ax_cm_s2,mean_ay_cm_s2,mean_acceleration_px_s2,mean_acceleration_cm_s2,mean_jerk_px_s3,mean_jerk_cm_s3,mean_normalized_jerk_cost,mean_normalized_jerk_cost_cm,mean_curvature_1_px,mean_curvature_1_cm,speed_curvature_power_law_slope,speed_curvature_power_law_r2,mean_path_length_px,mean_path_length_cm,mean_straightness_index,mean_straightness_index_cm,circular_mean_direction_deg,movement_direction_resultant_length
0,L_E_1,L,L_E,L,right,slightly_left,25.0,I,8,1.000000,-9.189720,-46.493343,-1.148715,-5.811668,12.937357,0.258747,176.218282,22.027285,65.999405,8.249926,-63.955510,NaN,45.216947,22.742699,5.652118,2.842837,245.026076,30.628260,55.741901,-5.359383,6.967738,-0.669923,1408.509583,176.063698,98607.300439,12325.912555,2.825172e+07,2.825172e+07,0.005753,0.046021,-0.328050,0.577481,620.729538,77.591192,0.000000,0.000000,-148.569588,0.686528
1,L_E_1,L,L_E,L,right,slightly_left,25.0,M,8,1.000000,-11.953369,-59.279457,-1.494171,-7.409932,13.179403,0.263588,212.316570,26.539571,82.316317,10.289540,-57.223924,NaN,38.009610,18.238002,4.751201,2.279750,216.249387,27.031173,47.298334,-46.777393,5.912292,-5.847174,1245.358128,155.669766,85776.813714,10722.101714,4.258448e+07,4.258448e+07,0.007779,0.062228,-0.345427,0.616404,699.243962,87.405495,0.000000,0.000000,-120.215714,0.767906
2,L_E_1,L,L_E,L,right,slightly_left,25.0,P,8,1.000000,1.238934,-49.728137,0.154867,-6.216017,10.538953,0.210779,171.594919,21.449365,106.776966,13.347121,-22.092501,NaN,0.443684,2.521100,0.055461,0.315137,134.665496,16.833187,-2.484058,-28.017591,-0.310507,-3.502199,774.374449,96.796806,61141.446603,7642.680825,4.737381e+07,4.737381e+07,0.007073,0.056580,-0.321488,0.626014,525.024661,65.628083,0.000000,0.000000,-43.961428,0.372481
3,L_E_1,L,L_E,L,right,slightly_left,25.0,R,8,1.000000,93.802452,-2.248256,11.725307,-0.281032,11.774526,0.235491,204.445885,25.555736,91.809184,11.476148,-27.440583,NaN,7.384698,0.052017,0.923087,0.006502,115.325174,14.415647,-4.191735,7.465567,-0.523967,0.933196,619.471306,77.433913,30304.281254,3788.035157,1.696625e+08,1.696625e+08,0.004180,0.033436,-0.417535,0.796598,426.603330,53.325416,0.000000,0.000000,-84.595068,0.095991
4,L_E_1,L,L_E,L,right,slightly_left,40.0,I,8,1.000000,8.698692,-63.319863,1.087336,-7.914983,13.680006,0.273600,192.351474,24.043934,63.782038,7.972755,-63.028480,NaN,15.573473,10.244637,1.946684,1.280580,254.109396,31.763674,5.011175,-3.969108,0.626397,-0.496139,1539.124095,192.390512,112686.688417,14085.836052,3.475786e+07,3.475786e+07,0.005249,0.041992,-0.353914,0.603494,675.005341,84.375668,0.000000,0.000000,-45.994214,0.806926
5,L_E_1,L,L_E,L,right,slightly_left,40.0,M,8,1.000000,-11.885674,-57.785693,-1.485709,-7.223212,12.387426,0.247749,181.227490,22.653436,83.443053,10.430382,-57.770629,NaN,42.573539,17.638831,5.321692,2.204854,199.681181,24.960148,32.769237,21.341882,4.096155,2.667735,1187.174238,148.396780,87918.214213,10989.776777,7.966027e+07,7.966027e+07,0.006705,0.053644,-0.394767,0.591016,639.251044,79.906380,0.000000,0.000000,-37.642225,0.560095
6,L_E_1,L,L_E,L,right,slightly_left,40.0,P,8,0.875000,-2.746983,-21.506703,-0.343373,-2.688338,8.770042,0.175401,193.106741,24.138343,110.793637,13.849205,-20.735187,NaN,-0.622391,0.963665,-0.077799,0.120458,145.434998,18.179375,-5.255981,-14.198003,-0.656998,-1.774750,717.236824,89.654603,59400.214786,7425.026848,4.289162e+07,4.289162e+07,0.006106,0.048845,-0.341044,0.666640,506.030033,63.253754,0.000000,0.000000,-145.536690,0.527575
7,L_E_1,L,L_E,L,right,slightly_left,40.0,R,8,0.875000,76.509867,-1.151504,9.563733,-0.143938,9.587730,0.191755,202.003989,25.250499,82.854374,10.356797,-27.337234,NaN,6.983108,0.645499,0.872888,0.080687,134.435061,16.804383,12.775399,3.434943,1.596925,0.429368,571.130472,71.391309,28414.956030,3551.869504,5.278141e+08,5.278141e+08,0.003268,0.026140,-0.441701,0.803617,415.065477,51.883185,0.000000,0.000000,-170.232392,0.583159
8,L_E_1,L,L_E,L,right,slightly_left,55.0,I,8,1.000000,15.563736,-68.417237,1.945467,-8.552155,14.256876,0.285138,194.805315,24.350664,63.829006,7.978626,-62.455229,NaN,-10.680359,4.645665,-1.335045,0.580708,229.380069,28.672509,19.013087,57.526168,2.376636,7.190771,1454.028807,181.753601,107898.746957,13487.343370,4.067129e+07,4.067129e+07,0.004337,0.034695,-0.362530,0.646316,840.776938,105.097117,0.000000,0.000000,135.198775,0.406645
9,L_E_1,L,L_E,L,right,slightly_left,55.0,M,8,0.875000,-11.929335,-79.208379,-1.491167,-9.901047,14.790537,0.295811,219.450120,27.431265,85.505626,10.688203,-57.131978,NaN,9.758757,6.954013,1.219845,0.869252,218.630018,27.328752,-2.096631,15.355735,-0.262079,1.919467,1189.447235,148.680904,85984.612913,10748.076614,2.117499e+08,2.117499e+08,0.007152,0.057215,-0.380971,0.665544,800.260511,100.032564,0.000000,0.000000,-122.341930,0.396314
10,L_E_1,L,L_E,L,right,slightly_left,55.0,P,8,1.000000,-2.498937,-49.079468,-0.312367,-6.134934,11.239938,0.224799,174.179677,21.772460,103.269373,12.908672,-23.420891,NaN,4.681272,2.965242,0.585159,0.370655,127.784377,15.973047,-5.251128,13.838613,-0.656391,1.729827,571.032836,71.379104,56390.410376,7048.801297,7.886414e+07,7.886414e+07,0.008774,0.070190,-0.376994,0.663753,537.026655,67.128332,0.000000,0.000000,-145.338517,0.354360
11,L_E_1,L,L_E,L,right,slightly_left,55.0,R,8,0.750000,98.461847,-0.082876,12.307731,-0.010360,12.345176,0.246904,205.406385,25.675798,87.526513,10.940814,-28.039101,NaN,8.248804,1.752099,1.031100,0.219012,117.573095,14.696637,-9.181750,0.580157,-1.147719,0.072520,612.803380,76.600423,31402.820604,3925.352575,1.801858e+08,1.801858e+08,0.003593,0.028743,-0.416418,0.747816,418.511776,52.313972,0.000000,0.000000,29.359809,0.451471
12,L_E_1,L,L_E,L,right,slightly_left,70.0,I,8,0.750000,3.849103,-65.170884,0.481138,-8.146361,14.363694,0.287274,188.218213,23.527277,64.783767,8.097971,-62.471718,NaN,20.568884,4.946210,2.571110,0.618276,222.414270,27.801784,52.152453,22.364534,6.519057,2.795567,1338.286819,167.285852,88651.475092,11081.434387,8.592928e+07,8.592928e+07,0.005667,0.045336,-0.361529,0.644023,761.094253,95.136782,0.000000,0.000000,-90.730478,0.471296
13,L_E_1,L,L_E,L,right,slightly_left,70.0,M,8,0.500000,-8.720093,-81.515644,-1.090012,-10.189455,16.459501,0.329190,195.739390,24.467424,85.937625,10.742203,-56.783727,NaN,31.250152,7.620720,3.906269,0.952590,189.060204,23.632525,25.324802,-2.087924,3.165600,-0.260991,1036.140273,129.517534,83779.574014,10472.446752,2.999129e+08,2.999129e+08,0.006468,0.051741,-0.390565,0.650505,883.634135,110.454267,0.000000,0.000000,-119.543924,0.560546
14,L_E_1,L,L_E,L,right,slightly_left,70.0,P,8,0.375000,-6.760624,-11.699269,-0.845078,-1.462409,11.438400,0.228768,200.591745,25.073968,109.089263,13.636158,-25.149038,NaN,-1.471001,-6.714269,-0.183875,-0.839284,160.706630,20.088329,-24.677495,9.826988,-3.084687,1.228374,759.992015,94.999002,59552.782359,7444.097795,1.274271e+08,1.274271e+08,0.006719,0.053752,-0.358953,0.686031,549.889506,68.736188,0.000000,0.000000,45.835460,0.174546
15,L_E_1,L,L_E,L,right,slightly_left,70.0,R,8,0.500000,91.399574,0.459516,11.424947,0.057440,11.461753,0.229235,214.754773,26.844347,79.570266,9.946283,-25.650110,NaN,7.070681,0.759626,0.883835,0.094953,104.363381,13.045423,-26.129838,-1.791920,-3.266230,-0.223990,577.111663,72.138958,28108.699069,3513.587384,2.289034e+08,2.289034e+08,0.003719,0.029751,-0.426054,0.759010,446.227064,55.778383,0.005853,0.005853,19.086388,0.387882
16,L_E_1,L,L_E,L,right,slightly_left,85.0,I,64,0.890625,0.555456,-65.477268,0.069432,-8.184658,14.823438,0.296469,192.938403,24.117300,64.407188,8.050898,-63.452489,NaN,22.355827,2.920327,2.794478,0.365041,237.200175,29.650022,32.905936,35.081849,4.113242,4.385231,1452.638741,181.579843,105501.378385,13187.672298,1.577506e+08,1.577506e+08,0.004614,0.036911,-0.364819,0.647971,984.598305,123.074788,0.000000,0.000000,-101.850617,0.284649
17,L_E_1,L,L_E,L,right,slightly_left,85.0,M,64,0.859375,-4.913099,-76.492016,-0.614137,-9.561502,15.136186,0.302724,200.305757,25.038220,83.132791,10.391599,-56.657633,NaN,20.077136,4.364735,2.509642,0.545592,202.466437,25.308305,7.326944,11.314678,0.915868,1.414335,1087.489346,135.936168,80720.400569,10090.050071,1.196438e+08,1.196438e+08,0.005906,0.047245,-0.369280,0.636222,875.280986,109.410123,0.000000,0.000000,-97.207872,0.387562
18,L_E_1,L,L_E,L,right,slightly_left,85.0,P,64,0.781250,0.402848,-39.387918,0.050356,-4.923490,11.920841,0.238417,182.544886,22.818111,106.129139,13.266142,-21.511912,NaN,2.299983,0.769500,0.287498,0.096187,146.434151,18.304269,-2.863020,10.193442,-0.357877,1.274180,715.627677,89.453460,58552.388294,7319.048537,9.817928e+07,9.817928e+07,0.007353,0.058824,-0.366316,0.683668,528.135269,66.016909,0.000000,0.000000,-126.074267,0.201183
19,L_E_1,L,L_E,L,right,slightly_left,85.0,R,64,0.718750,100.154533,-0.079778,12.519317,-0.009972,12.601881,0.252038,209.462790,26.182849,86.561483,10.820185,-26.703150,NaN,3.461564,0.789367,0.432696,0.098671,114.369851,14.296231,1.492156,0.715769,0.186520,0.089471,587.719463,73.464933,29584.308703,3698.038588,2.565474e+08,2.565474e+08,0.004002,0.032016,-0.422241,0.800791,432.270268,54.033783,0.006545,0.006545,-160.872232,0.045075
20,L_E_1,L,L_E,L,right,slightly_left,100.0,I,8,0.750000,6.411767,-64.217000,0.801471,-8.027125,16.030502,0.320610,184.934298,23.116787,64.852855,8.106607,-63.175029,NaN,-4.852242,-0.593154,-0.606530,-0.074144,250.322103,31.290263,-3.185417,38.727909,-0.398177,4.840989,1480.087345,185.010918,104282.383426,13035.297928,2.801107e+08,2.801107e+08,0.004342,0.034737,-0.388176,0.680935,1141.707263,142.713408,0.000000,0.000000,-17.838488,0.237049
21,L_E_1,L,L_E,L,right,slightly_left,100.0,M,8,0.750000,-10.758380,-89.138219,-1.344797,-11.142277,16.989746,0.339795,223.458583,27.932323,83.541175,10.442647,-56.203937,NaN,27.084703,7.707078,3.385588,0.963385,193.305869,24.163234,0.972541,24.831648,0.121568,3.103956,1128.693937,141.086742,81927.698253,10240.962282,2.479764e+08,2.479764e+08,0.005147,0.041175,-0.321057,0.597170,1077.119898,134.639987,0.000000,0.000000,-146.471116,0.394984
22,L_E_1,L,L_E,L,right,slightly_left,100.0,P,8,0.750000,5.043409,9.820858,0.630426,1.227607,11.785774,0.235715,188.217597,23.527200,102.380858,12.797607,-19.645637,NaN,8.923932,2.969438,1.115492,0.371180,137.096159,17.137020,-9.946298,-6.430137,-1.243287,-0.803767,648.901637,81.112705,54950.787827,6868.848478,1.100094e+08,1.100094e+08,0.007154,0.057233,-0.388244,0.696450,571.084285,71.385536,0.000000,0.000000,159.039231,0.123152
23,L_E_1,L,L_E,L,right,slightly_left,100.0,R,8,0.875000,109.048386,-0.678533,13.631048,-0.084817,13.664850,0.273297,211.511701,26.438963,83.147375,10.393422,-25.850581,NaN,7.453248,1.522396,0.931656,0.190299,114.046237,14.255780,-48.988332,1.718005,-6.123541,0.214751,627.819756,78.477470,33698.618684,4212.327336,1.697688e+08,1.697688e+08,0.003765,0.030123,-0.398766,0.774567,433.467752,54.183469,0.000000,0.000000,-87.639798,0.197567
24,L_E_1,L,L_E,L,right,slightly_left,115.0,I,8,0.750000,8.345890,-56.960993,1.043236,-7.120124,14.746057,0.294921,196.425941,24.553243,63.974924,7.996865,-63.200225,NaN,3.773092,0.842350,0.471636,0.105294,240.367952,30.045994,-6.854040,27.937496,-0.856755,3.492187,1467.696369,183.462046,98223.379319,12277.922415,4.917627e+08,4.917627e+08,0.003378,0.027023,-0.350030,0.665921,1066.292241,133.286530,0.000000,0.000000,-81.654761,0.282946
25,L_E_1,L,L_E,L,right,slightly_left,115.0,M,8,0.750000,-6.893532,-73.273344,-0.861692,-9.159168,15.070908,0.301418,196.719986,24.589998,84.817477,10.602185,-53.822871,NaN,34.263798,15.125591,4.282975,1.890699,222.683927,27.835491,16.599814,21.579685,2.074977,2.697461,1066.090194,133.261274,91468.194407,11433.524301,1.253927e+08,1.253927e+08,0.006642,0.053135,-0.357916,0.608883,636.349741,79.543718,0.000000,0.000000,-35.655067,0.531588
26,L_E_1,L,L_E,L,right,slightly_left,115.0,P,8,0.625000,1.816885,-40.490390,0.227111,-5.061299,12.013248,0.240265,182.626424,22.828303,105.963789,13.245474,-22.394586,NaN,1.267646,-1.696843,0.158456,-0.212105,147.607705,18.450963,5.622874,45.273190,0.702859,5.659149,754.322881,94.290360,62289.014066,7786.126758,5.639126e+07,5.639126e+07,0.008020,0.064157,-0.381795,0.710838,512.913523,64.114190,0.000000,0.000000,85.930243,0.581897
27,L_E_1,L,L_E,L,right,slightly_left,115.0,R,8,0.625000,92.501516,-0.151157,11.562690,-0.018895,11.570889,0.231418,209.227397,26.153425,93.684930,11.710616,-26.678055,NaN,0.727046,0.127266,0.090881,0.015908,95.483098,11.935387,1.378400,6.156826,0.172300,0.769603,558.861700,69.857713,22626.967705,2828.370963,2.339045e+08,2.339045e+08,0.005251,0.042004,-0.407407,0.808304,432.964942,54.120618,0.000000,0.000000,-173.338203,0.767388
28,L_E_1,L,L_E,L,right,slightly_left,130.0,I,8,0.875000,5.710177,-40.774823,0.713772,-5.096853,15.009764,0.300195,212.758512,26.594814,63.826389,7.978299,-61.739251,NaN,16.418616,6.963789,2.052327,0.870474,252.258270,31.532284,59.666742,33.340603,7.458343,4.167575,1483.556306,185.444538,109678.022032,13709.752754,2.480805e+08,2.480805e+08,0.003281,0.026247,-0.369668,0.587675,1149.264146,143.658018,0.000000,0.000000,-34.519294,0.204965
29,L_E_1,L,L_E,L,right,slightly_left,130.0,M,8,1.000000,-11.710033,-69.530319,-1.463754,-8.691290,15.719767,0.314395,212.049276,26.506159,82.841115,10.355139,-58.685371,NaN,45.055775,6.492751,5.631972,0.811594,220.618621,27.577328,81.181271,10.682353,10.147659,1.335294,1113.236875,139.154609,88377.593292,11047.199161,2.281403e+08,2.281403e+08,0.006362,0.050895,-0.340224,0.615821,961.835055,120.229382,0.000000,0.000000,-61.677893,0.288244
30,L_E_1,L,L_E,L,right,slightly_left,130.0,P,8,0.750000,-0.358284,-66.399071,-0.044786,-8.299884,9.682088,0.193642,153.122783,19.140348,101.688760,12.711095,-18.877510,NaN,5.724801,-1.179563,0.715600,-0.147445,122.222452,15.277807,2.762864,7.858496,0.345358,0.982312,542.518005,67.814751,48371.207603,6046.400950,6.256419e+07,6.256419e+07,0.007421,0.059368,-0.351534,0.671063,441.979793,55.247474,0.000000,0.000000,-157.911023,0.226334
31,L_E_1,L,L_E,L,right,slightly_left,130.0,R,8,0.750000,92.542458,-0.683750,11.567807,-0.085469,11.572924,0.231458,207.789263,25.973658,82.957788,10.369724,-26.702300,NaN,3.166099,0.004959,0.395762,0.000620,113.735983,14.216998,15.691182,-1.392319,1.961398,-0.174040,615.854403,76.981800,26163.261097,3270.407637,1.772424e+08,1.772424e+08,0.003002,0.024012,-0.419268,0.815726,433.041301,54.130163,0.000000,0.000000,-123.620425,0.389431
32,L_E_1,L,L_E,L,right,slightly_left,145.0,I,8,1.000000,-2.853853,-67.214012,-0.356732,-8.401752,15.876705,0.317534,193.617661,24.202208,65.540261,8.192533,-64.142581,NaN,5.068844,-3.963068,0.633606,-0.495384,227.964175,28.495522,-1.379396,55.613295,-0.172425,6.951662,1315.009101,164.376138,107233.821936,13404.227742,7.923617e+07,7.923617e+07,0.004679,0.037430,-0.334864,0.667248,979.641563,122.455195,0.000000,0.000000,-147.301869,0.407633
33,L_E_1,L,L_E,L,right,slightly_left,145.0,M,8,1.000000,0.678268,-79.223471,0.084784,-9.902934,15.586843,0.311737,194.818092,24.352262,83.873888,10.484236,-57.079974,NaN,11.928078,-1.501241,1.491010,-0.187655,197.242761,24.655345,69.036098,19.505846,8.629512,2.438231,1196.545805,149.568226,81496.744387,10187.093048,1.359557e+08,1.359557e+08,0.004580,0.036638,-0.327522,0.637149,969.077620,121.134702,0.000000,0.000000,-75.389219,0.325910
34,L_E_1,L,L_E,L,right,slightly_left,145.0,P,8,0.875000,-3.057218,-52.711201,-0.382152,-6.588900,12.271934,0.245439,178.727280,22.340910,104.243787,13.030473,-24.696108,NaN,9.670665,-0.407294,1.208833,-0.050912,144.243274,18.030409,-4.489537,0.011533,-0.561192,0.001442,659.345974,82.418247,60097.577399,7512.197175,1.252264e+08,1.252264e+08,0.007231,0.057849,-0.325563,0.653990,611.853524,76.481691,0.000000,0.000000,-1.896852,0.237034
35,L_E_1,L,L_E,L,right,slightly_left,145.0,R,8,0.375000,102.107067,-0.510275,12.763383,-0.063784,12.773531,0.255471,214.725514,26.840689,86.230142,10.778768,-26.537873,NaN,2.531963,0.632098,0.316495,0.079012,95.336863,11.917108,6.679972,1.433680,0.834996,0.179210,591.132166,73.891521,27442.712198,3430.339025,3.645637e+08,3.645637e+08,0.004520,0.036158,-0.404853,0.771414,445.120367,55.640046,0.000000,0.000000,-122.236050,0.423890
36,L_E_10,L,L_E,L,right,slightly_left,25.0,I,8,0.875000,4.376413,24.614171,0.547052,3.076771,8.335030,0.166701,146.686209,18.335776,44.510138,5.563767,-54.264179,NaN,1.040955,4.702034,0.130119,0.587754,164.789391,20.598674,-15.079989,21.112145,-1.884999,2.639018,1032.804194,129.100524,97300.657418,12162.582177,1.246864e+09,1.246864e+09,0.004349,0.034791,-0.317450,0.656522,597.295695,74.661962,0.000000,0.000000,23.429208,0.833634
37,L_E_10,L,L_E,L,right,slightly_left,25.0,M,8,1.000000,5.886663,51.163644,0.735833,6.395455,7.008220,0.140164,129.983067,16.247883,59.233428,7.404178,-54.853888,NaN,-1.727141,10.650247,-0.215893,1.331281,146.279363,18.284920,4.117477,12.436195,0.514685,1.554524,940.059003,117.507375,98006.851734,12250.856467,1.374996e+08,1.374996e+08,0.005579,0.044634,-0.336303,0.724559,293.913330,36.739166,0.000000,0.000000,92.623510,0.601568
38,L_E_10,L,L_E,L,right,slightly_left,25.0,P,8,1.000000,2.864484,29.795552,0.358061,3.724444,8.524741,0.170495,152.593643,19.074205,90.267223,11.283403,-29.246246,NaN,3.772930,4.797585,0.471616,0.599698,177.739825,22.217478,13.014661,-3.379151,1.626833,-0.422394,1114.251524,139.281441,105762.997642,13220.374705,4.208664e+08,4.208664e+08,0.003464,0.027714,-0.320903,0.726372,591.901182,73.987648,0.000000,0.000000,157.987050,0.483016
39,L_E_10,L,L_E,L,right,slightly_left,25.0,R,8,1.000000,1.240918,48.163187,0.155115,6.020398,7.943285,0.158866,155.840003,19.480000,79.616818,9.952102,-47.068951,NaN,7.730999,-6.513144,0.966375,-0.814143,203.736181,25.467023,4.831304,22.780712,0.603913,2.847589,1365.435911,170.679489,122871.244534,15358.905567,3.853210e+08,3.853210e+08,0.003718,0.029743,-0.321056,0.705722,573.480137,71.685017,0.000000,0.000000,109.486120,0.221999

All participants by stiffness

,stiffness_value,n_trials,n_subjects,success_rate,mean_x_centered_px,mean_y_centered_px,sem_x_centered_px,sem_y_centered_px,mean_vx_px_s,mean_vy_px_s,sem_vx_px_s,sem_vy_px_s,mean_vx_cm_s,mean_vy_cm_s,sem_vx_cm_s,sem_vy_cm_s,mean_speed_px_s,sem_speed_px_s,mean_speed_cm_s,sem_speed_cm_s,mean_ax_px_s2,mean_ay_px_s2,sem_ax_px_s2,sem_ay_px_s2,mean_ax_cm_s2,mean_ay_cm_s2,sem_ax_cm_s2,sem_ay_cm_s2,mean_acceleration_px_s2,sem_acceleration_px_s2,mean_acceleration_cm_s2,sem_acceleration_cm_s2,mean_jerk_px_s3,sem_jerk_px_s3,mean_jerk_cm_s3,sem_jerk_cm_s3,mean_normalized_jerk_cost,sem_normalized_jerk_cost,mean_normalized_jerk_cost_cm,sem_normalized_jerk_cost_cm,mean_path_length_px,mean_path_length_cm,circular_mean_direction_deg
0,25.0,1280,40,0.955469,3.318383,-0.439209,1.157362,0.830899,0.517070,0.304554,0.792852,0.382738,0.049916,0.032328,0.093452,0.042380,181.270337,2.804465,20.128194,0.306370,5.470835,8.992694,4.703807,3.562910,0.621879,0.945063,0.498762,0.371864,999.017283,24.385198,110.746400,2.466802,29767.234956,974.758500,3153.595876,121.677039,3.705075e+06,8.946170e+08,3.705075e+06,8.946170e+08,516.735898,56.677332,-78.147657
1,40.0,1280,40,0.911719,3.692808,-0.875355,1.158066,0.801406,0.348255,0.627102,0.780590,0.423584,0.039721,0.062235,0.091083,0.045045,179.818714,2.905321,20.608302,0.313662,4.606189,6.767891,4.407727,3.693469,0.446397,0.686970,0.470628,0.383173,978.685643,25.422685,111.076709,2.556037,29081.485983,970.863865,3216.600634,120.176125,4.386517e+06,4.611746e+08,4.386517e+06,4.611746e+08,542.912208,62.466962,-63.354977
2,55.0,1280,40,0.838281,4.451461,-1.114436,1.123564,0.810937,0.243028,0.270432,0.730555,0.387866,0.024040,0.030291,0.085767,0.041174,177.676732,3.082749,20.280542,0.326827,3.811326,8.174771,4.779783,3.593850,0.402631,0.888016,0.508889,0.375262,983.849975,26.564520,109.692290,2.649271,29259.476037,965.830870,3210.131988,118.993251,6.070992e+06,1.348408e+09,6.070992e+06,1.348408e+09,581.224763,65.784129,-52.342567
3,70.0,1280,40,0.676562,3.514142,-0.785284,1.125335,0.824983,0.160380,0.197728,0.780399,0.394238,0.016063,0.022143,0.092955,0.043030,175.565501,3.258283,19.575748,0.341305,6.269243,4.599938,4.610952,3.434023,0.595085,0.477839,0.489288,0.365646,975.337417,29.076930,110.318202,2.888684,29101.560343,1021.039261,3136.035226,125.077220,5.961284e+06,2.061952e+10,5.961284e+06,2.061952e+10,579.327159,66.275576,-87.651981
4,85.0,10240,40,0.799023,3.514876,-0.744455,0.396141,0.290575,0.468065,0.205058,0.265500,0.138959,0.051889,0.022379,0.031417,0.015189,175.217858,1.102421,19.530008,0.117069,5.759717,6.177437,1.570252,1.206348,0.620248,0.670839,0.169712,0.124703,966.564540,9.555515,107.943071,0.953369,28392.276128,351.333137,3071.317977,43.306383,5.664685e+06,5.302887e+08,5.664685e+06,5.302887e+08,570.311426,65.170828,-88.487427
5,100.0,1280,40,0.667969,3.288140,-0.547299,1.119592,0.818981,0.680913,0.000069,0.786177,0.382033,0.067061,0.000009,0.092418,0.041528,177.049677,3.140565,19.534901,0.335469,2.343809,6.295832,4.818079,3.475649,0.226117,0.711195,0.512026,0.358461,969.175745,26.583732,108.860384,2.663772,28738.086830,973.803653,3078.749114,120.366863,6.360471e+06,4.257887e+08,6.360471e+06,4.257887e+08,580.578747,66.604358,-66.304141
6,115.0,1280,40,0.742969,3.580175,-1.094952,1.084417,0.824057,0.693107,0.099044,0.789698,0.411012,0.073420,0.010316,0.094403,0.045217,169.299312,3.112348,19.224893,0.330641,5.245995,5.285920,4.432290,3.397343,0.536981,0.556650,0.472497,0.354449,931.727725,26.520061,104.687897,2.657848,27335.828607,986.908132,2958.049479,122.040381,6.389316e+06,1.295494e+12,6.389316e+06,1.295494e+12,579.733270,67.958097,-63.915349
7,130.0,1280,40,0.782813,3.272847,-0.297564,1.092026,0.840952,0.089590,-0.175735,0.770892,0.405395,0.009709,-0.016739,0.091623,0.043779,175.575669,3.118494,19.480202,0.330138,8.093532,4.569250,4.520695,3.241054,0.855784,0.521759,0.482546,0.339662,970.227981,26.926613,106.593429,2.677567,28079.060924,987.185845,3059.327688,121.108077,5.600919e+06,2.186816e+09,5.600919e+06,2.186816e+09,547.416156,60.766056,-83.902632
8,145.0,1280,40,0.816406,3.276864,-1.156146,1.083179,0.807224,0.153126,0.304826,0.746839,0.407227,0.014356,0.032812,0.088161,0.044053,173.488461,3.081183,19.360152,0.329953,8.236589,5.741106,4.115488,3.532189,0.865697,0.595121,0.448899,0.370801,965.365738,26.243834,107.881741,2.644007,28235.344692,951.454296,3004.856259,117.505188,5.528722e+06,6.417068e+08,5.528722e+06,6.417068e+08,558.524069,62.057770,-74.379925

N_E / L_E / L_P kinematic group summary

,experiment_group,metric,n_observations,mean,median,std,sem,ci95_lower,ci95_upper,raw_values_json,raw_values_count,raw_values_truncated,n_subjects
0,L_E,success_rate,711,7.827334e-01,7.656250e-01,1.832624e-01,6.872876e-03,7.692625e-01,7.962042e-01,"[1.0, 1.0, 0.859375, 0.625, 0.375, 0.875, 0.85...",711,True,20
1,L_E,mean_x_workspace_cm,711,2.176781e+00,5.781975e-01,4.309915e+00,1.616344e-01,1.859978e+00,2.493585e+00,"[-1.1487150192260742, 1.9454669952392596, -0.6...",711,True,20
2,L_E,mean_y_workspace_cm,711,-2.245199e-01,-1.799543e-01,3.652553e+00,1.369815e-01,-4.930035e-01,4.396375e-02,"[-5.811667889356615, -8.55215460062027, -9.561...",711,True,20
3,L_E,mean_r_workspace_cm,711,8.798502e+00,8.214929e+00,2.748030e+00,1.030592e-01,8.596506e+00,9.000498e+00,"[12.937357113927014, 14.256875884297711, 15.13...",711,True,20
4,L_E,mean_r_workspace_normalized,711,1.759700e-01,1.642986e-01,5.496060e-02,2.061183e-03,1.719301e-01,1.800100e-01,"[0.2587471422785403, 0.28513751768595424, 0.30...",711,True,20
5,L_E,mean_max_r_workspace_cm,711,2.439751e+01,2.247864e+01,5.847220e+00,2.192879e-01,2.396771e+01,2.482732e+01,"[22.027285207769175, 24.350664329875155, 25.03...",711,True,20
6,L_E,mean_thumb_active_span_cm,711,1.041253e+01,1.035505e+01,2.891511e+00,1.084401e-01,1.019999e+01,1.062507e+01,"[8.249925653565345, 7.978625759735636, 10.3915...",711,True,20
7,L_E,mean_vx_cm_s,711,9.970035e-01,9.477201e-02,3.296078e+00,1.236126e-01,7.547229e-01,1.239284e+00,"[5.652118434345417, -1.3350448591861472, 2.509...",711,True,20
8,L_E,mean_vy_cm_s,711,-3.292973e-02,1.590826e-02,8.577817e-01,3.216933e-02,-9.598162e-02,3.012215e-02,"[2.842837337359735, 0.5807081414660926, 0.5455...",711,True,20
9,L_E,mean_speed_cm_s,711,2.436998e+01,2.221591e+01,9.753182e+00,3.657729e-01,2.365307e+01,2.508690e+01,"[30.628259557515285, 28.672508567982028, 25.30...",711,True,20
10,L_E,mean_ax_cm_s2,711,4.697115e+00,1.426796e+00,9.503232e+00,3.563990e-01,3.998573e+00,5.395658e+00,"[6.967737681642491, 2.3766358808007024, 0.9158...",711,True,20
11,L_E,mean_ay_cm_s2,711,2.724448e+00,1.709001e+00,5.879217e+00,2.204879e-01,2.292292e+00,3.156604e+00,"[-0.669922919648906, 7.190771025968884, 1.4143...",711,True,20
12,L_E,mean_acceleration_cm_s2,711,1.375545e+02,1.238009e+02,6.787467e+01,2.545499e+00,1.325653e+02,1.425437e+02,"[176.0636978677088, 181.7536009059321, 135.936...",711,True,20
13,L_E,mean_jerk_cm_s3,711,5.968878e+03,4.078818e+03,4.765306e+03,1.787129e+02,5.618601e+03,6.319155e+03,"[12325.912554883867, 13487.343369684555, 10090...",711,True,20
14,L_E,mean_normalized_jerk_cost_cm,711,8.845856e+08,8.898984e+06,3.640923e+09,1.365453e+08,6.169569e+08,1.152214e+09,"[28251722.71054834, 40671291.954346, 119643835...",711,True,20
15,L_E,mean_curvature_1_cm,711,4.153142e-02,3.667744e-02,1.850380e-02,6.939469e-04,4.017128e-02,4.289155e-02,"[0.0460208663215956, 0.034694703413376965, 0.0...",711,True,20
16,L_E,speed_curvature_power_law_slope,711,-3.917556e-01,-3.870257e-01,5.179616e-02,1.942508e-03,-3.955629e-01,-3.879483e-01,"[-0.32804956659642104, -0.3625299264697976, -0...",711,True,20
17,L_E,speed_curvature_power_law_r2,711,7.385905e-01,7.419017e-01,5.251374e-02,1.969419e-03,7.347305e-01,7.424506e-01,"[0.5774813966625895, 0.6463159525396348, 0.636...",711,True,20
18,L_E,mean_path_length_cm,711,8.109760e+01,7.257927e+01,3.592694e+01,1.347365e+00,7.845676e+01,8.373843e+01,"[77.59119222566721, 105.0971172401805, 109.410...",711,True,20
19,L_E,mean_straightness_index_cm,711,2.086605e-03,0.000000e+00,4.040171e-03,1.515182e-04,1.789629e-03,2.383581e-03,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",711,True,20
20,L_E,movement_direction_resultant_length,711,3.786673e-01,3.538914e-01,1.984157e-01,7.441169e-03,3.640826e-01,3.932520e-01,"[0.6865276984584446, 0.40664510781238467, 0.38...",711,True,20
21,N_E,success_rate,711,8.125000e-01,8.750000e-01,1.772061e-01,6.645746e-03,7.994743e-01,8.255257e-01,"[1.0, 0.75, 0.8125, 0.75, 0.75, 1.0, 0.734375,...",711,True,20
22,N_E,mean_x_workspace_cm,711,1.360105e-01,1.084983e-01,2.304252e+00,8.641622e-02,-3.336528e-02,3.053863e-01,"[0.9956932067871094, 1.1576390318021215, 0.545...",711,True,20
23,N_E,mean_y_workspace_cm,711,-3.170677e-01,-1.637730e-02,1.827852e+00,6.854981e-02,-4.514253e-01,-1.827101e-01,"[-0.08608147501945496, -0.0061912089586257935,...",711,True,20
24,N_E,mean_r_workspace_cm,711,5.338457e+00,5.309537e+00,1.597484e+00,5.991034e-02,5.221033e+00,5.455881e+00,"[5.568264626567392, 6.374748227849942, 10.1876...",711,True,20
25,N_E,mean_r_workspace_normalized,711,1.423589e-01,1.415876e-01,4.259958e-02,1.597609e-03,1.392275e-01,1.454902e-01,"[0.1484870567084638, 0.16999328607599848, 0.27...",711,True,20
26,N_E,mean_max_r_workspace_cm,711,1.637168e+01,1.609746e+01,2.881622e+00,1.080693e-01,1.615986e+01,1.658350e+01,"[19.702846664004326, 21.72080892846563, 24.048...",711,True,20
27,N_E,mean_thumb_active_span_cm,711,1.008098e+01,1.024352e+01,2.414259e+00,9.054179e-02,9.903522e+00,1.025845e+01,"[9.330034782269857, 9.732766257937826, 11.3552...",711,True,20
28,N_E,mean_vx_cm_s,711,-5.513223e-02,1.616566e-02,8.468817e-01,3.176054e-02,-1.173829e-01,7.118435e-03,"[0.0620532442635303, -0.14685990351098704, 0.3...",711,True,20
29,N_E,mean_vy_cm_s,711,6.122105e-02,3.629889e-02,7.127418e-01,2.672990e-02,8.830441e-03,1.136117e-01,"[0.39601494363314615, 0.7706249781214103, 0.17...",711,True,20
30,N_E,mean_speed_cm_s,711,1.947955e+01,1.718559e+01,1.106008e+01,4.147852e-01,1.866657e+01,2.029253e+01,"[21.40501098818985, 26.181298074814215, 18.678...",711,True,20
31,N_E,mean_ax_cm_s2,711,5.584359e-01,1.397043e-02,7.991741e+00,2.997137e-01,-2.900299e-02,1.145875e+00,"[-1.6433324923010164, -1.4886174605396798, 0.1...",711,True,20
32,N_E,mean_ay_cm_s2,711,-7.308583e-02,2.473432e-01,6.753360e+00,2.532708e-01,-5.694965e-01,4.233249e-01,"[-1.6009160649775427, -4.578770280235375, 1.96...",711,True,20
33,N_E,mean_acceleration_cm_s2,711,1.284639e+02,8.848595e+01,1.025941e+02,3.847578e+00,1.209226e+02,1.360051e+02,"[121.93517418006843, 140.2898449344906, 84.234...",711,True,20
34,N_E,mean_jerk_cm_s3,711,2.756966e+03,2.286224e+03,1.893750e+03,7.102117e+01,2.617765e+03,2.896168e+03,"[2883.0544064404867, 3790.9690521286366, 2523....",711,True,20
35,N_E,mean_normalized_jerk_cost_cm,711,1.780611e+07,3.205686e+06,8.049972e+07,3.018975e+06,1.188892e+07,2.372331e+07,"[10365519.185285807, 35925944.552359164, 33791...",711,True,20
36,N_E,mean_curvature_1_cm,711,8.472563e-02,6.891447e-02,6.370239e-02,2.389026e-03,8.004314e-02,8.940812e-02,"[0.042038480822421245, 0.03511464116725954, 0....",711,True,20
37,N_E,speed_curvature_power_law_slope,711,-4.196962e-01,-4.158441e-01,4.851757e-02,1.819551e-03,-4.232625e-01,-4.161298e-01,"[-0.4205011054479363, -0.389840444046342, -0.3...",711,True,20
38,N_E,speed_curvature_power_law_r2,711,7.507626e-01,7.557267e-01,4.959606e-02,1.859997e-03,7.471170e-01,7.544082e-01,"[0.7672022222071794, 0.7192813772211681, 0.686...",711,True,20
39,N_E,mean_path_length_cm,711,6.763367e+01,4.853067e+01,4.537708e+01,1.701773e+00,6.429819e+01,7.096915e+01,"[79.15113931996352, 83.69424548357793, 208.006...",711,True,20
40,N_E,mean_straightness_index_cm,711,2.289503e-03,0.000000e+00,5.079241e-03,1.904864e-04,1.916150e-03,2.662857e-03,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.01466613836639535,...",711,True,20
41,N_E,movement_direction_resultant_length,711,3.539973e-01,3.183049e-01,2.015207e-01,7.557618e-03,3.391844e-01,3.688102e-01,"[0.10519660406130282, 0.31569389967818745, 0.1...",711,True,20

Between-group kinematic comparisons

,condition_col,condition_level,group_a,group_b,comparison,metric,n_subjects_a,n_subjects_b,mean_a,mean_b,mean_difference_b_minus_a,cohens_d_b_minus_a
0,all,all,N_E,L_E,L_E - N_E,success_rate,20,20,8.130859e-01,7.849609e-01,-2.812500e-02,-0.319073
1,all,all,N_E,L_E,L_E - N_E,mean_x_workspace_cm,20,20,1.554821e-01,2.259060e+00,2.103578e+00,0.689816
2,all,all,N_E,L_E,L_E - N_E,mean_y_workspace_cm,20,20,-3.151004e-01,-2.264408e-01,8.865953e-02,0.033068
3,all,all,N_E,L_E,L_E - N_E,mean_r_workspace_cm,20,20,5.365472e+00,8.798463e+00,3.432992e+00,1.764405
4,all,all,N_E,L_E,L_E - N_E,mean_r_workspace_normalized,20,20,1.430793e-01,1.759693e-01,3.289002e-02,0.773951
...,...,...,...,...,...,...,...,...,...,...,...,...
75,finger_condition,P,N_E,L_E,L_E - N_E,mean_acceleration_cm_s2,20,20,1.155621e+02,1.171631e+02,1.600991e+00,0.027248
76,finger_condition,P,N_E,L_E,L_E - N_E,mean_jerk_cm_s3,20,20,2.530620e+03,5.424147e+03,2.893527e+03,0.917540
77,finger_condition,P,N_E,L_E,L_E - N_E,mean_normalized_jerk_cost_cm,20,20,1.145014e+07,1.110945e+09,1.099495e+09,0.351777
78,finger_condition,P,N_E,L_E,L_E - N_E,mean_curvature_1_cm,20,20,8.233624e-02,4.072027e-02,-4.161597e-02,-0.941970
79,finger_condition,P,N_E,L_E,L_E - N_E,speed_curvature_power_law_slope,20,20,-4.140214e-01,-3.867505e-01,2.727091e-02,0.550849

Expanded requested scopes: all, protocol, E/P, N/L, sex, age, stiffness, finger, success/failure

    comparison_scope     status            column                                    note  n_levels
0                all  available               all                        all_participants         1
1           protocol    missing   protocol_factor    protocol 1/2/3/4 if present/inferred         0
2             E_vs_P  available     subject_group                                  E vs P         2
3   N_vs_L_workspace  available   workspace_setup                N=60x45 cm vs L=80x60 cm         2
4        side_camera  available  side_camera_side      right-side L vs left-side N camera         2
5   experiment_group  available  experiment_group                 N_E/L_E/L_P exact group         2
6                sex    missing        sex_factor               male vs female if present         0
7                age    missing         age_group                     age bins if present         0
8          stiffness  available   stiffness_value            skin-stretch/stiffness value         9
9             finger  available  finger_condition                           active finger         4
10           success    missing     success_label  answers.csv-derived success vs failure         0

    comparison_scope                       metric  comparison_value  n_observations  n_subjects      mean    median       sem  ci95_mean_low  ci95_mean_high
0                all                 success_rate  all_participants            1422          40  0.797617  0.859375  0.004795       0.788219        0.807015
1                all          mean_x_workspace_cm  all_participants            1422          40  1.156396  0.348356  0.095526       0.969166        1.343626
2                all          mean_y_workspace_cm  all_participants            1422          40 -0.270794 -0.099038  0.076571      -0.420873       -0.120715
3                all          mean_r_workspace_cm  all_participants            1422          40  7.068480  6.537000  0.075209       6.921070        7.215889
4                all  mean_r_workspace_normalized  all_participants            1422          40  0.159164  0.152099  0.001378       0.156464        0.161865
..               ...                          ...               ...             ...         ...       ...       ...       ...            ...             ...
115      side_camera          mean_y_workspace_cm             right             711          20 -0.224520 -0.179954  0.136981      -0.493004        0.043964
116      side_camera          mean_r_workspace_cm              left             711          20  5.338457  5.309537  0.059910       5.221033        5.455881
117      side_camera          mean_r_workspace_cm             right             711          20  8.798502  8.214929  0.103059       8.596506        9.000498
118      side_camera  mean_r_workspace_normalized              left             711          20  0.142359  0.141588  0.001598       0.139228        0.145490
119      side_camera  mean_r_workspace_normalized             right             711          20  0.175970  0.164299  0.002061       0.171930        0.180010

[120 rows x 10 columns]

## 4. Motor-control repeated-measures calculations

These calculations avoid trial-pooling across people. They produce: within-subject centered/z-scored kinematics, within-finger stiffness sensitivities for each subject, and paired finger comparisons using only subjects who contributed both fingers in a contrast. This is the preferred structure for motor-control interpretation.

In [9]:
motor_control = ka.compute_motor_control_comparisons(subject_kinematic_summary)
kinematic_within_subject = motor_control["within_subject"]
finger_metric_summary = motor_control["finger_metric_summary"]
within_finger_stiffness_effects = motor_control["within_finger_stiffness_effects"]
within_finger_stiffness_effect_summary = motor_control["within_finger_stiffness_effect_summary"]
finger_comparison_paired = motor_control["finger_comparison_paired"]
finger_comparison_by_stiffness_paired = motor_control["finger_comparison_by_stiffness_paired"]

ka.save_csv(kinematic_within_subject, OUTPUT_ROOT, "kinematic_within_subject.csv")
ka.save_csv(finger_metric_summary, OUTPUT_ROOT, "finger_metric_summary.csv")
ka.save_csv(within_finger_stiffness_effects, OUTPUT_ROOT, "within_finger_stiffness_effects.csv")
ka.save_csv(within_finger_stiffness_effect_summary, OUTPUT_ROOT, "within_finger_stiffness_effect_summary.csv")
ka.save_csv(finger_comparison_paired, OUTPUT_ROOT, "finger_comparison_paired.csv")
ka.save_csv(finger_comparison_by_stiffness_paired, OUTPUT_ROOT, "finger_comparison_by_stiffness_paired.csv")

motor_control_figure_paths = ka.save_motor_control_figures(OUTPUT_ROOT, motor_control, fig_dpi=FIG_DPI)

print("Within-subject rows:", kinematic_within_subject.shape)
display(kinematic_within_subject.head(30))
print("Within-finger stiffness effects: one slope per subject x finger x metric")
display(within_finger_stiffness_effects.head(30))
print("Within-finger stiffness-effect summary")
display(within_finger_stiffness_effect_summary.sort_values(["metric", "finger_condition"]).head(80))
print("Paired finger comparisons (finger_b - finger_a)")
display(finger_comparison_paired.sort_values(["metric", "comparison"]).head(80))
print(f"Saved {len(motor_control_figure_paths)} motor-control figures")

Within-subject rows: (1422, 57)

,subject_id,subject_group,finger_condition,stiffness_value,n_trials,success_rate,mean_max_r_workspace_cm,mean_speed_cm_s,mean_acceleration_cm_s2,mean_jerk_cm_s3,mean_normalized_jerk_cost_cm,mean_curvature_1_cm,speed_curvature_power_law_slope,speed_curvature_power_law_r2,mean_path_length_cm,mean_straightness_index_cm,mean_vx_cm_s,mean_vy_cm_s,success_rate_within_subject_centered,success_rate_within_subject_z,success_rate_within_subject_finger_centered,mean_max_r_workspace_cm_within_subject_centered,mean_max_r_workspace_cm_within_subject_z,mean_max_r_workspace_cm_within_subject_finger_centered,mean_speed_cm_s_within_subject_centered,mean_speed_cm_s_within_subject_z,mean_speed_cm_s_within_subject_finger_centered,mean_acceleration_cm_s2_within_subject_centered,mean_acceleration_cm_s2_within_subject_z,mean_acceleration_cm_s2_within_subject_finger_centered,mean_jerk_cm_s3_within_subject_centered,mean_jerk_cm_s3_within_subject_z,mean_jerk_cm_s3_within_subject_finger_centered,mean_normalized_jerk_cost_cm_within_subject_centered,mean_normalized_jerk_cost_cm_within_subject_z,mean_normalized_jerk_cost_cm_within_subject_finger_centered,mean_curvature_1_cm_within_subject_centered,mean_curvature_1_cm_within_subject_z,mean_curvature_1_cm_within_subject_finger_centered,speed_curvature_power_law_slope_within_subject_centered,speed_curvature_power_law_slope_within_subject_z,speed_curvature_power_law_slope_within_subject_finger_centered,speed_curvature_power_law_r2_within_subject_centered,speed_curvature_power_law_r2_within_subject_z,speed_curvature_power_law_r2_within_subject_finger_centered,mean_path_length_cm_within_subject_centered,mean_path_length_cm_within_subject_z,mean_path_length_cm_within_subject_finger_centered,mean_straightness_index_cm_within_subject_centered,mean_straightness_index_cm_within_subject_z,mean_straightness_index_cm_within_subject_finger_centered,mean_vx_cm_s_within_subject_centered,mean_vx_cm_s_within_subject_z,mean_vx_cm_s_within_subject_finger_centered,mean_vy_cm_s_within_subject_centered,mean_vy_cm_s_within_subject_z,mean_vy_cm_s_within_subject_finger_centered
0,L_E_1,L,I,25.0,8,1.000000,22.027285,30.628260,176.063698,12325.912555,2.825172e+07,0.046021,-0.328050,0.577481,77.591192,0.000000,5.652118,2.842837,0.187500,1.052007,0.109375,-2.529635,-1.319190,-2.031994,8.788520,1.326795,0.641558,55.597136,1.259023,-3.643763,3719.296248,1.021089,-629.131834,-1.382785e+08,-1.148165,-1.324761e+08,0.001757,0.138933,0.009311,0.044380,1.340263,0.029015,-0.102409,-1.454906,-0.058192,-7.229544,-0.242413,-36.563108,-0.000344,-0.238749,0.000000,4.084791,2.254618,4.076520,2.364135,2.992235,2.165762
1,L_E_1,L,M,25.0,8,1.000000,26.539571,27.031173,155.669766,10722.101714,4.258448e+07,0.062228,-0.345427,0.616404,87.405495,0.000000,4.751201,2.279750,0.187500,1.052007,0.140625,1.982651,1.033941,1.038387,5.191434,0.783746,1.198696,35.203204,0.797193,13.306210,2115.485407,0.580782,63.076079,-1.239457e+08,-1.029156,-1.230840e+08,0.017965,1.420279,0.011793,0.027003,0.815487,0.013210,-0.063487,-0.901941,-0.007897,2.584759,0.086669,-17.345240,-0.000344,-0.238749,0.000000,3.183873,1.757353,1.140069,1.801048,2.279548,1.131966
2,L_E_1,L,P,25.0,8,1.000000,21.449365,16.833187,96.796806,7642.680825,4.737381e+07,0.056580,-0.321488,0.626014,65.628083,0.000000,0.055461,0.315137,0.187500,1.052007,0.218750,-3.107556,-1.620572,-1.116080,-5.006552,-0.755835,-0.752858,-23.669756,-0.536013,11.472469,-963.935482,-0.264637,410.099863,-1.191564e+08,-0.989389,-3.584032e+07,0.012317,0.973769,-0.001953,0.050942,1.538407,0.035393,-0.053876,-0.765411,-0.047147,-19.192654,-0.643547,-0.815490,-0.000344,-0.238749,0.000000,-1.511867,-0.834482,-0.373964,-0.163565,-0.207020,0.312485
3,L_E_1,L,R,25.0,8,1.000000,25.555736,14.415647,77.433913,3788.035157,1.696625e+08,0.033436,-0.417535,0.796598,53.325416,0.000000,0.923087,0.006502,0.187500,1.052007,0.281250,0.998815,0.520876,-0.546038,-7.424092,-1.120808,0.461914,-43.032649,-0.974495,2.963020,-4818.581150,-1.322885,208.220916,3.132319e+06,0.026009,-8.684779e+07,-0.010827,-0.855996,0.002060,-0.045104,-1.362127,-0.000396,0.116707,1.658035,0.010171,-31.495320,-1.056067,-0.608921,-0.000344,-0.238749,-0.001378,-0.644241,-0.355591,0.269932,-0.472200,-0.597653,-0.080794
4,L_E_1,L,I,40.0,8,1.000000,24.043934,31.763674,192.390512,14085.836052,3.475786e+07,0.041992,-0.353914,0.603494,84.375668,0.000000,1.946684,1.280580,0.187500,1.052007,0.109375,-0.512986,-0.267519,-0.015345,9.923935,1.498207,1.776973,71.923950,1.628752,12.683051,5479.219745,1.504256,1130.791663,-1.317723e+08,-1.094143,-1.259700e+08,-0.002272,-0.179614,0.005282,0.018516,0.559182,0.003151,-0.076396,-1.085347,-0.032179,-0.445069,-0.014924,-29.778632,-0.000344,-0.238749,0.000000,0.379356,0.209387,0.371086,0.801877,1.014919,0.603504
5,L_E_1,L,M,40.0,8,1.000000,22.653436,24.960148,148.396780,10989.776777,7.966027e+07,0.053644,-0.394767,0.591016,79.906380,0.000000,5.321692,2.204854,0.187500,1.052007,0.140625,-1.903484,-0.992656,-2.847748,3.120408,0.471085,-0.872330,27.930218,0.632493,6.033224,2383.160470,0.654269,330.751141,-8.686993e+07,-0.721306,-8.600822e+07,0.009380,0.741614,0.003209,-0.022337,-0.674573,-0.036131,-0.088875,-1.262627,-0.033286,-4.914356,-0.164783,-24.844355,-0.000344,-0.238749,0.000000,3.754364,2.072238,1.710560,1.726152,2.184753,1.057069
6,L_E_1,L,P,40.0,8,0.875000,24.138343,18.179375,89.654603,7425.026848,4.289162e+07,0.048845,-0.341044,0.666640,63.253754,0.000000,-0.077799,0.120458,0.062500,0.350669,0.093750,-0.418578,-0.218286,1.572898,-3.660364,-0.552602,0.593330,-30.811959,-0.697751,4.330266,-1181.589459,-0.324392,192.445886,-1.236386e+08,-1.026606,-4.032250e+07,0.004582,0.362246,-0.009688,0.031386,0.947849,0.015838,-0.013251,-0.188249,-0.006521,-21.566982,-0.723161,-3.189819,-0.000344,-0.238749,0.000000,-1.645127,-0.908035,-0.507224,-0.358244,-0.453422,0.117806
7,L_E_1,L,R,40.0,8,0.875000,25.250499,16.804383,71.391309,3551.869504,5.278141e+08,0.026140,-0.441701,0.803617,51.883185,0.000000,0.872888,0.080687,0.062500,0.350669,0.156250,0.693578,0.361697,-0.851275,-5.035357,-0.760183,2.850650,-49.075253,-1.111332,-3.079584,-5054.746803,-1.387722,-27.944737,3.612839e+08,2.999843,2.713038e+08,-0.018123,-1.432837,-0.005236,-0.069271,-2.091949,-0.024563,0.123726,1.757749,0.017190,-32.937552,-1.104426,-2.051153,-0.000344,-0.238749,-0.001378,-0.694439,-0.383299,0.219733,-0.398015,-0.503759,-0.006609
8,L_E_1,L,I,55.0,8,1.000000,24.350664,28.672509,181.753601,13487.343370,4.067129e+07,0.034695,-0.362530,0.646316,105.097117,0.000000,-1.335045,0.580708,0.187500,1.052007,0.109375,-0.206256,-0.107561,0.291385,6.832769,1.031537,-1.314193,61.287039,1.387874,2.046140,4880.727063,1.339947,532.298981,-1.258589e+08,-1.045042,-1.200566e+08,-0.009569,-0.756511,-0.002015,0.009900,0.298978,-0.005466,-0.033575,-0.476989,0.010642,20.276381,0.679886,-9.057183,-0.000344,-0.238749,0.000000,-2.902373,-1.601977,-2.910643,0.102006,0.129107,-0.096368
9,L_E_1,L,M,55.0,8,0.875000,27.431265,27.328752,148.680904,10748.076614,2.117499e+08,0.057215,-0.380971,0.665544,100.032564,0.000000,1.219845,0.869252,0.062500,0.350669,0.015625,2.874344,1.498954,1.930081,5.489013,0.828671,1.496274,28.214343,0.638927,6.317348,2141.460307,0.587913,89.050979,4.521969e+07,0.375472,4.608140e+07,0.012951,1.023907,0.006780,-0.008541,-0.257942,-0.022335,-0.014347,-0.203824,0.041242,15.211828,0.510066,-4.718172,-0.000344,-0.238749,0.000000,-0.347483,-0.191795,-2.391288,0.390549,0.494310,-0.278533
10,L_E_1,L,P,55.0,8,1.000000,21.772460,15.973047,71.379104,7048.801297,7.886414e+07,0.070190,-0.376994,0.663753,67.128332,0.000000,0.585159,0.370655,0.187500,1.052007,0.218750,-2.784461,-1.452080,-0.792986,-5.866692,-0.885689,-1.612998,-49.087457,-1.111609,-13.945233,-1557.815010,-0.427680,-183.779666,-8.766606e+07,-0.727916,-4.349991e+06,0.025926,2.049732,0.011657,-0.004564,-0.137830,-0.020113,-0.016138,-0.229264,-0.009408,-17.692404,-0.593242,0.684759,-0.000344,-0.238749,0.000000,-0.982169,-0.542112,0.155734,-0.108047,-0.136753,0.368003
11,L_E_1,L,R,55.0,8,0.750000,25.675798,14.696637,76.600423,3925.352575,1.801858e+08,0.028743,-0.416418,0.747816,52.313972,0.000000,1.031100,0.219012,-0.062500,-0.350669,0.031250,1.118878,0.583488,-0.425975,-7.143102,-1.078388,0.742904,-43.866139,-0.993369,2.129529,-4681.263732,-1.285186,345.538335,1.365561e+07,0.113386,-7.632450e+07,-0.015521,-1.227075,-0.002633,-0.043988,-1.328402,0.000720,0.067926,0.965004,-0.038611,-32.506764,-1.089981,-1.620365,-0.000344,-0.238749,-0.001378,-0.536227,-0.295973,0.377945,-0.259690,-0.328684,0.131716
12,L_E_1,L,I,70.0,8,0.750000,23.527277,27.801784,167.285852,11081.434387,8.592928e+07,0.045336,-0.361529,0.644023,95.136782,0.000000,2.571110,0.618276,-0.062500,-0.350669,-0.140625,-1.029644,-0.536953,-0.532003,5.962045,0.900084,-2.184917,46.819291,1.060245,-12.421608,2474.818080,0.679432,-1873.610002,-8.060093e+07,-0.669252,-7.479859e+07,0.001072,0.084785,0.008626,0.010901,0.329211,-0.004465,-0.035868,-0.509568,0.008349,10.316045,0.345906,-19.017518,-0.000344,-0.238749,0.000000,1.003783,0.554042,0.995512,0.139574,0.176656,-0.058800
13,L_E_1,L,M,70.0,8,0.500000,24.467424,23.632525,129.517534,10472.446752,2.999129e+08,0.051741,-0.390565,0.650505,110.454267,0.000000,3.906269,0.952590,-0.312500,-1.753346,-0.359375,-0.089497,-0.046672,-1.033760,1.792786,0.270655,-2.199952,9.050972,0.204964,-12.846022,1865.830445,0.512242,-186.578884,1.333827e+08,1.107514,1.342444e+08,0.007478,0.591183,0.001306,-0.018135,-0.547670,-0.031929,-0.029386,-0.417483,0.026203,25.633531,0.859516,5.703531,-0.000344,-0.238749,0.000000,2.338941,1.290989,0.295136,0.473888,0.599790,-0.195194
14,L_E_1,L,P,70.0,8,0.375000,25.073968,20.088329,94.999002,7444.097795,1.274271e+08,0.053752,-0.358953,0.686031,68.736188,0.000000,-0.183875,-0.839284,-0.437500,-2.454684,-0.406250,0.517048,0.269637,2.508523,-1.751410,-0.264409,2.502284,-25.467560,-0.576725,9.674664,-1162.518512,-0.319156,211.516832,-3.910309e+07,-0.324684,4.421298e+07,0.009489,0.750169,-0.004781,0.013477,0.406991,-0.002072,0.006140,0.087233,0.012870,-16.084548,-0.539330,2.292615,-0.000344,-0.238749,0.000000,-1.751203,-0.966584,-0.613300,-1.317986,-1.668146,-0.841936
15,L_E_1,L,R,70.0,8,0.500000,26.844347,13.045423,72.138958,3513.587384,2.289034e+08,0.029751,-0.426054,0.759010,55.778383,0.005853,0.883835,0.094953,-0.312500,-1.753346,-0.218750,2.287426,1.192879,0.742573,-8.794317,-1.327670,-0.908310,-48.327604,-1.094401,-2.331935,-5093.028923,-1.398232,-66.226857,6.237317e+07,0.517902,-2.760693e+07,-0.014513,-1.147370,-0.001625,-0.053624,-1.619403,-0.008916,0.079119,1.124032,-0.027417,-29.042353,-0.973817,1.844046,0.005508,3.818670,0.004475,-0.683493,-0.377257,0.230679,-0.383749,-0.485703,0.007657
16,L_E_1,L,I,85.0,64,0.890625,24.117300,29.650022,181.579843,13187.672298,1.577506e+08,0.036911,-0.364819,0.647971,123.074788,0.000000,2.794478,0.365041,0.078125,0.438336,0.000000,-0.439620,-0.229259,0.058021,7.810283,1.179111,-0.336679,61.113281,1.383939,1.872382,4581.055991,1.257676,232.627909,-8.779585e+06,-0.072899,-2.977253e+06,-0.007353,-0.581306,0.000201,0.007611,0.229856,-0.007755,-0.031920,-0.453482,0.012297,38.254052,1.282693,8.920488,-0.000344,-0.238749,0.000000,1.227151,0.677331,1.218880,-0.113661,-0.143859,-0.312035
17,L_E_1,L,M,85.0,64,0.859375,25.038220,25.308305,135.936168,10090.050071,1.196438e+08,0.047245,-0.369280,0.636222,109.410123,0.000000,2.509642,0.545592,0.046875,0.263002,0.000000,0.481299,0.250995,-0.462965,3.468565,0.523646,-0.524173,15.469606,0.350317,-6.427388,1483.433764,0.407259,-568.975564,-4.688637e+07,-0.389311,-4.602466e+07,0.002981,0.235699,-0.003190,0.003150,0.095138,-0.010643,-0.043669,-0.620398,0.011920,24.589387,0.824505,4.659388,-0.000344,-0.238749,0.000000,0.942314,0.520114,-1.101491,0.066890,0.084661,-0.602193
18,L_E_1,L,P,85.0,64,0.781250,22.818111,18.304269,89.453460,7319.048537,9.817928e+07,0.058824,-0.366316,0.683668,66.016909,0.000000,0.287498,0.096187,-0.031250,-0.175335,0.000000,-1.738810,-0.906779,0.252666,-3.535470,-0.533747,0.718224,-31.013102,-0.702306,4.129122,-1287.567770,-0.353487,86.467574,-6.835093e+07,-0.567537,1.496515e+07,0.014560,1.151120,0.000290,0.006114,0.184646,-0.009435,0.003777,0.053665,0.010507,-18.803828,-0.630509,-0.426664,-0.000344,-0.238749,0.000000,-1.279830,-0.706408,-0.141927,-0.382515,-0.484141,0.093535
19,L_E_1,L,R,85.0,64,0.718750,26.182849,14.296231,73.464933,3698.038588,2.565474e+08,0.032016,-0.422241,0.800791,54.033783,0.006545,0.432696,0.098671,-0.093750,-0.526004,0.000000,1.625928,0.847912,0.081075,-7.543508,-1.138836,0.342499,-47.001629,-1.064374,-1.005960,-4908.577719,-1.347593,118.224347,9.001721e+07,0.747438,3.710182e+04,-0.012248,-0.968300,0.000640,-0.049811,-1.504254,-0.005103,0.120901,1.717610,0.014364,-30.786953,-1.032315,0.099446,0.006201,4.298804,0.005168,-1.134632,-0.626265,-0.220460,-0.380031,-0.480998,0.011375
20,L_E_1,L,I,100.0,8,0.750000,23.116787,31.290263,185.010918,13035.297928,2.801107e+08,0.034737,-0.388176,0.680935,142.713408,0.000000,-0.606530,-0.074144,-0.062500,-0.350669,-0.140625,-1.440133,-0.751021,-0.942492,9.450524,1.426737,1.303562,64.544356,1.461637,5.303457,4428.681621,1.215843,80.253539,1.135805e+08,0.943091,1.193828e+08,-0.009527,-0.753204,-0.001974,-0.015746,-0.475516,-0.031112,0.001044,0.014834,0.045261,57.892672,1.941194,28.559108,-0.000344,-0.238749,0.000000,-2.173858,-1.199870,-2.182129,-0.552846,-0.699726,-0.751220
21,L_E_1,L,M,100.0,8,0.750000,27.932323,24.163234,141.086742,10240.962282,2.479764e+08,0.041175,-0.321057,0.597170,134.639987,0.000000,3.385588,0.963385,-0.062500,-0.350669,-0.109375,3.375402,1.760252,2.431139,2.323495,0.350776,-1.669244,20.620180,0.466954,-1.276814,1634.345975,0.448691,-418.063354,8.144616e+07,0.676271,8.230787e+07,-0.003089,-0.244209,-0.009260,0.051373,1.551431,0.037580,-0.082721,-1.175199,-0.027132,49.819251,1.670485,29.889252,-0.000344,-0.238749,0.000000,1.818260,1.003596,-0.225545,0.484683,0.613452,-0.184400
22,L_E_1,L,P,100.0,8,0.750000,23.527200,17.137020,81.112705,6868.848478,1.100094e+08,0.057233,-0.388244,0.696450,71.385536,0.000000,1.115492,0.371180,-0.062500,-0.350669,-0.031250,-1.029721,-0.536993,0.961754,-4.702719,-0.709965,-0.449025,-39.353857,-0.891187,-4.211633,-1737.767829,-0.477084,-363.732484,-5.652083e+07,-0.469308,2.679524e+07,0.012969,1.025326,-0.001301,-0.015814,-0.477585,-0.031363,0.016559,0.235248,0.023289,-13.435201,-0.450495,4.941963,-0.000344,-0.238749,0.000000,-0.451836,-0.249393,0.686067,-0.107522,-0.136089,0.368527
23,L_E_1,L,R,100.0,8,0.875000,26.438963,14.255780,78.477470,4212.327336,1.697688e+08,0.030123,-0.398766,0.774567,54.183469,0.000000,0.931656,0.190299,0.062500,0.350669,0.156250,1.882042,0.981474,0.337189,-7.583959,-1.144943,0.302047,-41.989092,-0.950863,4.006576,-4394.288972,-1.206401,632.513095,3.238648e+06,0.026891,-8.674146e+07,-0.014141,-1.117962,-0.001253,-0.026336,-0.795337,0.018372,0.094676,1.345041,-0.011860,-30.637267,-1.027296,0.249132,-0.000344,-0.238749,-0.001378,-0.635672,-0.350862,0.278500,-0.288403,-0.365025,0.103003
24,L_E_1,L,I,115.0,8,0.750000,24.553243,30.045994,183.462046,12277.922415,4.917627e+08,0.027023,-0.350030,0.665921,133.286530,0.000000,0.471636,0.105294,-0.062500,-0.350669,-0.140625,-0.003678,-0.001918,0.493964,8.206255,1.238891,0.059293,62.995484,1.426562,3.754586,3671.306108,1.007914,-677.121974,3.252325e+08,2.700498,3.310349e+08,-0.017240,-1.363017,-0.009687,0.022400,0.676474,0.007034,-0.013970,-0.198470,0.030247,48.465794,1.625102,19.132230,-0.000344,-0.238749,0.000000,-1.095691,-0.604772,-1.103962,-0.373408,-0.472615,-0.571782
25,L_E_1,L,M,115.0,8,0.750000,24.589998,27.835491,133.261274,11433.524301,1.253927e+08,0.053135,-0.357916,0.608883,79.543718,0.000000,4.282975,1.890699,-0.062500,-0.350669,-0.109375,0.033078,0.017250,-0.911186,5.995752,0.905173,2.003013,12.794712,0.289742,-9.102282,2826.907994,0.776095,774.498665,-4.113752e+07,-0.341577,-4.027582e+07,0.008872,0.701379,0.002700,0.014514,0.438307,0.000720,-0.071008,-1.008791,-0.015418,-5.277019,-0.176943,-25.207018,-0.000344,-0.238749,0.000000,2.715647,1.498913,0.671842,1.411997,1.787134,0.742914
26,L_E_1,L,P,115.0,8,0.625000,22.828303,18.450963,94.290360,7786.126758,5.639126e+07,0.064157,-0.381795,0.710838,64.114190,0.000000,0.158456,-0.212105,-0.187500,-1.052007,-0.156250,-1.728618,-0.901464,0.262858,-3.388776,-0.511600,0.864918,-26.176202,-0.592772,8.966023,-820.489549,-0.225256,553.545796,-1.101389e+08,-0.914515,-2.682287e+07,0.019894,1.572782,0.005624,-0.009365,-0.282821,-0.024914,0.030947,0.439658,0.037677,-20.706546,-0.694309,-2.329383,-0.000344,-0.238749,0.000000,-1.408872,-0.777633,-0.270969,-0.690808,-0.874340,-0.214758
27,L_E_1,L,R,115.0,8,0.625000,26.153425,11.935387,69.857713,2828.370963,2.339045e+08,0.042004,-0.407407,0.808304,54.120618,0.000000,0.090881,0.015908,-0.187500,-1.052007,-0.093750,1.596504,0.832567,0.051651,-9.904352,-1.495251,-2.018345,-50.608849,-1.146061,-4.613181,-5778.245344,-1.586350,-751.443278,6.737434e+07,0.559428,-2.260577e+07,-0.002260,-0.178636,0.010628,-0.034977,-1.056292,0.009731,0.128413,1.824339,0.021877,-30.700119,-1.029403,0.186281,-0.000344,-0.238749,-0.001378,-1.476447,-0.814931,-0.562275,-0.462794,-0.585748,-0.071388
28,L_E_1,L,I,130.0,8,0.875000,26.594814,31.532284,185.444538,13709.752754,2.480805e+08,0.026247,-0.369668,0.587675,143.658018,0.000000,2.052327,0.870474,0.062500,0.350669,-0.015625,2.037893,1.062749,2.535535,9.692545,1.463275,1.545583,64.977976,1.471457,5.737078,5103.136447,1.401007,754.708365,8.155025e+07,0.677135,8.735258e+07,-0.018016,-1.424374,-0.010463,0.002763,0.083427,-0.012603,-0.092216,-1.310089,-0.047999,58.837282,1.972868,29.503718,-0.000344,-0.238749,0.000000,0.484999,0.267697,0.476729,0.391771,0.495857,0.193398
29,L_E_1,L,M,130.0,8,1.000000,26.506159,27.577328,139.154609,11047.199161,2.281403e+08,0.050895,-0.340224,0.615821,120.229382,0.000000,5.631972,0.811594,0.187500,1.052007,0.140625,1.949239,1.016517,1.004975,5.737588,0.866198,1.744850,18.688048,0.423200,-3.208947,2440.582854,0.670034,388.173526,6.161010e+07,0.511566,6.247180e+07,0.006631,0.524272,0.000460,0.032206,0.972603,0.018413,-0.064070,-0.910229,-0.008481,35.408646,1.187284,15.478646,-0.000344,-0.238749,0.000000,4.064644,2.243498,2.020839,0.332892,0.421334,-0.336191

Within-finger stiffness effects: one slope per subject x finger x metric

   subject_id finger_condition                           metric  n_stiffness_levels  slope_per_stiffness_unit  high_minus_low_stiffness_delta
0       L_E_1                I                     success_rate                   9             -9.722222e-04                    0.000000e+00
1       L_E_1                I          mean_max_r_workspace_cm                   9              1.816333e-02                    2.174922e+00
2       L_E_1                I                  mean_speed_cm_s                   9             -3.321859e-03                   -2.132738e+00
3       L_E_1                I          mean_acceleration_cm_s2                   9             -5.160690e-02                   -1.168756e+01
4       L_E_1                I                  mean_jerk_cm_s3                   9              3.022258e+00                    1.078315e+03
5       L_E_1                I     mean_normalized_jerk_cost_cm                   9              2.155855e+06                    5.098444e+07
6       L_E_1                I              mean_curvature_1_cm                   9             -1.194898e-04                   -8.591185e-03
7       L_E_1                I  speed_curvature_power_law_slope                   9             -8.462838e-05                   -6.814299e-03
8       L_E_1                I     speed_curvature_power_law_r2                   9              4.308128e-04                    8.976702e-02
9       L_E_1                I              mean_path_length_cm                   9              5.125095e-01                    4.486400e+01
10      L_E_1                I       mean_straightness_index_cm                   9              0.000000e+00                    0.000000e+00
11      L_E_1                I                     mean_vx_cm_s                   9             -2.146822e-02                   -5.018513e+00
12      L_E_1                I                     mean_vy_cm_s                   9             -1.802939e-02                   -3.338221e+00
13      L_E_1                M                     success_rate                   9             -4.199728e-18                    0.000000e+00
14      L_E_1                M          mean_max_r_workspace_cm                   9              6.569959e-04                   -2.187310e+00
15      L_E_1                M                  mean_speed_cm_s                   9             -1.195416e-04                   -2.375828e+00
16      L_E_1                M          mean_acceleration_cm_s2                   9             -7.933636e-02                   -6.101540e+00
17      L_E_1                M                  mean_jerk_cm_s3                   9             -9.203962e-01                   -5.350087e+02
18      L_E_1                M     mean_normalized_jerk_cost_cm                   9              6.603046e+05                    9.337126e+07
19      L_E_1                M              mean_curvature_1_cm                   9             -1.437050e-04                   -2.559039e-02
20      L_E_1                M  speed_curvature_power_law_slope                   9              3.898540e-04                    1.790500e-02
21      L_E_1                M     speed_curvature_power_law_r2                   9             -1.029216e-05                    2.074464e-02
22      L_E_1                M              mean_path_length_cm                   9              2.656598e-01                    3.372921e+01
23      L_E_1                M       mean_straightness_index_cm                   9              0.000000e+00                    0.000000e+00
24      L_E_1                M                     mean_vx_cm_s                   9             -7.227054e-03                   -3.260191e+00
25      L_E_1                M                     mean_vy_cm_s                   9             -1.332857e-02                   -2.467405e+00
26      L_E_1                P                     success_rate                   9             -1.388889e-03                   -1.250000e-01
27      L_E_1                P          mean_max_r_workspace_cm                   9             -1.206987e-02                    8.915452e-01
28      L_E_1                P                  mean_speed_cm_s                   9             -2.123658e-03                    1.197222e+00
29      L_E_1                P          mean_acceleration_cm_s2                   9             -1.012195e-01                   -1.437856e+01

Within-finger stiffness-effect summary

,finger_condition,metric,n_subjects_with_slope,mean_slope_per_stiffness_unit,sem_slope_per_stiffness_unit,slope_sign_flip_p,n_subjects_with_high_low_delta,mean_high_minus_low_stiffness_delta,sem_high_minus_low_stiffness_delta,high_low_delta_sign_flip_p
0,I,mean_acceleration_cm_s2,40,2.264426e-03,2.877795e-02,0.940403,40,1.761378e+00,5.541204e+00,0.781411
13,M,mean_acceleration_cm_s2,39,-2.271199e-02,2.709939e-02,0.425929,39,-2.426666e+00,4.230144e+00,0.575671
26,P,mean_acceleration_cm_s2,40,-1.991167e-02,1.520421e-02,0.196740,40,-8.654482e-01,3.367834e+00,0.799760
39,R,mean_acceleration_cm_s2,39,-1.450471e-02,2.345628e-02,0.561722,39,-1.226417e+00,4.394005e+00,0.800460
1,I,mean_curvature_1_cm,40,8.021358e-05,3.729624e-05,0.012449,40,9.751261e-03,6.507851e-03,0.100645
14,M,mean_curvature_1_cm,39,1.027356e-04,4.445118e-05,0.015349,39,9.937004e-03,5.949487e-03,0.105595
27,P,mean_curvature_1_cm,40,4.540680e-05,2.596774e-05,0.034748,40,9.125470e-03,4.887121e-03,0.022699
40,R,mean_curvature_1_cm,39,1.505099e-05,2.949123e-05,0.631568,39,5.341289e-03,4.030432e-03,0.197440
2,I,mean_jerk_cm_s3,40,-9.092321e-01,8.039070e-01,0.272936,40,-1.251899e+02,1.988083e+02,0.563722
15,M,mean_jerk_cm_s3,39,-5.534218e-01,1.001174e+00,0.594720,39,-2.642019e+01,1.251585e+02,0.835858
28,P,mean_jerk_cm_s3,40,-1.132899e+00,6.743459e-01,0.094195,40,5.613491e+01,9.567064e+01,0.560572
41,R,mean_jerk_cm_s3,39,-7.307676e-01,6.985998e-01,0.309585,39,-1.820883e+02,1.658152e+02,0.304785
3,I,mean_max_r_workspace_cm,40,1.470235e-04,1.451028e-03,0.921104,40,2.298096e-01,2.717577e-01,0.409580
16,M,mean_max_r_workspace_cm,39,-5.155359e-03,1.793516e-03,0.006650,39,-6.648897e-01,2.821601e-01,0.023549
29,P,mean_max_r_workspace_cm,40,-1.686555e-03,1.753733e-03,0.356882,40,-1.725115e-01,2.426586e-01,0.485776
42,R,mean_max_r_workspace_cm,39,-2.297662e-03,1.163451e-03,0.052997,39,-2.484870e-01,2.258164e-01,0.279986
4,I,mean_normalized_jerk_cost_cm,40,1.622451e+06,8.333715e+05,0.000650,40,3.139922e+08,2.347772e+08,0.000150
17,M,mean_normalized_jerk_cost_cm,39,1.576458e+06,1.218272e+06,0.250337,39,2.181255e+08,1.395158e+08,0.007050
30,P,mean_normalized_jerk_cost_cm,40,3.306760e+06,3.339236e+06,0.511674,40,5.594433e+08,5.336599e+08,0.031248
43,R,mean_normalized_jerk_cost_cm,39,3.413602e+06,3.058503e+06,0.039948,39,5.029245e+08,3.510949e+08,0.000150
5,I,mean_path_length_cm,40,9.100650e-02,2.912961e-02,0.001050,40,1.353317e+01,4.388000e+00,0.001550
18,M,mean_path_length_cm,39,6.743905e-02,2.863885e-02,0.020299,39,1.017494e+01,4.428107e+00,0.021499
31,P,mean_path_length_cm,40,3.577667e-02,2.068907e-02,0.090945,40,5.336371e+00,2.974230e+00,0.075946
44,R,mean_path_length_cm,39,5.190683e-02,1.966248e-02,0.008600,39,8.928667e+00,2.741353e+00,0.000450
6,I,mean_speed_cm_s,40,-3.021943e-03,4.466235e-03,0.527974,40,1.073309e-02,7.193000e-01,0.992000
19,M,mean_speed_cm_s,39,-5.153475e-03,3.739977e-03,0.178141,39,-6.937804e-01,5.643589e-01,0.227889
32,P,mean_speed_cm_s,40,-6.732991e-03,2.480221e-03,0.010049,40,-6.884720e-01,3.699081e-01,0.068897
45,R,mean_speed_cm_s,39,-4.339583e-03,3.616113e-03,0.234038,39,-3.163112e-01,6.151658e-01,0.607920
7,I,mean_straightness_index_cm,40,-4.654638e-07,5.404018e-06,0.932503,40,-2.471617e-04,1.199630e-03,0.847458
20,M,mean_straightness_index_cm,39,-4.913332e-06,4.390568e-06,0.276136,39,-7.981706e-04,7.307621e-04,0.286386
33,P,mean_straightness_index_cm,40,5.250765e-07,4.919422e-06,0.916204,40,-3.926766e-04,8.889825e-04,0.670416
46,R,mean_straightness_index_cm,39,-4.163398e-06,4.799146e-06,0.390880,39,-1.289192e-03,8.534192e-04,0.140393
8,I,mean_vx_cm_s,40,2.298566e-04,1.169916e-03,0.852757,40,-4.690464e-02,2.679704e-01,0.867907
21,M,mean_vx_cm_s,39,7.858398e-04,1.385688e-03,0.588571,39,-3.525197e-02,2.423781e-01,0.889406
34,P,mean_vx_cm_s,40,-2.980373e-04,1.017589e-03,0.783211,40,-4.929444e-02,1.166833e-01,0.673616
47,R,mean_vx_cm_s,39,-1.782054e-03,1.153995e-03,0.131693,39,-2.816598e-01,1.998117e-01,0.167992
9,I,mean_vy_cm_s,40,-8.965723e-04,8.217192e-04,0.291685,40,-7.719030e-02,1.220937e-01,0.558722
22,M,mean_vy_cm_s,39,-1.252860e-03,8.274885e-04,0.138143,39,-3.266742e-02,1.586753e-01,0.842608
35,P,mean_vy_cm_s,40,-9.429991e-04,6.349996e-04,0.146743,40,-6.569589e-02,8.336078e-02,0.432878
48,R,mean_vy_cm_s,39,3.634248e-04,7.749715e-04,0.649618,39,2.778835e-02,9.733592e-02,0.784711
10,I,speed_curvature_power_law_r2,40,2.888373e-05,3.451830e-05,0.408380,40,-3.783253e-03,7.083361e-03,0.606270
23,M,speed_curvature_power_law_r2,39,2.097752e-05,5.196214e-05,0.698265,39,2.367144e-03,7.410938e-03,0.748613
36,P,speed_curvature_power_law_r2,40,9.681057e-06,4.956478e-05,0.846958,40,-7.596381e-03,7.986875e-03,0.349583
49,R,speed_curvature_power_law_r2,39,1.929828e-05,3.636590e-05,0.597870,39,-4.534600e-04,6.593802e-03,0.946503
11,I,speed_curvature_power_law_slope,40,-2.206722e-05,2.413301e-05,0.367382,40,3.208459e-03,5.490245e-03,0.568122
24,M,speed_curvature_power_law_slope,39,-2.824923e-05,3.486619e-05,0.414029,39,-3.084379e-03,5.088161e-03,0.551822
37,P,speed_curvature_power_law_slope,40,-8.628437e-06,3.231906e-05,0.790160,40,4.317906e-03,5.646581e-03,0.450027
50,R,speed_curvature_power_law_slope,39,-4.502274e-05,3.213276e-05,0.166192,39,-3.400176e-03,4.797198e-03,0.479826
12,I,success_rate,40,-1.291667e-03,1.918452e-04,0.000050,40,-1.468750e-01,3.097232e-02,0.000050
25,M,success_rate,39,-1.374644e-03,2.189672e-04,0.000050,39,-1.410256e-01,2.874288e-02,0.000050
38,P,success_rate,40,-1.137153e-03,1.960671e-04,0.000050,40,-1.281250e-01,2.776659e-02,0.000100
51,R,success_rate,39,-1.296296e-03,1.799087e-04,0.000050,39,-1.474359e-01,2.672514e-02,0.000050

Paired finger comparisons (finger_b - finger_a)

,finger_a,finger_b,comparison,metric,mean_a,mean_b,n_paired_observations,mean_difference,median_difference,sem_difference,cohens_dz,sign_flip_p
3,I,M,M - I,mean_acceleration_cm_s2,136.248085,143.340073,39,7.091989,0.645728,7.504822,0.151320,0.354982
29,I,P,P - I,mean_acceleration_cm_s2,134.210572,116.362634,40,-17.847938,-0.916559,7.471787,-0.377688,0.022399
55,M,P,P - M,mean_acceleration_cm_s2,143.340073,117.866312,39,-25.473761,-9.349790,11.420592,-0.357168,0.028099
68,R,P,P - R,mean_acceleration_cm_s2,138.519528,117.661199,39,-20.858329,-4.957362,9.928952,-0.336391,0.039398
16,I,R,R - I,mean_acceleration_cm_s2,135.210882,138.519528,39,3.308645,8.028152,8.096470,0.065437,0.685766
...,...,...,...,...,...,...,...,...,...,...,...,...
26,I,P,P - I,success_rate,0.797266,0.807617,40,0.010352,0.023438,0.011103,0.147414,0.362932
52,M,P,P - M,success_rate,0.778045,0.804087,39,0.026042,0.015625,0.013367,0.311955,0.060947
65,R,P,P - R,success_rate,0.807292,0.805889,39,-0.001402,0.000000,0.009440,-0.023786,0.897605
13,I,R,R - I,success_rate,0.796074,0.807292,39,0.011218,0.000000,0.012270,0.146398,0.384331
39,M,R,R - M,success_rate,0.775905,0.803454,38,0.027549,0.015625,0.012198,0.366383,0.030048

Saved 3 motor-control figures

## 5. Side-camera Z/lift estimate

This filtered notebook uses the filtered `z_tracking.csv` side-view tracking copies created under `result_fillter`; it does not decode side-camera video. This section reports both the raw side-camera pixel proxy and a setup-scaled centimeter proxy. The cm proxy uses the same setup-specific vertical scale as the top-camera movement field because no independent side-camera calibration grid is stored with the analysis. Positive values mean the hand/finger region is higher in the side image relative to the within-trial baseline. Camera placement is normalized by setup: `L` side camera on the right, `N` side camera on the left, both 10 cm above the table.

In [10]:
side = ka.estimate_side_video_z(
    trial_kinematic_summary,
    samples_per_video=SIDE_VIDEO_SAMPLES_PER_TRIAL,
    max_trials=MAX_SIDE_VIDEO_TRIALS,
)
side_z_samples = side["side_samples"]
side_z_trial_summary = side["side_trial_summary"]
side_z_group_time_summary = side["side_group_time"]
side_z_subject_stiffness_summary = side["side_subject_stiffness_summary"]
side_z_by_stiffness_summary = side["side_stiffness_summary"]

ka.save_parquet(side_z_samples, OUTPUT_ROOT, "side_z_samples.parquet")
ka.save_csv(side_z_trial_summary, OUTPUT_ROOT, "side_z_trial_summary.csv")
ka.save_csv(side_z_group_time_summary, OUTPUT_ROOT, "side_z_group_time_summary.csv")
ka.save_csv(side_z_subject_stiffness_summary, OUTPUT_ROOT, "side_z_subject_stiffness_summary.csv")
ka.save_csv(side_z_by_stiffness_summary, OUTPUT_ROOT, "side_z_by_stiffness_summary.csv")

print("side samples", side_z_samples.shape, "side stiffness trial summary", side_z_trial_summary.shape)
display(side_z_trial_summary.head())
print("Z/lift by stiffness")
display(side_z_by_stiffness_summary.sort_values("stiffness_value").head(30))

side samples (614382, 176) side stiffness trial summary (20480, 46)

,subject_id,trial_index_raw,stiffness_segment_id,subject_group,experiment_group,finger_condition,stiffness_value,stiffness_order_in_trial,comparison_value,standard_value,signed_stiffness_delta,correct_response,side_video_file,z_tracking_file,z_tracking_warning,missing_z_tracking_csv,side_camera_side,side_camera_view_sign,n_side_samples,side_detection_rate,mean_side_z_lift_px,max_side_z_lift_px,mean_side_x_from_center_raw_px,mean_side_x_from_center_camera_corrected_px,max_abs_side_x_from_center_camera_corrected_px,mean_side_lift_lateral_angle_raw_deg,mean_side_lift_lateral_angle_camera_corrected_deg,mean_side_motion_direction_camera_corrected_deg,mean_side_mask_area_px,workspace_setup,workspace_label,workspace_width_cm,workspace_height_cm,top_camera_height_above_table_cm,side_camera_height_above_table_cm,top_camera_frame_width_px,top_camera_frame_height_px,x_cm_per_px,y_cm_per_px,side_z_cm_per_px,participant_position_context,movement_space_context,side_camera_interpretation_note,mean_side_x_from_center_camera_corrected_cm,mean_side_z_lift_cm,max_side_z_lift_cm
0,L_E_1,13,1,L,L_E,M,115.0,1,115.0,85.0,30.0,1.0,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,,0,right,1.0,30,1.0,12.098347,29.276152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,L workspace (80x60 cm),80.0,60.0,100.0,10.0,640.0,480.0,0.125,0.125,0.125,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,NaN,1.512293,3.659519
1,L_E_1,13,2,L,L_E,M,85.0,2,115.0,85.0,30.0,1.0,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,,0,right,1.0,30,1.0,20.063706,29.974700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,L workspace (80x60 cm),80.0,60.0,100.0,10.0,640.0,480.0,0.125,0.125,0.125,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,NaN,2.507963,3.746838
2,L_E_1,14,1,L,L_E,M,55.0,1,55.0,85.0,-30.0,1.0,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,,0,right,1.0,30,1.0,16.924711,30.199740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,L workspace (80x60 cm),80.0,60.0,100.0,10.0,640.0,480.0,0.125,0.125,0.125,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,NaN,2.115589,3.774968
3,L_E_1,14,2,L,L_E,M,85.0,2,55.0,85.0,-30.0,1.0,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,,0,right,1.0,30,1.0,11.381583,27.014313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,L workspace (80x60 cm),80.0,60.0,100.0,10.0,640.0,480.0,0.125,0.125,0.125,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,NaN,1.422698,3.376789
4,L_E_1,15,1,L,L_E,M,40.0,1,40.0,85.0,-45.0,1.0,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,,0,right,1.0,30,1.0,19.666888,37.970260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,L workspace (80x60 cm),80.0,60.0,100.0,10.0,640.0,480.0,0.125,0.125,0.125,slightly_left,Lab/airslide 80x60 cm movement field,L/Lab-airslide experiment: top camera was 100 ...,NaN,2.458361,4.746283

Z/lift by stiffness

,stiffness_value,n_trials,n_subjects,mean_side_z_lift_px,sem_side_z_lift_px,max_side_z_lift_px,mean_side_z_lift_cm,sem_side_z_lift_cm,max_side_z_lift_cm,mean_side_x_from_center_camera_corrected_px,mean_side_x_from_center_camera_corrected_cm,mean_side_lift_lateral_angle_camera_corrected_deg,mean_side_motion_direction_camera_corrected_deg,success_rate
0,25.0,1280,40,38.368488,1.177585,84.720481,4.136367,0.136296,9.062813,NaN,NaN,NaN,NaN,0.955469
1,40.0,1280,40,37.725843,1.139364,84.301463,4.021847,0.132336,9.023413,NaN,NaN,NaN,NaN,0.911719
2,55.0,1280,40,40.363465,1.177561,86.367046,4.363461,0.135604,9.218986,NaN,NaN,NaN,NaN,0.838281
3,70.0,1280,40,37.646160,1.222182,87.242911,3.956210,0.140549,9.292168,NaN,NaN,NaN,NaN,0.676562
4,85.0,10240,40,38.366988,0.428003,86.075205,4.113060,0.050119,9.202312,NaN,NaN,NaN,NaN,0.799023
5,100.0,1280,40,39.929404,1.188631,85.682582,4.131185,0.140273,9.166716,NaN,NaN,NaN,NaN,0.667969
6,115.0,1280,40,38.298598,1.288417,85.951323,4.059427,0.153754,9.190282,NaN,NaN,NaN,NaN,0.742969
7,130.0,1280,40,37.479655,1.287534,83.312978,4.001124,0.152892,8.923941,NaN,NaN,NaN,NaN,0.782813
8,145.0,1280,40,38.531469,1.242964,83.722871,4.001472,0.146375,8.936857,NaN,NaN,NaN,NaN,0.816406

In [ ]:
# --- 5b. Z-lift cm L/N colors and baseline-corrected trajectory ---
# L is pink, N is purple. This plot uses centimeters only and subtracts each
# segment's first-10-sample baseline to show lift relative to the trial start.
import matplotlib.pyplot as plt

Z_LIFT_GROUP_COLORS = {
    "L_E": "#FF69B4",  # pink
    "N_E": "#7B2CBF",  # purple
}

def _z_lift_sem(values: pd.Series) -> float:
    values = pd.to_numeric(values, errors="coerce").dropna()
    return float(values.std(ddof=1) / np.sqrt(values.size)) if values.size > 1 else np.nan

z_lift_cm_timecourse = pd.DataFrame()
z_lift_plot_path = None

if side_z_samples.empty or "side_z_lift_cm" not in side_z_samples.columns:
    print("No side_z_lift_cm samples available for the L/N cm Z-lift plot.")
else:
    z_lift_plot = side_z_samples.copy()
    if ka.EXPERIMENT_GROUP_COLUMN not in z_lift_plot.columns:
        z_lift_plot[ka.EXPERIMENT_GROUP_COLUMN] = (
            z_lift_plot["subject_id"].astype(str).str.extract(r"^(L_E|N_E)", expand=False)
        )

    z_lift_plot = z_lift_plot[
        z_lift_plot[ka.EXPERIMENT_GROUP_COLUMN].isin(Z_LIFT_GROUP_COLORS)
    ].copy()

    if z_lift_plot.empty:
        print("No L_E/N_E rows available for the L/N cm Z-lift plot.")
    else:
        z_lift_keys = ["subject_id", "trial_index_raw", "stiffness_segment_id"]
        for col in ["trial_index_raw", "stiffness_segment_id", "side_time_fraction", "side_time_bin", "side_z_lift_cm"]:
            z_lift_plot[col] = pd.to_numeric(z_lift_plot[col], errors="coerce")

        z_lift_plot = z_lift_plot.dropna(
            subset=[ka.EXPERIMENT_GROUP_COLUMN, "side_z_lift_cm", "side_time_fraction", "side_time_bin"]
        ).sort_values(z_lift_keys + ["side_time_fraction", "side_time_bin"])

        z_lift_plot["_baseline_rank"] = z_lift_plot.groupby(z_lift_keys).cumcount()
        z_lift_baseline = (
            z_lift_plot[z_lift_plot["_baseline_rank"] < 10]
            .groupby(z_lift_keys, as_index=False)
            .agg(z_lift_baseline_cm=("side_z_lift_cm", "mean"), z_lift_baseline_n=("side_z_lift_cm", "count"))
        )
        z_lift_plot = z_lift_plot.merge(z_lift_baseline, on=z_lift_keys, how="left")
        z_lift_plot["side_z_lift_delta_from_first10_cm"] = (
            z_lift_plot["side_z_lift_cm"] - z_lift_plot["z_lift_baseline_cm"]
        )

        z_lift_cm_timecourse = (
            z_lift_plot.groupby(["side_time_bin", ka.EXPERIMENT_GROUP_COLUMN], as_index=False)
            .agg(
                side_time_fraction=("side_time_fraction", "mean"),
                abs_cm=("side_z_lift_cm", "mean"),
                abs_sem_cm=("side_z_lift_cm", _z_lift_sem),
                delta_cm=("side_z_lift_delta_from_first10_cm", "mean"),
                delta_sem_cm=("side_z_lift_delta_from_first10_cm", _z_lift_sem),
                n_samples=("side_z_lift_cm", "size"),
            )
            .sort_values(["side_time_bin", ka.EXPERIMENT_GROUP_COLUMN])
        )

        fig, axes = plt.subplots(1, 2, figsize=(12, 4), sharex=True)
        for group in ["L_E", "N_E"]:
            g = z_lift_cm_timecourse[
                z_lift_cm_timecourse[ka.EXPERIMENT_GROUP_COLUMN].astype(str).eq(group)
            ].sort_values("side_time_bin")
            if g.empty:
                continue
            color = Z_LIFT_GROUP_COLORS[group]
            axes[0].plot(
                g["side_time_fraction"], g["abs_cm"], marker="o", label=group, color=color, linewidth=2.2
            )
            axes[0].fill_between(
                g["side_time_fraction"], g["abs_cm"] - g["abs_sem_cm"], g["abs_cm"] + g["abs_sem_cm"],
                color=color, alpha=0.14
            )
            axes[1].plot(
                g["side_time_fraction"], g["delta_cm"], marker="o", label=group, color=color, linewidth=2.2
            )
            axes[1].fill_between(
                g["side_time_fraction"], g["delta_cm"] - g["delta_sem_cm"], g["delta_cm"] + g["delta_sem_cm"],
                color=color, alpha=0.14
            )

        axes[0].set_title("Absolute side Z/lift (cm)")
        axes[0].set_ylabel("Z/lift (cm)")
        axes[1].set_title("Baseline-corrected side Z/lift (cm)\nsubtract first 10 samples per segment")
        axes[1].set_ylabel("Delta from first-10 baseline (cm)")
        for ax in axes:
            ax.set_xlabel("Normalized side-video time")
            ax.grid(alpha=0.25)
            ax.legend(title="Group")
        fig.tight_layout()

        z_lift_fig_dir = OUTPUT_ROOT / "figures"
        z_lift_fig_dir.mkdir(parents=True, exist_ok=True)
        z_lift_plot_path = z_lift_fig_dir / "side_z_lift_cm_absolute_vs_first10_baseline_by_experiment_group.png"
        fig.savefig(z_lift_plot_path, dpi=FIG_DPI, bbox_inches="tight")
        plt.show()

        ka.save_csv(
            z_lift_cm_timecourse,
            OUTPUT_ROOT,
            "side_z_lift_cm_absolute_vs_first10_baseline_timecourse.csv",
        )
        print("Saved", z_lift_plot_path)
        display(z_lift_cm_timecourse.head(10))

## 6. Advanced success, Z-height, and trajectory structure

IEEE-style motor-control layer: successful-vs-unsuccessful kinematic/Z contrasts are computed within subject and finger; trajectory templates are compared between fingers and between correct/incorrect trials using normalized XY paths.

In [11]:
success_kinematic_z = ka.compute_success_kinematic_z_analysis(trial_kinematic_summary, side_z_trial_summary)
trial_success_kinematic_z_table = success_kinematic_z["trial_success_table"]
success_kinematic_z_contrast_by_subject_finger = success_kinematic_z["success_contrast_by_subject_finger"]
success_kinematic_z_contrast_summary = success_kinematic_z["success_contrast_summary"]
success_kinematic_z_contrast_by_finger_summary = success_kinematic_z["success_contrast_by_finger_summary"]

trajectory_structure = ka.compute_trajectory_similarity_analysis(trajectory_time_bins)
subject_finger_trajectory = trajectory_structure["subject_finger_trajectory"]
trajectory_variability_summary = trajectory_structure["trajectory_variability_summary"]
finger_trajectory_distance_paired = trajectory_structure["finger_trajectory_distance_paired"]
finger_trajectory_distance_summary = trajectory_structure["finger_trajectory_distance_summary"]
success_failure_trajectory_distance = trajectory_structure["success_failure_trajectory_distance"]
success_failure_trajectory_distance_summary = trajectory_structure["success_failure_trajectory_distance_summary"]

ka.save_csv(trial_success_kinematic_z_table, OUTPUT_ROOT, "trial_success_kinematic_z_table.csv")
ka.save_csv(success_kinematic_z_contrast_by_subject_finger, OUTPUT_ROOT, "success_kinematic_z_contrast_by_subject_finger.csv")
ka.save_csv(success_kinematic_z_contrast_summary, OUTPUT_ROOT, "success_kinematic_z_contrast_summary.csv")
ka.save_csv(success_kinematic_z_contrast_by_finger_summary, OUTPUT_ROOT, "success_kinematic_z_contrast_by_finger_summary.csv")
ka.save_csv(subject_finger_trajectory, OUTPUT_ROOT, "subject_finger_trajectory.csv")
ka.save_csv(trajectory_variability_summary, OUTPUT_ROOT, "trajectory_variability_summary.csv")
ka.save_csv(finger_trajectory_distance_paired, OUTPUT_ROOT, "finger_trajectory_distance_paired.csv")
ka.save_csv(finger_trajectory_distance_summary, OUTPUT_ROOT, "finger_trajectory_distance_summary.csv")
ka.save_csv(success_failure_trajectory_distance, OUTPUT_ROOT, "success_failure_trajectory_distance.csv")
ka.save_csv(success_failure_trajectory_distance_summary, OUTPUT_ROOT, "success_failure_trajectory_distance_summary.csv")

advanced_figure_paths = ka.save_advanced_kinematic_figures(OUTPUT_ROOT, success_kinematic_z, trajectory_structure, fig_dpi=FIG_DPI)

print("Success-linked kinematic/Z contrasts")
display(success_kinematic_z_contrast_summary.sort_values("metric").head(80))
print("Between-finger trajectory distance summary")
display(finger_trajectory_distance_summary.head(80))
print("Correct-vs-incorrect trajectory distance summary")
display(success_failure_trajectory_distance_summary.head(80))
print(f"Saved {len(advanced_figure_paths)} advanced figures")

Success-linked kinematic/Z contrasts

                                 metric  n_paired_observations  mean_difference  median_difference  sem_difference  cohens_dz  sign_flip_p
0                            duration_s                    158    -5.166499e-01          -0.172689    1.230530e-01  -0.334022     0.000050
1                max_acceleration_cm_s2                    158    -3.052464e+01           6.697492    1.794700e+01  -0.135310     0.088646
2                        max_jerk_cm_s3                    158    -1.018968e+03         117.203757    1.301125e+03  -0.062304     0.439178
3                    max_r_workspace_cm                    158    -4.173204e-01          -0.166840    1.001368e-01  -0.331549     0.000050
4                    max_side_z_lift_cm                    158    -3.557380e-01          -0.131185    1.435758e-01  -0.197115     0.013599
5                        max_speed_cm_s                    158    -1.407956e+00          -0.396507    6.629534e-01  -0.168957     0.032848
6         mean_abs_radial_velocity_cm_s                    158     1.936271e-01           0.227854    1.104910e-01   0.139415     0.083696
7     mean_abs_tangential_velocity_cm_s                    158     7.733594e-03           0.044758    4.075434e-02   0.015097     0.853307
8               mean_acceleration_cm_s2                    158     7.150045e-01           0.894927    1.034924e+00   0.054963     0.495325
9                   mean_curvature_1_cm                    158     5.542465e+40           0.000502    5.542465e+40   0.079556     1.000000
10                      mean_jerk_cm_s3                    158    -1.838075e+01          22.938061    3.668587e+01  -0.039860     0.625319
11                  mean_side_z_lift_cm                    158    -7.956407e-02          -0.048076    8.707906e-02  -0.072690     0.373081
12                      mean_speed_cm_s                    158     1.562940e-01           0.164349    1.386609e-01   0.089673     0.263887
13      movement_direction_entropy_bits                    158    -4.010504e-02          -0.038171    8.001198e-03  -0.398763     0.000050
14  movement_direction_resultant_length                    158     1.288807e-03           0.000889    4.332746e-04   0.236644     0.002000
15              normalized_jerk_cost_cm                    158    -5.238899e+11       32130.441009    5.247433e+11  -0.079426     0.523824
16                       path_length_cm                    158    -1.075846e+01          -5.038992    2.255628e+00  -0.379450     0.000050
17                  side_detection_rate                    158    -6.541099e-04           0.000000    1.632010e-03  -0.031886     0.697865
18         speed_curvature_power_law_r2                    158     2.195946e-03           0.002562    1.733083e-03   0.100803     0.206540
19      speed_curvature_power_law_slope                    158     3.897044e-04           0.000277    1.448348e-03   0.021406     0.789361
20                straightness_index_cm                    158     1.618213e-04           0.000162    3.044895e-04   0.042280     0.601720

Between-finger trajectory distance summary

   comparison                          metric  n_subject_stiffness_pairs       mean    median       sem
0       M - I  mean_xy_trajectory_distance_cm                        351   3.204410  2.955948  0.090120
1       M - I   rms_xy_trajectory_distance_cm                        351   4.236618  3.891447  0.121219
2       M - I         speed_profile_rmse_cm_s                        351  10.128245  8.935846  0.290450
3       P - I  mean_xy_trajectory_distance_cm                        360   3.176032  2.966756  0.082692
4       P - I   rms_xy_trajectory_distance_cm                        360   4.168073  3.842784  0.108292
5       P - I         speed_profile_rmse_cm_s                        360   9.421160  8.170704  0.255986
6       P - M  mean_xy_trajectory_distance_cm                        351   3.366638  3.203618  0.093743
7       P - M   rms_xy_trajectory_distance_cm                        351   4.436071  4.203439  0.125875
8       P - M         speed_profile_rmse_cm_s                        351  10.902756  9.340178  0.377225
9       P - R  mean_xy_trajectory_distance_cm                        351   3.260893  2.958965  0.106761
10      P - R   rms_xy_trajectory_distance_cm                        351   4.310094  3.862960  0.147177
11      P - R         speed_profile_rmse_cm_s                        351   9.748273  8.371833  0.328672
12      R - I  mean_xy_trajectory_distance_cm                        351   3.383371  2.892370  0.118097
13      R - I   rms_xy_trajectory_distance_cm                        351   4.428667  3.805334  0.157717
14      R - I         speed_profile_rmse_cm_s                        351  10.144441  9.109030  0.287815
15      R - M  mean_xy_trajectory_distance_cm                        342   3.335867  2.850111  0.134894
16      R - M   rms_xy_trajectory_distance_cm                        342   4.374908  3.739501  0.177869
17      R - M         speed_profile_rmse_cm_s                        342   9.564436  8.562530  0.240235

Correct-vs-incorrect trajectory distance summary

   finger_condition                               metric  n_subject_stiffness_pairs       mean     median       sem
0                 I  success_failure_mean_xy_distance_cm                        264   5.111712   4.587671  0.189958
1                 I   success_failure_rms_xy_distance_cm                        264   7.197120   6.553758  0.260246
2                 I      success_failure_speed_rmse_cm_s                        264  12.825429  11.045890  0.545857
3                 M  success_failure_mean_xy_distance_cm                        267   5.121091   4.608027  0.194185
4                 M   success_failure_rms_xy_distance_cm                        267   7.257035   6.449824  0.263964
5                 M      success_failure_speed_rmse_cm_s                        267  13.203804  11.208158  0.565543
6                 P  success_failure_mean_xy_distance_cm                        257   4.353796   3.954296  0.154785
7                 P   success_failure_rms_xy_distance_cm                        257   6.176734   5.719845  0.209691
8                 P      success_failure_speed_rmse_cm_s                        257  11.637728  10.827324  0.363344
9                 R  success_failure_mean_xy_distance_cm                        252   4.737704   4.113360  0.175454
10                R   success_failure_rms_xy_distance_cm                        252   6.754865   5.877263  0.241076
11                R      success_failure_speed_rmse_cm_s                        252  13.392791  10.836293  0.530225

Saved 3 advanced figures

## 7. Subject-specific XY trajectories in space

This is the subject-first view: one spatial XY trajectory table and one figure per subject. No pooling across participants is used in these outputs. Thin lines show that subject's stiffness-specific trajectories; thick lines show that same subject's finger-average trajectory.

In [12]:
subject_spatial = ka.compute_subject_spatial_trajectory_analysis(trajectory_time_bins)
subject_xy_trajectory = subject_spatial["subject_xy_trajectory"]
subject_spatial_trajectory_summary = subject_spatial["subject_spatial_trajectory_summary"]
subject_finger_spatial_distance = subject_spatial["subject_finger_spatial_distance"]
subject_spatial_metric_distribution = subject_spatial["subject_spatial_metric_distribution"]

ka.save_csv(subject_xy_trajectory, OUTPUT_ROOT, "subject_xy_trajectory.csv")
ka.save_csv(subject_spatial_trajectory_summary, OUTPUT_ROOT, "subject_spatial_trajectory_summary.csv")
ka.save_csv(subject_finger_spatial_distance, OUTPUT_ROOT, "subject_finger_spatial_distance.csv")
ka.save_csv(subject_spatial_metric_distribution, OUTPUT_ROOT, "subject_spatial_metric_distribution.csv")
subject_xy_figure_paths = ka.save_subject_xy_trajectory_figures(OUTPUT_ROOT, subject_xy_trajectory, fig_dpi=FIG_DPI)

print("Subject XY trajectory table:", subject_xy_trajectory.shape)
display(subject_xy_trajectory.head(30))
print("Subject-specific spatial trajectory summary:")
display(subject_spatial_trajectory_summary.sort_values(["subject_id", "finger_condition", "stiffness_value"]).head(80))
print("Subject-specific finger spatial distances:")
display(subject_finger_spatial_distance.sort_values(["subject_id", "stiffness_value", "comparison"]).head(80))
print("Subject spatial metric distributions with mean/median/95% CI and log-backtransformed summaries:")
display(subject_spatial_metric_distribution.head(80))
print(f"Saved {len(subject_xy_figure_paths)} per-subject XY figures")

Subject XY trajectory table: (71100, 25)

,subject_id,finger_condition,stiffness_value,trajectory_time_bin,n_segments,time_fraction,x_centered_px,y_centered_px,sd_x_centered_px,sd_y_centered_px,r_center_px,speed_px_s,subject_group,experiment_group,workspace_setup,workspace_label,workspace_width_cm,workspace_height_cm,x_workspace_cm,y_workspace_cm,r_workspace_cm,r_workspace_normalized,success_label,success_rate,xy_sd_radius_px
0,L_E_1,I,25.0,1,8,0.008130,0.000000,0.000000,0.000000,0.000000,0.000000,19.513735,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
1,L_E_1,I,25.0,2,8,0.030007,0.000000,0.000000,0.000000,0.000000,0.000000,8.207517,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
2,L_E_1,I,25.0,3,8,0.050044,0.000000,0.000000,0.000000,0.000000,0.000000,1.272294,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
3,L_E_1,I,25.0,4,8,0.069877,0.000000,0.000000,0.000000,0.000000,0.000000,1.122887,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
4,L_E_1,I,25.0,5,8,0.089672,0.000000,0.000000,0.000000,0.000000,0.000000,3.667713,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
5,L_E_1,I,25.0,6,8,0.110164,0.000000,0.000000,0.000000,0.000000,0.000000,9.585927,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.000000,0.000000,0.000000,0.000000,success,1.0,0.000000
6,L_E_1,I,25.0,7,8,0.129873,0.223554,-0.152897,0.632305,0.432459,0.290784,15.835575,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.027944,-0.019112,0.033855,0.000677,success,1.0,0.766049
7,L_E_1,I,25.0,8,8,0.149511,-0.096285,-0.880466,2.705283,3.315101,2.423602,18.482263,L,L_E,L,L workspace (80x60 cm),80.0,60.0,-0.012036,-0.110058,0.303109,0.006062,success,1.0,4.278838
8,L_E_1,I,25.0,9,8,0.169710,-0.458347,-1.101515,3.051522,3.157734,2.501492,23.760156,L,L_E,L,L workspace (80x60 cm),80.0,60.0,-0.057293,-0.137689,0.313306,0.006266,success,1.0,4.391250
9,L_E_1,I,25.0,10,8,0.189807,0.854073,-2.484988,4.741200,3.199361,4.421308,35.598449,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.106759,-0.310624,0.547073,0.010941,success,1.0,5.719693
10,L_E_1,I,25.0,11,8,0.210507,3.740317,-3.744204,8.175494,3.998909,7.356117,42.935014,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.467540,-0.468025,0.920492,0.018410,success,1.0,9.101098
11,L_E_1,I,25.0,12,8,0.230466,5.041118,-5.741123,8.191908,6.434144,9.165630,64.973352,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.630140,-0.717640,1.137523,0.022750,success,1.0,10.416601
12,L_E_1,I,25.0,13,8,0.249503,7.037333,-9.099519,9.910863,7.896533,12.667297,100.910248,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.879667,-1.137440,1.579611,0.031592,success,1.0,12.672033
13,L_E_1,I,25.0,14,8,0.269103,11.469900,-14.930295,15.564573,12.254620,20.117892,137.898237,L,L_E,L,L workspace (80x60 cm),80.0,60.0,1.433738,-1.866287,2.513938,0.050279,success,1.0,19.809887
14,L_E_1,I,25.0,15,8,0.289528,18.288992,-21.309505,22.817443,16.490363,29.574414,188.484410,L,L_E,L,L workspace (80x60 cm),80.0,60.0,2.286124,-2.663688,3.695674,0.073913,success,1.0,28.152580
15,L_E_1,I,25.0,16,8,0.309516,26.376224,-30.096218,29.309583,21.494781,42.013616,242.007084,L,L_E,L,L workspace (80x60 cm),80.0,60.0,3.297028,-3.762027,5.249947,0.104999,success,1.0,36.346626
16,L_E_1,I,25.0,17,8,0.329859,35.364715,-39.167344,42.631106,25.703504,58.213046,268.913365,L,L_E,L,L workspace (80x60 cm),80.0,60.0,4.420589,-4.895918,7.270908,0.145418,success,1.0,49.780331
17,L_E_1,I,25.0,18,8,0.350331,45.525229,-50.472389,51.791407,30.657260,75.210920,286.160855,L,L_E,L,L workspace (80x60 cm),80.0,60.0,5.690654,-6.309049,9.402140,0.188043,success,1.0,60.184860
18,L_E_1,I,25.0,19,8,0.370758,55.742182,-60.528680,60.394466,34.547281,90.674665,287.511175,L,L_E,L,L workspace (80x60 cm),80.0,60.0,6.967773,-7.566085,11.332938,0.226659,success,1.0,69.577339
19,L_E_1,I,25.0,20,8,0.390078,65.537212,-70.058949,68.929082,37.233196,106.615035,260.260470,L,L_E,L,L workspace (80x60 cm),80.0,60.0,8.192152,-8.757369,13.324655,0.266493,success,1.0,78.342385
20,L_E_1,I,25.0,21,8,0.409283,70.944199,-77.780643,75.589687,39.133393,118.951810,244.702095,L,L_E,L,L workspace (80x60 cm),80.0,60.0,8.868025,-9.722580,14.867161,0.297343,success,1.0,85.118877
21,L_E_1,I,25.0,22,8,0.429963,73.699704,-85.523312,82.362427,38.514695,130.490913,216.097148,L,L_E,L,L workspace (80x60 cm),80.0,60.0,9.212463,-10.690414,16.305901,0.326118,success,1.0,90.922776
22,L_E_1,I,25.0,23,8,0.450305,75.578109,-92.787884,87.012694,35.498805,140.269134,206.553589,L,L_E,L,L workspace (80x60 cm),80.0,60.0,9.447264,-11.598485,17.532856,0.350657,success,1.0,93.975391
23,L_E_1,I,25.0,24,8,0.469997,71.767702,-99.790865,91.540754,32.999380,146.847569,215.983448,L,L_E,L,L workspace (80x60 cm),80.0,60.0,8.970963,-12.473858,18.333322,0.366666,success,1.0,97.307084
24,L_E_1,I,25.0,25,8,0.490089,63.398610,-104.821592,95.181873,30.116485,149.110575,262.324998,L,L_E,L,L workspace (80x60 cm),80.0,60.0,7.924826,-13.102699,18.619166,0.372383,success,1.0,99.832818
25,L_E_1,I,25.0,26,8,0.509759,48.748079,-108.192073,97.304946,26.373218,147.664197,312.242340,L,L_E,L,L workspace (80x60 cm),80.0,60.0,6.093510,-13.524009,18.454023,0.369080,success,1.0,100.815669
26,L_E_1,I,25.0,27,8,0.529736,29.439502,-110.783865,97.944804,21.914604,144.387780,365.033674,L,L_E,L,L workspace (80x60 cm),80.0,60.0,3.679938,-13.847983,18.050461,0.361009,success,1.0,100.366501
27,L_E_1,I,25.0,28,8,0.549942,7.035200,-110.661903,98.530964,19.329027,141.694212,405.565972,L,L_E,L,L workspace (80x60 cm),80.0,60.0,0.879400,-13.832738,17.693862,0.353877,success,1.0,100.408975
28,L_E_1,I,25.0,29,8,0.570305,-18.839126,-109.886727,93.720031,18.777770,139.773009,444.702433,L,L_E,L,L workspace (80x60 cm),80.0,60.0,-2.354891,-13.735841,17.467640,0.349353,success,1.0,95.582681
29,L_E_1,I,25.0,30,8,0.590626,-44.356650,-105.667552,85.431666,22.710750,138.669892,430.830899,L,L_E,L,L workspace (80x60 cm),80.0,60.0,-5.544581,-13.208444,17.310476,0.346210,success,1.0,88.398800

Subject-specific spatial trajectory summary:

,subject_id,finger_condition,stiffness_value,subject_group,experiment_group,workspace_setup,workspace_label,workspace_width_cm,workspace_height_cm,n_time_bins,n_segments_mean,start_x_centered_px,start_y_centered_px,end_x_centered_px,end_y_centered_px,centroid_x_centered_px,centroid_y_centered_px,min_x_centered_px,max_x_centered_px,min_y_centered_px,max_y_centered_px,xy_width_px,xy_height_px,spatial_extent_area_px2,mean_radius_px,max_radius_px,mean_trajectory_speed_px_s,mean_xy_sd_radius_px,mean_trajectory_path_length_px,mean_trajectory_net_displacement_px,mean_trajectory_straightness,mean_trajectory_signed_area_px2,success_rate
0,L_E_1,I,25.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,-4.368948,-3.473994,-16.859020,-45.454219,-135.770973,75.578109,-110.783865,0.000000,211.349082,110.783865,23414.068076,67.362018,152.720721,201.646488,46.084879,503.827508,5.581786,0.011079,-13537.651225,1.000000
1,L_E_1,I,40.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,4.988188,-4.596750,-1.359306,-49.355576,-58.776972,36.160442,-98.103607,0.000000,94.937414,98.103607,9313.702703,53.754414,106.551566,201.831596,76.367797,360.219429,6.783225,0.018831,-2756.034486,1.000000
2,L_E_1,I,55.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,1.052263,1.069826,11.907574,-44.873050,-57.392344,78.299987,-87.588254,1.069826,135.692332,88.658080,12030.221673,53.697252,113.798983,203.947888,77.702823,448.956423,1.500595,0.003342,-1306.015553,1.000000
3,L_E_1,I,70.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,0.359268,-5.020476,-6.859548,-52.850891,-77.773821,41.710284,-91.643793,0.616205,119.484105,92.259998,11023.603275,59.525775,114.960366,209.908286,71.313493,347.263473,5.033315,0.014494,-3229.259332,0.750000
4,L_E_1,I,85.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,64.0,0.0,0.0,-0.599369,-2.679370,-5.818512,-51.024158,-44.889940,50.418168,-85.663084,0.000000,95.308108,85.663084,8164.386427,55.948378,95.044197,215.617191,81.935420,316.223464,2.745591,0.008682,-2403.520536,0.890625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,L_E_11,I,70.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,1.862752,-4.160038,21.781008,-33.296724,0.000000,45.554199,-60.446818,0.000000,45.554199,60.446818,2753.606359,40.201201,72.228649,128.959307,63.786433,237.685808,4.558044,0.019177,-352.132122,0.500000
76,L_E_11,I,85.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,64.0,0.0,0.0,5.651117,-9.918803,18.984867,-34.217998,-3.472765,45.349555,-68.381341,0.000000,48.822320,68.381341,3338.535756,39.618442,81.169158,123.792320,60.977635,212.123005,11.415681,0.053816,745.570933,0.703125
77,L_E_11,I,100.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,7.132833,-12.073653,22.930529,-40.005424,-0.721418,61.779421,-86.238243,0.000000,62.500839,86.238243,5389.962566,46.520009,106.083606,102.884735,45.077465,324.031254,14.023210,0.043277,950.369330,0.625000
78,L_E_11,I,115.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,-3.418508,-4.476650,1.624180,-20.463913,-28.083685,34.924854,-39.463836,0.000000,63.008539,39.463836,2486.558641,24.813515,49.992183,126.720775,68.220300,370.334371,5.632636,0.015210,-186.599565,0.625000
79,L_E_11,I,130.0,L,L_E,L,L workspace (80x60 cm),80.0,60.0,50,8.0,0.0,0.0,-0.267001,-4.831197,14.347432,-30.220107,-11.471851,55.395619,-69.036807,0.000000,66.867470,69.036807,4616.316642,35.224587,87.991181,135.486824,64.107956,349.884571,4.838570,0.013829,338.190923,0.625000

Subject-specific finger spatial distances:

   subject_id  stiffness_value finger_a finger_b comparison  n_matched_time_bins  mean_xy_distance_px  median_xy_distance_px  rms_xy_distance_px  max_xy_distance_px
0       L_E_1             25.0        I        M      M - I                   50            24.917749              22.054145           32.494988           71.257294
2       L_E_1             25.0        I        P      P - I                   50            40.155002              36.268803           52.837145          106.148972
4       L_E_1             25.0        M        P      P - M                   50            40.740819              43.997292           49.776860           91.977325
5       L_E_1             25.0        R        P      P - R                   50            81.596991              39.055656          120.153556          245.048975
1       L_E_1             25.0        I        R      R - I                   50           111.010828              70.281965          160.413516          335.935059
..        ...              ...      ...      ...        ...                  ...                  ...                    ...                 ...                 ...
77     L_E_10             70.0        R        P      P - R                   50            28.078940              27.585585           35.387827           70.821789
73     L_E_10             70.0        I        R      R - I                   50            37.411457              33.581305           45.313543           83.457640
75     L_E_10             70.0        M        R      R - M                   50            37.908873              34.369629           47.458882           83.959128
78     L_E_10             85.0        I        M      M - I                   50            24.343309              21.873163           29.749900           53.474904
80     L_E_10             85.0        I        P      P - I                   50            22.514610              21.718055           27.749383           51.763132

[80 rows x 10 columns]

Subject spatial metric distributions with mean/median/95% CI and log-backtransformed summaries:

,subject_id,finger_condition,metric,n,mean,mean_ci95_low,mean_ci95_high,median,median_ci95_low,median_ci95_high,sd,sem,skewness,log_transform_valid,log_transform_recommended,geometric_mean_backtransformed,geometric_ci95_low_backtransformed,geometric_ci95_high_backtransformed
0,L_E_1,I,mean_trajectory_path_length_px,9,437.864259,384.105230,491.623288,448.956423,347.263473,522.005390,82.284228,27.428076,-0.185071,True,False,430.684550,379.063123,489.335866
1,L_E_1,I,mean_trajectory_net_displacement_px,9,4.071413,2.957050,5.185777,3.845028,2.745591,5.581786,1.705658,0.568553,0.081610,True,False,3.719144,2.730564,5.065632
2,L_E_1,I,mean_trajectory_straightness,9,0.009776,0.006530,0.013022,0.008682,0.005664,0.014494,0.004968,0.001656,0.415525,True,False,0.008635,0.006049,0.012329
3,L_E_1,I,spatial_extent_area_px2,9,12638.036576,9047.518663,16228.554488,11023.603275,8164.386427,17906.866910,5495.690683,1831.896894,0.710766,True,False,11697.993733,8951.753472,15286.732125
4,L_E_1,I,mean_radius_px,9,58.133135,52.538159,63.728110,55.948378,52.179899,67.362018,8.563738,2.854579,0.036414,True,False,57.565642,52.213260,63.466697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,L_E_11,P,max_radius_px,9,83.157095,68.818034,97.496155,86.668525,53.001647,102.141996,21.947542,7.315847,-0.313443,True,False,80.317861,66.557373,96.923279
76,L_E_11,P,mean_xy_sd_radius_px,9,59.092782,54.689821,63.495744,59.082595,52.100683,66.736478,6.739227,2.246409,0.202605,True,False,58.755142,54.563196,63.269144
77,L_E_11,R,mean_trajectory_path_length_px,9,323.652444,281.998462,365.306425,340.884828,249.512129,372.900322,63.756094,21.252031,-0.441972,True,False,317.460117,275.857472,365.336943
78,L_E_11,R,mean_trajectory_net_displacement_px,9,6.595363,5.645351,7.545375,7.016174,5.909651,7.656654,1.454100,0.484700,-1.248767,True,True,6.402733,5.330283,7.690960
79,L_E_11,R,mean_trajectory_straightness,9,0.021236,0.016851,0.025621,0.020832,0.016780,0.028599,0.006712,0.002237,0.010019,True,False,0.020169,0.015956,0.025493

Saved 42 per-subject XY figures

## 8. Subject-specific velocity and acceleration

Same subject-first structure as the XY spatial plots, now for velocity and acceleration. The profiles use derivatives computed inside each stiffness segment, so velocity/acceleration do not bridge object transitions.

In [13]:
subject_va = ka.compute_subject_velocity_acceleration_analysis(trajectory_time_bins, side_z_samples=side_z_samples, n_time_bins=TRAJECTORY_TIME_BINS)
subject_velocity_acceleration_profile = subject_va["subject_velocity_acceleration_profile"]
subject_velocity_acceleration_summary = subject_va["subject_velocity_acceleration_summary"]
subject_finger_velocity_acceleration_distance = subject_va["subject_finger_velocity_acceleration_distance"]
subject_velocity_acceleration_metric_distribution = subject_va["subject_velocity_acceleration_metric_distribution"]
velocity_stiffness_influence_summary = subject_va.get("velocity_stiffness_influence_summary", pd.DataFrame())
velocity_finger_influence_summary = subject_va.get("velocity_finger_influence_summary", pd.DataFrame())
velocity_time_influence_summary = subject_va.get("velocity_time_influence_summary", pd.DataFrame())

ka.save_csv(subject_velocity_acceleration_profile, OUTPUT_ROOT, "subject_velocity_acceleration_profile.csv")
ka.save_csv(subject_velocity_acceleration_summary, OUTPUT_ROOT, "subject_velocity_acceleration_summary.csv")
ka.save_csv(subject_finger_velocity_acceleration_distance, OUTPUT_ROOT, "subject_finger_velocity_acceleration_distance.csv")
ka.save_csv(subject_velocity_acceleration_metric_distribution, OUTPUT_ROOT, "subject_velocity_acceleration_metric_distribution.csv")
ka.save_csv(velocity_stiffness_influence_summary, OUTPUT_ROOT, "velocity_stiffness_influence_summary.csv")
ka.save_csv(velocity_finger_influence_summary, OUTPUT_ROOT, "velocity_finger_influence_summary.csv")
ka.save_csv(velocity_time_influence_summary, OUTPUT_ROOT, "velocity_time_influence_summary.csv")
subject_va_figure_paths = ka.save_subject_velocity_acceleration_figures(
    OUTPUT_ROOT,
    subject_velocity_acceleration_profile,
    fig_dpi=FIG_DPI,
)
standard_vs_comparison_figure_paths = ka.save_standard_vs_comparison_velocity_figures(
    OUTPUT_ROOT,
    subject_velocity_acceleration_profile,
    levels=("subject", "group"),
    fig_dpi=FIG_DPI,
)
print(f"Saved {len(standard_vs_comparison_figure_paths)} standard-vs-comparison velocity figures (per subject + per group, 8 metrics)")

print("Subject velocity/acceleration profile:", subject_velocity_acceleration_profile.shape)
display(subject_velocity_acceleration_profile.head(30))
print("Subject velocity/acceleration summary:")
display(subject_velocity_acceleration_summary.sort_values(["subject_id", "finger_condition", "stiffness_value"]).head(80))
print("Subject-specific finger velocity/acceleration distances:")
display(subject_finger_velocity_acceleration_distance.sort_values(["subject_id", "stiffness_value", "comparison"]).head(80))
print("Subject velocity/acceleration metric distributions with mean/median/95% CI and log-backtransformed summaries:")
display(subject_velocity_acceleration_metric_distribution.head(80))
print("Velocity influence answers: stiffness, fingers, and time thirds")
display(velocity_stiffness_influence_summary)
display(velocity_finger_influence_summary)
display(velocity_time_influence_summary.head(80))
print(f"Saved {len(subject_va_figure_paths)} velocity/acceleration figures for this selection level")

C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(

Saved 860 standard-vs-comparison velocity figures (per subject + per group, 8 metrics)
Subject velocity/acceleration profile: (71100, 131)

,subject_id,finger_condition,stiffness_value,trajectory_time_bin,n_segments,time_fraction,subject_group,experiment_group,workspace_setup,workspace_label,workspace_width_cm,workspace_height_cm,success_label,standard_value,comparison_value,success_rate,vx_cm_s,sd_vx_cm_s,vy_cm_s,sd_vy_cm_s,vz_cm_s,sd_vz_cm_s,vx_3d_cm_s,sd_vx_3d_cm_s,vy_3d_cm_s,sd_vy_3d_cm_s,vz_3d_proxy_cm_s,sd_vz_3d_proxy_cm_s,speed_cm_s,sd_speed_cm_s,speed_3d_proxy_cm_s,sd_speed_3d_proxy_cm_s,ax_cm_s2,sd_ax_cm_s2,ay_cm_s2,sd_ay_cm_s2,az_cm_s2,sd_az_cm_s2,ax_3d_cm_s2,sd_ax_3d_cm_s2,ay_3d_cm_s2,sd_ay_3d_cm_s2,az_3d_proxy_cm_s2,sd_az_3d_proxy_cm_s2,acceleration_cm_s2,sd_acceleration_cm_s2,acceleration_3d_proxy_cm_s2,sd_acceleration_3d_proxy_cm_s2,jx_cm_s3,sd_jx_cm_s3,jy_cm_s3,sd_jy_cm_s3,jerk_cm_s3,sd_jerk_cm_s3,radial_velocity_cm_s,sd_radial_velocity_cm_s,tangential_velocity_cm_s,sd_tangential_velocity_cm_s,x_workspace_cm,sd_x_workspace_cm,...,sd_vx_px_s,vy_px_s,sd_vy_px_s,vz_px_s,sd_vz_px_s,vx_3d_px_s,sd_vx_3d_px_s,vy_3d_px_s,sd_vy_3d_px_s,vz_3d_proxy_px_s,sd_vz_3d_proxy_px_s,speed_px_s,sd_speed_px_s,speed_3d_proxy_px_s,sd_speed_3d_proxy_px_s,ax_px_s2,sd_ax_px_s2,ay_px_s2,sd_ay_px_s2,az_px_s2,sd_az_px_s2,ax_3d_px_s2,sd_ax_3d_px_s2,ay_3d_px_s2,sd_ay_3d_px_s2,az_3d_proxy_px_s2,sd_az_3d_proxy_px_s2,acceleration_px_s2,sd_acceleration_px_s2,acceleration_3d_proxy_px_s2,sd_acceleration_3d_proxy_px_s2,jx_px_s3,sd_jx_px_s3,jy_px_s3,sd_jy_px_s3,jerk_px_s3,sd_jerk_px_s3,radial_velocity_px_s,sd_radial_velocity_px_s,tangential_velocity_px_s,sd_tangential_velocity_px_s,x_centered_px,sd_x_centered_px,y_centered_px,sd_y_centered_px,z_lift_px,sd_z_lift_px,abs_x_centered_px,sd_abs_x_centered_px,abs_y_centered_px,sd_abs_y_centered_px,abs_z_lift_px,sd_abs_z_lift_px,movement_angle_deg,velocity_heading_deg,velocity_heading_cm_deg,acceleration_heading_deg,acceleration_heading_cm_deg,speed_acceleration_product,speed_acceleration_product_cm
0,L_E_1,I,25.0,1,8,0.008130,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,0.319109,2.566959,0.774973,2.542645,NaN,NaN,0.319109,2.566959,0.774973,2.542645,NaN,NaN,2.436366,2.659553,NaN,NaN,-1.554260,26.405181,-15.789132,24.363923,NaN,NaN,-1.554260,26.405181,-15.789132,24.363923,NaN,NaN,24.873705,29.519799,NaN,NaN,-201.450963,750.128368,514.230368,1912.977570,912.652346,1902.324845,0.000000,0.000000,0.774973,2.542645,0.000000,0.000000,...,20.535672,6.199784,20.341158,NaN,NaN,2.552874,20.535672,6.199784,20.341158,NaN,NaN,19.513735,21.295806,NaN,NaN,-12.434078,211.241447,-126.313056,194.911382,NaN,NaN,-12.434078,211.241447,-126.313056,194.911382,NaN,NaN,230.323024,248.612357,NaN,NaN,-1611.607707,6001.026943,4113.842944,15303.820560,7565.380420,15147.271031,0.000000,0.000000,6.199784,20.341158,0.000000,0.000000,0.000000,0.000000,2.866305,0.0,0.000000,0.000000,0.000000,0.000000,2.866305,0.0,30.498464,67.619691,67.619691,-95.622002,-95.622002,4.494462e+03,60.601441
1,L_E_1,I,25.0,2,8,0.030007,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,0.204445,1.065734,0.123101,1.177919,1.519985,0.0,0.204445,1.065734,0.123101,1.177919,1.519985,0.0,1.025588,1.177403,2.045367,0.669027,-2.577875,25.280084,-7.120694,27.183076,NaN,NaN,-2.577875,25.280084,-7.120694,27.183076,NaN,NaN,25.055922,26.945501,NaN,NaN,-46.754065,181.281923,195.952029,337.739334,245.514736,352.736687,0.000000,0.000000,0.123101,1.177919,0.000000,0.000000,...,8.525871,0.984804,9.423350,12.159877,0.0,1.635557,8.525871,0.984804,9.423350,12.159877,0.0,8.207517,9.420805,16.362940,5.352216,-20.623000,202.240674,-56.965549,217.464610,NaN,NaN,-20.623000,202.240674,-56.965549,217.464610,NaN,NaN,200.849998,215.861459,NaN,NaN,-374.032520,1450.255386,1567.616229,2701.914672,2995.521843,3323.266482,0.000000,0.000000,0.984804,9.423350,0.000000,0.000000,0.000000,0.000000,3.196594,0.0,0.000000,0.000000,0.000000,0.000000,3.196594,0.0,49.524744,31.053047,31.053047,-109.901565,-109.901565,1.648480e+03,25.697041
2,L_E_1,I,25.0,3,8,0.050044,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,0.040473,0.116233,-0.050718,0.212140,-0.551231,0.0,0.040473,0.116233,-0.050718,0.212140,-0.551231,0.0,0.152835,0.191389,0.595083,0.076654,-1.663182,10.021365,-0.685221,10.844210,NaN,NaN,-1.663182,10.021365,-0.685221,10.844210,NaN,NaN,9.415634,10.972855,NaN,NaN,38.884200,167.991427,39.512847,216.476408,180.456529,203.417790,0.000000,0.000000,-0.050718,0.212140,0.000000,0.000000,...,0.929866,-0.405747,1.697119,-4.409848,0.0,0.323785,0.929866,-0.405747,1.697119,-4.409848,0.0,1.272294,1.551713,4.760666,0.613234,-13.305456,80.170918,-5.481765,86.753677,NaN,NaN,-13.305456,80.170918,-5.481765,86.753677,NaN,NaN,75.543165,87.847059,NaN,NaN,311.073597,1343.931416,316.102780,1731.811265,1591.830069,1705.702207,0.000000,0.000000,-0.405747,1.697119,0.000000,0.000000,0.000000,0.000000,5.290897,0.0,0.000000,0.000000,0.000000,0.000000,5.290897,0.0,-28.666633,-51.410263,-51.410263,-157.608643,-157.608643,9.611315e+01,1.439042
3,L_E_1,I,25.0,4,8,0.069877,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,-0.030776,0.149674,-0.025092,0.123794,4.118444,0.0,-0.030776,0.149674,-0.025092,0.123794,4.118444,0.0,0.141384,0.129167,4.122638,0.005123,-1.375474,3.381746,0.978823,5.682784,22.207944,0.0,-1.375474,3.381746,0.978823,5.682784,22.207944,0.0,4.365320,5.020866,23.066333,1.603932,22.768444,132.190402,15.848375,76.427765,95.786894,117.086105,0.000000,0.000000,-0.025092,0.123794,0.000000,0.000000,...,1.197391,-0.200740,0.990353,32.947550,0.0,-0.246209,1.197391,-0.200740,0.990353,32.947550,0.0,1.122887,1.030169,32.981104,0.040980,-11.003790,27.053969,7.830582,45.462269,177.663551,0.0,-11.003790,27.053969,7.830582,45.462269,177.663551,0.0,34.707368,39.634809,184.530666,12.831456,182.147554,1057.523218,126.786999,611.422117,1015.063996,1033.323638,0.000000,0.000000,-0.200740,0.990353,0.000000,0.000000,0.000000,0.000000,2.886853,0.0,0.000000,0.000000,0.000000,0.000000,2.886853,0.0,-145.819926,-140.808948,-140.808948,144.563359,144.563359,3.897244e+01,0.617186
4,L_E_1,I,25.0,5,8,0.089672,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,-0.120795,0.462940,-0.010719,0.472861,4.880692,0.0,-0.120795,0.462940,-0.010719,0.472861,4.880692,0.0,0.458453,0.463156,4.920933,0.062814,-2.788326,10.468259,0.347515,9.279907,4.149268,0.0,-2.788326,10.468259,0.347515,9.279907,4.149268,0.0,8.419200,11.122748,10.514960,9.901576,-84.958001,254.730814,-13.157008,154.583037,161.463595,259.683800,0.000000,0.000000,-0.010719,0.472861,0.000000,0.000000,...,3.703518,-0.085750,3.782892,39.045536,0.0,-0.966358,3.703518,-0.085750,3.782892,39.045536,0.0,3.667713,3.705278,39.367464,0.502514,-22.306612,83.746074,2.780117,74.239252,33.194143,0.0,-22.306612,83.746074,2.780117,74.239252,33.194143,0.0,67.513272,88.973761,84.119677,79.212608,-679.664011,2037.846513,-105.256067,1236.664293,2336.974007,2968.879956,0.000000,0.000000,-0.085750,3.782892,0.000000,0.000000,0.000000,0.000000,19.832022,0.0,0.000000,0.000000,0.000000,0.000000,19.832022,0.0,-130.721696,-174.929140,-174.929140,172.895748,172.895748,2.476193e+02,3.859811
5,L_E_1,I,25.0,6,8,0.110164,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,-0.224351,1.283717,-0.237271,1.398757,1.903293,0.0,-0.224351,1.283717,-0.237271,1.398757,1.903293,0.0,1.197666,1.444644,2.494676,0.868259,-2.258117,18.099342,-5.949040,21.103646,-7.217654,0.0,-2.258117,18.099342,-5.949040,21.103646,-7.217654,0.0,16.103875,22.865737,20.235286,20.268179,154.130714,266.132595,-189.761197,282.946166,265.027054,372.713148,0.000000,0.000000,-0.237271,1.398757,0.000000,0.000000,...,10.269733,-1.898168,11.190059,15.226345,0.0,-1.794805,10.269733,-1.898168,11.190059,15.226345,0.0,9.585927,11.555186,19.957410,6.946074,-18.064932,144.794737,-47.592320,168.829170,-57.741231,0.0,-18.064932,144.794737,-47.592320,168.829170,-57.741231,0.0,131.126826,181.626023,161.882291,162.145431,1233.045709,2129.060759,-1518.089576,2263.569331,5051.464998,6647.973626,0.000000,0.000000,-1.898168,11.190059,0.000000,0.000000,0.000000,0.000000,11.047432,0.0,0.000000,0.000000,0.000000,0.000000,11.047432,0.0,-134.796161,-133.396758,-133.396758,-110.785591,-110.785591,1.256972e+03,19.287060
6,L_E_1,I,25.0,7,8,0.129873,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,-0.266948,2.249584,-0.664253,2.514618,2.544754,0.0,-0.266948,2.249584,-0.664253,2.514618,2.544754,0.0,1.946191,2.764215,3.732438,1.857221,0.854228,15.859516,-8.178667,14.783293,-23.254777,0.0,0.854228,15.859516,-8.178667,14.783293,-23.254777,0.0,15.809308,16.177492,30.640187,9.615172,342.259019,818.982965,-132.465524,555.718597,563.063921,878.153320,0.000000,0.000000,-0.485415,2.282548,0.027944,0.079038,...,17.996673,-5.314021,20.116945,20.358035,0.0,-2.135580,17.996673,-5.314021,20.116945,20.358035,0.0,15.835575,21.618337,29.859508,14.857768,6.833826,126.876125,-65.429332,118.266347,-186.038214,0.0,6.833826,126.876125,-65.429332,118.266347,-186.038214,0.0,130.918539,130.203453,245.121499,76.921380,2738.072153,6551.863720,-1059.724192,4445.748778,5447.139078,7197.666871,0.000000,0.000000,-3.883317,18.260385,0.223554,0.632305,-0.152897,0.432459,10.154589,0.0,0.223554,0.632305,0.152897,0.432459,10.154589,0.0,-85.564898,-111.894037,-111.894037,-84.037310,-84.037310,2.073170e+03,30.767935
7,L_E_1,I,25.0,8,8,0.149511,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,-0.043243,2.622733,-0.870826,2.008837,-0.618625,0.0,-0.043243,2.622733,-0.870826,2.008837,-0.618625,0.0,2.293661,2.402193,2.521950,2.225196,10.073856,29.088869,-4.089140,25.436798,-0.127939,0.0,10.073856,29.088869,-4.089140,25.436798,-0.127939,0.0,28.513755,26.440516,28.526875,26.424691,434.474249,550.376544,-266.768133,343.183636,566.786298,592.128927,-0.076456,1.346745,-0.082146,0.902462,-0.012036,0.338160,...,20.981867,-6.966610,16.070699,-4.949000,0.0,-0.345941,20.981867,-6.966610,16.070699,-4.949000,0.0,18.482263,19.240007,20.175603,17.801566,80.590847,232.710950,-32.713120,203.494381,-1.023511,0.0,80.590847,232.710950,-32.713120,203.494381,-1.023511,0.0,249.177964,231.239085,228.215001,211.397526,3475.793993,4403.012354,-2134.145063,2745.469091,10446.566782,12643.137606,-0.611652,10.773963,-0.657168,7.219694,-0.096285,2.705283,-0.880466,3.315101,12.712619,0.0,1.418916,2.242367,1.768922,2.880931,12.712619,0.0,-39.376527,-92.842805,-92.842805,-22.093024,-22.093024,4.605373e+03,65.400883
8,L_E_1,I,25.0,9,8,0.169710,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,1.267249,3.673381,-1.401901,1.332304,2.158590,0.0,1.267249,3.673381,-1.401901,1.332304,2.158590,0.0,2.964765,3.050355,4.030283,2.472187,32.096764,55.391369,-12.054614,28.594287,4.969134,0.0,32.096764,55.391369,-12.054614,28.594287,4.969134,0.0,43.774610,55.130048,45.353949,53.913528,590.405839,1464.663546,-234.119208,452.719543,812.161565,1434.355784,0.205521,0.370298,-0.215697,1.614687,-0.057293,0.381440,...,29.387047,-11.215211,10.658430,17.268719,0.0,10.137993,29.387047,-11.215211,10.658430,17.268719,0.0,23.760156,24.422251,32.242261,19.777497,256.774114,443.130952,-96.436909,228.754295,39.753071,0.0,256.774114,443.130952,-96.436909,228.754295,39.753071,0.0,359.041597,442.588432,362.831595,431.308223,4723.246711,11717.308365,-1872.953666,3621.756346,10856.467600,11480.392061,1.644168,2.962386,-1.725573,12.917496,-0.458347,3.051522,-1.101515,3.157734,14.907667,0.0,1.459274,2.667994,1.693285,2.842734,14.907667,0.0,-72.929634,-47.887985,-47.887985,-20.584722,-20.584722,8.530884e+03,129.781439
9,L_E_1,I,25.0,10,8,0.189807,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,2.994649,5.122471,-2.363896,2.482013,-0.027904,0.0,2.994649,5.122471,-2.363896,2.482013,-0.027904,0.0,4.427138,5.161003,4.429986,5.158296,19.142400,22.321892,-11.452213,20.352617,6.899283,0.0,19.142400,22.321892,-11.452213,20.352617,6.899283,0.0,25.960141,26.663826,28.003114,25.285665,-410.053917,877.921382,-0.325896,430.205015,734.804440,728.639653,1.522985,3.691680,0.393677,2.286070,0.106759,0.592650,...,40.979771,-18.911164,19.856107,-0.223230,0.0,23.957189,40.979771,-18.911164,19.856107,-0.223230,0.0,35.598449,41.139487,35.439888,41.266369,153.139200,178.575133,-91.617707,162.820940,55.194263,0.0,153.139200,178.575133,-91.617707,162.820940,55.194263,0.0,295.212469,264.639464,224.024913,202.285324,-3280.431337,7023.371057,-2.607165,3441.640121,24712.524116,33713.895708,12.183882,29.533441,3.149416,18.288556,0.854073,4.741200,-2.484988,3.199361,0.277722,0.0,2.856201,3.740231,2.484988,3.199361,0.277722,0.0,-46.616896,-38.286618,-38.286618,-30.890574,-30.890574,1.050911e+04,114.929136
10,L_E_1,I,25.0,11,8,0.210507,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,3.436134,4.319161,-3.467830,3.806597,0.665499,0.0,3.436134,4.319161,-3.467830,3.806597,0.665499,0.0,5.373403,5.233034,5.536896,5.084508,-0.233449,78.180871,-22.633468,34.656538,-10.270954,0.0,-0.233449,78.180871,-22.633468,34.656538,-10.270954,0.0,66.000041,54.042117,68.441853,51.632683,-198.725668,1067.956589,-156.711547,1265.118147,1188.096547,1095.914646,-1.285775,5.242279,1.481940,3.814688,0.467540,1.021937,...,34.553285,-27.742638,30.452775,5.323995,0.0,27.489075,34.553285,-27.742638,30.452775,5.323995,0.0,42.935014,41.266296,44.295169,40.676066,-1.867596,625.446967,-181.067744,277.252306,-82.167629,0.0,-1.867596,625.446967,-181.067744,277.252306,-82.167629,0.0,533.972009,427.073832,547.534828,413.061467,-1589.805345,8543.652711,-1253.692374,10120.945180,23355.916129,25137.682928,-10.286199,41.938232,11.855521,30.517507,3.740317,8.175494,-3.744204,3.998909,13.707507,0.0,5.509736,6.937817,3.744204,3.998909,13.707507,0.0,-51.392790,-45.263037,-45.263037,-90.590948,-90.590948,2.292610e+04,354.644812
11,L_E_1,I,25.0,12,8,0.230466,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,4.584589,7.013352,-5.921411,5.705143,0.495788,0.0,4.584589,7.013352,-5.921411,5.705143,0.495788,0.0,8.115177,8.400289,8.190942,8.332698,24.205947,84.427862,-58.435750,39.983663,-4.054339,0.0,24.205947,84.427862,-58.435750,39.983663,-4.054339,0.0,86.614634,68.739529,86.993616,68.327996,252.552005,1439.606368,-1188.718291,2954.075100,2023.861694,2793.863776,4.485453,7.539735,1.335814,6.086099,0.630140,1.023988,...,56.106817,-47.371285,45.641140,3.966301,0.0,36.676711,56.106817,-47.371285,45.641140,3.966301,0.0,64.973352,67.127339,65.527538,66.661582,193.647577,675.422900,-467.485996,319.869301,-32.434709,0.0,193.647577,675.422900,-467.485996,319.869301,-32.434709,0.0,711.986495,543.259911,695.948930,546.623969,2020.416042,11516.850944,-9509.746327,23632.600799,44261.395624,36990.752082,35.883620,60.317880,10.686510,48.688791,5.041118,8.191908,-5.741123,6.434144,14.280176,0.0,6.041208,7.378394,5.991137,6.168140,14.280176,0.0,-55.497040,-52.251555,-52.251555,-67.499107,-67.499107,4.626015e+04,702.893087
12,L_E_1,I,25.0,13,8,0.249503,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,7.034130,11.036876,-9.316855,7.490193,0.488759,0.0,7.034130,11.036876,-9.316855,7.490193,0.488759,0.0,12.601735,12.336019,12.647926,12.292984,59.960937,85.679103,-67.194852,65.701448,-0.786291,0.0,59.960937,85.679103,-67.194852,65.701448,-0.786291,0.0,101.642902,95.496135,101.717100,95.409507,2110.051120,2956.752384,-1818.866971,4589.607918,3691.211306,4806.730602,7.311542,10.314706,1.104788,6.865456,0.879667,1.238858,...,88.295004,-74.534836,59.921545,3.910072,0.0,56.273036,88.295004,-74.534836,59.921545,3.910072,0.0,100.910248,98.641163,101.183409,98.343871,479.687499,685.432825,-537.558815,525.611584,-6.290330,0.0,479.687499,685.432825,-537.558815,525.611584,-6.290330,0.0,826.105246,745.104913,813.736798,763.276060,16880.408962,23654.019073,-14550.935768,36716.863340,64662.614976,67559.561635,58.492334,82.517650,8.838304,54.923652,7.037333,9.910863,-9.099519,7.896533,14.178165,0.0,7.037333,9.910863,9.099519,7.896533,14.178165,0.0,-60.694886,-52.947570,-52.947570,-48.256057,-48.256057,8.336249e+04,1280.876960
13,L_E_1,I,25.0,14,8,0.269103,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,10.436381,13.749152,-12.112470,9.047009,-0.906691,0.0,10.436381,13.749152,-12.112470,9.047009,-0.906691,0.0,17.229202,14.959419,17.359848,14.817532,86.019243,88.505229,-75.495187,81.516532,-14.862910,0.0,86.019243,88.505229,-75.495187,81.516532,-14.862910,0.0,137.846001,87.932891,139.522043,86.332874,-56.518987,5181.771111,-1040.168502,4789.696793,5008.506733,4728.993734,17.350481,15.909180,1.272666,6.663791,1.433738,1.945572,...,109.993213,-96.899762,72.376069,-7.253530,0.0,83.491051,109.993213,-96.899762,72.376069,-7.253530,0.0,137.898237,119.493599,138.878785,118.540255,688.153945,708.041836,-603.961500,652.132256,-118.903280,0.0,688.153945,708.041836,-603.961500,652.132256,-118.903280,0.0,1335.865040,1030.536328,1116.176348,690.662995,-452.151895,41454.168887,-8321.348016,38317.574343,106350.150407,107451.655235,138.803852,127.273439,10.181330,53.310330,11.469900,15.564573,-14.930295,12.254620,16.531120,0.0,12.098617,15.010701,14.930295,12.254620,16.531120,0.0,-63.821155,-49.251061,-49.251061,-41.271957,-41.271957,1.842134e+05,2374.976523
14,L_E_1,I,25.0,15,8,0.289528,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,14.269411,16.990198,-15.504892,10.881585,-0.938811,0.0,14.269411,16.990198,-15.504892,10.881585,-0.938811,0.0,23.561200,16.735893,23.600962,16.701923,53.928323,78.399855,-47.097020,39.098811,-7.122677,0.0,53.928323,78.399855,-47.097020,39.098811,-7.122677,0.0,104.242354,33.394138,104.503929,33.327846,-1076.379978,2857.515440,878.233514,3624.051260,3480.673605,3107.879111,20.370719,19.065783,1.922501,6.977031,2.286124,2.852180,...,135.921584,-124.039134,87.052679,-7.510486,0.0,114.155288,135.921584,-124.039134,87.052679,-7.510486,0.0,188.484410,133.816071,188.807698,133.615386,431.426585,627.198838,-376.776157,312.790487,-56.981418,0.0,431.426585,627.198838,-376.776157,312.790487,-56.981418,0.0,918.818959,282.483053,836.031429,266.622771,-8611.039823,22860.123522,7025.868113,28992.410083,78780.853550,65883.383841,162.965753,152.526261,15.380009,55.816247,18.288992,22.817443,-21.309505,16.490363,4.296352,0.0,18.635782,22.494472,21.309505,16.490363,4.296352,0.0,-63.569375,-47.376118,-47.376118,-41.131565,-41.131565,1.731830e+05,2456.074952
15,L_E_1,I,25.0,16,8,0.309516,L,L_E,L,L workspace (80x60 cm),80.0,60.0,success,85.0,25.0,1.0,17.506842,20.542780,-18.886908,12.154831,-1.613713,0.0,17.506842,20.542780,-18.886908,12.154831,-1.613713,0.0,30.234877,16.821228,30.299575,16.776586,64.250309,101.321038,-57.627730,64.475926,-7.019152,0.0,64.250309,101.321038,-57.627730,64.475926,-7.019152,0.0,120.960236,78.833563,121.312421,78.571771,-8.665311,3788.185560,745.449952,3897.059119,4389.513665,2855.207307,30.318840,22.989021,2.204651,7.483701,3.297028,3.663698,...,164.342241,-151.095260,97.238649,-12.909701,0.0,140.054734,164.342241,-151.095260,97.238649,-12.909701,0.0,242.007084,134.271872,242.396603,134.212686,514.002470,810.568302,-461.021839,515.807409,-56.153218,0.0,514.002470,810.568302,-461.021839,515.807409,-56.153218,0.0,1331.801786,705.244384,970.499372,628.574171,-69.322489,30305.484482,5963.599612,31176.472955,91643.286187,68069.622965,242.550716,183.912169,17.637209,59.869612,26.376224,29.309583,-30.096218,21.494781,12.159543,0.0,26.981440,28.673078,30.096218,21.494781,12.159543,0.0,-61.073287,-47.171639,-47.171639,-41.889735,-41.889735,3.223055e+05,3657.217889

Subject velocity/acceleration summary:

,subject_id,finger_condition,stiffness_value,subject_group,experiment_group,workspace_setup,workspace_label,n_time_bins,n_segments_mean,success_rate,mean_vx_cm_s,peak_abs_vx_cm_s,sd_over_time_vx_cm_s,time_fraction_peak_abs_vx_cm_s,mean_vy_cm_s,peak_abs_vy_cm_s,sd_over_time_vy_cm_s,time_fraction_peak_abs_vy_cm_s,mean_vz_cm_s,peak_abs_vz_cm_s,sd_over_time_vz_cm_s,time_fraction_peak_abs_vz_cm_s,mean_vx_3d_cm_s,peak_abs_vx_3d_cm_s,sd_over_time_vx_3d_cm_s,time_fraction_peak_abs_vx_3d_cm_s,mean_vy_3d_cm_s,peak_abs_vy_3d_cm_s,sd_over_time_vy_3d_cm_s,time_fraction_peak_abs_vy_3d_cm_s,mean_vz_3d_proxy_cm_s,peak_abs_vz_3d_proxy_cm_s,sd_over_time_vz_3d_proxy_cm_s,time_fraction_peak_abs_vz_3d_proxy_cm_s,mean_speed_3d_proxy_cm_s,peak_abs_speed_3d_proxy_cm_s,sd_over_time_speed_3d_proxy_cm_s,time_fraction_peak_abs_speed_3d_proxy_cm_s,mean_speed_cm_s,peak_abs_speed_cm_s,sd_over_time_speed_cm_s,time_fraction_peak_abs_speed_cm_s,mean_ax_cm_s2,peak_abs_ax_cm_s2,sd_over_time_ax_cm_s2,time_fraction_peak_abs_ax_cm_s2,mean_ay_cm_s2,peak_abs_ay_cm_s2,sd_over_time_ay_cm_s2,time_fraction_peak_abs_ay_cm_s2,mean_az_cm_s2,peak_abs_az_cm_s2,sd_over_time_az_cm_s2,time_fraction_peak_abs_az_cm_s2,mean_ax_3d_cm_s2,peak_abs_ax_3d_cm_s2,sd_over_time_ax_3d_cm_s2,time_fraction_peak_abs_ax_3d_cm_s2,mean_ay_3d_cm_s2,peak_abs_ay_3d_cm_s2,...,mean_ay_px_s2,peak_abs_ay_px_s2,sd_over_time_ay_px_s2,time_fraction_peak_abs_ay_px_s2,mean_az_px_s2,peak_abs_az_px_s2,sd_over_time_az_px_s2,time_fraction_peak_abs_az_px_s2,mean_ax_3d_px_s2,peak_abs_ax_3d_px_s2,sd_over_time_ax_3d_px_s2,time_fraction_peak_abs_ax_3d_px_s2,mean_ay_3d_px_s2,peak_abs_ay_3d_px_s2,sd_over_time_ay_3d_px_s2,time_fraction_peak_abs_ay_3d_px_s2,mean_az_3d_proxy_px_s2,peak_abs_az_3d_proxy_px_s2,sd_over_time_az_3d_proxy_px_s2,time_fraction_peak_abs_az_3d_proxy_px_s2,mean_acceleration_3d_proxy_px_s2,peak_abs_acceleration_3d_proxy_px_s2,sd_over_time_acceleration_3d_proxy_px_s2,time_fraction_peak_abs_acceleration_3d_proxy_px_s2,mean_acceleration_px_s2,peak_abs_acceleration_px_s2,sd_over_time_acceleration_px_s2,time_fraction_peak_abs_acceleration_px_s2,mean_jx_px_s3,peak_abs_jx_px_s3,sd_over_time_jx_px_s3,time_fraction_peak_abs_jx_px_s3,mean_jy_px_s3,peak_abs_jy_px_s3,sd_over_time_jy_px_s3,time_fraction_peak_abs_jy_px_s3,mean_jerk_px_s3,peak_abs_jerk_px_s3,sd_over_time_jerk_px_s3,time_fraction_peak_abs_jerk_px_s3,mean_radial_velocity_px_s,peak_abs_radial_velocity_px_s,sd_over_time_radial_velocity_px_s,time_fraction_peak_abs_radial_velocity_px_s,mean_tangential_velocity_px_s,peak_abs_tangential_velocity_px_s,sd_over_time_tangential_velocity_px_s,time_fraction_peak_abs_tangential_velocity_px_s,early_mean_speed_cm_s,late_mean_speed_cm_s,late_minus_early_speed_cm_s,early_mean_acceleration_cm_s2,late_mean_acceleration_cm_s2,late_minus_early_acceleration_cm_s2,early_mean_speed_px_s,late_mean_speed_px_s,late_minus_early_speed_px_s,early_mean_acceleration_px_s2,late_mean_acceleration_px_s2,late_minus_early_acceleration_px_s2
0,L_E_1,I,25.0,L,L_E,L,L workspace (80x60 cm),50,8.0,1.000000,0.003769,53.019371,23.087357,0.570305,-0.023934,22.129792,11.057053,0.350331,0.587074,7.831731,2.778299,0.529736,0.003769,53.019371,23.087357,0.570305,-0.023934,22.129792,11.057053,0.350331,0.587074,7.831731,2.778299,0.529736,24.725717,54.334480,15.709965,0.590626,25.171138,55.589523,16.293163,0.570305,3.924342,199.802007,91.338208,0.469997,0.138126,75.495187,33.972353,0.269103,-0.019574,34.097262,12.476669,0.509759,3.924342,199.802007,91.338208,0.469997,0.138126,75.495187,...,1.105004,603.961500,271.778823,0.269103,-0.156591,272.778098,99.813352,0.509759,31.394733,1598.416057,730.705666,0.469997,1.105004,603.961500,271.778823,0.269103,-0.156591,272.778098,99.813352,0.509759,1047.341339,2004.971993,597.087281,0.529736,1372.882500,3238.605386,856.136710,0.549942,519.447756,78623.853340,22983.383413,0.570305,-1388.133921,57729.385921,14564.206724,0.390078,125653.216033,380809.311555,92948.207656,0.549942,-1.727903,300.839204,145.821868,0.829986,-59.102355,409.542735,135.833228,0.570305,7.134978,27.102470,19.967492,51.224852,131.028249,79.803397,57.140929,217.242216,160.101287,464.560235,1399.962858,935.402623
1,L_E_1,I,40.0,L,L_E,L,L workspace (80x60 cm),50,8.0,1.000000,0.004801,22.812751,8.904875,0.510012,-0.029340,19.915331,9.907698,0.410407,0.452669,11.232112,2.617893,0.090274,0.004801,22.812751,8.904875,0.510012,-0.029340,19.915331,9.907698,0.410407,0.452669,11.232112,2.617893,0.090274,26.510750,47.753027,13.244517,0.609982,25.171094,47.428920,14.040027,0.609982,-8.825035,160.710041,45.672120,0.429981,1.559188,94.541612,30.585466,0.449946,-0.776609,37.682358,11.401179,0.550245,-8.825035,160.710041,45.672120,0.429981,1.559188,94.541612,...,12.473501,756.332897,244.683724,0.449946,-6.212876,301.458868,91.209434,0.550245,-70.600283,1285.680330,365.376956,0.429981,12.473501,756.332897,244.683724,0.449946,-6.212876,301.458868,91.209434,0.550245,1026.548667,2135.880567,496.493655,0.510012,1368.469084,2679.795069,727.316736,0.429981,-1280.640993,79874.254354,22857.737652,0.429981,-1236.476853,45956.202727,13921.098742,0.449946,121622.058016,265244.569359,73189.606768,0.609982,0.931143,227.666718,111.205915,0.349657,-17.234385,157.533405,64.800662,0.489810,8.320973,28.424323,20.103351,49.020695,129.326654,80.305960,66.863787,227.962193,161.098406,513.328197,1459.147277,945.819080
2,L_E_1,I,55.0,L,L_E,L,L workspace (80x60 cm),50,8.0,1.000000,-0.061250,27.755624,12.342659,0.510174,0.027095,17.055512,9.217181,0.289801,-0.206413,10.819655,2.702238,0.430495,-0.061250,27.755624,12.342659,0.510174,0.027095,17.055512,9.217181,0.289801,-0.206413,10.819655,2.702238,0.430495,26.483562,47.380354,13.928003,0.650008,25.421798,47.380296,14.185069,0.650008,-0.383832,111.154624,50.078221,0.569874,3.210128,74.930097,33.023259,0.409771,-0.945950,44.151443,10.588792,0.530342,-0.383832,111.154624,50.078221,0.569874,3.210128,74.930097,...,25.681023,599.440778,264.186073,0.409771,-7.567600,353.211543,84.710338,0.530342,-3.070654,889.236993,400.625768,0.569874,25.681023,599.440778,264.186073,0.409771,-7.567600,353.211543,84.710338,0.530342,976.091844,1647.542514,395.486370,0.629742,1363.833801,2768.398976,727.927218,0.669778,6845.261588,84118.914054,24615.170286,0.389602,-2135.239094,40027.134701,13255.555344,0.350730,127085.288176,281506.049903,77892.070029,0.650008,1.486799,246.395206,134.703574,0.289801,-9.132586,235.941480,95.191240,0.470276,10.364137,26.333324,15.969187,61.015344,108.675467,47.660124,83.311108,211.162022,127.850914,620.565374,1333.341411,712.776038
3,L_E_1,I,70.0,L,L_E,L,L workspace (80x60 cm),50,8.0,0.750000,0.049136,24.012641,11.653808,0.549379,-0.034807,18.676066,8.286475,0.250363,0.154533,6.878045,2.101359,0.569659,0.049136,24.012641,11.653808,0.549379,-0.034807,18.676066,8.286475,0.250363,0.154533,6.878045,2.101359,0.569659,26.846036,56.076532,14.464643,0.610194,26.162562,56.060812,14.860934,0.610194,-1.185862,136.366350,52.281214,0.629853,3.096279,67.860315,30.771834,0.610194,-0.387381,20.758986,6.827101,0.429481,-1.185862,136.366350,52.281214,0.629853,3.096279,67.860315,...,24.770228,542.882522,246.174670,0.610194,-3.099044,166.071891,54.616809,0.429481,-9.486897,1090.930803,418.249709,0.629853,24.770228,542.882522,246.174670,0.610194,-3.099044,166.071891,54.616809,0.429481,1041.098195,1929.120978,470.168550,0.689983,1433.629707,2872.624593,731.377698,0.610194,-380.499637,76944.752827,24736.742045,0.629853,-14.163884,30870.035867,9948.845925,0.629853,126593.799953,302489.965612,75253.891916,0.610194,-1.300219,242.810701,115.703705,0.829846,-31.468502,189.013373,71.688217,0.569659,12.418910,25.833204,13.414294,66.700882,131.029515,64.328633,99.583400,206.902621,107.319220,773.036646,1439.240736,666.204090
4,L_E_1,I,85.0,L,L_E,L,L workspace (80x60 cm),50,64.0,0.890625,-0.002222,20.583397,8.272749,0.410028,-0.002074,15.765705,7.266381,0.269938,0.129934,4.250709,1.541870,0.430143,-0.002222,20.583397,8.272749,0.410028,-0.002074,15.765705,7.266381,0.269938,0.129934,4.250709,1.541870,0.430143,27.456796,44.883184,13.402986,0.589938,26.865501,44.854097,13.668675,0.589938,0.582065,93.612210,31.709361,0.330097,0.848676,43.737453,17.784548,0.389921,-1.169416,33.209417,8.784299,0.469944,0.582065,93.612210,31.709361,0.330097,0.848676,43.737453,...,6.789405,349.899620,142.276380,0.389921,-9.355327,265.675339,70.274393,0.469944,4.656523,748.897683,253.674890,0.330097,6.789405,349.899620,142.276380,0.389921,-9.355327,265.675339,70.274393,0.469944,1030.704722,1635.406913,427.636563,0.489986,1434.066150,2372.179236,694.783252,0.549852,113.634271,21178.724690,8309.176338,0.549852,110.366727,7761.375770,3035.148349,0.769940,126082.223876,211369.575389,63581.758244,0.670122,1.203959,190.285194,96.847885,0.889954,-25.412875,207.388818,66.258641,0.389921,12.974457,26.430038,13.455582,67.784058,113.530296,45.746238,104.153156,212.223208,108.070052,746.479865,1361.837907,615.358042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,L_E_11,I,70.0,L,L_E,L,L workspace (80x60 cm),50,8.0,0.500000,-0.009630,9.725777,3.726303,0.289717,0.052617,8.185299,3.802987,0.930139,0.309474,36.541831,7.623022,0.289717,-0.009630,9.725777,3.726303,0.289717,0.052617,8.185299,3.802987,0.930139,0.309474,36.541831,7.623022,0.289717,18.095020,44.835903,9.473545,0.289717,16.055561,29.301780,8.595870,0.270135,0.819502,112.785064,29.153506,0.270135,0.438559,108.861945,31.258788,0.910169,-1.446672,396.666237,90.414474,0.530009,0.819502,112.785064,29.153506,0.270135,0.438559,108.861945,...,3.508474,870.895562,250.070305,0.910169,-11.573377,3173.329898,723.315790,0.530009,6.556016,902.280510,233.228051,0.270135,3.508474,870.895562,250.070305,0.910169,-11.573377,3173.329898,723.315790,0.530009,879.971727,3314.651313,584.378986,0.530009,1423.177386,2772.853635,775.860978,0.270135,-1031.746882,76195.019922,21205.755382,0.389873,2699.471941,60963.784492,19921.591005,0.389873,163122.177451,415930.559098,105673.744992,0.729924,3.500332,223.255993,70.288589,0.930139,1.590083,38.549250,13.564239,0.270135,8.895388,19.314725,10.419338,51.733574,96.063169,44.329595,71.255134,155.603744,84.348610,717.721698,1740.500919,1022.779221
76,L_E_11,I,85.0,L,L_E,L,L workspace (80x60 cm),50,64.0,0.703125,0.005000,9.145170,3.710910,0.310071,-0.018943,13.219856,4.749092,0.910096,0.152976,4.398213,1.425301,0.529967,0.005000,9.145170,3.710910,0.310071,-0.018943,13.219856,4.749092,0.910096,0.152976,4.398213,1.425301,0.529967,15.735285,25.810672,6.833561,0.910096,15.389162,25.726056,6.975293,0.910096,0.230472,39.855869,15.261916,0.870008,0.973464,51.323086,16.962664,0.990857,1.320329,27.227213,9.054149,0.630082,0.230472,39.855869,15.261916,0.870008,0.973464,51.323086,...,7.787708,410.584685,135.701310,0.990857,10.562629,217.817707,72.433195,0.630082,1.843778,318.846952,122.095330,0.870008,7.787708,410.584685,135.701310,0.990857,10.562629,217.817707,72.433195,0.630082,667.108984,952.882838,215.778472,0.509883,1399.808759,2180.495011,622.569945,0.509883,-204.533076,23036.913353,10634.632276,0.330030,757.326358,36455.887045,12579.596585,0.930025,171377.860324,313841.623784,84959.878362,0.509883,4.365826,207.200309,59.203394,0.910096,-0.833590,12.067843,5.014113,0.009025,7.365904,19.633306,12.267402,43.750130,94.862983,51.112853,59.435693,157.815949,98.380256,651.256306,1731.790086,1080.533781
77,L_E_11,I,100.0,L,L_E,L,L workspace (80x60 cm),50,8.0,0.625000,-0.043920,11.020921,4.312248,0.890286,0.172524,16.701425,5.728119,0.890286,0.204329,10.166761,2.496339,0.609937,-0.043920,11.020921,4.312248,0.890286,0.172524,16.701425,5.728119,0.890286,0.204329,10.166761,2.496339,0.609937,13.303504,29.589075,8.155648,0.769811,12.779664,29.420278,7.776670,0.769811,-1.437278,102.347153,21.638966,0.810004,0.743991,115.041246,32.563771,0.810004,0.073548,153.475227,32.466499,0.509759,-1.437278,102.347153,21.638966,0.810004,0.743991,115.041246,...,5.951929,920.329972,260.510164,0.810004,0.588388,1227.801812,259.731991,0.509759,-11.498227,818.777227,173.111724,0.810004,5.951929,920.329972,260.510164,0.810004,0.588388,1227.801812,259.731991,0.509759,546.783058,1487.882080,320.475248,0.509759,1054.266852,2724.990497,689.242220,0.789673,-500.133640,47480.647933,18229.731835,0.810004,-902.407429,56046.534031,21875.486053,0.810004,126926.015240,331180.460981,93606.255091,0.509759,-4.970216,180.438682,57.887788,0.910091,4.413550,63.829605,13.210354,0.008865,3.584160,19.948502,16.364343,28.505573,96.375157,67.869585,28.806534,160.982304,132.175770,307.784645,1635.330885,1327.546240
78,L_E_11,I,115.0,L,L_E,L,L workspace (80x60 cm),50,8.0,0.625000,0.028460,14.603592,6.334255,0.709813,-0.005633,10.032487,3.585591,0.209531,0.454328,19.489372,5.590463,0.350152,0.028460,14.603592,6.334255,0.709813,-0.005633,10.032487,3.585591,0.209531,0.454328,19.489372,5.590463,0.350152,16.925207,30.738241,8.267883,0.270159,15.698250,31.230791,8.398814,0.910149,4.003520,66.822890,27.157970,0.970291,1.482621,78.429599,22.727884,0.270159,-3.724401,250.023291,53.149292,0.390284,4.003520,66.822890,27.157970,0.970291,1.482621,78.429599,...,11.860964,627.436789,181.823076,0.270159,-29.795209,2000.186325,425.194338,0.390284,32.028161,534.583123,217.263757,0.970291,11.860964,627.436789,181.823076,0.270159,-29.795209,2000.186325,425.194338,0.390284,774.295015,2200.482287,375.878258,0.390284,1464.353040,4621.691830,872.705480,0.910149,-3048.787698,109969.029170,36100.129998,0.509834,2326.992397,85464.631280,23560.674514,0.270159,179872.105732,544382.893726,121644.219969,0.910149,0.518602,228.436079,105.073081,0.930070,-1.948059,32.732712,12.486705,0.329584,9.503216,20.371872,10.868656,57.483506,93.448244,35.964738,77.029924,164.488074,87.458150,925.560925,2046.014659,1120.453735
79,L_E_11,I,130.0,L,L_E,L,L workspace (80x60 cm),50,8.0,0.625000,-0.050290,14.651551,6.375371,0.770265,0.031761,14.412209,5.398056,0.910065,0.297866,4.505713,1.900093,0.830243,-0.050290,14.651551,6.375371,0.770265,0.031761,14.412209,5.398056,0.910065,0.297866,4.505713,1.900093,0.830243,17.764896,31.381103,8.118961,0.390051,16.881566,31.340094,8.461996,0.390051,2.065441,93.514258,37.374172,0.830243,-0.071651,75.793520,31.785348,0.770265,-0.499253,79.637047,17.135909,0.530082,2.065441,93.514258,37.374172,0.830243,-0.071651,75.793520,...,-0.573205,606.348158,254.282784,0.770265,-3.994024,637.096372,137.087268,0.530082,16.523529,748.114064,298.993374,0.830243,-0.573205,606.348158,254.282784,0.770265,-3.994024,637.096372,137.087268,0.530082,750.065500,1322.217084,284.733779,0.789902,1550.880606,3198.667182,788.419018,0.530082,-1857.482005,73551.739994,32082.837119,0.750542,2447.708600,66332.215336,27461.492942,0.770265,180637.634704,376530.598082,99856.177347,0.770265,1.268783,271.016966,86.695889,0.910065,0.730891,34.910164,14.241191,0.930220,9.654037,19.188872,9.534836,59.503074,103.235177,43.732103,77.629607,153.827813,76.198206,859.841035,1829.103569,969.262534

Subject-specific finger velocity/acceleration distances:

,subject_id,stiffness_value,finger_a,finger_b,comparison,n_matched_time_bins,mean_velocity_vector_distance_cm_s,rms_velocity_vector_distance_cm_s,mean_velocity_vector_distance_3d_proxy_cm_s,rms_velocity_vector_distance_3d_proxy_cm_s,mean_acceleration_vector_distance_cm_s2,rms_acceleration_vector_distance_cm_s2,mean_acceleration_vector_distance_3d_proxy_cm_s2,rms_acceleration_vector_distance_3d_proxy_cm_s2,speed_profile_rmse_cm_s,speed_profile_rmse_3d_proxy_cm_s,acceleration_profile_rmse_cm_s2,acceleration_profile_rmse_3d_proxy_cm_s2,mean_velocity_vector_distance_px_s,rms_velocity_vector_distance_px_s,mean_velocity_vector_distance_3d_proxy_px_s,rms_velocity_vector_distance_3d_proxy_px_s,mean_acceleration_vector_distance_px_s2,rms_acceleration_vector_distance_px_s2,mean_acceleration_vector_distance_3d_proxy_px_s2,rms_acceleration_vector_distance_3d_proxy_px_s2,speed_profile_rmse_px_s,speed_profile_rmse_3d_proxy_px_s,acceleration_profile_rmse_px_s2,acceleration_profile_rmse_3d_proxy_px_s2
0,L_E_1,25.0,I,M,M - I,50,9.433282,11.687538,9.903329,11.805794,52.862184,66.328753,51.864187,62.608151,6.064000,5.888142,42.890162,41.065241,75.466256,93.500301,79.226635,94.446356,422.897474,530.630027,414.913492,500.865209,48.231570,47.105135,379.333996,328.521931
2,L_E_1,25.0,I,P,P - I,50,13.106090,16.507325,13.811795,16.925294,58.875465,75.262195,72.790311,90.802725,13.464460,13.405036,90.502772,91.904647,104.848717,132.058599,110.494357,135.402352,471.003718,602.097560,582.322489,726.421798,107.794767,107.240287,828.209058,735.237178
4,L_E_1,25.0,M,P,P - M,50,9.469493,11.064607,10.435249,12.041249,44.457565,53.013259,58.272713,71.215023,10.548539,10.587068,57.793425,61.642089,75.755945,88.516853,83.481990,96.329995,355.660519,424.106068,466.181706,569.720182,84.480369,84.696544,652.716851,493.136714
5,L_E_1,25.0,R,P,P - R,50,16.434981,21.080409,17.928238,22.517315,49.955101,63.199053,61.001503,79.708605,5.260230,5.235285,44.476486,48.582645,131.479846,168.643275,143.425904,180.138517,399.640809,505.592428,488.012021,637.668843,42.232054,41.882277,560.626560,388.661161
1,L_E_1,25.0,I,R,R - I,50,27.391673,34.839730,29.206021,36.100680,88.439488,116.336122,98.609208,124.747079,17.780078,17.459414,94.504598,96.293741,219.133384,278.717837,233.648169,288.805438,707.515907,930.688977,788.873667,997.976632,142.466988,139.675312,965.838460,770.349924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,L_E_10,70.0,R,P,P - R,50,8.973221,11.239994,9.096857,11.363221,53.951479,63.507091,58.605677,68.738574,4.567194,4.921741,39.961427,43.793896,71.785766,89.919952,72.774856,90.905771,431.611834,508.056731,468.845419,549.908595,35.945557,39.373928,786.030609,350.351169
73,L_E_10,70.0,I,R,R - I,50,9.666970,11.035979,12.751358,15.326477,48.208286,57.566429,91.040484,138.493831,4.296600,8.374317,47.304199,103.415866,77.335760,88.287834,102.010863,122.611820,385.666285,460.531434,728.323872,1107.950652,33.790373,66.994538,893.096750,827.326930
75,L_E_10,70.0,M,R,R - M,50,11.462701,13.198830,11.584188,13.209136,57.653964,65.768314,60.807695,68.958269,6.728143,6.673588,48.584586,50.141078,91.701610,105.590639,92.673504,105.673089,461.231715,526.146514,486.461562,551.666150,53.538552,53.388708,898.946847,401.128621
78,L_E_10,85.0,I,M,M - I,50,6.609505,7.802507,7.569749,8.813011,23.784231,29.772169,43.836327,68.797675,4.277198,5.203383,14.268437,50.636292,52.876038,62.420053,60.557989,70.504084,190.273851,238.177354,350.690618,550.381401,34.383504,41.627063,280.580222,405.090335
80,L_E_10,85.0,I,P,P - I,50,5.348303,6.588969,6.437605,7.902297,20.605759,23.993594,40.570365,66.484112,2.483702,3.251639,17.954241,46.922218,42.786423,52.711755,51.500839,63.218379,164.846071,191.948752,324.562919,531.872894,19.740464,26.013115,193.085223,375.377741

Subject velocity/acceleration metric distributions with mean/median/95% CI and log-backtransformed summaries:

,subject_id,finger_condition,metric,n,mean,mean_ci95_low,mean_ci95_high,median,median_ci95_low,median_ci95_high,sd,sem,skewness,log_transform_valid,log_transform_recommended,geometric_mean_backtransformed,geometric_ci95_low_backtransformed,geometric_ci95_high_backtransformed
0,L_E_1,I,mean_vx_cm_s,9,0.015230,-0.012152,0.042613,0.004801,-0.019465,0.049136,0.041912,0.013971,-0.276289,True,True,0.022354,0.007866,0.063532
1,L_E_1,I,peak_abs_vx_cm_s,9,29.342284,22.773621,35.910946,27.755624,21.247888,34.885371,10.054075,3.351358,1.291120,True,True,28.115095,23.168707,34.117508
2,L_E_1,I,mean_vy_cm_s,9,-0.021343,-0.035148,-0.007538,-0.029340,-0.037372,-0.002074,0.021130,0.007043,1.280900,False,False,NaN,NaN,NaN
3,L_E_1,I,peak_abs_vy_cm_s,9,17.419119,14.777707,20.060532,17.055512,13.568351,22.129792,4.042978,1.347659,0.118788,True,False,16.996289,14.557115,19.844169
4,L_E_1,I,mean_vz_3d_proxy_cm_s,9,0.083479,-0.112603,0.279560,0.069226,-0.206413,0.452669,0.300125,0.100042,0.236941,True,True,0.155507,0.066889,0.361535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,L_E_1,P,late_minus_early_acceleration_cm_s2,9,35.320717,28.522093,42.119342,35.476763,30.147511,45.497635,10.406057,3.468686,-0.886557,True,False,33.375241,25.749276,43.259728
76,L_E_1,P,mean_radial_velocity_cm_s,9,-0.042572,-0.128166,0.043022,-0.070851,-0.172238,0.089938,0.131011,0.043670,0.694384,True,True,0.040541,0.003404,0.482800
77,L_E_1,P,mean_tangential_velocity_cm_s,9,-1.308811,-2.193911,-0.423710,-1.357397,-2.978847,0.366055,1.354746,0.451582,0.115891,True,False,0.558019,0.244213,1.275059
78,L_E_1,R,mean_vx_cm_s,9,-0.002272,-0.050924,0.046381,-0.013769,-0.062339,0.070558,0.074468,0.024823,-0.086670,True,False,0.072701,0.042321,0.124888
79,L_E_1,R,peak_abs_vx_cm_s,9,27.285136,25.678527,28.891744,27.102677,24.575060,30.200585,2.459095,0.819698,0.002794,True,False,27.186269,25.625372,28.842243

Velocity influence answers: stiffness, fingers, and time thirds

,stiffness_value,n_observations,n_subjects,median_vx_cm_s,median_vy_cm_s,median_vz_3d_proxy_cm_s,mean_velocity_cm_s,mean_velocity_3d_proxy_cm_s,sem_velocity_cm_s,median_ax_cm_s2,median_ay_cm_s2,median_az_3d_proxy_cm_s2,mean_acceleration_cm_s2,mean_acceleration_3d_proxy_cm_s2
0,25.0,7900,40,0.026569,0.017860,0.039324,16.026067,17.403293,0.172774,0.182984,0.000004,-0.778278,80.148022,94.478430
1,40.0,7900,40,0.039628,0.005293,0.043133,16.375818,17.557667,0.177060,0.031329,-0.108705,-0.811479,79.584548,91.278123
2,55.0,7900,40,0.038005,-0.002806,0.022193,16.315893,17.501709,0.175811,0.394813,-0.414177,-0.599329,78.684514,91.611683
3,70.0,7900,40,0.019845,0.000025,0.024912,16.151571,17.616253,0.178529,0.199687,-0.059497,-0.703443,77.525765,91.356999
4,85.0,7900,40,0.024020,0.007421,0.093965,16.435578,17.495118,0.166902,0.305895,-0.054424,-0.432879,81.106439,90.493467
5,100.0,7900,40,0.019685,0.005197,0.020475,16.229138,17.463988,0.174378,0.439774,0.000044,-0.566100,78.220144,91.094625
6,115.0,7900,40,0.027233,-0.018096,0.000000,15.699249,16.807764,0.167989,0.034057,0.262144,-0.790261,74.989543,88.834539
7,130.0,7900,40,0.023298,0.006847,0.069575,15.746290,17.163601,0.175701,0.263097,-0.117474,-0.634827,76.929391,90.797747
8,145.0,7900,40,0.015909,0.003378,0.037927,16.005650,17.367505,0.176309,0.153983,-0.169493,-0.648842,76.363793,89.884019

,finger_condition,n_observations,n_subjects,median_vx_cm_s,median_vy_cm_s,median_vz_3d_proxy_cm_s,mean_velocity_cm_s,mean_velocity_3d_proxy_cm_s,sem_velocity_cm_s,median_ax_cm_s2,median_ay_cm_s2,median_az_3d_proxy_cm_s2,mean_acceleration_cm_s2,mean_acceleration_3d_proxy_cm_s2
0,I,18000,40,0.038672,0.000254,0.059767,16.338686,17.716935,0.113456,0.201773,-0.159302,-0.677214,80.425130,94.286136
1,M,17550,39,0.009168,0.003046,0.039302,15.904082,17.283195,0.130956,0.042684,-0.031855,-0.655520,79.321207,94.446198
2,P,18000,40,0.042671,0.003242,0.018609,15.844406,16.919426,0.095815,0.571506,-0.033367,-0.537729,74.445843,84.716761
3,R,17550,39,0.017803,0.008057,0.038463,16.384685,17.576569,0.121129,0.082873,-0.000052,-0.783823,79.694947,92.147786

,time_third,stiffness_value,n_observations,n_subjects,median_vx_cm_s,median_vy_cm_s,median_vz_3d_proxy_cm_s,mean_velocity_cm_s,mean_velocity_3d_proxy_cm_s,mean_acceleration_cm_s2,mean_acceleration_3d_proxy_cm_s2
0,early,25.0,2686,40,0.031654,-0.024227,0.150105,1.954403,3.952501,22.095588,36.708622
1,early,40.0,2686,40,0.043289,-0.035605,0.181681,2.181495,4.281686,24.125978,38.826160
2,early,55.0,2686,40,0.041167,-0.024407,0.104176,2.394333,4.399116,25.544564,41.626380
3,early,70.0,2686,40,0.014781,-0.016933,0.120956,2.607412,4.895895,26.003566,41.545891
4,early,85.0,2686,40,0.039628,-0.015465,0.207339,2.951165,4.784750,27.287619,42.285201
5,early,100.0,2686,40,0.043544,-0.013984,0.076579,2.534996,4.734004,25.950523,42.174756
6,early,115.0,2686,40,0.045126,-0.052789,0.017261,2.590433,4.420893,27.182569,43.484037
7,early,130.0,2686,40,0.028128,-0.004333,0.219855,2.385461,4.768608,25.507408,40.139518
8,early,145.0,2686,40,0.029553,-0.033382,0.176856,2.587031,4.714003,26.021745,41.013286
9,middle,25.0,2528,40,1.062896,0.335308,0.031679,21.613926,22.618189,108.716558,116.544192
10,middle,40.0,2528,40,0.915647,0.420089,0.056437,21.157168,22.325771,108.149577,118.580133
11,middle,55.0,2528,40,1.282133,0.217957,0.000000,21.716418,22.794589,106.582661,118.363626
12,middle,70.0,2528,40,1.144478,-0.078652,0.026619,21.546223,22.753945,106.265973,115.699663
13,middle,85.0,2528,40,0.611317,0.154974,0.124585,21.668754,22.359765,110.162348,115.640999
14,middle,100.0,2528,40,0.823434,0.117908,0.076633,21.865211,22.756685,109.033073,118.489518
15,middle,115.0,2528,40,0.676338,0.108454,0.004186,20.314988,21.755193,103.501508,112.905988
16,middle,130.0,2528,40,1.023167,0.210657,0.064928,20.988939,22.128013,108.377223,116.886025
17,middle,145.0,2528,40,0.816860,0.200161,0.010673,21.131614,22.128128,105.552398,115.627310
18,late,25.0,2686,40,-0.825145,0.151212,-0.040639,22.469438,23.348833,109.768692,118.854071
19,late,40.0,2686,40,-0.801633,0.139341,-0.106256,22.323998,23.156246,107.452944,115.430602
20,late,55.0,2686,40,-1.112759,0.035343,-0.011209,21.750510,22.454172,103.121310,111.053666
21,late,70.0,2686,40,-0.990380,0.287641,-0.054659,21.422947,22.305925,101.311028,110.121470
22,late,85.0,2686,40,-0.550058,0.092368,-0.079740,21.515796,22.046989,103.375513,108.156970
23,late,100.0,2686,40,-0.935756,0.053859,-0.035879,21.157826,21.827158,97.428059,105.619519
24,late,115.0,2686,40,-0.852952,0.147480,-0.038474,20.487894,21.342037,97.843690,105.720826
25,late,130.0,2686,40,-0.929647,-0.041908,-0.007293,20.948446,21.874687,99.935100,108.177107
26,late,145.0,2686,40,-0.743266,0.205503,-0.037425,20.989078,21.719963,101.868138,110.333399

Saved 525 velocity/acceleration figures for this selection level

In [14]:
standard_vs_comparison_position_figure_paths = ka.save_standard_vs_comparison_position_figures(
    OUTPUT_ROOT, subject_velocity_acceleration_profile, levels=("subject", "group"), fig_dpi=FIG_DPI
)
print(
    f"Saved {len(standard_vs_comparison_position_figure_paths)} standard-vs-comparison position figures "
    "(|Y| and |X| distance from center + movement direction; per subject + per group)"
)

Saved 215 standard-vs-comparison position figures (|Y| and |X| distance from center + movement direction; per subject + per group)

## 9. 3D proxy kinematics, confidence intervals, and optional LMM

Combines top-camera XY with side-camera Z/lift proxy inside each subject/trial/stiffness segment. Outputs include 3D path length, max excursion, peak velocity, peak acceleration, median and 95% confidence intervals, log-domain summaries back-transformed to original units, individual data points in the direction/stiffness figure, and an optional mixed-effects model if `statsmodels` is installed.

In [15]:
proxy3d = ka.compute_3d_proxy_kinematics(kinematic_samples, side_z_samples)
kinematic_3d_proxy_samples = proxy3d["kinematic_3d_proxy_samples"]
trial_3d_kinematic_summary = proxy3d["trial_3d_kinematic_summary"]
subject_3d_kinematic_summary = proxy3d["subject_3d_kinematic_summary"]
subject_3d_metric_distribution = proxy3d["subject_3d_metric_distribution"]
stiffness_direction_3d_metric_distribution = proxy3d["stiffness_direction_3d_metric_distribution"]
mixedlm_model_input = proxy3d["mixedlm_model_input"]

ka.save_parquet(kinematic_3d_proxy_samples, OUTPUT_ROOT, "kinematic_3d_proxy_samples.parquet")
ka.save_csv(trial_3d_kinematic_summary, OUTPUT_ROOT, "trial_3d_kinematic_summary.csv")
ka.save_csv(subject_3d_kinematic_summary, OUTPUT_ROOT, "subject_3d_kinematic_summary.csv")
ka.save_csv(subject_3d_metric_distribution, OUTPUT_ROOT, "subject_3d_metric_distribution.csv")
ka.save_csv(stiffness_direction_3d_metric_distribution, OUTPUT_ROOT, "stiffness_direction_3d_metric_distribution.csv")
ka.save_csv(mixedlm_model_input, OUTPUT_ROOT, "mixedlm_model_input.csv")

mixedlm = ka.fit_optional_mixed_effects_models(mixedlm_model_input)
ka.save_csv(mixedlm["mixedlm_status"], OUTPUT_ROOT, "mixedlm_status.csv")
ka.save_csv(mixedlm["mixedlm_coefficients"], OUTPUT_ROOT, "mixedlm_coefficients.csv")
proxy_3d_figure_paths = ka.save_3d_proxy_figures(OUTPUT_ROOT, kinematic_3d_proxy_samples, trial_3d_kinematic_summary, fig_dpi=FIG_DPI)

print("3D proxy trial summary:", trial_3d_kinematic_summary.shape)
display(trial_3d_kinematic_summary.head(30))
print("3D subject summaries:")
display(subject_3d_kinematic_summary.head(30))
print("3D metric distributions: mean, median, 95% CI, log-transform recommendation, and back-transformed geometric mean/CI")
display(subject_3d_metric_distribution.head(80))
print("MixedLM status / coefficients")
display(mixedlm["mixedlm_status"])
display(mixedlm["mixedlm_coefficients"].head(80))
print(f"Saved {len(proxy_3d_figure_paths)} 3D proxy figures")

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:1634: UserWarning: Random effects covariance is singular
  warnings.warn(msg)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2054: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2245: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:1634: UserWarning: Random effects covariance is singular
  warnings.warn(msg)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2054: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2245: UserWarning: The random effects covariance matrix is singular.
  warnings.warn(_warn_cov_sing)

3D proxy trial summary: (20478, 38)

,subject_id,subject_group,trial_index_raw,pair_number,finger_condition,stiffness_value,stiffness_segment_id,correct_response,dominant_movement_direction,n_3d_samples,path_length_3d_proxy_px,path_length_3d_proxy_cm,max_excursion_3d_from_start_px,max_excursion_3d_from_start_cm,max_radius_3d_from_center_px,max_radius_3d_from_center_cm,peak_velocity_3d_proxy_px_s,peak_velocity_3d_proxy_cm_s,mean_velocity_3d_proxy_px_s,mean_velocity_3d_proxy_cm_s,peak_acceleration_3d_proxy_px_s2,peak_acceleration_3d_proxy_cm_s2,mean_acceleration_3d_proxy_px_s2,mean_acceleration_3d_proxy_cm_s2,mean_z_lift_px,mean_z_lift_cm,max_z_lift_px,max_z_lift_cm,mean_side_lateral_camera_corrected_px,mean_side_lateral_camera_corrected_cm,path_length_side_view_camera_corrected_px,path_length_side_view_camera_corrected_cm,mean_side_lift_lateral_angle_camera_corrected_deg,mean_hand_orientation_xy_deg,mean_hand_orientation_yz_deg,mean_hand_orientation_zx_deg,straightness_3d_proxy,straightness_3d_proxy_cm
0,L_E_1,L,13,13,M,115.0,1,1.0,W,395,526.908247,65.863531,160.872087,20.109011,162.883645,20.360456,274.172969,34.271621,85.326562,10.665820,3993.987751,499.248469,558.220837,69.777605,11.529791,1.441224,29.233342,3.654168,NaN,NaN,0.0,0.0,NaN,-58.124665,171.291069,75.198887,0.305313,0.305313
1,L_E_1,L,13,13,M,85.0,2,1.0,ESE,311,590.221979,73.777747,153.576432,19.197054,155.699888,19.462486,278.861226,34.857653,120.865814,15.108227,4441.325059,555.165632,914.982277,114.372785,18.861240,2.357655,29.973501,3.746688,NaN,NaN,0.0,0.0,NaN,-56.502679,165.954122,68.508949,0.260201,0.260201
2,L_E_1,L,14,14,M,55.0,1,1.0,SSW,395,705.721291,88.215161,223.353598,27.919200,225.205565,28.150696,310.862869,38.857859,115.337282,14.417160,5123.882625,640.485328,735.087889,91.885986,16.440788,2.055099,30.198101,3.774763,NaN,NaN,0.0,0.0,NaN,-63.057167,168.526889,65.722761,0.316490,0.316490
3,L_E_1,L,14,14,M,85.0,2,1.0,S,250,605.198276,75.649785,165.652836,20.706605,168.095300,21.011913,427.251459,53.406432,155.622023,19.452753,4923.110570,615.388821,1032.535875,129.066984,12.689004,1.586126,26.989447,3.373681,NaN,NaN,0.0,0.0,NaN,-58.716775,170.662117,72.958058,0.273717,0.273717
4,L_E_1,L,15,15,M,40.0,1,1.0,S,287,567.374557,70.921820,168.741021,21.092628,166.347454,20.793432,309.818514,38.727314,126.195894,15.774487,6022.254961,752.781870,904.230381,113.028798,20.052793,2.506599,37.962569,4.745321,NaN,NaN,0.0,0.0,NaN,-54.997717,165.732080,66.941464,0.297407,0.297407
5,L_E_1,L,15,15,M,85.0,2,1.0,ESE,190,514.261438,64.282680,157.267107,19.658388,161.270554,20.158819,405.830351,50.728794,175.060946,21.882618,5172.632670,646.579084,1234.775489,154.346936,25.421553,3.177694,37.718462,4.714808,NaN,NaN,0.0,0.0,NaN,-59.706511,161.563747,59.587359,0.305812,0.305812
6,L_E_1,L,16,16,M,145.0,1,1.0,ESE,290,524.700751,65.587594,152.457515,19.057189,150.193134,18.774142,361.944289,45.243036,116.178122,14.522265,3830.581917,478.822740,782.801735,97.850217,10.305192,1.288149,22.395633,2.799454,NaN,NaN,0.0,0.0,NaN,-56.368057,172.297393,76.259870,0.290561,0.290561
7,L_E_1,L,16,16,M,85.0,2,1.0,SE,228,577.444868,72.180609,184.922329,23.115291,181.149236,22.643655,358.842445,44.855306,163.230306,20.403788,4867.744153,608.468019,1061.508630,132.688579,14.904415,1.863052,27.700078,3.462510,NaN,NaN,0.0,0.0,NaN,-60.188052,169.208768,69.995515,0.320242,0.320242
8,L_E_1,L,17,17,M,85.0,1,1.0,S,325,715.837814,89.479727,201.981620,25.247702,205.027507,25.628438,409.944222,51.243028,140.147680,17.518460,5915.496639,739.437080,980.290673,122.536334,20.166107,2.520763,35.345803,4.418225,NaN,NaN,0.0,0.0,NaN,-62.980198,165.879654,61.861207,0.282161,0.282161
9,L_E_1,L,17,17,M,130.0,2,1.0,S,270,739.158380,92.394798,220.334758,27.541845,223.990083,27.998760,515.019302,64.377413,174.877911,21.859739,8779.723138,1097.465392,1277.495957,159.686995,18.983478,2.372935,35.311958,4.413995,NaN,NaN,0.0,0.0,NaN,-63.196114,166.405301,62.028746,0.298089,0.298089
10,L_E_1,L,18,18,M,85.0,1,0.0,SW,327,745.175299,93.146912,213.356259,26.669532,210.705272,26.338159,485.082690,60.635336,147.166514,18.395814,5650.266350,706.283294,989.107386,123.638423,23.571855,2.946482,44.070415,5.508802,NaN,NaN,0.0,0.0,NaN,-58.898986,162.535620,59.846955,0.286317,0.286317
11,L_E_1,L,18,18,M,70.0,2,0.0,S,307,870.072991,108.759124,254.744002,31.843000,252.440783,31.555098,467.940568,58.492571,182.179245,22.772406,18483.230327,2310.403791,1312.945310,164.118164,19.485659,2.435707,40.188244,5.023530,NaN,NaN,0.0,0.0,NaN,-62.304079,164.733645,63.539127,0.292785,0.292785
12,L_E_1,L,19,19,M,85.0,1,0.0,SE,266,708.113975,88.514247,222.157426,27.769678,216.328223,27.041028,395.384303,49.423038,167.798081,20.974760,5880.805118,735.100640,1077.569266,134.696158,17.577404,2.197175,38.793334,4.849167,NaN,NaN,0.0,0.0,NaN,-58.883287,167.149511,66.476340,0.313731,0.313731
13,L_E_1,L,19,19,M,100.0,2,0.0,NNE,256,737.819208,92.227401,224.467113,28.058389,230.070847,28.758856,539.250265,67.406283,184.313209,23.039151,8175.390862,1021.923858,1419.071287,177.383911,26.379213,3.297402,42.990527,5.373816,NaN,NaN,0.0,0.0,NaN,-61.763780,160.651217,55.670575,0.304231,0.304231
14,L_E_1,L,20,20,M,85.0,1,1.0,SE,257,700.491605,87.561451,196.404468,24.550558,199.309975,24.913747,550.994752,68.874344,174.032351,21.754044,7970.710190,996.338774,1183.089957,147.886245,17.888482,2.236060,34.404885,4.300611,NaN,NaN,0.0,0.0,NaN,-62.272808,167.055763,63.535810,0.280381,0.280381
15,L_E_1,L,20,20,M,25.0,2,1.0,SE,213,638.306603,79.788325,177.441899,22.180237,179.530298,22.441287,531.256579,66.407072,191.668101,23.958513,5497.667650,687.208456,1284.560966,160.570121,18.294036,2.286755,34.325928,4.290741,NaN,NaN,0.0,0.0,NaN,-60.289895,166.146995,64.379347,0.277989,0.277989
16,L_E_1,L,21,21,M,70.0,1,1.0,NNE,309,644.952664,80.619083,189.190209,23.648776,192.011343,24.001418,443.270393,55.408799,133.576299,16.697037,8690.612559,1086.326570,1013.542715,126.692839,18.577353,2.322169,33.441372,4.180171,NaN,NaN,0.0,0.0,NaN,-63.661243,166.136087,61.800855,0.293340,0.293340
17,L_E_1,L,21,21,M,85.0,2,1.0,NNE,256,814.043864,101.755483,248.074576,31.009322,252.739717,31.592465,484.934293,60.616787,205.234017,25.654252,7210.166364,901.270795,1336.534673,167.066834,19.223741,2.402968,35.640260,4.455033,NaN,NaN,0.0,0.0,NaN,-62.985783,165.777889,60.638081,0.304743,0.304743
18,L_E_1,L,22,22,M,55.0,1,1.0,NNE,271,798.851314,99.856414,226.219636,28.277455,222.627671,27.828459,483.242531,60.405316,189.607518,23.700940,5954.482443,744.310305,1237.763567,154.720446,18.236429,2.279554,39.579578,4.947447,NaN,NaN,0.0,0.0,NaN,-61.405052,166.475630,62.959453,0.283181,0.283181
19,L_E_1,L,22,22,M,85.0,2,1.0,SE,233,775.830228,96.978779,249.237102,31.154638,251.112521,31.389065,626.035274,78.254409,213.459222,26.682403,6309.466584,788.683323,1440.682354,180.085294,23.036316,2.879540,41.001586,5.125198,NaN,NaN,0.0,0.0,NaN,-65.570188,162.959984,54.553576,0.321252,0.321252
20,L_E_1,L,23,23,M,115.0,1,1.0,SE,283,638.172465,79.771558,191.186387,23.898298,188.850632,23.606329,444.927284,55.615911,146.041115,18.255139,5951.013054,743.876632,1027.816299,128.477037,12.697718,1.587215,31.410831,3.926354,NaN,NaN,0.0,0.0,NaN,-61.941305,170.502408,69.594669,0.299584,0.299584
21,L_E_1,L,23,23,M,85.0,2,1.0,SE,212,633.247800,79.155975,202.255918,25.281990,206.475657,25.809457,429.442570,53.680321,191.509828,23.938728,6165.074366,770.634296,1316.001622,164.500203,17.764195,2.220524,31.959677,3.994960,NaN,NaN,0.0,0.0,NaN,-64.463987,166.644169,61.606136,0.319395,0.319395
22,L_E_1,L,24,24,M,40.0,1,1.0,SE,257,671.758646,83.969831,207.284229,25.910529,209.975811,26.246976,453.100685,56.637586,167.750669,20.968834,24170.375511,3021.296939,1287.356249,160.919531,17.370988,2.171373,33.669051,4.208631,NaN,NaN,0.0,0.0,NaN,-67.580491,167.041083,59.216589,0.308569,0.308569
23,L_E_1,L,24,24,M,85.0,2,1.0,SE,209,768.492247,96.061531,250.613670,31.326709,251.218525,31.402316,622.454705,77.806838,234.620010,29.327501,9852.615537,1231.576942,1898.674709,237.334339,19.621422,2.452678,37.397810,4.674726,NaN,NaN,0.0,0.0,NaN,-66.107696,165.269229,57.258170,0.326111,0.326111
24,L_E_1,L,25,25,M,85.0,1,1.0,S,333,526.014366,65.751796,162.009536,20.251192,157.629210,19.703651,354.206274,44.275784,102.365445,12.795681,5821.759845,727.719981,690.296183,86.287023,13.954684,1.744336,34.253131,4.281641,NaN,NaN,0.0,0.0,NaN,-62.376935,169.042097,66.320189,0.307995,0.307995
25,L_E_1,L,25,25,M,130.0,2,1.0,SE,497,1420.561229,177.570154,255.027426,31.878428,259.684930,32.460616,496.871056,62.108882,178.210496,22.276312,6441.992836,805.249105,1208.957755,151.119719,26.889214,3.361152,46.516890,5.814611,NaN,NaN,0.0,0.0,NaN,-68.222736,160.458924,47.870629,0.179526,0.179526
26,L_E_1,L,26,26,M,85.0,1,1.0,SE,266,670.359090,83.794886,216.777724,27.097215,215.369272,26.921159,366.113559,45.764195,159.488006,19.936001,4844.397237,605.549655,1098.889359,137.361170,20.760638,2.595080,42.050078,5.256260,NaN,NaN,0.0,0.0,NaN,-65.011439,164.649136,57.144062,0.323376,0.323376
27,L_E_1,L,26,26,M,25.0,2,1.0,SE,210,621.598204,77.699776,215.640920,26.955115,217.549491,27.193686,440.695178,55.086897,188.139193,23.517399,9122.576927,1140.322116,1374.857311,171.857164,24.370064,3.046258,41.492383,5.186548,NaN,NaN,0.0,0.0,NaN,-68.200379,161.382341,49.664073,0.346914,0.346914
28,L_E_1,L,27,27,M,85.0,1,1.0,NNE,285,666.493531,83.311691,216.505393,27.063174,219.626120,27.453265,376.876822,47.109603,151.784930,18.973116,5163.043594,645.380449,994.450238,124.306280,22.272525,2.784066,36.948483,4.618560,NaN,NaN,0.0,0.0,NaN,-67.584046,163.292784,52.424529,0.324842,0.324842
29,L_E_1,L,27,27,M,145.0,2,1.0,S,229,639.750662,79.968833,196.494580,24.561822,200.378969,25.047371,483.461327,60.432666,175.495762,21.936970,5305.228990,663.153624,1259.525823,157.440728,15.849624,1.981203,34.981303,4.372663,NaN,NaN,0.0,0.0,NaN,-64.361801,167.551267,63.537753,0.307142,0.307142

3D subject summaries:

,subject_id,subject_group,finger_condition,stiffness_value,n_trials,success_rate,path_length_3d_proxy_px,path_length_3d_proxy_cm,max_excursion_3d_from_start_px,max_excursion_3d_from_start_cm,max_radius_3d_from_center_px,max_radius_3d_from_center_cm,peak_velocity_3d_proxy_px_s,peak_velocity_3d_proxy_cm_s,mean_velocity_3d_proxy_px_s,mean_velocity_3d_proxy_cm_s,peak_acceleration_3d_proxy_px_s2,peak_acceleration_3d_proxy_cm_s2,mean_z_lift_px,mean_z_lift_cm,max_z_lift_px,max_z_lift_cm,mean_side_lateral_camera_corrected_px,mean_side_lateral_camera_corrected_cm,path_length_side_view_camera_corrected_px,path_length_side_view_camera_corrected_cm,mean_side_lift_lateral_angle_camera_corrected_deg,mean_hand_orientation_xy_deg,mean_hand_orientation_yz_deg,mean_hand_orientation_zx_deg,straightness_3d_proxy,straightness_3d_proxy_cm
0,L_E_1,L,I,25.0,8,1.000000,637.496514,79.687064,189.534404,23.691800,188.532564,23.566570,572.678519,71.584815,193.952758,24.244095,8503.141275,1062.892659,13.418194,1.677274,30.530685,3.816336,NaN,NaN,0.0,0.0,NaN,-62.584462,165.827826,62.678055,0.301844,0.301844
1,L_E_1,L,I,40.0,8,1.000000,828.865064,103.608133,197.002615,24.625327,196.027459,24.503432,570.460480,71.307560,204.755278,25.594410,9561.193318,1195.149165,11.088442,1.386055,28.507103,3.563388,NaN,NaN,0.0,0.0,NaN,-61.735252,166.913269,63.643450,0.258412,0.258412
2,L_E_1,L,I,55.0,8,1.000000,781.287939,97.660992,205.312566,25.664071,205.562902,25.695363,541.143007,67.642876,212.587512,26.573439,7990.942778,998.867847,24.107417,3.013427,36.942443,4.617805,NaN,NaN,0.0,0.0,NaN,-62.851125,159.986702,53.337413,0.283532,0.283532
3,L_E_1,L,I,70.0,8,0.750000,821.453786,102.681723,180.488688,22.561086,180.471875,22.558984,586.907571,73.363446,201.777610,25.222201,8596.894837,1074.611855,10.147115,1.268389,29.041781,3.630223,NaN,NaN,0.0,0.0,NaN,-61.870606,166.152436,62.495529,0.233977,0.233977
4,L_E_1,L,I,85.0,64,0.890625,1023.519582,127.939948,200.098942,25.012368,199.829732,24.978717,605.527653,75.690957,217.451965,27.181496,9869.603718,1233.700465,14.085759,1.760720,33.891491,4.236436,NaN,NaN,0.0,0.0,NaN,-63.647730,162.328363,56.050091,0.211247,0.211247
5,L_E_1,L,I,100.0,8,0.750000,1107.226084,138.403260,191.204596,23.900574,190.967770,23.870971,617.879961,77.234995,213.093894,26.636737,8841.174414,1105.146802,17.825269,2.228159,32.486711,4.060839,NaN,NaN,0.0,0.0,NaN,-63.326168,163.804670,57.423426,0.180174,0.180174
6,L_E_1,L,I,115.0,8,0.750000,1266.261497,158.282687,200.886404,25.110800,199.315029,24.914379,561.063510,70.132939,221.032391,27.629049,9438.763805,1179.845476,14.735436,1.841930,31.654581,3.956823,NaN,NaN,0.0,0.0,NaN,-63.713370,164.143070,58.336113,0.176379,0.176379
7,L_E_1,L,I,130.0,8,0.875000,1069.887428,133.735928,221.976367,27.747046,220.858103,27.607263,640.593886,80.074236,223.240646,27.905081,10680.621509,1335.077689,23.849033,2.981129,49.130982,6.141373,NaN,NaN,0.0,0.0,NaN,-61.523286,153.151037,48.308062,0.218486,0.218486
8,L_E_1,L,I,145.0,8,1.000000,947.678483,118.459810,198.974121,24.871765,197.926242,24.740780,607.571894,75.946487,211.748253,26.468532,10483.005943,1310.375743,15.507771,1.938471,30.488371,3.811046,NaN,NaN,0.0,0.0,NaN,-63.534267,165.258936,60.527841,0.217032,0.217032
9,L_E_1,L,M,25.0,8,1.000000,795.891320,99.486415,210.605542,26.325693,210.271935,26.283992,526.229704,65.778713,189.903647,23.737956,7274.386877,909.298360,22.922026,2.865253,46.766400,5.845800,NaN,NaN,0.0,0.0,NaN,-57.282724,160.144254,58.976914,0.283282,0.283282
10,L_E_1,L,M,40.0,8,1.000000,622.542953,77.817869,187.608633,23.451079,188.418546,23.552318,477.793419,59.724177,155.442788,19.430348,8705.400170,1088.175021,17.535557,2.191945,38.043036,4.755379,NaN,NaN,0.0,0.0,NaN,-56.731852,165.294270,66.379297,0.303270,0.303270
11,L_E_1,L,M,55.0,8,0.875000,944.782463,118.097808,217.799043,27.224880,217.515539,27.189442,488.049154,61.006144,175.681481,21.960185,6410.641314,801.330164,17.338609,2.167326,41.614392,5.201799,NaN,NaN,0.0,0.0,NaN,-57.131174,164.246905,63.771997,0.257953,0.257953
12,L_E_1,L,M,70.0,8,0.500000,907.591777,113.448972,206.657809,25.832226,208.107747,26.013468,476.702609,59.587826,168.827576,21.103447,8579.850914,1072.481364,19.031506,2.378938,41.324321,5.165540,NaN,NaN,0.0,0.0,NaN,-56.729961,164.388298,65.298523,0.243996,0.243996
13,L_E_1,L,M,85.0,64,0.859375,883.857284,110.482160,201.143270,25.142909,202.258324,25.282290,495.943859,61.992982,174.902609,21.862826,7382.871563,922.858945,19.893764,2.486721,41.118107,5.139763,NaN,NaN,0.0,0.0,NaN,-56.780225,163.064771,63.552203,0.257471,0.257471
14,L_E_1,L,M,100.0,8,0.750000,1030.355629,128.794454,223.682632,27.960329,223.497226,27.937153,533.911862,66.738983,189.389172,23.673647,8479.305175,1059.913147,22.531209,2.816401,49.554368,6.194296,NaN,NaN,0.0,0.0,NaN,-56.100255,160.842166,60.719664,0.234046,0.234046
15,L_E_1,L,M,115.0,8,0.750000,857.414079,107.176760,203.878538,25.484817,203.626148,25.453269,435.381791,54.422724,168.928607,21.116076,6267.921138,783.490142,15.412374,1.926547,36.995490,4.624436,NaN,NaN,0.0,0.0,NaN,-54.191047,164.504511,67.239220,0.280932,0.280932
16,L_E_1,L,M,130.0,8,1.000000,1053.014396,131.626799,215.755792,26.969474,217.391024,27.173878,503.978427,62.997303,185.618426,23.202303,7579.862868,947.482859,21.306321,2.663290,44.317778,5.539722,NaN,NaN,0.0,0.0,NaN,-58.304537,162.146350,60.436213,0.235273,0.235273
17,L_E_1,L,M,145.0,8,1.000000,892.414166,111.551771,191.493991,23.936749,194.230002,24.278750,525.211432,65.651429,185.873082,23.234135,6986.745862,873.343233,16.198018,2.024752,36.169687,4.521211,NaN,NaN,0.0,0.0,NaN,-57.265851,166.857291,67.581308,0.229043,0.229043
18,L_E_1,L,P,25.0,8,1.000000,520.782740,65.097842,169.730582,21.216323,169.727767,21.215971,330.663040,41.332880,121.187447,15.148431,9066.876543,1133.359568,24.304331,3.038041,31.548069,3.943509,NaN,NaN,0.0,0.0,NaN,-21.956192,146.527824,76.895604,0.367201,0.367201
19,L_E_1,L,P,40.0,8,0.875000,614.198045,76.774756,179.625545,22.453193,179.131329,22.391416,333.617964,41.702245,116.850131,14.606266,6420.946225,802.618278,17.367063,2.170883,27.447929,3.430991,NaN,NaN,0.0,0.0,NaN,-18.329367,147.727167,80.786834,0.354505,0.354505
20,L_E_1,L,P,55.0,8,1.000000,694.235825,86.779478,176.015968,22.001996,175.708464,21.963558,418.556210,52.319526,113.223696,14.152962,8627.301285,1078.412661,20.438598,2.554825,28.364296,3.545537,NaN,NaN,0.0,0.0,NaN,-23.175253,154.965326,78.627565,0.320623,0.320623
21,L_E_1,L,P,70.0,8,0.375000,591.333089,73.916636,196.118641,24.514830,194.480791,24.310099,374.236108,46.779513,124.369934,15.546242,8097.765564,1012.220695,22.744801,2.843100,31.437357,3.929670,NaN,NaN,0.0,0.0,NaN,-24.296954,150.754090,77.837781,0.359531,0.359531
22,L_E_1,L,P,85.0,64,0.781250,601.096903,75.137113,185.956074,23.244509,185.715283,23.214410,386.247862,48.280983,123.530038,15.441255,7660.581168,957.572646,20.175652,2.521956,30.531269,3.816409,NaN,NaN,0.0,0.0,NaN,-21.753351,149.423855,78.338983,0.348899,0.348899
23,L_E_1,L,P,100.0,8,0.750000,622.516440,77.814555,194.670095,24.333762,193.951016,24.243877,377.811265,47.226408,123.629433,15.453679,8393.503884,1049.187986,21.326434,2.665804,36.795614,4.599452,NaN,NaN,0.0,0.0,NaN,-19.825122,137.094954,76.343329,0.354498,0.354498
24,L_E_1,L,P,115.0,8,0.625000,513.061237,64.132655,180.365631,22.545704,181.442997,22.680375,313.746685,39.218336,107.182774,13.397847,6571.477122,821.434640,16.620547,2.077568,30.569581,3.821198,NaN,NaN,0.0,0.0,NaN,-22.110219,153.605152,78.686784,0.379387,0.379387
25,L_E_1,L,P,130.0,8,0.750000,410.687533,51.335942,167.042401,20.880300,166.521535,20.815192,259.857580,32.482198,93.249861,11.656233,3943.260011,492.907501,12.282473,1.535309,19.800056,2.475007,NaN,NaN,0.0,0.0,NaN,-17.906393,157.718780,82.331550,0.424749,0.424749
26,L_E_1,L,P,145.0,8,0.875000,622.562533,77.820317,184.840571,23.105071,183.661368,22.957671,341.766510,42.720814,118.806312,14.850789,7386.800128,923.350016,18.469967,2.308746,28.637676,3.579710,NaN,NaN,0.0,0.0,NaN,-23.500228,154.409491,78.757678,0.334720,0.334720
27,L_E_1,L,R,25.0,8,1.000000,459.758938,57.469867,214.869575,26.858697,208.650389,26.081299,405.398554,50.674819,103.190754,12.898844,10176.327414,1272.040927,35.977961,4.497245,55.405981,6.925748,NaN,NaN,0.0,0.0,NaN,-30.211665,146.456927,66.053763,0.468122,0.468122
28,L_E_1,L,R,40.0,8,0.875000,466.884142,58.360518,213.802646,26.725331,209.595336,26.199417,499.338903,62.417363,95.696592,11.962074,15757.649365,1969.706171,34.388618,4.298577,56.671809,7.083976,NaN,NaN,0.0,0.0,NaN,-29.954589,143.653395,64.532541,0.461368,0.461368
29,L_E_1,L,R,55.0,8,0.750000,478.464275,59.808034,224.886314,28.110789,219.038780,27.379848,428.518898,53.564862,97.281633,12.160204,11990.375986,1498.796998,40.528538,5.066067,61.339001,7.667375,NaN,NaN,0.0,0.0,NaN,-30.579755,142.762453,63.042980,0.471712,0.471712

3D metric distributions: mean, median, 95% CI, log-transform recommendation, and back-transformed geometric mean/CI

,subject_id,finger_condition,metric,n,mean,mean_ci95_low,mean_ci95_high,median,median_ci95_low,median_ci95_high,sd,sem,skewness,log_transform_valid,log_transform_recommended,geometric_mean_backtransformed,geometric_ci95_low_backtransformed,geometric_ci95_high_backtransformed
0,L_E_1,I,path_length_3d_proxy_cm,9,117.828839,101.978453,133.679225,118.459810,97.660992,138.403260,24.260795,8.086932,0.077258,True,False,115.563938,100.682424,132.645036
1,L_E_1,I,max_excursion_3d_from_start_cm,9,24.798315,23.855531,25.741099,24.871765,23.691800,25.664071,1.443037,0.481012,0.482455,True,False,24.761628,23.848630,25.709577
2,L_E_1,I,max_radius_3d_from_center_cm,9,24.715162,23.786581,25.643743,24.740780,23.566570,25.695363,1.421298,0.473766,0.503382,True,False,24.679484,23.780647,25.612293
3,L_E_1,I,peak_velocity_3d_proxy_cm_s,9,73.664257,71.114478,76.214035,73.363446,70.132939,77.234995,3.902722,1.300907,0.083459,True,False,73.572487,71.070547,76.162504
4,L_E_1,I,peak_acceleration_3d_proxy_cm_s2,9,1166.185300,1091.096286,1241.274314,1179.845476,1062.892659,1310.375743,114.932165,38.310722,0.100162,True,False,1161.159939,1088.714068,1238.426547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,L_E_10,M,mean_z_lift_cm,9,1.421268,1.167056,1.675480,1.264873,1.181537,1.616005,0.389100,0.129700,1.508725,True,True,1.383730,1.188576,1.610926
76,L_E_10,M,max_z_lift_cm,9,2.236509,2.027224,2.445793,2.298877,1.914528,2.448796,0.320334,0.106778,0.342152,True,False,2.216602,2.021264,2.430818
77,L_E_10,M,mean_side_lateral_camera_corrected_cm,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN
78,L_E_10,M,path_length_side_view_camera_corrected_cm,9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,False,False,NaN,NaN,NaN
79,L_E_10,M,mean_side_lift_lateral_angle_camera_corrected_deg,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN

MixedLM status / coefficients

                           metric  status           reason  n_rows  n_subjects  n_directions            aic            bic
0  max_excursion_3d_from_start_px     fit                    20478          40            12  211546.902331  211753.007098
1    max_radius_3d_from_center_px     fit                    20478          40            12  212363.753016  212569.857782
2         path_length_3d_proxy_px  failed  Singular matrix   20478          40            12            NaN            NaN
3     peak_velocity_3d_proxy_px_s  failed  Singular matrix   20478          40            12            NaN            NaN

                            metric                                        term    estimate  std_error        p_value
0   max_excursion_3d_from_start_px                                   Intercept  196.044759   8.606015  7.243958e-115
1   max_excursion_3d_from_start_px                  C(direction_factor)[T.ENE]    1.340666   5.026146   7.896706e-01
2   max_excursion_3d_from_start_px                  C(direction_factor)[T.ESE]    6.888170   6.403221   2.820457e-01
3   max_excursion_3d_from_start_px                   C(direction_factor)[T.NE]    7.404939   4.776258   1.210542e-01
4   max_excursion_3d_from_start_px                  C(direction_factor)[T.NNE]   16.458686   4.267046   1.147114e-04
5   max_excursion_3d_from_start_px                    C(direction_factor)[T.S]   10.312071   4.790791   3.135974e-02
6   max_excursion_3d_from_start_px                   C(direction_factor)[T.SE]    9.006813   4.595515   5.000587e-02
7   max_excursion_3d_from_start_px                  C(direction_factor)[T.SSE]   15.298733   4.357534   4.466440e-04
8   max_excursion_3d_from_start_px                  C(direction_factor)[T.SSW]   -3.228614   5.118332   5.281751e-01
9   max_excursion_3d_from_start_px                   C(direction_factor)[T.SW]   -0.579516   5.580924   9.172974e-01
10  max_excursion_3d_from_start_px                    C(direction_factor)[T.W]   12.236451   4.795206   1.071652e-02
11  max_excursion_3d_from_start_px                  C(direction_factor)[T.WSW]    6.964886   6.650820   2.949972e-01
12  max_excursion_3d_from_start_px                             stiffness_value   -0.024385   0.039641   5.384531e-01
13  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.ENE]   -0.037299   0.055216   4.993508e-01
14  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.ESE]    0.010153   0.070364   8.852723e-01
15  max_excursion_3d_from_start_px   stiffness_value:C(direction_factor)[T.NE]   -0.004614   0.052107   9.294436e-01
16  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.NNE]   -0.024247   0.046408   6.013482e-01
17  max_excursion_3d_from_start_px    stiffness_value:C(direction_factor)[T.S]   -0.038921   0.052336   4.570746e-01
18  max_excursion_3d_from_start_px   stiffness_value:C(direction_factor)[T.SE]    0.029042   0.050355   5.641178e-01
19  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.SSE]   -0.013729   0.047424   7.721993e-01
20  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.SSW]   -0.018739   0.056338   7.394275e-01
21  max_excursion_3d_from_start_px   stiffness_value:C(direction_factor)[T.SW]    0.008857   0.062220   8.868029e-01
22  max_excursion_3d_from_start_px    stiffness_value:C(direction_factor)[T.W]    0.004765   0.052200   9.272748e-01
23  max_excursion_3d_from_start_px  stiffness_value:C(direction_factor)[T.WSW]    0.076790   0.073715   2.975480e-01
24  max_excursion_3d_from_start_px                                   Group Var    1.374741   0.306881   7.474301e-06
25    max_radius_3d_from_center_px                                   Intercept  199.831027   8.914985  2.798820e-111
26    max_radius_3d_from_center_px                  C(direction_factor)[T.ENE]   -0.109821   5.127211   9.829112e-01
27    max_radius_3d_from_center_px                  C(direction_factor)[T.ESE]    8.130965   6.531977   2.132075e-01
28    max_radius_3d_from_center_px                   C(direction_factor)[T.NE]    5.143526   4.872302   2.911205e-01
29    max_radius_3d_from_center_px                  C(direction_factor)[T.NNE]   13.047211   4.352848   2.722962e-03
30    max_radius_3d_from_center_px                    C(direction_factor)[T.S]    7.555002   4.887126   1.221290e-01
31    max_radius_3d_from_center_px                   C(direction_factor)[T.SE]    3.996484   4.687922   3.939331e-01
32    max_radius_3d_from_center_px                  C(direction_factor)[T.SSE]   10.237356   4.445156   2.127679e-02
33    max_radius_3d_from_center_px                  C(direction_factor)[T.SSW]   -5.748067   5.221251   2.709409e-01
34    max_radius_3d_from_center_px                   C(direction_factor)[T.SW]   -1.849423   5.693144   7.452939e-01
35    max_radius_3d_from_center_px                    C(direction_factor)[T.W]    7.338868   4.891629   1.335390e-01
36    max_radius_3d_from_center_px                  C(direction_factor)[T.WSW]    5.551376   6.784555   4.132217e-01
37    max_radius_3d_from_center_px                             stiffness_value   -0.029000   0.040438   4.732823e-01
38    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.ENE]   -0.020872   0.056326   7.109741e-01
39    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.ESE]   -0.022869   0.071779   7.500315e-01
40    max_radius_3d_from_center_px   stiffness_value:C(direction_factor)[T.NE]   -0.008092   0.053155   8.790003e-01
41    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.NNE]   -0.006917   0.047341   8.838378e-01
42    max_radius_3d_from_center_px    stiffness_value:C(direction_factor)[T.S]   -0.017500   0.053388   7.430683e-01
43    max_radius_3d_from_center_px   stiffness_value:C(direction_factor)[T.SE]    0.057703   0.051368   2.612986e-01
44    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.SSE]    0.014994   0.048377   7.566140e-01
45    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.SSW]    0.005783   0.057471   9.198522e-01
46    max_radius_3d_from_center_px   stiffness_value:C(direction_factor)[T.SW]    0.015465   0.063471   8.075004e-01
47    max_radius_3d_from_center_px    stiffness_value:C(direction_factor)[T.W]    0.040966   0.053250   4.417085e-01
48    max_radius_3d_from_center_px  stiffness_value:C(direction_factor)[T.WSW]    0.081224   0.075198   2.800776e-01
49    max_radius_3d_from_center_px                                   Group Var    1.427050   0.318463   7.427778e-06

Saved 41 3D proxy figures

## 10. Hand / active-finger orientation planes

Summarizes the thumb-to-active-finger orientation in XY from the top camera and YZ/ZX from the side-camera Z/lift proxy. The figures include three side-by-side vector panels (XY, YZ, ZX): faded vectors are individual trials and thick colored vectors are group means, matching common motor-control vector-field / mean-vector visualization practice. Raw pixel/proxy columns are preserved for traceability, while workspace labels document the setup calibration (`L` Lab/airslide = 80x60 cm; `N` Natural = 60x45 cm; top camera 100 cm above the table; side camera 10 cm above the table).

In [16]:
hand_orientation = ka.compute_hand_orientation_plane_analysis(trial_kinematic_summary, side_z_trial_summary)
hand_orientation_plane_trials = hand_orientation["hand_orientation_plane_trials"]
hand_orientation_plane_summary = hand_orientation["hand_orientation_plane_summary"]

ka.save_parquet(hand_orientation_plane_trials, OUTPUT_ROOT, "hand_orientation_plane_trials.parquet")
ka.save_csv(hand_orientation_plane_summary, OUTPUT_ROOT, "hand_orientation_plane_summary.csv")
hand_orientation_figure_paths = ka.save_hand_orientation_plane_figures(
    OUTPUT_ROOT, hand_orientation_plane_summary, hand_orientation_plane_trials, fig_dpi=FIG_DPI
)
hand_orientation_axis_matrix_paths = ka.save_hand_orientation_axis_matrix_figures(
    OUTPUT_ROOT, hand_orientation_plane_trials, fig_dpi=FIG_DPI
)

print("Hand orientation plane trials:", hand_orientation_plane_trials.shape)
display(hand_orientation_plane_summary.head(30))
print(f"Saved {len(hand_orientation_figure_paths)} hand-orientation figures")
print(f"Saved {len(hand_orientation_axis_matrix_paths)} hand-orientation axis matrix figures")

Hand orientation plane trials: (20480, 126)

               scope    group plane                   metric      n  circular_mean_deg  median_deg  resultant_length
0                all      all    XY  hand_orientation_xy_deg  20480         -51.784810  -54.378976          0.951733
1                all      all    YZ  hand_orientation_yz_deg  20478         148.107225  150.743180          0.932247
2                all      all    ZX  hand_orientation_zx_deg  20478          52.466145   54.935782          0.921356
3   experiment_group      L_E    XY  hand_orientation_xy_deg  10240         -49.181909  -52.529848          0.939927
4   experiment_group      L_E    YZ  hand_orientation_yz_deg  10240         145.391921  148.612939          0.908223
5   experiment_group      L_E    ZX  hand_orientation_zx_deg  10240          52.653272   55.062817          0.911331
6   experiment_group      N_E    XY  hand_orientation_xy_deg  10240         -54.318847  -55.741010          0.965452
7   experiment_group      N_E    YZ  hand_orientation_yz_deg  10238         150.681141  152.287438          0.958263
8   experiment_group      N_E    ZX  hand_orientation_zx_deg  10238          52.283013   54.799379          0.931392
9      subject_group        L    XY  hand_orientation_xy_deg  10240         -49.181909  -52.529848          0.939927
10     subject_group        L    YZ  hand_orientation_yz_deg  10240         145.391921  148.612939          0.908223
11     subject_group        L    ZX  hand_orientation_zx_deg  10240          52.653272   55.062817          0.911331
12     subject_group        N    XY  hand_orientation_xy_deg  10240         -54.318847  -55.741010          0.965452
13     subject_group        N    YZ  hand_orientation_yz_deg  10238         150.681141  152.287438          0.958263
14     subject_group        N    ZX  hand_orientation_zx_deg  10238          52.283013   54.799379          0.931392
15         workspace        L    XY  hand_orientation_xy_deg  10240         -49.181909  -52.529848          0.939927
16         workspace        L    YZ  hand_orientation_yz_deg  10240         145.391921  148.612939          0.908223
17         workspace        L    ZX  hand_orientation_zx_deg  10240          52.653272   55.062817          0.911331
18         workspace        N    XY  hand_orientation_xy_deg  10240         -54.318847  -55.741010          0.965452
19         workspace        N    YZ  hand_orientation_yz_deg  10238         150.681141  152.287438          0.958263
20         workspace        N    ZX  hand_orientation_zx_deg  10238          52.283013   54.799379          0.931392
21           success  failure    XY  hand_orientation_xy_deg   4116         -51.325573  -54.473244          0.946159
22           success  failure    YZ  hand_orientation_yz_deg   4116         145.423259  147.785402          0.923526
23           success  failure    ZX  hand_orientation_zx_deg   4116          50.130712   51.654168          0.920167
24           success  success    XY  hand_orientation_xy_deg  16364         -51.899473  -54.353350          0.953144
25           success  success    YZ  hand_orientation_yz_deg  16362         148.774056  151.479762          0.934759
26           success  success    ZX  hand_orientation_zx_deg  16362          53.052390   55.657911          0.921895
27            finger        I    XY  hand_orientation_xy_deg   5120         -65.659338  -64.875103          0.981901
28            finger        I    YZ  hand_orientation_yz_deg   5120         145.396690  146.872211          0.936716
29            finger        I    ZX  hand_orientation_zx_deg   5120          36.767837   32.491172          0.915921

Saved 43 hand-orientation figures
Saved 43 hand-orientation axis matrix figures

## 11. Figures

All figures are saved under `analysis/Kinematics/result_fillter/figures`, including polar radiation patterns per participant and for all/E/P, side-by-side success/failure polar dwell-time plots with semi-transparent stiffness colors, and side-Z participant plots over time and over stiffness. Group summary graphs include faded raw values behind the summary bars when raw values are available.

In [17]:
group_output_side_z_samples = None if ka.is_single_subject_selection(DATA_SELECTION, _selected_subjects) else side_z_samples
movement_cycle_angle_figure_paths = ka.save_movement_cycle_hand_angle_figures(
    OUTPUT_ROOT,
    trajectory_time_bins,
    side_z_samples=group_output_side_z_samples,
    fig_dpi=FIG_DPI,
)
print(f"Saved {len(movement_cycle_angle_figure_paths)} movement-cycle hand-angle figures")

figure_paths = ka.save_kinematic_figures(
    OUTPUT_ROOT,
    trial_kinematic_summary,
    group_time_summary,
    direction_success_summary,
    distance_success_summary,
    side_z_group_time_summary,
    side_z_by_stiffness_summary,
    side_z_samples=side_z_samples,
    fig_dpi=FIG_DPI,
)
print(f"Saved {len(figure_paths)} figures")
display(pd.DataFrame({"figure": [str(p) for p in figure_paths]}).head(80))

Saved 43 movement-cycle hand-angle figures
Saved 15 figures

                                               figure
0   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
1   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
2   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
3   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
4   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
5   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
6   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
7   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
8   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
9   C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
10  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
11  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
12  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
13  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
14  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...

In [18]:
# -------------------------------------------------------------------
# 11b. Per-individual full reports (group runs)
# -------------------------------------------------------------------
#
# In a group run, each individual's results/<subject>/ folder receives only the
# per-subject *scoped* figures; every helper's AGGREGATE figures
# (velocity_vs_time_by_stiffness, average_velocity_vs_stiffness,
# all_velocity_vs_time_by_stiffness, *_acceleration_by_finger,
# time_magnitude / time_speed / time_radial_velocity /
# time_tangential_velocity, success_by_dominant_direction,
# success_vs_distance_from_center, the side_z_lift_* panels,
# the motor-control grids, and the success/Z + trajectory-distance
# contrasts) are produced once at the group level.
#
# This re-runs the ENTIRE per-selection figure pipeline for EVERY
# subject—restricted to that subject's rows—into results/<subject>/,
# so each individual folder matches a standalone single-subject run.
#
# It reuses the already-computed frames (no tracking recompute,
# no video re-decode) and is a no-op for a single-subject selection.
#
# Runs before organize_kinematic_results_tree() so the new files get
# sorted into figures/<category>/.

individual_report_paths = ka.save_individual_subject_reports(
    RESULTS_ROOT,
    trial_kinematic_summary=trial_kinematic_summary,
    trajectory_time_bins=trajectory_time_bins,
    kinematic_samples=kinematic_samples,
    side_z_trial_summary=side_z_trial_summary,
    side_z_samples=side_z_samples,
    side_z_group_time_summary=side_z_group_time_summary,
    n_time_bins=TRAJECTORY_TIME_BINS,
    fig_dpi=FIG_DPI,
)

print(
    f"Per-individual full reports: "
    f"{sum(len(v) for v in individual_report_paths.values())} figures across "
    f"{len(individual_report_paths)} subjects"
)

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice

Per-individual full reports: 4476 figures across 40 subjects

## 13. All-interactions kinematic folder

This cell writes only the `all` interaction-analysis branch for the normal kinematics results.

- `results/all` (`all`): all standard + comparison interaction segments.

The `standard` and `Comparison` split outputs are not created here; use dedicated analysis functions when those specific subsets are needed.

In [19]:
interaction_folder_index = ka.save_interaction_filtered_kinematic_outputs(
    OUTPUT_ROOT,
    trial_kinematic_summary=trial_kinematic_summary,
    trajectory_time_bins=trajectory_time_bins,
    pair_kinematic_summary=pair_kinematic_summary,
    side_z_trial_summary=side_z_trial_summary,
    side_z_samples=group_output_side_z_samples,
    fig_dpi=FIG_DPI,
    save_figures=True,
    save_sample_tables=False,  # keep large raw sample tables only in the legacy flat results folder
)
display(interaction_folder_index)

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(
C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:7780: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  out["tangential_radial_velocity_ratio_3d_proxy"] = np.where(

,interaction_scope,interaction_code,folder_name,description,path,n_trial_segments,n_time_bins,n_subjects,manifest_exists
0,all,all,all,All stiffness interactions already used by the...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,20480,1021379,40,True

## 12. Manifest and interpretation notes

- `kinematic_samples.csv`: sample-level XY time series with raw pixel columns plus setup-scaled centimeter position, velocity, acceleration, jerk, and direction columns.
- `trial_kinematic_summary.csv`: per-trial features for modeling success, with cm metrics as the default physical analysis columns and px columns retained for traceability.
- `direction_success_summary.csv`: direction bins vs success.
- `distance_success_summary.csv`: distance-from-center vs success using setup-scaled centimeters.
- `kinematic_within_subject.csv`: subject-preserving table with centered/z-scored kinematic metrics.
- `within_finger_stiffness_effects.csv`: per-subject stiffness slopes by finger.
- Side-camera Z/lift outputs include raw pixel/proxy columns and setup-scaled cm proxy columns; without a side-camera calibration target, Z cm should be interpreted as a physical proxy rather than a true calibrated 3D reconstruction.

In [20]:
manifest = ka.analysis_manifest(OUTPUT_ROOT)
display(manifest)
print("Figures:", OUTPUT_ROOT / "figures")

                                  output  exists                                               path
0                trial_file_manifest.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
1           experiment_setup_context.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
2              kinematic_samples.parquet    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
3             pair_kinematic_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
4            trial_kinematic_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
..                                   ...     ...                                                ...
83              side_z_trial_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
84         side_z_group_time_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
85  side_z_subject_stiffness_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
86       side_z_by_stiffness_summary.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
87                   figure_manifest.csv    True  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...

[88 rows x 3 columns]

Figures: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\result_fillter\L_N_E\figures

In [21]:
# --- 14. Per-subject csv tree (mirrors psychophysics save_selected_analysis_tree) ---
# Split every per-subject table (one carrying a subject_id column) by subject into
# results/<subject>/csv/. Tables without a subject_id are written to the selected
# subject/group owner folder and categorized by organize_kinematic_results_tree.
# Per-subject and aggregate figures were already written during the run by the
# figure helpers, so this only reorganizes the in-memory tables (no recompute).
per_subject_tables = {
    "trial_kinematic_summary.csv": trial_kinematic_summary,
    "pair_kinematic_summary.csv": pair_kinematic_summary,
    "trajectory_time_bins.csv": trajectory_time_bins,
    "direction_success_summary.csv": direction_success_summary,
    "distance_success_summary.csv": distance_success_summary,
    "subject_kinematic_summary.csv": subject_kinematic_summary,
    "participant_stiffness_kinematic_summary.csv": participant_stiffness_kinematic_summary,
    "kinematic_within_subject.csv": kinematic_within_subject,
    "within_finger_stiffness_effects.csv": within_finger_stiffness_effects,
    "finger_comparison_paired.csv": finger_comparison_paired,
    "trial_success_kinematic_z_table.csv": trial_success_kinematic_z_table,
    "success_kinematic_z_contrast_by_subject_finger.csv": success_kinematic_z_contrast_by_subject_finger,
    "subject_finger_trajectory.csv": subject_finger_trajectory,
    "subject_xy_trajectory.csv": subject_xy_trajectory,
    "subject_spatial_trajectory_summary.csv": subject_spatial_trajectory_summary,
    "subject_finger_spatial_distance.csv": subject_finger_spatial_distance,
    "subject_velocity_acceleration_profile.csv": subject_velocity_acceleration_profile,
    "subject_velocity_acceleration_summary.csv": subject_velocity_acceleration_summary,
    "subject_finger_velocity_acceleration_distance.csv": subject_finger_velocity_acceleration_distance,
    "trial_3d_kinematic_summary.csv": trial_3d_kinematic_summary,
    "subject_3d_kinematic_summary.csv": subject_3d_kinematic_summary,
    "hand_orientation_plane_summary.csv": hand_orientation_plane_summary,
    "side_z_trial_summary.csv": side_z_trial_summary,
    "side_z_subject_stiffness_summary.csv": side_z_subject_stiffness_summary,
}
per_subject_tree_manifest = ka.save_selected_kinematic_tree(RUN_OUTPUT_ROOT, tables=per_subject_tables)
_n_subject = int((per_subject_tree_manifest["kind"] == "subject").sum())
_n_aggregate = int((per_subject_tree_manifest["kind"] == "aggregate").sum())
print(f"Per-subject csv files written: {_n_subject}; aggregate csv files: {_n_aggregate}")
print("Per-subject tree base:", RESULTS_ROOT.resolve())
display(per_subject_tree_manifest.head(60))

C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\kinematics_analysis.py:784: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, encoding=enc, **kwargs)

Per-subject csv files written: 3400; aggregate csv files: 2
Per-subject tree base: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\Kinematics\result_fillter

                          table     kind                                               path
0   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
1   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
2   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
3   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
4   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
5   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
6   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
7   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
8   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
9   trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
10  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
11  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
12  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
13  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
14  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
15  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
16  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
17  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
18  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
19  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
20  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
21  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
22  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
23  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
24  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
25  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
26  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
27  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
28  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
29  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
30  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
31  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
32  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
33  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
34  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
35  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
36  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
37  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
38  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
39  trial_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
40   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
41   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
42   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
43   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
44   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
45   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
46   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
47   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
48   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
49   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
50   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
51   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
52   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
53   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
54   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
55   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
56   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
57   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
58   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...
59   pair_kinematic_summary.csv  subject  C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...

In [22]:
# --- 15. Organize the results tree by subject + category ---
# Reorganize everything this run produced into the final layout:
#   results/<owner>/figures/<category>/...   and   results/<owner>/csv/<category>/...
# where <owner> is each subject plus the requested aggregate owner. Named
# group/combined runs use L_E / N_E / L_N_E top-level siblings; hand-picked
# subject lists use one custom aggregate folder and are not widened to full groups.
# Single-subject runs stay as one
# folder. Categories: s_vs_c_pos, s_vs_c_v, s_vs_c_a, hand_orientation,
# movement_orientation, z_lift, trajectories, velocity, acceleration, success, other.
organize_log = ka.organize_kinematic_results_tree(RESULTS_ROOT, RUN_OUTPUT_ROOT, DATA_SELECTION)
print(f"Reorganized {len(organize_log)} files into the by-subject / by-category tree.")
print("Owners:", sorted(organize_log["owner"].unique()) if not organize_log.empty else "(none)")
display(organize_log.groupby("owner").size().reset_index(name="files"))

Reorganized 8324 files into the by-subject / by-category tree.
Owners: ['L_E', 'L_E_1', 'L_E_10', 'L_E_11', 'L_E_12', 'L_E_14', 'L_E_15', 'L_E_16', 'L_E_17', 'L_E_18', 'L_E_2', 'L_E_20', 'L_E_21', 'L_E_22', 'L_E_3', 'L_E_4', 'L_E_5', 'L_E_6', 'L_E_7', 'L_E_8', 'L_E_9', 'L_N_E', 'N_E', 'N_E_1', 'N_E_11', 'N_E_12', 'N_E_13', 'N_E_14', 'N_E_15', 'N_E_16', 'N_E_17', 'N_E_18', 'N_E_19', 'N_E_2', 'N_E_20', 'N_E_21', 'N_E_3', 'N_E_4', 'N_E_5', 'N_E_6', 'N_E_7', 'N_E_8', 'N_E_9']

     owner  files
0      L_E     45
1    L_E_1    151
2   L_E_10    151
3   L_E_11    151
4   L_E_12    151
5   L_E_14    151
6   L_E_15    151
7   L_E_16    151
8   L_E_17    151
9   L_E_18    151
10   L_E_2    149
11  L_E_20    151
12  L_E_21    151
13  L_E_22    151
14   L_E_3    151
15   L_E_4    151
16   L_E_5    151
17   L_E_6    151
18   L_E_7    151
19   L_E_8    151
20   L_E_9    151
21   L_N_E   2198
22     N_E     45
23   N_E_1    151
24  N_E_11    151
25  N_E_12    151
26  N_E_13    151
27  N_E_14    151
28  N_E_15    151
29  N_E_16    151
30  N_E_17    151
31  N_E_18    151
32  N_E_19    151
33   N_E_2    151
34  N_E_20    151
35  N_E_21    151
36   N_E_3    151
37   N_E_4    149
38   N_E_5    151
39   N_E_6    151
40   N_E_7    151
41   N_E_8    151
42   N_E_9    151

## 16. Filtered output sanity summary

Run this after the organization cell to confirm that `result_fillter` contains filtered z-tracking inputs and categorized outputs.

In [23]:
def list_existing_category_dirs(root: Path) -> pd.DataFrame:
    rows = []
    for owner in sorted([p for p in root.iterdir() if p.is_dir()]):
        if owner.name == "filtered_z_tracking_sources":
            continue
        for kind in ["csv", "figures"]:
            base = owner / kind
            if not base.exists():
                continue
            for category in sorted([p for p in base.iterdir() if p.is_dir()]):
                rows.append({
                    "owner": owner.name,
                    "kind": kind,
                    "category": category.name,
                    "files": sum(1 for p in category.rglob("*") if p.is_file()),
                    "filter_tag": FILTER_TAG,
                })
    return pd.DataFrame(rows)


category_manifest = list_existing_category_dirs(RESULTS_ROOT)
ka.save_csv(category_manifest, OUTPUT_ROOT, "category_manifest_fillter.csv")
print({
    "results_root": str(RESULTS_ROOT),
    "run_output_root": str(OUTPUT_ROOT),
    "filtered_z_tracking_root": str(FILTERED_Z_TRACKING_ROOT),
    "filtered_z_tracking_files": len(list(FILTERED_Z_TRACKING_ROOT.rglob("z_tracking_fillter.csv"))),
    "category_rows": len(category_manifest),
    "filter_tag": FILTER_TAG,
})
display(category_manifest.head(100))

{'results_root': 'C:\\Users\\user\\BIO MEDICAL ROBOTICS Dropbox\\Elisheva Shiri Decktor\\BGU\\Codes\\Parallel_Heptics\\analysis\\Kinematics\\result_fillter', 'run_output_root': 'C:\\Users\\user\\BIO MEDICAL ROBOTICS Dropbox\\Elisheva Shiri Decktor\\BGU\\Codes\\Parallel_Heptics\\analysis\\Kinematics\\result_fillter\\L_N_E', 'filtered_z_tracking_root': 'C:\\Users\\user\\BIO MEDICAL ROBOTICS Dropbox\\Elisheva Shiri Decktor\\BGU\\Codes\\Parallel_Heptics\\analysis\\Kinematics\\result_fillter\\filtered_z_tracking_sources\\L_N_E_fillter', 'filtered_z_tracking_files': 10240, 'category_rows': 469, 'filter_tag': 'fillter'}

     owner     kind          category  files filter_tag
0      L_E      csv             other      8    fillter
1      L_E      csv           success      3    fillter
2      L_E      csv      trajectories      3    fillter
3      L_E      csv          velocity      2    fillter
4      L_E      csv            z_lift      2    fillter
..     ...      ...               ...    ...        ...
95  L_E_17  figures      trajectories     23    fillter
96  L_E_17  figures          velocity     28    fillter
97  L_E_18      csv  hand_orientation      1    fillter
98  L_E_18      csv             other      9    fillter
99  L_E_18      csv           success      4    fillter

[100 rows x 5 columns]