# 2AFC Constant-Stimuli Psychophysics Analysis

This notebook analyzes a two-alternative forced-choice (2AFC) constant-stimuli experiment, following the relevant perception-analysis structure used by Farajian & Nisky: count matrices of comparison-standard stiffness differences, logistic psychometric curves, PSE, and JND.

**Raw data rule:** set `DATA_ROOT` to the main data folder. The notebook treats it as read-only and writes all outputs to `OUTPUT_ROOT`.

**Important fitting rule:** the raw `answer` column is **not** used directly for fitting. Each trial is first converted into `response_comparison_greater` after determining whether the comparison stimulus was object 1 or object 2.

**Added for this experiment:** success/correctness is analyzed separately from the psychometric response, including answer duration (`time_to_answer`) and fatigue/learning proxies (trial order, elapsed time, first-vs-second half, and early/middle/late bins) per participant and across participants.

## 0. Configuration

Edit `DATA_SELECTION` to choose the cohort/subject to analyze:

- Group flags: `L_E`, `L_P`, `N_E`, `N_P`, `L_N_E`
- One subject: e.g. `L_E_14`

The notebook reads canonical subject folders from the new raw results folder and ignores folders marked `not finish` or `not include`. Outputs are written under `RUN_OUTPUT_ROOT` with separate `figures/` and `csv/` trees.

In [ ]:
from pathlib import Path
import sys
import json
import shutil
import importlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Works whether Jupyter's current directory is the project root, analysis/, or this folder.
CWD = Path.cwd()
if (CWD / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD
elif (CWD / "analysis" / "psychophysics" / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD / "analysis" / "psychophysics"
elif (CWD / "psychophysics" / "twoafc_psychophysics.py").exists():
    ANALYSIS_DIR = CWD / "psychophysics"
else:
    raise FileNotFoundError("Could not locate twoafc_psychophysics.py. Open the notebook from the project root, analysis/, or analysis/psychophysics/.")
sys.path.insert(0, str(ANALYSIS_DIR))
import twoafc_psychophysics as pf
pf = importlib.reload(pf)  # keep notebook kernel synced with local code edits

pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)

# New read-only results folder. Expected subject folders: L_E_i, L_P_i, N_E_i, N_P_i.
DATA_ROOT = Path(r"C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\results")

# Choose one group, one subject, or a custom subject list.
# Examples: "L_E", "L_P", "N_E", "N_P", "L_N_E", "L_E_14", ["L_E_1", "L_E_2", "L_E_3"].
DATA_SELECTION = "N_E_1"
SELECTION_LABEL = pf.selection_label(DATA_SELECTION)

# Run-specific output folder. It is reset on each run so old outputs do not mix with the current selection.
OUTPUT_BASE = ANALYSIS_DIR / "results"
RUN_OUTPUT_ROOT = OUTPUT_BASE / SELECTION_LABEL
OVERWRITE_SELECTION_OUTPUT = True
KEEP_WORKING_OUTPUTS = False
if OVERWRITE_SELECTION_OUTPUT:
    pf.reset_output_root(RUN_OUTPUT_ROOT)
else:
    RUN_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

# Intermediate notebook tables/figures are written here, then the requested tree is written to RUN_OUTPUT_ROOT.
OUTPUT_ROOT = RUN_OUTPUT_ROOT / "_working"
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

STANDARD_FALLBACK = 85.0          # used only as fallback/tie-break anchor
STANDARD_ABS_TOLERANCE = 0.75     # tolerance for classifying the inferred standard
FIG_DPI = 160

# Optional manual column overrides if automatic detection needs help.
# Example: {"object_1_value": "object_1_stiffness", "answer": "answer"}
MANUAL_COLUMN_OVERRIDES = {}

print("ANALYSIS_DIR:", ANALYSIS_DIR.resolve())
print("DATA_ROOT:", DATA_ROOT)
print("DATA_SELECTION:", DATA_SELECTION, "->", SELECTION_LABEL)
print("RUN_OUTPUT_ROOT:", RUN_OUTPUT_ROOT.resolve())
print("WORKING OUTPUT_ROOT:", OUTPUT_ROOT.resolve())

ANALYSIS_DIR: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics
DATA_ROOT: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\results
DATA_SELECTION: ('N_E', 'L_E') -> custom_N_E_plus_L_E
RUN_OUTPUT_ROOT: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics\results\custom_N_E_plus_L_E
WORKING OUTPUT_ROOT: C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics\results\custom_N_E_plus_L_E\_working

## 1. File discovery and loading

One canonical folder per subject is expected under `DATA_ROOT` (`L_E_i`, `L_P_i`, `N_E_i`, `N_P_i`). Folder names containing `not finish` or `not include` are skipped. The code searches each included subject folder recursively for files named exactly `answers.csv`, then saves a discovery audit table.

In [258]:
pf.validate_paths(DATA_ROOT, RUN_OUTPUT_ROOT)

file_discovery_summary = pf.discover_answer_files(DATA_ROOT, RUN_OUTPUT_ROOT, selection=DATA_SELECTION)

# Subject folders are siblings of the group folder, e.g. results/L_E and results/L_E_1, results/L_E_2, ...
# Reset only the subjects included in this run so old subject outputs do not mix with the current run.
selected_subject_ids = sorted(
    file_discovery_summary.loc[file_discovery_summary["selected"], "canonical_subject_id"].dropna().astype(str).unique(),
    key=pf._subject_sort_key,
)
if OVERWRITE_SELECTION_OUTPUT:
    for subject_id in selected_subject_ids:
        pf.reset_output_root(OUTPUT_BASE / pf.sanitize_name(subject_id))

pf.save_csv(file_discovery_summary, OUTPUT_ROOT, "file_discovery_summary.csv")
display(file_discovery_summary.head(30))

combined_raw_imported_data = pf.load_selected_subject_csvs(file_discovery_summary)
pf.save_csv(combined_raw_imported_data, OUTPUT_ROOT, "combined_raw_imported_data.csv")
display(combined_raw_imported_data.head())
print("combined raw shape:", combined_raw_imported_data.shape)
print("included subjects:", sorted(combined_raw_imported_data["subject_id"].astype(str).unique(), key=pf._subject_sort_key))
print("group output folder:", RUN_OUTPUT_ROOT)
print("subject output folders:", [OUTPUT_BASE / pf.sanitize_name(s) for s in selected_subject_ids])

,subject_id,canonical_subject_id,subject_group_code,subject_folder,candidate_rank,candidate_score,selected,source_file,source_file_name,n_answer_csv_candidates,n_total_csv_files_in_subject_folder,selection_warning
0,L_E_1,L_E_1,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
1,L_E_10,L_E_10,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
2,L_E_11,L_E_11,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
3,L_E_12,L_E_12,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
4,L_E_14,L_E_14,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
5,L_E_15,L_E_15,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
6,L_E_16,L_E_16,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
7,L_E_17,L_E_17,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
8,L_E_18,L_E_18,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
9,L_E_19,L_E_19,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
10,L_E_2,L_E_2,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
11,L_E_3,L_E_3,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
12,L_E_4,L_E_4,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
13,L_E_5,L_E_5,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
14,L_E_6,L_E_6,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
15,L_E_7,L_E_7,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
16,L_E_8,L_E_8,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
17,L_E_9,L_E_9,L_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
18,N_E_1,N_E_1,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
19,N_E_11,N_E_11,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
20,N_E_12,N_E_12,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
21,N_E_13,N_E_13,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
22,N_E_14,N_E_14,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
23,N_E_15,N_E_15,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
24,N_E_16,N_E_16,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
25,N_E_17,N_E_17,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,271,
26,N_E_18,N_E_18,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
27,N_E_19,N_E_19,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
28,N_E_2,N_E_2,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,
29,N_E_3,N_E_3,N_E,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,1,37,True,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,272,

,subject_id,_subject_folder,_source_file,_source_file_name,_row_in_source,timestamp,pair_number,object_1_finger,object_1_stiffness,object_2_finger,object_2_stiffness,time_to_answer,answer
0,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,0,2026-05-11T11:02:36.482977,1,index,85,index,40,5.399998,0
1,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,2026-05-11T11:03:01.054278,2,index,85,index,130,2.521047,1
2,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,2,2026-05-11T11:03:19.190788,3,index,70,index,85,2.313266,1
3,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,3,2026-05-11T11:03:57.492458,4,middle,85,middle,70,2.368027,0
4,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,4,2026-05-11T11:04:11.951749,5,middle,130,middle,85,2.532164,0

combined raw shape: (9648, 13)
included subjects: ['L_E_1', 'L_E_10', 'L_E_11', 'L_E_12', 'L_E_14', 'L_E_15', 'L_E_16', 'L_E_17', 'L_E_18', 'L_E_19', 'L_E_2', 'L_E_3', 'L_E_4', 'L_E_5', 'L_E_6', 'L_E_7', 'L_E_8', 'L_E_9', 'N_E_1', 'N_E_11', 'N_E_12', 'N_E_13', 'N_E_14', 'N_E_15', 'N_E_16', 'N_E_17', 'N_E_18', 'N_E_19', 'N_E_2', 'N_E_3', 'N_E_4', 'N_E_5', 'N_E_6', 'N_E_7', 'N_E_8', 'N_E_9']
group output folder: c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Elisheva Shiri Decktor\BGU\Codes\Parallel_Heptics\analysis\psychophysics\results\custom_N_E_plus_L_E
subject output folders: [WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_1'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_10'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_11'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_12'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_14'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_15'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_16'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_17'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_18'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_19'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_2'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_3'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_4'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_5'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_6'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_7'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_8'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/L_E_9'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_1'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_11'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_12'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_13'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_14'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_15'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_16'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_17'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_18'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_19'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_2'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_3'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_4'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_5'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_6'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_7'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_8'), WindowsPath('c:/Users/user/BIO MEDICAL ROBOTICS Dropbox/Elisheva Shiri Decktor/BGU/Codes/Parallel_Heptics/analysis/psychophysics/results/N_E_9')]

## 2. Column detection and validation

Detects object values, object fingers, answer, reaction time, trial index, timestamp, and optional block columns. Review the detection table; if needed, set `MANUAL_COLUMN_OVERRIDES` above and rerun.

In [259]:
detected_columns, column_detection_details = pf.detect_columns(combined_raw_imported_data, MANUAL_COLUMN_OVERRIDES)
print(json.dumps(detected_columns, indent=2, ensure_ascii=False))
pf.save_csv(column_detection_details, OUTPUT_ROOT, "column_detection_details.csv")
display(column_detection_details.groupby("target").head(5))

missing_required = [k for k in ["object_1_value", "object_2_value", "answer"] if not detected_columns.get(k)]
if missing_required:
    raise RuntimeError(f"Missing required detected columns: {missing_required}. Add MANUAL_COLUMN_OVERRIDES and rerun.")

{
  "object_1_value": "object_1_stiffness",
  "object_2_value": "object_2_stiffness",
  "object_1_finger": "object_1_finger",
  "object_2_finger": "object_2_finger",
  "answer": "answer",
  "reaction_time": "time_to_answer",
  "trial_index": "pair_number",
  "timestamp": "timestamp",
  "block": null
}

             target              column          normalized  score  manual
0    object_1_value  object_1_stiffness  object_1_stiffness     23   False
1    object_1_value  object_2_stiffness  object_2_stiffness      9   False
2    object_1_value     object_1_finger     object_1_finger      6   False
3    object_1_value      _row_in_source       row_in_source      0   False
4    object_1_value        _source_file         source_file      0   False
8    object_2_value  object_2_stiffness  object_2_stiffness     23   False
9    object_2_value  object_1_stiffness  object_1_stiffness      9   False
10   object_2_value     object_2_finger     object_2_finger      6   False
11   object_2_value      _row_in_source       row_in_source      0   False
12   object_2_value        _source_file         source_file      0   False
16  object_1_finger     object_1_finger     object_1_finger     24   False
17  object_1_finger     object_2_finger     object_2_finger     10   False
18  object_1_finger  object_1_stiffness  object_1_stiffness      8   False
19  object_1_finger      _row_in_source       row_in_source      0   False
20  object_1_finger        _source_file         source_file      0   False
24  object_2_finger     object_2_finger     object_2_finger     24   False
25  object_2_finger     object_1_finger     object_1_finger     10   False
26  object_2_finger  object_2_stiffness  object_2_stiffness      8   False
27  object_2_finger      _row_in_source       row_in_source      0   False
28  object_2_finger        _source_file         source_file      0   False
32           answer              answer              answer     10   False
33           answer      time_to_answer      time_to_answer      2   False
34           answer      _row_in_source       row_in_source      0   False
35           answer        _source_file         source_file      0   False
36           answer   _source_file_name    source_file_name      0   False
40    reaction_time      time_to_answer      time_to_answer     13   False
41    reaction_time      _row_in_source       row_in_source      0   False
42    reaction_time        _source_file         source_file      0   False
43    reaction_time   _source_file_name    source_file_name      0   False
44    reaction_time     _subject_folder      subject_folder      0   False
48      trial_index         pair_number         pair_number      8   False
49      trial_index      _row_in_source       row_in_source      0   False
50      trial_index        _source_file         source_file      0   False
51      trial_index   _source_file_name    source_file_name      0   False
52      trial_index     _subject_folder      subject_folder      0   False
56        timestamp           timestamp           timestamp      8   False
57        timestamp      _row_in_source       row_in_source      0   False
58        timestamp        _source_file         source_file      0   False
59        timestamp   _source_file_name    source_file_name      0   False
60        timestamp     _subject_folder      subject_folder      0   False
64            block      _row_in_source       row_in_source      0   False
65            block        _source_file         source_file      0   False
66            block   _source_file_name    source_file_name      0   False
67            block     _subject_folder      subject_folder      0   False
68            block         pair_number         pair_number      0   False

## 3. Trial cleaning and canonicalization

Protocol rows and invalid/ambiguous trials are flagged and saved separately. Valid trials receive `response_comparison_greater` for fitting.

Examples:
- standard object 1, comparison object 2 ? response is 1 when `answer == 1`.
- standard object 2, comparison object 1 ? response is 1 when `answer == 0`.

In [260]:
inferred_standard_value, standard_inference_table = pf.infer_standard_value(combined_raw_imported_data, detected_columns, STANDARD_FALLBACK)
print(f"Inferred standard/reference value: {inferred_standard_value:g}")
pf.save_csv(standard_inference_table, OUTPUT_ROOT, "standard_value_inference.csv")
display(standard_inference_table.head(10))

combined_clean_trials, combined_flagged_trials = pf.canonicalize_trials(
    combined_raw_imported_data,
    detected_columns,
    standard_value=inferred_standard_value,
    standard_tolerance=STANDARD_ABS_TOLERANCE,
)
pf.save_csv(combined_clean_trials, OUTPUT_ROOT, "combined_clean_trials.csv")
pf.save_csv(combined_flagged_trials, OUTPUT_ROOT, "combined_flagged_trials.csv")

print("Clean trials:", combined_clean_trials.shape)
display(combined_clean_trials.head())
print("Flagged trials:", combined_flagged_trials.shape)
display(combined_flagged_trials.head())

Inferred standard/reference value: 85

   candidate_value  count  n_unique_partners  distance_from_fallback  standard_score
0               85   9648                  8                     0.0        1.350000
1               70   1296                  1                    15.0        0.165578
2              100   1152                  1                    15.0        0.150653
3              130   1296                  1                    45.0        0.140578
4               40   1296                  1                    45.0        0.140578
5              115   1152                  1                    30.0        0.138153
6               55   1152                  1                    30.0        0.138153
7              145   1152                  1                    60.0        0.113153
8               25   1152                  1                    60.0        0.113153

Clean trials: (9216, 30)

,subject_id,source_file,source_file_name,row_in_source,trial_index_raw,timestamp,block_raw,object_1_value,object_2_value,object_1_finger_raw,object_2_finger_raw,object_1_finger,object_2_finger,standard_value,standard_side,comparison_side,comparison_value,standard_finger,comparison_finger,finger_condition,raw_answer,answer_code,response_comparison_greater,reaction_time,protocol_marker,finger_warning,excluded_from_fit,flag_reason,global_trial_order,answer_chose_object_2
0,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,12,13,2026-05-11T11:07:26.541520,NaN,115,85,ring,ring,R,R,85.0,object_2,object_1,115.0,R,R,R,0,0,1,2.323103,False,,False,,13,0.0
1,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,13,14,2026-05-11T11:07:46.816911,NaN,55,85,ring,ring,R,R,85.0,object_2,object_1,55.0,R,R,R,1,1,0,2.351829,False,,False,,14,1.0
2,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,14,15,2026-05-11T11:08:03.041546,NaN,40,85,ring,ring,R,R,85.0,object_2,object_1,40.0,R,R,R,0,0,1,2.152518,False,,False,,15,0.0
3,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,15,16,2026-05-11T11:08:29.746061,NaN,145,85,ring,ring,R,R,85.0,object_2,object_1,145.0,R,R,R,0,0,1,2.168074,False,,False,,16,0.0
4,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,16,17,2026-05-11T11:08:46.876595,NaN,85,130,ring,ring,R,R,85.0,object_1,object_2,130.0,R,R,R,1,1,1,2.160077,False,,False,,17,1.0

Flagged trials: (432, 30)

,subject_id,source_file,source_file_name,row_in_source,trial_index_raw,timestamp,block_raw,object_1_value,object_2_value,object_1_finger_raw,object_2_finger_raw,object_1_finger,object_2_finger,standard_value,standard_side,comparison_side,comparison_value,standard_finger,comparison_finger,finger_condition,raw_answer,answer_code,response_comparison_greater,reaction_time,protocol_marker,finger_warning,excluded_from_fit,flag_reason,global_trial_order,answer_chose_object_2
0,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,0,1,2026-05-11T11:02:36.482977,NaN,85,40,index,index,I,I,85.0,object_1,object_2,40.0,I,I,I,0,0,0,5.399998,False,,True,pilot_onboarding_excluded,1,0.0
1,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,1,2,2026-05-11T11:03:01.054278,NaN,85,130,index,index,I,I,85.0,object_1,object_2,130.0,I,I,I,1,1,1,2.521047,False,,True,pilot_onboarding_excluded,2,1.0
2,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,2,3,2026-05-11T11:03:19.190788,NaN,70,85,index,index,I,I,85.0,object_2,object_1,70.0,I,I,I,1,1,0,2.313266,False,,True,pilot_onboarding_excluded,3,1.0
3,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,3,4,2026-05-11T11:03:57.492458,NaN,85,70,middle,middle,M,M,85.0,object_1,object_2,70.0,M,M,M,0,0,0,2.368027,False,,True,pilot_onboarding_excluded,4,0.0
4,L_E_1,C:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...,answers.csv,4,5,2026-05-11T11:04:11.951749,NaN,130,85,middle,middle,M,M,85.0,object_2,object_1,130.0,M,M,M,0,0,1,2.532164,False,,True,pilot_onboarding_excluded,5,0.0

## 4. Block and finger detection

Finger labels are normalized to `I`, `M`, `R`, `P`. Block order is inferred from changes in `finger_condition` within each subject.

In [261]:
combined_clean_trials, block_order_summary = pf.add_block_numbers(combined_clean_trials)
pf.save_csv(combined_clean_trials, OUTPUT_ROOT, "combined_clean_trials.csv")
pf.save_csv(block_order_summary, OUTPUT_ROOT, "block_order_summary.csv")
display(block_order_summary.head(30))
display(pd.crosstab(combined_clean_trials["subject_id"], combined_clean_trials["finger_condition"]))

   subject_id  block_number finger_condition  first_global_trial_order  n_trials_in_block
0       L_E_1             1                R                        13                 64
1       L_E_1             2                P                        77                 64
2       L_E_1             3                M                       141                 64
3       L_E_1             4                I                       205                 64
4      L_E_10             1                I                        13                 64
5      L_E_10             2                M                        77                 64
6      L_E_10             3                P                       141                 64
7      L_E_10             4                R                       205                 64
8      L_E_11             1                P                        13                 64
9      L_E_11             2                I                        77                 64
10     L_E_11             3                R                       141                 64
11     L_E_11             4                M                       205                 64
12     L_E_12             1                R                        13                 64
13     L_E_12             2                P                        77                 64
14     L_E_12             3                M                       141                 64
15     L_E_12             4                I                       205                 64
16     L_E_14             1                M                        13                 64
17     L_E_14             2                R                        77                 64
18     L_E_14             3                I                       141                 64
19     L_E_14             4                P                       205                 64
20     L_E_15             1                I                        13                 64
21     L_E_15             2                M                        77                 64
22     L_E_15             3                P                       141                 64
23     L_E_15             4                R                       205                 64
24     L_E_16             1                P                        13                 64
25     L_E_16             2                I                        77                 64
26     L_E_16             3                R                       141                 64
27     L_E_16             4                M                       205                 64
28     L_E_17             1                R                        13                 64
29     L_E_17             2                P                        77                 64

finger_condition   I   M   P   R
subject_id
L_E_1             64  64  64  64
L_E_10            64  64  64  64
L_E_11            64  64  64  64
L_E_12            64  64  64  64
L_E_14            64  64  64  64
L_E_15            64  64  64  64
L_E_16            64  64  64  64
L_E_17            64  64  64  64
L_E_18            64  64  64  64
L_E_19            64  64  64  64
L_E_2             64  64  64  64
L_E_3             64  64  64  64
L_E_4             64  64  64  64
L_E_5             64  64  64  64
L_E_6             64  64  64  64
L_E_7             64  64  64  64
L_E_8             64  64  64  64
L_E_9             64  64  64  64
N_E_1             64  64  64  64
N_E_11            64  64  64  64
N_E_12            64  64  64  64
N_E_13            64  64  64  64
N_E_14            64  64  64  64
N_E_15            64  64  64  64
N_E_16            64  64  64  64
N_E_17            64  64  64  64
N_E_18            64  64  64  64
N_E_19            64  64  64  64
N_E_2             64  64  64  64
N_E_3             64  64  64  64
N_E_4             64  64  64  64
N_E_5             64  64  64  64
N_E_6             64  64  64  64
N_E_7             64  64  64  64
N_E_8             64  64  64  64
N_E_9             64  64  64  64

## 5. Success/correctness coding and Farajian-style count matrices

Psychometric fitting uses `response_comparison_greater`. Success-rate analysis asks a different question: did the participant choose the physically stiffer stimulus? This cell adds `correct_response`, signed stiffness deltas, elapsed time, participant group (`pilot`/`experiment`), and fatigue/order proxies.

In [262]:
combined_success_trials = pf.add_success_and_time_columns(combined_clean_trials)
pf.save_csv(combined_success_trials, OUTPUT_ROOT, "combined_success_trials.csv")

farajian_style_input_by_subject_finger = pf.make_farajian_style_psychometric_input(combined_success_trials, ["subject_id", "finger_condition"])
farajian_style_input_group_by_finger = pf.make_farajian_style_psychometric_input(combined_success_trials, ["finger_condition"])
pf.save_csv(farajian_style_input_by_subject_finger, OUTPUT_ROOT, "farajian_style_input_by_subject_finger.csv")
pf.save_csv(farajian_style_input_group_by_finger, OUTPUT_ROOT, "farajian_style_input_group_by_finger.csv")

display(combined_success_trials[[
    "subject_id", "subject_group_label", "finger_condition", "global_trial_order",
    "signed_stiffness_delta", "response_comparison_greater", "correct_response",
    "reaction_time", "elapsed_minutes", "session_half", "fatigue_tertile"
]].head(20))
display(farajian_style_input_by_subject_finger.head(30))

,subject_id,subject_group_label,finger_condition,global_trial_order,signed_stiffness_delta,response_comparison_greater,correct_response,reaction_time,elapsed_minutes,session_half,fatigue_tertile
0,L_E_1,other,R,13,30.0,1,1.0,2.323103,0.000000,first_half,early
1,L_E_1,other,R,14,-30.0,0,1.0,2.351829,0.337923,first_half,early
2,L_E_1,other,R,15,-45.0,1,0.0,2.152518,0.608334,first_half,early
3,L_E_1,other,R,16,60.0,1,1.0,2.168074,1.053409,first_half,early
4,L_E_1,other,R,17,45.0,1,1.0,2.160077,1.338918,first_half,early
5,L_E_1,other,R,18,-15.0,1,0.0,2.202255,1.625668,first_half,early
6,L_E_1,other,R,19,15.0,1,1.0,2.254923,1.862973,first_half,early
7,L_E_1,other,R,20,-60.0,0,1.0,2.053244,2.103824,first_half,early
8,L_E_1,other,R,21,-15.0,0,1.0,2.129709,2.350896,first_half,early
9,L_E_1,other,R,22,-30.0,0,1.0,2.054690,2.597496,first_half,early
10,L_E_1,other,R,23,30.0,0,0.0,2.176742,2.860247,first_half,early
11,L_E_1,other,R,24,-45.0,0,1.0,2.118868,3.100312,first_half,early
12,L_E_1,other,R,25,45.0,1,1.0,3.082627,3.343249,first_half,early
13,L_E_1,other,R,26,-60.0,0,1.0,2.119346,3.587986,first_half,early
14,L_E_1,other,R,27,60.0,0,0.0,2.115713,3.812072,first_half,early
15,L_E_1,other,R,28,15.0,1,1.0,2.178354,4.030427,first_half,early
16,L_E_1,other,R,29,60.0,1,1.0,2.172424,4.281927,first_half,early
17,L_E_1,other,R,30,30.0,1,1.0,2.371429,4.518400,first_half,early
18,L_E_1,other,R,31,-15.0,1,0.0,2.101664,4.774703,first_half,early
19,L_E_1,other,R,32,-45.0,0,1.0,2.129087,4.981180,first_half,early

,subject_id,finger_condition,delta_comparison_minus_standard,delta_standard_minus_comparison,n_comparison_greater,n_comparison_less,n_trials,n_data_points,p_comparison_greater,p_comparison_greater_ci95_lower,p_comparison_greater_ci95_upper,p_comparison_less,p_comparison_less_ci95_lower,p_comparison_less_ci95_upper,n_correct,success_rate,success_rate_ci95_lower,success_rate_ci95_upper,mean_reaction_time,median_reaction_time,reaction_time_ci95_lower,reaction_time_ci95_upper,mean_log_reaction_time,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s,standard_value,comparison_value,comparison_over_standard,signed_delta_over_standard,abs_delta_over_standard,signed_stiffness_delta,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper
0,L_E_1,I,-60.0,60.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.754411,1.747458,1.722376,1.786447,0.561830,1.753879,1.722173,1.786170,85.0,25.0,0.294118,-0.705882,0.705882,-60.0,0.543587,0.580073
1,L_E_1,I,-45.0,45.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.843788,1.798201,1.747599,1.939977,0.609462,1.839441,1.749236,1.934297,85.0,40.0,0.470588,-0.529412,0.529412,-45.0,0.559179,0.659744
2,L_E_1,I,-30.0,30.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.748191,1.720479,1.697054,1.799328,0.557816,1.746853,1.697175,1.797986,85.0,55.0,0.647059,-0.352941,0.352941,-30.0,0.528965,0.586667
3,L_E_1,I,-15.0,15.0,2,6,8,8,0.250,0.071478,0.590730,0.750,0.409270,0.928522,6.0,0.750,0.409270,0.928522,1.790395,1.769528,1.733259,1.847531,0.581516,1.788748,1.732884,1.846412,85.0,70.0,0.823529,-0.176471,0.176471,-15.0,0.549787,0.613244
4,L_E_1,I,15.0,-15.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.837103,1.776203,1.728583,1.945624,0.605233,1.831679,1.732002,1.937092,85.0,100.0,1.176471,0.176471,0.176471,15.0,0.549278,0.661188
5,L_E_1,I,30.0,-30.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.757840,1.762569,1.705581,1.810098,0.563284,1.756431,1.705155,1.809250,85.0,115.0,1.352941,0.352941,0.352941,30.0,0.533656,0.592912
6,L_E_1,I,45.0,-45.0,7,1,8,8,0.875,0.529105,0.977583,0.125,0.022417,0.470895,7.0,0.875,0.529105,0.977583,1.789623,1.776900,1.745184,1.834063,0.581452,1.788634,1.745283,1.833062,85.0,130.0,1.529412,0.529412,0.529412,45.0,0.556917,0.605988
7,L_E_1,I,60.0,-60.0,8,0,8,8,1.000,0.675584,1.000000,0.000,0.000000,0.324416,8.0,1.000,0.675584,1.000000,1.818003,1.797513,1.724315,1.911691,0.595410,1.813775,1.725160,1.906941,85.0,145.0,1.705882,0.705882,0.705882,60.0,0.545320,0.645501
8,L_E_1,M,-60.0,60.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.912087,1.806236,1.687564,2.136610,0.637865,1.892436,1.710083,2.094235,85.0,25.0,0.294118,-0.705882,0.705882,-60.0,0.536542,0.739189
9,L_E_1,M,-45.0,45.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.795579,1.786498,1.766832,1.824326,0.585095,1.795162,1.766780,1.824000,85.0,40.0,0.470588,-0.529412,0.529412,-45.0,0.569158,0.601032
10,L_E_1,M,-30.0,30.0,1,7,8,8,0.125,0.022417,0.470895,0.875,0.529105,0.977583,7.0,0.875,0.529105,0.977583,1.855490,1.820994,1.778068,1.932911,0.616586,1.852593,1.777727,1.930612,85.0,55.0,0.647059,-0.352941,0.352941,-30.0,0.575336,0.657837
11,L_E_1,M,-15.0,15.0,4,4,8,8,0.500,0.215213,0.784787,0.500,0.215213,0.784787,4.0,0.500,0.215213,0.784787,1.840736,1.814939,1.772571,1.908901,0.608944,1.838489,1.772740,1.906677,85.0,70.0,0.823529,-0.176471,0.176471,-15.0,0.572526,0.645362
12,L_E_1,M,15.0,-15.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.813248,1.800104,1.781943,1.844553,0.594848,1.812755,1.781706,1.844345,85.0,100.0,1.176471,0.176471,0.176471,15.0,0.577572,0.612124
13,L_E_1,M,30.0,-30.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.887835,1.872656,1.817874,1.957797,0.634199,1.885512,1.817712,1.955841,85.0,115.0,1.352941,0.352941,0.352941,30.0,0.597578,0.670820
14,L_E_1,M,45.0,-45.0,8,0,8,8,1.000,0.675584,1.000000,0.000,0.000000,0.324416,8.0,1.000,0.675584,1.000000,1.830872,1.830194,1.778136,1.883609,0.604037,1.829490,1.777558,1.882938,85.0,130.0,1.529412,0.529412,0.529412,45.0,0.575241,0.632833
15,L_E_1,M,60.0,-60.0,8,0,8,8,1.000,0.675584,1.000000,0.000,0.000000,0.324416,8.0,1.000,0.675584,1.000000,1.823217,1.825394,1.786554,1.859880,0.600234,1.822546,1.786270,1.859558,85.0,145.0,1.705882,0.705882,0.705882,60.0,0.580130,0.620339
16,L_E_1,P,-60.0,60.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.862681,1.865036,1.818415,1.906947,0.621505,1.861728,1.818195,1.906303,85.0,25.0,0.294118,-0.705882,0.705882,-60.0,0.597844,0.645166
17,L_E_1,P,-45.0,45.0,1,7,8,8,0.125,0.022417,0.470895,0.875,0.529105,0.977583,7.0,0.875,0.529105,0.977583,1.870440,1.863401,1.790910,1.949970,0.624590,1.867480,1.791925,1.946220,85.0,40.0,0.470588,-0.529412,0.529412,-45.0,0.583291,0.665889
18,L_E_1,P,-30.0,30.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,1.875543,1.838763,1.792415,1.958670,0.627184,1.872331,1.793690,1.954420,85.0,55.0,0.647059,-0.352941,0.352941,-30.0,0.584275,0.670093
19,L_E_1,P,-15.0,15.0,5,3,8,8,0.625,0.305738,0.863158,0.375,0.136842,0.694262,3.0,0.375,0.136842,0.694262,1.973384,1.879691,1.821490,2.125278,0.674635,1.963317,1.823425,2.113942,85.0,70.0,0.823529,-0.176471,0.176471,-15.0,0.600717,0.748554
20,L_E_1,P,15.0,-15.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.903431,1.922214,1.833935,1.972927,0.642415,1.901067,1.831734,1.973025,85.0,100.0,1.176471,0.176471,0.176471,15.0,0.605263,0.679568
21,L_E_1,P,30.0,-30.0,5,3,8,8,0.625,0.305738,0.863158,0.375,0.136842,0.694262,5.0,0.625,0.305738,0.863158,1.883599,1.885776,1.835497,1.931701,0.632589,1.882477,1.834936,1.931251,85.0,115.0,1.352941,0.352941,0.352941,30.0,0.607009,0.658168
22,L_E_1,P,45.0,-45.0,6,2,8,8,0.750,0.409270,0.928522,0.250,0.071478,0.590730,6.0,0.750,0.409270,0.928522,1.903171,1.884108,1.861009,1.945334,0.643080,1.902332,1.861055,1.944524,85.0,130.0,1.529412,0.529412,0.529412,45.0,0.621143,0.665017
23,L_E_1,P,60.0,-60.0,7,1,8,8,0.875,0.529105,0.977583,0.125,0.022417,0.470895,7.0,0.875,0.529105,0.977583,1.878972,1.890083,1.831598,1.926345,0.630142,1.877876,1.830885,1.926073,85.0,145.0,1.705882,0.705882,0.705882,60.0,0.604800,0.655483
24,L_E_1,R,-60.0,60.0,0,8,8,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,8.0,1.000,0.675584,1.000000,2.068241,2.084809,2.014405,2.122077,0.726060,2.066922,2.012480,2.122836,85.0,25.0,0.294118,-0.705882,0.705882,-60.0,0.699368,0.752753
25,L_E_1,R,-45.0,45.0,1,7,8,8,0.125,0.022417,0.470895,0.875,0.529105,0.977583,7.0,0.875,0.529105,0.977583,2.058108,2.071213,2.001992,2.114224,0.721098,2.056691,2.000670,2.114280,85.0,40.0,0.470588,-0.529412,0.529412,-45.0,0.693482,0.748714
26,L_E_1,R,-30.0,30.0,2,6,8,8,0.250,0.071478,0.590730,0.750,0.409270,0.928522,6.0,0.750,0.409270,0.928522,2.090856,2.042778,2.011218,2.170494,0.736321,2.088239,2.013227,2.166046,85.0,55.0,0.647059,-0.352941,0.352941,-30.0,0.699739,0.772903
27,L_E_1,R,-15.0,15.0,4,4,8,8,0.500,0.215213,0.784787,0.500,0.215213,0.784787,4.0,0.500,0.215213,0.784787,2.091320,2.099781,2.040180,2.142460,0.737239,2.090158,2.038889,2.142715,85.0,70.0,0.823529,-0.176471,0.176471,-15.0,0.712405,0.762074
28,L_E_1,R,15.0,-15.0,7,1,8,8,0.875,0.529105,0.977583,0.125,0.022417,0.470895,7.0,0.875,0.529105,0.977583,2.131676,2.146746,2.069356,2.193995,0.756123,2.130002,2.068243,2.193606,85.0,100.0,1.176471,0.176471,0.176471,15.0,0.726699,0.785547
29,L_E_1,R,30.0,-30.0,5,3,8,8,0.625,0.305738,0.863158,0.375,0.136842,0.694262,5.0,0.625,0.305738,0.863158,2.213477,2.136843,2.049518,2.377437,0.789816,2.202991,2.051382,2.365804,85.0,115.0,1.352941,0.352941,0.352941,30.0,0.718514,0.861118

## 6. Quality-control summaries

Flags suspicious cases without silently deleting more data: missing/invalid rows, trial counts per value/finger, non-monotonic curves, apparent error rate, RT outliers, side bias, standard-side bias, and related warnings.

In [263]:
qc_summary = pf.make_qc_summary(combined_clean_trials, combined_flagged_trials)
pf.save_csv(qc_summary, OUTPUT_ROOT, "qc_summary.csv")
display(qc_summary)

,subject_id,finger_condition,n_clean_trials,n_stimulus_levels,min_trials_per_value,median_trials_per_value,side_bias_p_chose_object2,standard_side_p_object2,apparent_error_rate,rt_outlier_count,monotonic_violations,spearman_r,non_monotonic_flag,qc_warnings,n_flagged_rows
0,L_E_1,I,64,8,8,8.0,0.515625,0.5,0.109375,1,0,0.969782,False,,12
1,L_E_1,M,64,8,8,8.0,0.390625,0.5,0.140625,1,0,0.981981,False,,12
2,L_E_1,P,64,8,8,8.0,0.375000,0.5,0.218750,2,0,0.897118,False,,12
3,L_E_1,R,64,8,8,8.0,0.500000,0.5,0.281250,3,2,0.690476,True,non_monotonic_curve,12
4,L_E_10,I,64,8,8,8.0,0.515625,0.5,0.234375,4,0,0.945611,False,,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,N_E_8,R,64,8,8,8.0,0.406250,0.5,0.156250,2,1,0.891631,True,non_monotonic_curve,12
140,N_E_9,I,64,8,8,8.0,0.515625,0.5,0.171875,3,0,0.906687,False,,12
141,N_E_9,M,64,8,8,8.0,0.531250,0.5,0.187500,1,1,0.927778,True,non_monotonic_curve,12
142,N_E_9,P,64,8,8,8.0,0.484375,0.5,0.234375,3,0,0.988024,False,,12
143,N_E_9,R,64,8,8,8.0,0.468750,0.5,0.281250,4,1,0.790433,True,non_monotonic_curve,12

## 7. Psychometric aggregation

Aggregates valid trials into binomial counts: `comparison_value`, `n_trials`, `n_comparison_greater`, and observed probability.

In [264]:
# Enrich-once: feed the already-enriched `combined_success_trials` into
# make_psychometric_input (it carries log_reaction_time, so the helper uses its
# fast pre-enriched branch instead of re-running add_success_and_time_columns).
psychometric_input_by_subject_finger = pf.make_psychometric_input(combined_success_trials, ["subject_id", "finger_condition"])
pf.save_csv(psychometric_input_by_subject_finger, OUTPUT_ROOT, "psychometric_input_by_subject_finger.csv")
display(psychometric_input_by_subject_finger.head(30))

,subject_id,finger_condition,comparison_value,n_trials,n_data_points,n_comparison_greater,n_comparison_less,p_comparison_greater,p_comparison_greater_ci95_lower,p_comparison_greater_ci95_upper,p_comparison_less,p_comparison_less_ci95_lower,p_comparison_less_ci95_upper,mean_rt,median_rt,rt_ci95_lower,rt_ci95_upper,mean_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,standard_value,comparison_over_standard,signed_delta_over_standard,abs_delta_over_standard,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s,delta_comparison_minus_standard,delta_standard_minus_comparison
0,L_E_1,I,25.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.754411,1.747458,1.722376,1.786447,0.561830,0.543587,0.580073,85.0,0.294118,-0.705882,0.705882,1.753879,1.722173,1.786170,-60.0,60.0
1,L_E_1,I,40.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.843788,1.798201,1.747599,1.939977,0.609462,0.559179,0.659744,85.0,0.470588,-0.529412,0.529412,1.839441,1.749236,1.934297,-45.0,45.0
2,L_E_1,I,55.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.748191,1.720479,1.697054,1.799328,0.557816,0.528965,0.586667,85.0,0.647059,-0.352941,0.352941,1.746853,1.697175,1.797986,-30.0,30.0
3,L_E_1,I,70.0,8,8,2,6,0.250,0.071478,0.590730,0.750,0.409270,0.928522,1.790395,1.769528,1.733259,1.847531,0.581516,0.549787,0.613244,85.0,0.823529,-0.176471,0.176471,1.788748,1.732884,1.846412,-15.0,15.0
4,L_E_1,I,100.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.837103,1.776203,1.728583,1.945624,0.605233,0.549278,0.661188,85.0,1.176471,0.176471,0.176471,1.831679,1.732002,1.937092,15.0,-15.0
5,L_E_1,I,115.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.757840,1.762569,1.705581,1.810098,0.563284,0.533656,0.592912,85.0,1.352941,0.352941,0.352941,1.756431,1.705155,1.809250,30.0,-30.0
6,L_E_1,I,130.0,8,8,7,1,0.875,0.529105,0.977583,0.125,0.022417,0.470895,1.789623,1.776900,1.745184,1.834063,0.581452,0.556917,0.605988,85.0,1.529412,0.529412,0.529412,1.788634,1.745283,1.833062,45.0,-45.0
7,L_E_1,I,145.0,8,8,8,0,1.000,0.675584,1.000000,0.000,0.000000,0.324416,1.818003,1.797513,1.724315,1.911691,0.595410,0.545320,0.645501,85.0,1.705882,0.705882,0.705882,1.813775,1.725160,1.906941,60.0,-60.0
8,L_E_1,M,25.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.912087,1.806236,1.687564,2.136610,0.637865,0.536542,0.739189,85.0,0.294118,-0.705882,0.705882,1.892436,1.710083,2.094235,-60.0,60.0
9,L_E_1,M,40.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.795579,1.786498,1.766832,1.824326,0.585095,0.569158,0.601032,85.0,0.470588,-0.529412,0.529412,1.795162,1.766780,1.824000,-45.0,45.0
10,L_E_1,M,55.0,8,8,1,7,0.125,0.022417,0.470895,0.875,0.529105,0.977583,1.855490,1.820994,1.778068,1.932911,0.616586,0.575336,0.657837,85.0,0.647059,-0.352941,0.352941,1.852593,1.777727,1.930612,-30.0,30.0
11,L_E_1,M,70.0,8,8,4,4,0.500,0.215213,0.784787,0.500,0.215213,0.784787,1.840736,1.814939,1.772571,1.908901,0.608944,0.572526,0.645362,85.0,0.823529,-0.176471,0.176471,1.838489,1.772740,1.906677,-15.0,15.0
12,L_E_1,M,100.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.813248,1.800104,1.781943,1.844553,0.594848,0.577572,0.612124,85.0,1.176471,0.176471,0.176471,1.812755,1.781706,1.844345,15.0,-15.0
13,L_E_1,M,115.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.887835,1.872656,1.817874,1.957797,0.634199,0.597578,0.670820,85.0,1.352941,0.352941,0.352941,1.885512,1.817712,1.955841,30.0,-30.0
14,L_E_1,M,130.0,8,8,8,0,1.000,0.675584,1.000000,0.000,0.000000,0.324416,1.830872,1.830194,1.778136,1.883609,0.604037,0.575241,0.632833,85.0,1.529412,0.529412,0.529412,1.829490,1.777558,1.882938,45.0,-45.0
15,L_E_1,M,145.0,8,8,8,0,1.000,0.675584,1.000000,0.000,0.000000,0.324416,1.823217,1.825394,1.786554,1.859880,0.600234,0.580130,0.620339,85.0,1.705882,0.705882,0.705882,1.822546,1.786270,1.859558,60.0,-60.0
16,L_E_1,P,25.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.862681,1.865036,1.818415,1.906947,0.621505,0.597844,0.645166,85.0,0.294118,-0.705882,0.705882,1.861728,1.818195,1.906303,-60.0,60.0
17,L_E_1,P,40.0,8,8,1,7,0.125,0.022417,0.470895,0.875,0.529105,0.977583,1.870440,1.863401,1.790910,1.949970,0.624590,0.583291,0.665889,85.0,0.470588,-0.529412,0.529412,1.867480,1.791925,1.946220,-45.0,45.0
18,L_E_1,P,55.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,1.875543,1.838763,1.792415,1.958670,0.627184,0.584275,0.670093,85.0,0.647059,-0.352941,0.352941,1.872331,1.793690,1.954420,-30.0,30.0
19,L_E_1,P,70.0,8,8,5,3,0.625,0.305738,0.863158,0.375,0.136842,0.694262,1.973384,1.879691,1.821490,2.125278,0.674635,0.600717,0.748554,85.0,0.823529,-0.176471,0.176471,1.963317,1.823425,2.113942,-15.0,15.0
20,L_E_1,P,100.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.903431,1.922214,1.833935,1.972927,0.642415,0.605263,0.679568,85.0,1.176471,0.176471,0.176471,1.901067,1.831734,1.973025,15.0,-15.0
21,L_E_1,P,115.0,8,8,5,3,0.625,0.305738,0.863158,0.375,0.136842,0.694262,1.883599,1.885776,1.835497,1.931701,0.632589,0.607009,0.658168,85.0,1.352941,0.352941,0.352941,1.882477,1.834936,1.931251,30.0,-30.0
22,L_E_1,P,130.0,8,8,6,2,0.750,0.409270,0.928522,0.250,0.071478,0.590730,1.903171,1.884108,1.861009,1.945334,0.643080,0.621143,0.665017,85.0,1.529412,0.529412,0.529412,1.902332,1.861055,1.944524,45.0,-45.0
23,L_E_1,P,145.0,8,8,7,1,0.875,0.529105,0.977583,0.125,0.022417,0.470895,1.878972,1.890083,1.831598,1.926345,0.630142,0.604800,0.655483,85.0,1.705882,0.705882,0.705882,1.877876,1.830885,1.926073,60.0,-60.0
24,L_E_1,R,25.0,8,8,0,8,0.000,0.000000,0.324416,1.000,0.675584,1.000000,2.068241,2.084809,2.014405,2.122077,0.726060,0.699368,0.752753,85.0,0.294118,-0.705882,0.705882,2.066922,2.012480,2.122836,-60.0,60.0
25,L_E_1,R,40.0,8,8,1,7,0.125,0.022417,0.470895,0.875,0.529105,0.977583,2.058108,2.071213,2.001992,2.114224,0.721098,0.693482,0.748714,85.0,0.470588,-0.529412,0.529412,2.056691,2.000670,2.114280,-45.0,45.0
26,L_E_1,R,55.0,8,8,2,6,0.250,0.071478,0.590730,0.750,0.409270,0.928522,2.090856,2.042778,2.011218,2.170494,0.736321,0.699739,0.772903,85.0,0.647059,-0.352941,0.352941,2.088239,2.013227,2.166046,-30.0,30.0
27,L_E_1,R,70.0,8,8,4,4,0.500,0.215213,0.784787,0.500,0.215213,0.784787,2.091320,2.099781,2.040180,2.142460,0.737239,0.712405,0.762074,85.0,0.823529,-0.176471,0.176471,2.090158,2.038889,2.142715,-15.0,15.0
28,L_E_1,R,100.0,8,8,7,1,0.875,0.529105,0.977583,0.125,0.022417,0.470895,2.131676,2.146746,2.069356,2.193995,0.756123,0.726699,0.785547,85.0,1.176471,0.176471,0.176471,2.130002,2.068243,2.193606,15.0,-15.0
29,L_E_1,R,115.0,8,8,5,3,0.625,0.305738,0.863158,0.375,0.136842,0.694262,2.213477,2.136843,2.049518,2.377437,0.789816,0.718514,0.861118,85.0,1.352941,0.352941,0.352941,2.202991,2.051382,2.365804,30.0,-30.0

## Psychometric fitting setup

The notebook attempts Wichmann-lab `psignifit` first when available and compatible. If not, it prints installation guidance and uses the scipy logistic fallback on physical stimulus values.

## Psychometric model: lapse-aware yes/no fit

Each subject-by-finger psychometric function is fitted to **P(y=1)** -- the probability that the participant judged the **comparison** stimulus C as stiffer than the fixed **standard** S = 85 (response in `response_comparison_greater`; this is the participant's perceptual judgement, **not** percent-correct, side, order, or physical truth).

Because this is a yes/no probability (not a 2AFC percent-correct curve with a fixed guess rate), we fit a **lapse-aware sigmoid with four free parameters** (`mu`, `scale`, `lapse_low`, `lapse_high`):

$$P(y=1) = \lambda_	ext{low} + (1 - \lambda_	ext{low} - \lambda_	ext{high})\,F(\delta;\ \mu,\ 	ext{scale}),\qquad \delta = C - 85$$

where $F$ is a monotonic logistic sigmoid.

**Fitter used:** `psignifit` when installed (preferred); otherwise the custom lapse-aware maximum-likelihood fitter (`fit_with_scipy_logistic`). The fitter for each fit is recorded in the `fit_method` / `psignifit_status` columns.

**Derived quantities** (the fit is in comparison-stiffness units, so these equal the delta-space definitions):
- **PSE** = comparison value where P(y=1)=0.5; **Bias** = PSE - 85 = delta at P(y=1)=0.5 (`pse_delta_from_standard`).
- **JND** = (x75 - x25)/2, where x25/x75 are where the curve reaches 0.25/0.75. Because of the lapse asymptotes, 0.25/0.75 are only attainable within `[lapse_low, 1 - lapse_high]`; when they are not, PSE/JND are returned as NaN and flagged in `fit_warning` (`pse_outside_lapse_range` / `jnd_quantile_outside_lapse_range`) rather than reported as invalid.

In [265]:
PSIGNIFIT_AVAILABLE, PSIGNIFIT_STATUS = pf.check_psignifit_available()
print(PSIGNIFIT_STATUS)
if not PSIGNIFIT_AVAILABLE:
    print("Optional psignifit install example: pip install psignifit")
    print("Continuing with scipy logistic fallback fits.")

psignifit import succeeded (version=unknown)

## 8. Subject x finger psychometric fits

In [266]:
# Fit per subject/finger first (ALL subjects, incl. pilots — kept for the
# individual curves). The GROUP-level fits below then pool ONLY valid subjects'
# trials, so pilot/protocol subjects (*_P) and band-pass-disqualified subjects
# (PSE outside 25-145) do not contaminate the experiment-group result.
pse_jnd_by_subject_finger = pf.fit_conditions(
    psychometric_input_by_subject_finger, ["subject_id", "finger_condition"], PSIGNIFIT_AVAILABLE
)
pf.save_csv(pse_jnd_by_subject_finger, OUTPUT_ROOT, "pse_jnd_by_subject_finger.csv")

# Valid subject/finger fits for the selected all/group analysis. The selection has already
# removed other cohorts/subjects, so keep both experiment and protocol subjects here.
# Only the PSE reliability band excludes a subject/finger from all-level pooling.
valid_group_fits = pse_jnd_by_subject_finger.copy()
if "excluded_from_group_analysis" in valid_group_fits.columns:
    valid_group_fits = valid_group_fits[~valid_group_fits["excluded_from_group_analysis"].astype(bool)]
_valid_keys = set(valid_group_fits["subject_id"].astype(str) + "||" + valid_group_fits["finger_condition"].astype(str))
_trial_key = combined_success_trials["subject_id"].astype(str) + "||" + combined_success_trials["finger_condition"].astype(str)
group_trials = combined_success_trials[_trial_key.isin(_valid_keys)].copy()
print(
    f"All/group analysis for {DATA_SELECTION} uses {group_trials['subject_id'].nunique()} selected subjects "
    f"({len(group_trials)} of {len(combined_success_trials)} trials after the PSE reliability band)."
)

psychometric_input_subject_pooled = pf.make_psychometric_input(group_trials, ["subject_id"])
psychometric_input_group_by_finger = pf.make_psychometric_input(group_trials, ["finger_condition"])
all_pooled_trials = group_trials.copy()
all_pooled_trials["group"] = "all_pooled"
psychometric_input_group_all_pooled = pf.make_psychometric_input(all_pooled_trials, ["group"])

pf.save_csv(psychometric_input_subject_pooled, OUTPUT_ROOT, "psychometric_input_subject_pooled.csv")
pf.save_csv(psychometric_input_group_by_finger, OUTPUT_ROOT, "psychometric_input_group_by_finger.csv")
pf.save_csv(psychometric_input_group_all_pooled, OUTPUT_ROOT, "psychometric_input_group_all_pooled.csv")

(
    pse_jnd_subject_pooled,
    pse_jnd_group_by_finger,
    pse_jnd_group_all_pooled,
) = pf.fit_conditions_many(
    [
        (psychometric_input_subject_pooled, ["subject_id"]),
        (psychometric_input_group_by_finger, ["finger_condition"]),
        (psychometric_input_group_all_pooled, ["group"]),
    ],
    PSIGNIFIT_AVAILABLE,
)

pf.save_csv(pse_jnd_subject_pooled, OUTPUT_ROOT, "pse_jnd_subject_pooled.csv")
pf.save_csv(pse_jnd_group_by_finger, OUTPUT_ROOT, "pse_jnd_group_by_finger.csv")
pf.save_csv(pse_jnd_group_all_pooled, OUTPUT_ROOT, "pse_jnd_group_all_pooled.csv")
display(pse_jnd_by_subject_finger)

All/group analysis for ('N_E', 'L_E') uses 35 selected subjects (8704 of 9216 trials after the PSE reliability band).

,subject_id,finger_condition,fit_method,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_se,jnd_ci95_lower,jnd_ci95_upper,weber_fraction,jnd_over_standard,x25,x75,slope_at_pse,lapse_rate,lapse_rate_ci95_lower,lapse_rate_ci95_upper,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,n_bootstrap,bootstrap_method,deviance,aic,psignifit_status,neg_log_likelihood,lapse_rate_se,n_bootstrap_effective_pse,n_bootstrap_effective_jnd,mu,scale,standard_value,comparison_min,comparison_max,experiment_group,experiment_group_label,setup_factor,setup_label,protocol_group,protocol_group_label,success_label,workspace_setup,workspace_width_cm,workspace_height_cm,workspace_label,protocol_factor,sex_factor,age_years,age_group,pse_delta_comparison_minus_standard,pse_delta_standard_minus_comparison,abs_pse_delta_from_standard,pse_in_valid_band,excluded_from_group_analysis,group_exclusion_reason,pse_delta_se,jnd_over_standard_ci95_lower,jnd_over_standard_ci95_upper
0,L_E_1,I,scipy_logistic_fallback,91.108696,9.009330,70.408383,100.869088,6.108696,-14.591617,15.869088,1.0,0.497746,14.535883,5.846663,0.812416,18.324958,0.171010,0.171010,76.918570,105.990336,0.019068,0.035741,0.000000,0.200000,0.000000,0.035741,ok,,64,8,200,parametric_binomial,3.519438,44.539848,psignifit_failed: 'dict' object has no attribu...,18.269924,0.061682,200,200,90.172331,12.625223,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,6.108696,-6.108696,6.108696,True,False,,9.009330,0.009558,0.215588
1,L_E_1,M,scipy_logistic_fallback,82.438040,9.059173,66.808820,99.055071,-2.561960,-18.191180,14.055071,1.0,0.777328,16.756857,6.174225,0.774389,19.882109,0.197139,0.197139,65.681183,99.194897,0.016390,0.000000,0.000000,0.197970,0.000000,0.000000,ok,,64,8,200,parametric_binomial,4.930972,48.044374,psignifit_failed: 'dict' object has no attribu...,20.022187,0.057824,200,200,82.438040,15.252749,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-2.561960,2.561960,2.561960,True,False,,9.059173,0.009110,0.233907
2,L_E_1,P,scipy_logistic_fallback,69.531903,5.344104,56.320824,84.286972,-15.468097,-28.679176,-0.713028,0.0,0.003799,1.086504,5.054087,0.845586,21.479602,0.012782,0.012782,68.695145,70.868153,0.302197,0.241667,0.062845,0.312763,0.041667,0.200000,warning,high_lapse_estimate,64,8,200,parametric_binomial,4.139365,63.360759,psignifit_failed: 'dict' object has no attribu...,27.680379,0.056546,200,200,69.277613,0.600002,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-15.468097,15.468097,15.468097,True,False,,5.344104,0.009948,0.252701
3,L_E_1,R,scipy_logistic_fallback,68.767526,9.326705,54.993778,91.465298,-16.232474,-30.006222,6.465298,1.0,0.081784,19.096955,9.318958,1.048644,34.840626,0.224670,0.224670,54.574880,92.768789,0.017165,0.200000,0.000000,0.325469,0.000000,0.200000,warning,high_lapse_estimate,64,8,200,parametric_binomial,9.201238,79.512986,psignifit_failed: 'dict' object has no attribu...,35.756493,0.076443,200,200,63.187550,10.923445,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-16.232474,16.232474,16.232474,True,False,,9.326705,0.012337,0.409890
4,L_E_10,I,scipy_logistic_fallback,90.499935,12.320023,69.479502,113.654648,5.499935,-15.520498,28.654648,1.0,0.655292,30.808008,13.547575,1.204485,44.997789,0.362447,0.362447,66.782550,128.398565,0.010657,0.241262,0.000000,0.386383,0.041262,0.200000,warning,high_lapse_estimate,64,8,200,parametric_binomial,2.699994,72.506399,psignifit_failed: 'dict' object has no attribu...,32.253199,0.096444,200,200,83.271772,17.019583,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,5.499935,-5.499935,5.499935,True,False,,12.320023,0.014170,0.529386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,N_E_8,R,scipy_logistic_fallback,76.268076,9.567909,60.643636,98.627039,-8.731924,-24.356364,13.627039,1.0,0.361439,19.083737,8.507041,1.051205,30.059820,0.224515,0.224515,59.632160,97.799634,0.015381,0.137601,0.000000,0.294252,0.000000,0.137601,ok,,64,8,200,parametric_binomial,10.756501,62.361922,psignifit_failed: 'dict' object has no attribu...,27.180961,0.078949,200,200,71.871172,13.660790,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-8.731924,8.731924,8.731924,True,False,,9.567909,0.012367,0.353645
140,N_E_9,I,scipy_logistic_fallback,98.315497,8.017938,78.319522,109.383281,13.315497,-6.680478,24.383281,1.0,0.096771,15.669795,8.117940,0.912996,28.842888,0.184351,0.184351,81.940831,113.280421,0.018612,0.181122,0.000000,0.354165,0.112425,0.068697,ok,,64,8,200,parametric_binomial,3.419721,62.731358,psignifit_failed: 'dict' object has no attribu...,27.365679,0.095703,200,200,99.487990,10.968099,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,13.315497,-13.315497,13.315497,True,False,,8.017938,0.010741,0.339328
141,N_E_9,M,scipy_logistic_fallback,90.040196,10.117012,69.453000,105.221116,5.040196,-15.547000,20.221116,1.0,0.618350,23.666748,8.144389,1.231324,30.465098,0.278432,0.278432,66.373448,113.706944,0.011605,0.000000,0.000000,0.260208,0.000000,0.000000,ok,,64,8,200,parametric_binomial,11.235496,62.470214,psignifit_failed: 'dict' object has no attribu...,27.235107,0.086961,200,200,90.040196,21.542402,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,5.040196,-5.040196,5.040196,True,False,,10.117012,0.014486,0.358413
142,N_E_9,P,scipy_logistic_fallback,83.009517,12.762726,58.337715,104.756591,-1.990483,-26.662285,19.756591,1.0,0.876064,30.792606,12.936019,1.218410,46.347568,0.362266,0.362266,55.503978,117.089190,0.009398,0.121862,0.000000,0.387811,0.000000,0.121862,ok,,64,8,200,parametric_binomial,2.200644,73.388440,psignifit_failed: 'dict' object has no attribu...,32.694220,0.115892,200,200,76.609940,22.908915,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-1.990483,1.990483,1.990483,True,False,,12.762726,0.014334,0.545266
143,N_E_9,R,scipy_logistic_fallback,82.788515,14.947096,55.000599,111.395972,-2.211485,-29.999401,26.395972,1.0,0.882379,49.952987,21.738579,1.473942,81.382886,0.587682,0.587682,45.664004,145.569978,0.006562,0.200000,0.000000,0.400000,0.000000,0.200000,warning,high_lapse_estimate,64,8,200,parametric_binomial,5.299510,84.608620,psignifit_failed: 'dict' object has no attribu...,38.304310,0.096929,200,200,68.192656,28.573075,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-2.211485,2.211485,2.211485,True,False,,14.947096,0.017340,0.957446

## 9. Subject-level pooled-across-fingers fits

In [267]:
# Fitted above in one shared parallel pool; display the subject-pooled result.
display(pse_jnd_subject_pooled)

,subject_id,fit_method,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_se,jnd_ci95_lower,jnd_ci95_upper,weber_fraction,jnd_over_standard,x25,x75,slope_at_pse,lapse_rate,lapse_rate_ci95_lower,lapse_rate_ci95_upper,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,n_bootstrap,bootstrap_method,deviance,aic,psignifit_status,neg_log_likelihood,lapse_rate_se,n_bootstrap_effective_pse,n_bootstrap_effective_jnd,mu,scale,standard_value,comparison_min,comparison_max,experiment_group,experiment_group_label,setup_factor,setup_label,protocol_group,protocol_group_label,success_label,workspace_setup,workspace_width_cm,workspace_height_cm,workspace_label,protocol_factor,sex_factor,age_years,age_group,pse_delta_comparison_minus_standard,pse_delta_standard_minus_comparison,abs_pse_delta_from_standard,pse_in_valid_band,excluded_from_group_analysis,group_exclusion_reason,pse_delta_se,jnd_over_standard_ci95_lower,jnd_over_standard_ci95_upper
0,L_E_1,scipy_logistic_fallback,72.982062,3.982017,66.470491,81.859043,-12.017938,-18.529509,-3.140957,0.0,0.002544,15.593722,4.484891,1.488443,20.789256,0.183456,0.183456,61.392979,92.580424,0.021021,0.200000,0.140765,0.243075,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,4.605021,223.708875,psignifit_failed: 'dict' object has no attribu...,107.854438,0.025140,200,200,68.425702,8.919599,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-12.017938,12.017938,12.017938,True,False,,3.982017,0.017511,0.244579
1,L_E_10,scipy_logistic_fallback,89.137498,4.516684,79.310970,96.877307,4.137498,-5.689030,11.877307,1.0,0.359642,20.865031,3.199417,12.760475,24.252867,0.245471,0.245471,69.035811,110.765874,0.013357,0.052460,0.000000,0.215762,0.000000,0.052460,ok,,256,8,200,parametric_binomial,18.025129,211.072580,psignifit_failed: 'dict' object has no attribu...,101.536290,0.059879,200,200,87.177755,17.680500,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,4.137498,-4.137498,4.137498,True,False,,4.516684,0.150123,0.285328
2,L_E_11,scipy_logistic_fallback,93.144585,6.128952,82.421825,107.402790,8.144585,-2.578175,22.402790,1.0,0.183891,44.728077,7.664089,24.568362,56.075815,0.526213,0.526213,59.903170,149.359323,0.007329,0.200000,0.000000,0.359510,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,6.266557,292.104509,psignifit_failed: 'dict' object has no attribu...,142.052254,0.084326,200,200,80.075402,25.584430,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,8.144585,-8.144585,8.144585,True,False,,6.128952,0.289040,0.659715
3,L_E_12,scipy_logistic_fallback,84.378494,4.755407,73.205238,91.726926,-0.621506,-11.794762,6.726926,1.0,0.896017,15.617595,3.278818,6.860610,19.494511,0.183736,0.183736,69.801969,101.037159,0.018107,0.086223,0.007629,0.183250,0.000000,0.086223,ok,,256,8,200,parametric_binomial,7.162937,180.514350,psignifit_failed: 'dict' object has no attribu...,86.257175,0.042581,200,200,82.011760,12.503815,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-0.621506,0.621506,0.621506,True,False,,4.755407,0.080713,0.229347
4,L_E_14,scipy_logistic_fallback,78.513260,6.646040,66.875849,91.400963,-6.486740,-18.124151,6.400963,1.0,0.329049,36.952520,8.404300,12.987496,46.727470,0.434736,0.434736,51.050553,124.955594,0.008871,0.200000,0.028073,0.392201,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,6.538409,294.326289,psignifit_failed: 'dict' object has no attribu...,143.163144,0.079203,200,200,67.716032,21.136817,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-6.486740,6.486740,6.486740,True,False,,6.646040,0.152794,0.549735
5,L_E_15,scipy_logistic_fallback,92.533620,5.786759,81.797460,105.301645,7.533620,-3.202540,20.301645,1.0,0.192960,40.287282,6.614803,22.364624,48.162853,0.473968,0.473968,62.592555,143.167119,0.008137,0.200000,0.000000,0.342497,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,7.715316,282.257605,psignifit_failed: 'dict' object has no attribu...,137.128802,0.076374,200,200,80.762002,23.044299,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,7.533620,-7.533620,7.533620,True,False,,5.786759,0.263113,0.566622
6,L_E_16,scipy_logistic_fallback,101.242395,8.825581,88.329777,121.393207,16.242395,3.329777,36.393207,0.0,0.065713,78.733793,16.954305,42.213402,107.263524,0.926280,0.926280,42.728306,200.195892,0.004163,0.200000,0.000000,0.400000,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,4.032664,328.743217,psignifit_failed: 'dict' object has no attribu...,160.371608,0.099677,200,200,78.237017,45.035677,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,16.242395,-16.242395,16.242395,True,False,,8.825581,0.496628,1.261924
7,L_E_17,scipy_logistic_fallback,91.730319,5.032450,81.138653,100.779185,6.730319,-3.861347,15.779185,1.0,0.181097,23.551087,4.091558,12.945636,27.725152,0.277072,0.277072,74.227410,121.329583,0.013919,0.200000,0.077533,0.244112,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,8.891435,219.276014,psignifit_failed: 'dict' object has no attribu...,105.638007,0.039456,200,200,84.848882,13.471206,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,6.730319,-6.730319,6.730319,True,False,,5.032450,0.152302,0.326178
8,L_E_18,scipy_logistic_fallback,84.178822,6.428939,73.312391,97.104797,-0.821178,-11.687609,12.104797,1.0,0.898361,41.951610,7.535111,23.416677,51.614347,0.493548,0.493548,53.000847,136.904066,0.007814,0.200000,0.000000,0.385424,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,3.415379,295.837134,psignifit_failed: 'dict' object has no attribu...,143.918567,0.086902,200,200,71.920901,23.996293,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-0.821178,0.821178,0.821178,True,False,,6.428939,0.275490,0.607228
9,L_E_19,scipy_logistic_fallback,83.684395,209.123553,-579.351498,490.438031,-1.315605,-664.351498,405.438031,1.0,0.994981,230.257894,840.591124,61.048225,2730.244573,2.708916,2.708916,-91.408479,369.107309,0.001425,0.227723,0.019236,0.400000,0.027723,0.200000,warning,high_lapse_estimate,64,8,200,parametric_binomial,15.594643,95.986060,psignifit_failed: 'dict' object has no attribu...,43.993030,0.090096,200,200,25.252441,128.765963,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-1.315605,1.315605,1.315605,True,False,,209.123553,0.718214,32.120524
10,L_E_2,scipy_logistic_fallback,83.079390,6.736511,71.173627,89.572471,-1.920610,-13.826373,4.572471,1.0,0.775564,6.343845,3.102050,0.694027,9.344505,0.074633,0.074633,76.967126,89.654816,0.043930,0.052360,0.010139,0.089230,0.000000,0.052360,ok,,256,8,200,parametric_binomial,0.868659,87.518415,psignifit_failed: 'dict' object has no attribu...,39.759207,0.020215,200,200,82.484652,5.376437,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-1.920610,1.920610,1.920610,True,False,,6.736511,0.008165,0.109935
11,L_E_3,scipy_logistic_fallback,86.165097,6.230578,72.943556,97.540612,1.165097,-12.056444,12.540612,1.0,0.851663,30.782331,6.300262,12.283237,37.082532,0.362145,0.362145,63.288007,124.852669,0.010649,0.200000,0.023682,0.301316,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,7.717789,268.250161,psignifit_failed: 'dict' object has no attribu...,130.125081,0.058377,200,200,77.170749,17.607473,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,1.165097,-1.165097,1.165097,True,False,,6.230578,0.144509,0.436265
12,L_E_4,scipy_logistic_fallback,97.212190,4.778970,87.801590,106.456190,12.212190,2.801590,21.456190,0.0,0.010607,28.486699,4.649927,14.727456,33.328631,0.335138,0.335138,76.041189,133.014587,0.011507,0.200000,0.015363,0.255839,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,10.063746,229.687546,psignifit_failed: 'dict' object has no attribu...,110.843773,0.053831,200,200,88.888607,16.294373,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,12.212190,-12.212190,12.212190,True,False,,4.778970,0.173264,0.392102
13,L_E_5,scipy_logistic_fallback,83.331776,5.767148,71.012083,91.524376,-1.668224,-13.987917,6.524376,1.0,0.772380,17.474201,4.866181,1.490206,22.936847,0.205579,0.205579,69.023354,103.971756,0.017482,0.168776,0.083627,0.226674,0.000000,0.168776,warning,high_lapse_estimate,256,8,200,parametric_binomial,3.156086,204.909774,psignifit_failed: 'dict' object has no attribu...,98.454887,0.036482,200,200,78.638465,11.396696,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-1.668224,1.668224,1.668224,True,False,,5.767148,0.017532,0.269845
14,L_E_6,scipy_logistic_fallback,94.695258,5.923784,84.441679,108.706619,9.695258,-0.558321,23.706619,1.0,0.101700,43.782314,7.346257,23.077737,52.051925,0.515086,0.515086,62.156724,149.721352,0.007487,0.200000,0.000000,0.355453,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,12.272425,288.558389,psignifit_failed: 'dict' object has no attribu...,140.279195,0.084342,200,200,81.902420,25.043455,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,9.695258,-9.695258,9.695258,True,False,,5.923784,0.271503,0.612376
15,L_E_7,scipy_logistic_fallback,88.280448,3.113254,82.604787,93.654071,3.280448,-2.395213,8.654071,1.0,0.292018,15.105443,1.934192,9.908565,17.408298,0.177711,0.177711,73.175005,103.385891,0.018182,0.000000,0.000000,0.078845,0.000000,0.000000,ok,,256,8,200,parametric_binomial,5.744454,151.215425,psignifit_failed: 'dict' object has no attribu...,71.607712,0.023634,200,200,88.280448,13.749567,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,3.280448,-3.280448,3.280448,True,False,,3.113254,0.116571,0.204804
16,L_E_8,scipy_logistic_fallback,82.817845,6.623514,71.495086,97.019597,-2.182155,-13.504914,12.019597,1.0,0.741811,44.494824,8.033478,24.210457,55.062939,0.523469,0.523469,49.749781,138.739430,0.007367,0.200000,0.000000,0.395359,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,17.795451,302.812797,psignifit_failed: 'dict' object has no attribu...,147.406398,0.091955,200,200,69.816817,25.451010,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,-2.182155,2.182155,2.182155,True,False,,6.623514,0.284829,0.647799
17,L_E_9,scipy_logistic_fallback,86.351692,4.067423,78.467483,93.262626,1.351692,-6.532517,8.262626,1.0,0.739646,14.408231,3.139098,6.192362,19.256802,0.169509,0.169509,72.196815,101.013278,0.019455,0.079913,0.000000,0.165144,0.028214,0.051699,ok,,256,8,200,parametric_binomial,4.022530,174.949856,psignifit_failed: 'dict' object has no attribu...,83.474928,0.044786,200,200,85.748373,11.815454,85.0,25.0,145.0,L_E,lab_experiment,airsled,with_airsled_L,NaN,other,unknown_success,L,60.0,60.0,L workspace (60x60 cm),experiment,unknown_sex,NaN,unknown_age,1.351692,-1.351692,1.351692,True,False,,4.067423,0.072851,0.226551
18,N_E_1,scipy_logistic_fallback,86.829680,5.918757,72.806318,97.155295,1.829680,-12.193682,12.155295,1.0,0.757221,24.456903,5.197481,9.005231,30.274055,0.287728,0.287728,68.653578,117.567385,0.013403,0.200000,0.087986,0.260626,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,6.312116,235.905771,psignifit_failed: 'dict' object has no attribu...,113.952886,0.041654,200,200,79.683570,13.989332,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,1.829680,-1.829680,1.829680,True,False,,5.918757,0.105944,0.356165
19,N_E_12,scipy_logistic_fallback,71.737284,3.529112,67.043943,81.097044,-13.262716,-17.956057,-3.902956,0.0,0.000171,9.066617,6.899630,1.088496,24.446853,0.106666,0.106666,64.224232,82.357465,0.036598,0.306663,0.179075,0.356786,0.106663,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,6.627437,279.847944,psignifit_failed: 'dict' object has no attribu...,135.923972,0.046034,200,200,70.477594,4.650302,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-13.262716,13.262716,13.262716,True,False,,3.529112,0.012806,0.287610
20,N_E_13,scipy_logistic_fallback,87.779672,3.702957,80.066827,93.827998,2.779672,-4.933173,8.827998,1.0,0.452856,14.502497,2.472288,8.975788,17.661831,0.170618,0.170618,73.596788,102.601782,0.019098,0.033332,0.000000,0.125508,0.000000,0.033332,ok,,256,8,200,parametric_binomial,4.118693,155.590898,psignifit_failed: 'dict' object has no attribu...,73.795449,0.034671,200,200,86.907699,12.639120,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,2.779672,-2.779672,2.779672,True,False,,3.702957,0.105598,0.207786
21,N_E_14,scipy_logistic_fallback,82.635704,5.109888,70.788596,89.063063,-2.364296,-14.211404,4.063063,1.0,0.643586,12.584724,3.875384,1.167593,16.003618,0.148056,0.148056,70.914024,96.083471,0.022494,0.088149,0.030700,0.161631,0.000000,0.088149,ok,,256,8,200,parametric_binomial,2.822383,158.787043,psignifit_failed: 'dict' object has no attribu...,75.393521,0.035575,200,200,80.688523,10.039758,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-2.364296,2.364296,2.364296,True,False,,5.109888,0.013736,0.188278
22,N_E_15,scipy_logistic_fallback,86.387133,6.117732,73.103305,96.532848,1.387133,-11.896695,11.532848,1.0,0.820626,32.709556,5.742497,17.457001,39.958281,0.384818,0.384818,56.425922,121.845033,0.008728,0.102794,0.000000,0.346398,0.000000,0.102794,ok,,256,8,200,parametric_binomial,4.905085,274.352827,psignifit_failed: 'dict' object has no attribu...,133.176414,0.098464,200,200,80.550033,25.361686,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,1.387133,-1.387133,1.387133,True,False,,6.117732,0.205376,0.470097
23,N_E_16,scipy_logistic_fallback,83.248354,6.727767,71.396117,97.121264,-1.751646,-13.603883,12.121264,1.0,0.794586,44.997006,8.447884,24.802256,56.484941,0.529377,0.529377,49.807074,139.801087,0.007285,0.200000,0.006273,0.400000,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,7.868961,300.226159,psignifit_failed: 'dict' object has no attribu...,146.113079,0.091738,200,200,70.100592,25.738258,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-1.751646,1.751646,1.751646,True,False,,6.727767,0.291791,0.664529
24,N_E_17,scipy_logistic_fallback,88.331540,20.123677,35.009515,117.596516,3.331540,-49.990485,32.596516,1.0,0.868509,136.110341,79.871717,70.858387,332.005726,1.601298,1.601298,-82.733434,189.487249,0.002408,0.200000,0.060126,0.398211,0.200000,0.000000,warning,high_lapse_estimate,192,8,200,parametric_binomial,5.321522,267.580570,psignifit_failed: 'dict' object has no attribu...,129.790285,0.074923,200,200,128.101882,77.855025,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,3.331540,-3.331540,3.331540,True,False,,20.123677,0.833628,3.905950
25,N_E_18,scipy_logistic_fallback,79.432106,4.333927,70.625358,85.279209,-5.567894,-14.374642,0.279209,1.0,0.198889,10.418743,3.419394,1.045862,13.712834,0.122573,0.122573,69.474683,90.312169,0.026843,0.061785,0.011207,0.119826,0.000000,0.061785,ok,,256,8,200,parametric_binomial,7.546631,135.347103,psignifit_failed: 'dict' object has no attribu...,63.673551,0.026954,200,200,78.284595,8.699943,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-5.567894,5.567894,5.567894,True,False,,4.333927,0.012304,0.161327
26,N_E_19,scipy_logistic_fallback,73.641747,5.249718,64.593727,84.707013,-11.358253,-20.406273,-0.292987,0.0,0.030496,23.736917,6.290469,2.364699,30.229202,0.279258,0.279258,56.000731,103.474566,0.013810,0.200000,0.116201,0.293887,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,4.174618,267.377100,psignifit_failed: 'dict' object has no attribu...,129.688550,0.044153,200,200,66.706012,13.577501,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-11.358253,11.358253,11.358253,True,False,,5.249718,0.027820,0.355638
27,N_E_2,scipy_logistic_fallback,75.555506,7.414985,62.290057,91.571924,-9.444494,-22.709943,6.571924,1.0,0.202768,54.841007,10.789882,33.810159,73.175633,0.645188,0.645188,34.798272,144.480287,0.005977,0.200000,0.000000,0.400000,0.000000,0.200000,warning,high_lapse_estimate,256,8,200,parametric_binomial,8.439922,320.013536,psignifit_failed: 'dict' object has no attribu...,156.006768,0.099182,200,200,59.531407,31.369020,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-9.444494,9.444494,9.444494,True,False,,7.414985,0.397767,0.860890
28,N_E_3,scipy_logistic_fallback,82.506888,5.602348,70.809231,89.245218,-2.493112,-14.190769,4.245218,1.0,0.656311,11.466456,4.161941,1.187116,15.235340,0.134899,0.134899,72.105925,95.038836,0.025027,0.110590,0.052672,0.179686,0.000000,0.110590,ok,,256,8,200,parametric_binomial,3.198183,158.348589,psignifit_failed: 'dict' object has no attribu...,75.174295,0.033167,200,200,80.320299,8.747212,85.0,25.0,145.0,N_E,natural_experiment,no_airsled,without_airsled_N,NaN,other,unknown_success,N,40.0,50.0,N workspace (40x50 cm),experiment,unknown_sex,NaN,unknown_age,-2.493112,2.493112,2.493112,True,False,,5.602348,0.013966,0.179239

## 10. Group-level fits by finger

Pools all valid trials across subjects within each finger condition.

In [268]:
# Fitted above in one shared parallel pool; display the finger-pooled result.
display(pse_jnd_group_by_finger)

,finger_condition,fit_method,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_se,jnd_ci95_lower,jnd_ci95_upper,weber_fraction,jnd_over_standard,x25,x75,slope_at_pse,lapse_rate,lapse_rate_ci95_lower,lapse_rate_ci95_upper,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,n_bootstrap,bootstrap_method,deviance,aic,psignifit_status,neg_log_likelihood,lapse_rate_se,n_bootstrap_effective_pse,n_bootstrap_effective_jnd,mu,scale,standard_value,comparison_min,comparison_max,experiment_group,experiment_group_label,setup_factor,setup_label,protocol_group,protocol_group_label,success_label,workspace_setup,workspace_width_cm,workspace_height_cm,workspace_label,protocol_factor,sex_factor,age_years,age_group,pse_delta_comparison_minus_standard,pse_delta_standard_minus_comparison,abs_pse_delta_from_standard,pse_in_valid_band,excluded_from_group_analysis,group_exclusion_reason,pse_delta_se,jnd_over_standard_ci95_lower,jnd_over_standard_ci95_upper
0,I,scipy_logistic_fallback,85.545648,1.888568,81.725831,88.743946,0.545648,-3.274169,3.743946,1.0,0.772641,26.867196,1.977367,22.835112,30.582390,0.316085,0.316085,63.545755,117.280148,0.011407,0.176124,0.122296,0.234393,0.005654,0.170470,warning,high_lapse_estimate,2176,8,200,parametric_binomial,5.023916,2061.393868,psignifit_failed: 'dict' object has no attribu...,1026.696934,0.028816,200,200,78.515691,17.333651,85.0,25.0,145.0,NaN,other,NaN,unknown_setup,NaN,other,unknown_success,NaN,NaN,NaN,unknown workspace,unknown_protocol,unknown_sex,NaN,unknown_age,0.545648,-0.545648,0.545648,True,False,,1.888568,0.268648,0.359793
1,M,scipy_logistic_fallback,83.829492,2.139011,79.670388,87.697760,-1.170508,-5.329612,2.697760,1.0,0.584228,27.150480,1.991699,22.981247,31.080661,0.319417,0.319417,62.271612,116.572573,0.011661,0.209426,0.139043,0.260022,0.022921,0.186505,warning,high_lapse_estimate,2176,8,200,parametric_binomial,1.538376,2112.783601,psignifit_failed: 'dict' object has no attribu...,1052.391800,0.029674,200,200,77.017003,16.224068,85.0,25.0,145.0,NaN,other,NaN,unknown_setup,NaN,other,unknown_success,NaN,NaN,NaN,unknown workspace,unknown_protocol,unknown_sex,NaN,unknown_age,-1.170508,1.170508,1.170508,True,False,,2.139011,0.270368,0.365655
2,P,scipy_logistic_fallback,82.297059,2.056042,78.162329,86.212346,-2.702941,-6.837671,1.212346,1.0,0.188633,23.737386,2.017728,19.280489,28.108161,0.279263,0.279263,63.056216,110.530988,0.013095,0.195255,0.147047,0.244599,0.017389,0.177866,warning,high_lapse_estimate,2176,8,200,parametric_binomial,1.724874,2014.526651,psignifit_failed: 'dict' object has no attribu...,1003.263325,0.026162,200,200,76.333460,14.752438,85.0,25.0,145.0,NaN,other,NaN,unknown_setup,NaN,other,unknown_success,NaN,NaN,NaN,unknown workspace,unknown_protocol,unknown_sex,NaN,unknown_age,-2.702941,2.702941,2.702941,True,False,,2.056042,0.226829,0.330684
3,R,scipy_logistic_fallback,84.436397,1.797666,80.775112,87.938851,-0.563603,-4.224888,2.938851,1.0,0.753886,24.627884,2.069060,20.281313,28.525376,0.289740,0.289740,65.308035,114.563803,0.013050,0.214098,0.152703,0.244199,0.021293,0.192804,warning,high_lapse_estimate,2176,8,200,parametric_binomial,2.091765,2014.959269,psignifit_failed: 'dict' object has no attribu...,1003.479634,0.023356,200,200,78.075894,14.338251,85.0,25.0,145.0,NaN,other,NaN,unknown_setup,NaN,other,unknown_success,NaN,NaN,NaN,unknown workspace,unknown_protocol,unknown_sex,NaN,unknown_age,-0.563603,0.563603,0.563603,True,False,,1.797666,0.238604,0.335593

## 11. Group-level all-pooled fit

In [269]:
# Fitted above in one shared parallel pool; display the all-pooled result.
display(pse_jnd_group_all_pooled)

,group,fit_method,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_se,jnd_ci95_lower,jnd_ci95_upper,weber_fraction,jnd_over_standard,x25,x75,slope_at_pse,lapse_rate,lapse_rate_ci95_lower,lapse_rate_ci95_upper,lapse_low,lapse_high,fit_quality,fit_warning,n_trials,n_stimulus_levels,n_bootstrap,bootstrap_method,deviance,aic,psignifit_status,neg_log_likelihood,lapse_rate_se,n_bootstrap_effective_pse,n_bootstrap_effective_jnd,mu,scale,standard_value,comparison_min,comparison_max,experiment_group,experiment_group_label,setup_factor,setup_label,protocol_group,protocol_group_label,success_label,workspace_setup,workspace_width_cm,workspace_height_cm,workspace_label,protocol_factor,sex_factor,age_years,age_group,pse_delta_comparison_minus_standard,pse_delta_standard_minus_comparison,abs_pse_delta_from_standard,pse_in_valid_band,excluded_from_group_analysis,group_exclusion_reason,pse_delta_se,jnd_over_standard_ci95_lower,jnd_over_standard_ci95_upper
0,all_pooled,scipy_logistic_fallback,83.977923,1.064203,81.961832,86.128506,-1.022077,-3.038168,1.128506,1.0,0.336846,25.589488,1.012319,23.805835,27.774275,0.301053,0.301053,63.544226,114.723201,0.012277,0.200627,0.166311,0.229512,0.017461,0.183166,warning,high_lapse_estimate,8704,8,200,parametric_binomial,0.911094,8185.540095,psignifit_failed: 'dict' object has no attribu...,4088.770048,0.017019,200,200,77.424462,15.578125,85.0,25.0,145.0,NaN,other,NaN,unknown_setup,NaN,other,unknown_success,NaN,NaN,NaN,unknown workspace,unknown_protocol,unknown_sex,NaN,unknown_age,-1.022077,1.022077,1.022077,True,False,,1.064203,0.280069,0.326756

## 12. Subject-average group analysis

Computes subject-level probabilities first, then averages subjects so each subject has equal weight. This complements trial-pooled group fits.

In [270]:
subject_average_group_by_finger = pf.subject_average_psychometric(combined_clean_trials, ["finger_condition"])
subject_average_group_all = pf.subject_average_psychometric(combined_clean_trials.assign(group="all_subject_average"), ["group"])
pf.save_csv(subject_average_group_by_finger, OUTPUT_ROOT, "subject_average_group_by_finger.csv")
pf.save_csv(subject_average_group_all, OUTPUT_ROOT, "subject_average_group_all_pooled.csv")
display(subject_average_group_by_finger.head(30))

,finger_condition,comparison_value,n_subjects,n_data_points,mean_p_comparison_greater,mean_p_comparison_less,median_p_comparison_greater,median_p_comparison_less,sem_p_comparison_greater,sem_p_comparison_less,p_comparison_greater_ci95_lower,p_comparison_greater_ci95_upper,p_comparison_less_ci95_lower,p_comparison_less_ci95_upper,total_trials,median_rt,mean_rt,rt_ci95_lower,rt_ci95_upper,mean_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,standard_value,comparison_over_standard,signed_delta_over_standard,abs_delta_over_standard,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s,delta_comparison_minus_standard,delta_standard_minus_comparison
0,I,25.0,36,288,0.076389,0.923611,0.0000,1.0000,0.028294,0.028294,0.020933,0.131845,0.868155,0.979067,288,1.946660,2.073341,1.978455,2.168227,0.708554,0.668401,0.748707,85.0,0.294118,-0.705882,0.705882,2.031052,1.951115,2.114264,-60.0,60.0
1,I,40.0,36,288,0.118056,0.881944,0.0000,1.0000,0.032254,0.032254,0.054839,0.181272,0.818728,0.945161,288,1.954245,2.040007,1.959474,2.120539,0.698069,0.662889,0.733249,85.0,0.470588,-0.529412,0.529412,2.009868,1.940390,2.081833,-45.0,45.0
2,I,55.0,36,288,0.187500,0.812500,0.1250,0.8750,0.035739,0.035739,0.117451,0.257549,0.742451,0.882549,288,1.959736,2.150625,2.012711,2.288540,0.728234,0.680530,0.775937,85.0,0.647059,-0.352941,0.352941,2.071419,1.974924,2.172628,-30.0,30.0
3,I,70.0,36,288,0.357639,0.642361,0.3750,0.6250,0.032334,0.032334,0.294265,0.421013,0.578987,0.705735,288,1.963639,2.199322,2.071607,2.327038,0.750546,0.702592,0.798499,85.0,0.823529,-0.176471,0.176471,2.118155,2.018980,2.222202,-15.0,15.0
4,I,100.0,36,288,0.642361,0.357639,0.6250,0.3750,0.034197,0.034197,0.575334,0.709388,0.290612,0.424666,288,1.955677,2.121517,2.021378,2.221655,0.728053,0.689896,0.766209,85.0,1.176471,0.176471,0.176471,2.071043,1.993508,2.151594,15.0,-15.0
5,I,115.0,36,288,0.684028,0.315972,0.7500,0.2500,0.033955,0.033955,0.617476,0.750579,0.249421,0.382524,288,1.983519,2.165292,2.062915,2.267669,0.739234,0.702932,0.775536,85.0,1.352941,0.352941,0.352941,2.094331,2.019665,2.171756,30.0,-30.0
6,I,130.0,36,288,0.802083,0.197917,0.8125,0.1875,0.026528,0.026528,0.750088,0.854079,0.145921,0.249912,288,1.972429,2.098901,2.009948,2.187854,0.722331,0.685213,0.759448,85.0,1.529412,0.529412,0.529412,2.059227,1.984194,2.137097,45.0,-45.0
7,I,145.0,36,288,0.784722,0.215278,0.8750,0.1250,0.033263,0.033263,0.719527,0.849918,0.150082,0.280473,288,1.914365,2.096609,1.991419,2.201799,0.712463,0.674605,0.750321,85.0,1.705882,0.705882,0.705882,2.039007,1.963257,2.117680,60.0,-60.0
8,M,25.0,36,288,0.097222,0.902778,0.0000,1.0000,0.033818,0.033818,0.030940,0.163505,0.836495,0.969060,288,1.964664,2.042461,1.958751,2.126170,0.697859,0.660953,0.734764,85.0,0.294118,-0.705882,0.705882,2.009445,1.936638,2.084990,-60.0,60.0
9,M,40.0,36,288,0.135417,0.864583,0.0000,1.0000,0.037059,0.037059,0.062781,0.208053,0.791947,0.937219,288,1.975033,2.058867,1.983599,2.134135,0.705748,0.670446,0.741049,85.0,0.470588,-0.529412,0.529412,2.025361,1.955110,2.098136,-45.0,45.0
10,M,55.0,36,288,0.211806,0.788194,0.1250,0.8750,0.035502,0.035502,0.142221,0.281390,0.718610,0.857779,288,1.972116,2.066824,1.990727,2.142920,0.709218,0.675189,0.743247,85.0,0.647059,-0.352941,0.352941,2.032401,1.964404,2.102752,-30.0,30.0
11,M,70.0,36,288,0.347222,0.652778,0.3125,0.6875,0.035604,0.035604,0.277439,0.417006,0.582994,0.722561,288,1.967503,2.221995,1.966147,2.477843,0.737195,0.688631,0.785759,85.0,0.823529,-0.176471,0.176471,2.090065,1.990989,2.194072,-15.0,15.0
12,M,100.0,36,288,0.652778,0.347222,0.6875,0.3125,0.029927,0.029927,0.594121,0.711434,0.288566,0.405879,288,1.979221,2.136920,2.042263,2.231577,0.733320,0.694488,0.772152,85.0,1.176471,0.176471,0.176471,2.081981,2.002683,2.164420,15.0,-15.0
13,M,115.0,36,288,0.704861,0.295139,0.7500,0.2500,0.038945,0.038945,0.628530,0.781193,0.218807,0.371470,288,1.956150,2.165430,2.031144,2.299717,0.736445,0.689906,0.782985,85.0,1.352941,0.352941,0.352941,2.088498,1.993528,2.187993,30.0,-30.0
14,M,130.0,36,288,0.753472,0.246528,0.7500,0.2500,0.031688,0.031688,0.691364,0.815580,0.184420,0.308636,288,1.961534,2.109206,2.008825,2.209586,0.722803,0.682795,0.762810,85.0,1.529412,0.529412,0.529412,2.060199,1.979403,2.144293,45.0,-45.0
15,M,145.0,36,288,0.791667,0.208333,0.8750,0.1250,0.035215,0.035215,0.722646,0.860688,0.139312,0.277354,288,1.941903,2.084039,2.014227,2.153852,0.714337,0.681188,0.747487,85.0,1.705882,0.705882,0.705882,2.042832,1.976223,2.111687,60.0,-60.0
16,P,25.0,36,288,0.083333,0.916667,0.0000,1.0000,0.033777,0.033777,0.017131,0.149536,0.850464,0.982869,288,1.999402,2.053214,1.984000,2.122429,0.704957,0.675240,0.734674,85.0,0.294118,-0.705882,0.705882,2.023760,1.964505,2.084801,-60.0,60.0
17,P,40.0,36,288,0.114583,0.885417,0.0000,1.0000,0.036041,0.036041,0.043942,0.185224,0.814776,0.956058,288,1.936764,2.062839,1.988014,2.137665,0.707868,0.675389,0.740347,85.0,0.470588,-0.529412,0.529412,2.029660,1.964797,2.096664,-45.0,45.0
18,P,55.0,36,288,0.208333,0.791667,0.1875,0.8125,0.032657,0.032657,0.144326,0.272341,0.727659,0.855674,288,2.022405,2.124751,2.038251,2.211251,0.732297,0.698454,0.766139,85.0,0.647059,-0.352941,0.352941,2.079852,2.010643,2.151443,-30.0,30.0
19,P,70.0,36,288,0.336806,0.663194,0.3750,0.6250,0.027647,0.027647,0.282617,0.390994,0.609006,0.717383,288,2.006902,2.098663,2.014322,2.183005,0.723032,0.687637,0.758427,85.0,0.823529,-0.176471,0.176471,2.060672,1.989010,2.134915,-15.0,15.0
20,P,100.0,36,288,0.677083,0.322917,0.6250,0.3750,0.028336,0.028336,0.621544,0.732623,0.267377,0.378456,288,2.002660,2.216910,2.095899,2.337920,0.761496,0.717535,0.805457,85.0,1.176471,0.176471,0.176471,2.141478,2.049376,2.237718,15.0,-15.0
21,P,115.0,36,288,0.750000,0.250000,0.7500,0.2500,0.029881,0.029881,0.691434,0.808566,0.191434,0.308566,288,1.975062,2.092438,2.002928,2.181947,0.719295,0.684199,0.754391,85.0,1.352941,0.352941,0.352941,2.052986,1.982184,2.126316,30.0,-30.0
22,P,130.0,36,288,0.770833,0.229167,0.7500,0.2500,0.033222,0.033222,0.705719,0.835948,0.164052,0.294281,288,1.964075,2.145760,2.053627,2.237892,0.733551,0.701668,0.765434,85.0,1.529412,0.529412,0.529412,2.082462,2.017114,2.149928,45.0,-45.0
23,P,145.0,36,288,0.788194,0.211806,0.8750,0.1250,0.040403,0.040403,0.709004,0.867385,0.132615,0.290996,288,1.946219,2.061814,1.985938,2.137690,0.709146,0.675291,0.743001,85.0,1.705882,0.705882,0.705882,2.032255,1.964604,2.102235,60.0,-60.0
24,R,25.0,36,288,0.072917,0.927083,0.0000,1.0000,0.032419,0.032419,0.009376,0.136457,0.863543,0.990624,288,2.014139,2.063234,1.999320,2.127147,0.711672,0.682599,0.740744,85.0,0.294118,-0.705882,0.705882,2.037394,1.979015,2.097496,-60.0,60.0
25,R,40.0,36,288,0.104167,0.895833,0.0000,1.0000,0.030901,0.030901,0.043601,0.164732,0.835268,0.956399,288,1.975440,2.125881,2.015241,2.236521,0.721340,0.685661,0.757020,85.0,0.470588,-0.529412,0.529412,2.057189,1.985083,2.131913,-45.0,45.0
26,R,55.0,36,288,0.187500,0.812500,0.1250,0.8750,0.039055,0.039055,0.110952,0.264048,0.735952,0.889048,288,2.022526,2.146010,2.031879,2.260141,0.733565,0.699309,0.767822,85.0,0.647059,-0.352941,0.352941,2.082492,2.012362,2.155067,-30.0,30.0
27,R,70.0,36,288,0.315972,0.684028,0.2500,0.7500,0.031688,0.031688,0.253864,0.378080,0.621920,0.746136,288,2.006559,2.185317,2.085679,2.284955,0.753971,0.718240,0.789703,85.0,0.823529,-0.176471,0.176471,2.125423,2.050820,2.202741,-15.0,15.0
28,R,100.0,36,288,0.642361,0.357639,0.6875,0.3125,0.035965,0.035965,0.571870,0.712852,0.287148,0.428130,288,1.992332,2.186053,2.054079,2.318027,0.751466,0.702230,0.800702,85.0,1.176471,0.176471,0.176471,2.120106,2.018249,2.227105,15.0,-15.0
29,R,115.0,36,288,0.753472,0.246528,0.7500,0.2500,0.030082,0.030082,0.694512,0.812433,0.187567,0.305488,288,2.018481,2.150050,2.067105,2.232995,0.744391,0.711973,0.776808,85.0,1.352941,0.352941,0.352941,2.105159,2.038009,2.174521,30.0,-30.0

## 11b. PSE uncertainty and bias sanity check

Each call to `pf.fit_conditions` now also runs a parametric binomial bootstrap (default `n_bootstrap=200`) to estimate, for every fit:

- `pse_se`, `pse_ci95_lower`, `pse_ci95_upper` - standard error and 95% percentile CI of the PSE on the original stimulus axis;
- `pse_delta_ci95_lower`, `pse_delta_ci95_upper` - the same CI expressed as comparison - standard so it can be compared against `0`;
- `standard_inside_pse_ci95` - boolean flag (`True` if the standard value falls within the 95% CI of the PSE, i.e. **no statistically significant bias**);
- `pse_bias_p_value` - Wald p-value for the null hypothesis `PSE == standard`;
- `jnd_se`, `jnd_ci95_lower`, `jnd_ci95_upper` and matching `lapse_rate_*` columns.

When `psignifit` is installed, the same columns are filled with its built-in Bayesian credible intervals instead (column `bootstrap_method == "psignifit_bayesian_ci"`).

The cells below print compact "bias verdict" tables so you can quickly spot fits where the PSE is significantly biased from the standard.

In [271]:
pse_bias_by_subject_finger = pf.pse_bias_summary(pse_jnd_by_subject_finger, ["subject_id", "finger_condition"])
pse_bias_subject_pooled = pf.pse_bias_summary(pse_jnd_subject_pooled, ["subject_id"])
pse_bias_group_by_finger = pf.pse_bias_summary(pse_jnd_group_by_finger, ["finger_condition"])
pse_bias_group_all_pooled = pf.pse_bias_summary(pse_jnd_group_all_pooled, ["group"])

pf.save_csv(pse_bias_by_subject_finger, OUTPUT_ROOT, "pse_bias_by_subject_finger.csv")
pf.save_csv(pse_bias_subject_pooled, OUTPUT_ROOT, "pse_bias_subject_pooled.csv")
pf.save_csv(pse_bias_group_by_finger, OUTPUT_ROOT, "pse_bias_group_by_finger.csv")
pf.save_csv(pse_bias_group_all_pooled, OUTPUT_ROOT, "pse_bias_group_all_pooled.csv")

print("=== Group-level fits (all subjects pooled, by finger) ===")
display(pse_bias_group_by_finger)
print("=== Group-level fit (all subjects, all fingers pooled) ===")
display(pse_bias_group_all_pooled)
print("=== Subject-pooled fits ===")
display(pse_bias_subject_pooled)

if not pse_bias_by_subject_finger.empty and "standard_inside_pse_ci95" in pse_bias_by_subject_finger.columns:
    flag = pse_bias_by_subject_finger["standard_inside_pse_ci95"]
    inside_mask = flag.astype("object").map(lambda v: bool(v) if pd.notna(v) else False)
    biased = pse_bias_by_subject_finger.loc[~inside_mask & flag.notna()]
    n_total = int(flag.notna().sum())
    n_biased = int((~inside_mask & flag.notna()).sum())
    print(
        f"\nPer-subject/finger fits with PSE significantly biased from the standard at 95% CI: "
        f"{n_biased} / {n_total} ({(n_biased / n_total * 100) if n_total else 0:.1f}%)."
    )
    if not biased.empty:
        print("Biased (subject, finger) fits:")
        display(
            biased[[
                "subject_id",
                "finger_condition",
                "pse",
                "pse_ci95_lower",
                "pse_ci95_upper",
                "pse_delta_from_standard",
                "pse_delta_ci95_lower",
                "pse_delta_ci95_upper",
                "pse_bias_p_value",
                "bias_verdict",
            ]]
        )

=== Group-level fits (all subjects pooled, by finger) ===

,finger_condition,n_trials,n_stimulus_levels,fit_method,standard_value,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_ci95_lower,jnd_ci95_upper,lapse_rate,fit_warning,bias_verdict
0,I,2176,8,scipy_logistic_fallback,85.0,85.545648,1.888568,81.725831,88.743946,0.545648,-3.274169,3.743946,1.0,0.772641,26.867196,22.835112,30.582390,0.176124,high_lapse_estimate,standard within 95% CI (no significant bias)
1,M,2176,8,scipy_logistic_fallback,85.0,83.829492,2.139011,79.670388,87.697760,-1.170508,-5.329612,2.697760,1.0,0.584228,27.150480,22.981247,31.080661,0.209426,high_lapse_estimate,standard within 95% CI (no significant bias)
2,P,2176,8,scipy_logistic_fallback,85.0,82.297059,2.056042,78.162329,86.212346,-2.702941,-6.837671,1.212346,1.0,0.188633,23.737386,19.280489,28.108161,0.195255,high_lapse_estimate,standard within 95% CI (no significant bias)
3,R,2176,8,scipy_logistic_fallback,85.0,84.436397,1.797666,80.775112,87.938851,-0.563603,-4.224888,2.938851,1.0,0.753886,24.627884,20.281313,28.525376,0.214098,high_lapse_estimate,standard within 95% CI (no significant bias)

=== Group-level fit (all subjects, all fingers pooled) ===

,group,n_trials,n_stimulus_levels,fit_method,standard_value,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_ci95_lower,jnd_ci95_upper,lapse_rate,fit_warning,bias_verdict
0,all_pooled,8704,8,scipy_logistic_fallback,85.0,83.977923,1.064203,81.961832,86.128506,-1.022077,-3.038168,1.128506,1.0,0.336846,25.589488,23.805835,27.774275,0.200627,high_lapse_estimate,standard within 95% CI (no significant bias)

=== Subject-pooled fits ===

,subject_id,n_trials,n_stimulus_levels,fit_method,standard_value,pse,pse_se,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,standard_inside_pse_ci95,pse_bias_p_value,jnd,jnd_ci95_lower,jnd_ci95_upper,lapse_rate,fit_warning,bias_verdict
0,L_E_1,256,8,scipy_logistic_fallback,85.0,72.982062,3.982017,66.470491,81.859043,-12.017938,-18.529509,-3.140957,0.0,0.002544,15.593722,1.488443,20.789256,0.200000,high_lapse_estimate,standard OUTSIDE 95% CI (significant bias)
1,L_E_10,256,8,scipy_logistic_fallback,85.0,89.137498,4.516684,79.310970,96.877307,4.137498,-5.689030,11.877307,1.0,0.359642,20.865031,12.760475,24.252867,0.052460,,standard within 95% CI (no significant bias)
2,L_E_11,256,8,scipy_logistic_fallback,85.0,93.144585,6.128952,82.421825,107.402790,8.144585,-2.578175,22.402790,1.0,0.183891,44.728077,24.568362,56.075815,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
3,L_E_12,256,8,scipy_logistic_fallback,85.0,84.378494,4.755407,73.205238,91.726926,-0.621506,-11.794762,6.726926,1.0,0.896017,15.617595,6.860610,19.494511,0.086223,,standard within 95% CI (no significant bias)
4,L_E_14,256,8,scipy_logistic_fallback,85.0,78.513260,6.646040,66.875849,91.400963,-6.486740,-18.124151,6.400963,1.0,0.329049,36.952520,12.987496,46.727470,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
5,L_E_15,256,8,scipy_logistic_fallback,85.0,92.533620,5.786759,81.797460,105.301645,7.533620,-3.202540,20.301645,1.0,0.192960,40.287282,22.364624,48.162853,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
6,L_E_16,256,8,scipy_logistic_fallback,85.0,101.242395,8.825581,88.329777,121.393207,16.242395,3.329777,36.393207,0.0,0.065713,78.733793,42.213402,107.263524,0.200000,high_lapse_estimate,standard OUTSIDE 95% CI (significant bias)
7,L_E_17,256,8,scipy_logistic_fallback,85.0,91.730319,5.032450,81.138653,100.779185,6.730319,-3.861347,15.779185,1.0,0.181097,23.551087,12.945636,27.725152,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
8,L_E_18,256,8,scipy_logistic_fallback,85.0,84.178822,6.428939,73.312391,97.104797,-0.821178,-11.687609,12.104797,1.0,0.898361,41.951610,23.416677,51.614347,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
9,L_E_19,64,8,scipy_logistic_fallback,85.0,83.684395,209.123553,-579.351498,490.438031,-1.315605,-664.351498,405.438031,1.0,0.994981,230.257894,61.048225,2730.244573,0.227723,high_lapse_estimate,standard within 95% CI (no significant bias)
10,L_E_2,256,8,scipy_logistic_fallback,85.0,83.079390,6.736511,71.173627,89.572471,-1.920610,-13.826373,4.572471,1.0,0.775564,6.343845,0.694027,9.344505,0.052360,,standard within 95% CI (no significant bias)
11,L_E_3,256,8,scipy_logistic_fallback,85.0,86.165097,6.230578,72.943556,97.540612,1.165097,-12.056444,12.540612,1.0,0.851663,30.782331,12.283237,37.082532,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
12,L_E_4,256,8,scipy_logistic_fallback,85.0,97.212190,4.778970,87.801590,106.456190,12.212190,2.801590,21.456190,0.0,0.010607,28.486699,14.727456,33.328631,0.200000,high_lapse_estimate,standard OUTSIDE 95% CI (significant bias)
13,L_E_5,256,8,scipy_logistic_fallback,85.0,83.331776,5.767148,71.012083,91.524376,-1.668224,-13.987917,6.524376,1.0,0.772380,17.474201,1.490206,22.936847,0.168776,high_lapse_estimate,standard within 95% CI (no significant bias)
14,L_E_6,256,8,scipy_logistic_fallback,85.0,94.695258,5.923784,84.441679,108.706619,9.695258,-0.558321,23.706619,1.0,0.101700,43.782314,23.077737,52.051925,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
15,L_E_7,256,8,scipy_logistic_fallback,85.0,88.280448,3.113254,82.604787,93.654071,3.280448,-2.395213,8.654071,1.0,0.292018,15.105443,9.908565,17.408298,0.000000,,standard within 95% CI (no significant bias)
16,L_E_8,256,8,scipy_logistic_fallback,85.0,82.817845,6.623514,71.495086,97.019597,-2.182155,-13.504914,12.019597,1.0,0.741811,44.494824,24.210457,55.062939,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
17,L_E_9,256,8,scipy_logistic_fallback,85.0,86.351692,4.067423,78.467483,93.262626,1.351692,-6.532517,8.262626,1.0,0.739646,14.408231,6.192362,19.256802,0.079913,,standard within 95% CI (no significant bias)
18,N_E_1,256,8,scipy_logistic_fallback,85.0,86.829680,5.918757,72.806318,97.155295,1.829680,-12.193682,12.155295,1.0,0.757221,24.456903,9.005231,30.274055,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
19,N_E_12,256,8,scipy_logistic_fallback,85.0,71.737284,3.529112,67.043943,81.097044,-13.262716,-17.956057,-3.902956,0.0,0.000171,9.066617,1.088496,24.446853,0.306663,high_lapse_estimate,standard OUTSIDE 95% CI (significant bias)
20,N_E_13,256,8,scipy_logistic_fallback,85.0,87.779672,3.702957,80.066827,93.827998,2.779672,-4.933173,8.827998,1.0,0.452856,14.502497,8.975788,17.661831,0.033332,,standard within 95% CI (no significant bias)
21,N_E_14,256,8,scipy_logistic_fallback,85.0,82.635704,5.109888,70.788596,89.063063,-2.364296,-14.211404,4.063063,1.0,0.643586,12.584724,1.167593,16.003618,0.088149,,standard within 95% CI (no significant bias)
22,N_E_15,256,8,scipy_logistic_fallback,85.0,86.387133,6.117732,73.103305,96.532848,1.387133,-11.896695,11.532848,1.0,0.820626,32.709556,17.457001,39.958281,0.102794,,standard within 95% CI (no significant bias)
23,N_E_16,256,8,scipy_logistic_fallback,85.0,83.248354,6.727767,71.396117,97.121264,-1.751646,-13.603883,12.121264,1.0,0.794586,44.997006,24.802256,56.484941,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
24,N_E_17,192,8,scipy_logistic_fallback,85.0,88.331540,20.123677,35.009515,117.596516,3.331540,-49.990485,32.596516,1.0,0.868509,136.110341,70.858387,332.005726,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
25,N_E_18,256,8,scipy_logistic_fallback,85.0,79.432106,4.333927,70.625358,85.279209,-5.567894,-14.374642,0.279209,1.0,0.198889,10.418743,1.045862,13.712834,0.061785,,standard within 95% CI (no significant bias)
26,N_E_19,256,8,scipy_logistic_fallback,85.0,73.641747,5.249718,64.593727,84.707013,-11.358253,-20.406273,-0.292987,0.0,0.030496,23.736917,2.364699,30.229202,0.200000,high_lapse_estimate,standard OUTSIDE 95% CI (significant bias)
27,N_E_2,256,8,scipy_logistic_fallback,85.0,75.555506,7.414985,62.290057,91.571924,-9.444494,-22.709943,6.571924,1.0,0.202768,54.841007,33.810159,73.175633,0.200000,high_lapse_estimate,standard within 95% CI (no significant bias)
28,N_E_3,256,8,scipy_logistic_fallback,85.0,82.506888,5.602348,70.809231,89.245218,-2.493112,-14.190769,4.245218,1.0,0.656311,11.466456,1.187116,15.235340,0.110590,,standard within 95% CI (no significant bias)
29,N_E_4,256,8,scipy_logistic_fallback,85.0,89.246737,4.645465,78.424557,95.955295,4.246737,-6.575443,10.955295,1.0,0.360628,15.813175,7.942097,21.006582,0.120862,,standard within 95% CI (no significant bias)
30,N_E_5,256,8,scipy_logistic_fallback,85.0,96.188962,4.104667,86.898292,102.248592,11.188962,1.898292,17.248592,0.0,0.006412,19.590333,11.851354,23.378196,0.088010,,standard OUTSIDE 95% CI (significant bias)
31,N_E_6,256,8,scipy_logistic_fallback,85.0,88.600335,4.469671,78.355878,95.307846,3.600335,-6.644122,10.307846,1.0,0.420529,16.449776,9.466981,20.083170,0.079851,,standard within 95% CI (no significant bias)
32,N_E_7,256,8,scipy_logistic_fallback,85.0,83.942024,3.607466,75.487749,90.001556,-1.057976,-9.512251,5.001556,1.0,0.769313,13.260720,7.875267,16.021117,0.016030,,standard within 95% CI (no significant bias)
33,N_E_8,256,8,scipy_logistic_fallback,85.0,92.093774,4.191109,82.570624,98.648045,7.093774,-2.429376,13.648045,1.0,0.090536,19.499878,11.656845,23.229263,0.058223,,standard within 95% CI (no significant bias)
34,N_E_9,256,8,scipy_logistic_fallback,85.0,87.410113,5.826955,74.906658,96.974424,2.410113,-10.093342,11.974424,1.0,0.679156,30.074768,15.518146,37.486650,0.131277,,standard within 95% CI (no significant bias)

Per-subject/finger fits with PSE significantly biased from the standard at 95% CI: 32 / 144 (22.2%).
Biased (subject, finger) fits:

,subject_id,finger_condition,pse,pse_ci95_lower,pse_ci95_upper,pse_delta_from_standard,pse_delta_ci95_lower,pse_delta_ci95_upper,pse_bias_p_value,bias_verdict
2,L_E_1,P,69.531903,56.320824,84.286972,-15.468097,-28.679176,-0.713028,3.798558e-03,standard OUTSIDE 95% CI (significant bias)
5,L_E_10,M,69.132538,62.547376,70.008180,-15.867462,-22.452624,-14.991820,2.233103e-12,standard OUTSIDE 95% CI (significant bias)
18,L_E_14,P,54.377357,47.660032,62.057974,-30.622643,-37.339968,-22.942026,0.000000e+00,standard OUTSIDE 95% CI (significant bias)
22,L_E_15,P,111.976933,88.646895,144.376045,26.976933,3.646895,59.376045,5.338133e-02,standard OUTSIDE 95% CI (significant bias)
23,L_E_15,R,100.170906,86.445516,113.037874,15.170906,1.445516,28.037874,1.614204e-02,standard OUTSIDE 95% CI (significant bias)
29,L_E_17,M,112.808704,96.186042,131.470452,27.808704,11.186042,46.470452,1.616364e-03,standard OUTSIDE 95% CI (significant bias)
39,L_E_19,R,877.990749,109.585898,855.646038,792.990749,24.585898,770.646038,1.339475e-03,standard OUTSIDE 95% CI (significant bias)
41,L_E_2,M,85.076650,85.030736,98.065083,0.076650,0.030736,13.065083,9.871199e-01,standard OUTSIDE 95% CI (significant bias)
42,L_E_2,P,71.244401,70.354542,82.565304,-13.755599,-14.645458,-2.434696,6.436834e-03,standard OUTSIDE 95% CI (significant bias)
47,L_E_3,R,69.999997,68.587330,71.615346,-15.000003,-16.412670,-13.384654,1.998401e-15,standard OUTSIDE 95% CI (significant bias)
51,L_E_4,R,106.877407,90.654918,117.995044,21.877407,5.654918,32.995044,2.515552e-03,standard OUTSIDE 95% CI (significant bias)
59,L_E_6,R,70.000000,68.642666,71.615346,-15.000000,-16.357334,-13.384654,2.220446e-15,standard OUTSIDE 95% CI (significant bias)
61,L_E_7,M,98.126029,86.373146,106.742819,13.126029,1.373146,21.742819,1.925999e-02,standard OUTSIDE 95% CI (significant bias)
70,L_E_9,P,70.691532,69.991971,82.324550,-14.308468,-15.008029,-2.675450,5.351777e-07,standard OUTSIDE 95% CI (significant bias)
74,N_E_1,P,70.001196,56.908820,84.677147,-14.998804,-28.091180,-0.322853,1.594448e-02,standard OUTSIDE 95% CI (significant bias)
77,N_E_11,M,-707.990749,-686.151811,71.148160,-792.990749,-771.151811,-13.851840,1.884760e-03,standard OUTSIDE 95% CI (significant bias)
80,N_E_12,I,109.021554,86.388648,141.072218,24.021554,1.388648,56.072218,7.343490e-02,standard OUTSIDE 95% CI (significant bias)
82,N_E_12,P,70.537407,67.480397,84.630867,-14.462593,-17.519603,-0.369133,3.058283e-03,standard OUTSIDE 95% CI (significant bias)
88,N_E_14,I,70.323400,69.173582,71.278565,-14.676600,-15.826418,-13.721435,0.000000e+00,standard OUTSIDE 95% CI (significant bias)
95,N_E_15,R,69.531904,56.319813,84.286972,-15.468096,-28.680187,-0.713028,3.828708e-03,standard OUTSIDE 95% CI (significant bias)
104,N_E_18,I,66.644131,56.265072,78.278926,-18.355869,-28.734928,-6.721074,5.146177e-05,standard OUTSIDE 95% CI (significant bias)
106,N_E_18,P,70.722384,69.991121,81.055460,-14.277616,-15.008879,-3.944540,6.471433e-07,standard OUTSIDE 95% CI (significant bias)
107,N_E_18,R,96.379302,85.183371,99.291959,11.379302,0.183371,14.291959,2.299124e-02,standard OUTSIDE 95% CI (significant bias)
108,N_E_19,I,61.815980,50.704960,82.857341,-23.184020,-34.295040,-2.142659,5.866012e-03,standard OUTSIDE 95% CI (significant bias)
115,N_E_2,R,58.704164,40.521148,83.374036,-26.295836,-44.478852,-1.625964,3.649619e-02,standard OUTSIDE 95% CI (significant bias)
118,N_E_3,P,95.477088,88.250775,101.288621,10.477088,3.250775,16.288621,5.257230e-03,standard OUTSIDE 95% CI (significant bias)
119,N_E_3,R,71.246049,70.354542,82.749347,-13.753951,-14.645458,-2.250653,5.345033e-03,standard OUTSIDE 95% CI (significant bias)
121,N_E_4,M,70.543940,67.480397,84.630867,-14.456060,-17.519603,-0.369133,2.689428e-03,standard OUTSIDE 95% CI (significant bias)
127,N_E_5,R,105.467792,87.913924,118.313945,20.467792,2.913924,33.313945,9.323969e-03,standard OUTSIDE 95% CI (significant bias)
129,N_E_6,M,70.704156,69.991156,82.329112,-14.295844,-15.008844,-2.670888,1.678298e-06,standard OUTSIDE 95% CI (significant bias)
130,N_E_6,P,104.531955,93.262267,114.507011,19.531955,8.262267,29.507011,1.429820e-04,standard OUTSIDE 95% CI (significant bias)
137,N_E_8,M,102.466338,85.900067,114.990869,17.466338,0.900067,29.990869,2.138148e-02,standard OUTSIDE 95% CI (significant bias)

## 13. Order-effect analysis

Summarizes fatigue/order effects across trial number and inferred block order.

In [272]:
order_effects_summary, order_effects_binned = pf.compute_order_effects(combined_clean_trials)
pf.save_csv(order_effects_summary, OUTPUT_ROOT, "order_effects_summary.csv")
pf.save_csv(order_effects_binned, OUTPUT_ROOT, "order_effects_binned.csv")
display(order_effects_summary)

,subject_id,finger_condition,n_trials,n_data_points,first_half_p_comparison_greater,second_half_p_comparison_greater,first_half_mean_rt,second_half_mean_rt,median_rt,rt_ci95_lower,rt_ci95_upper,mean_log_reaction_time,median_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,spearman_response_vs_order,spearman_rt_vs_order,first_block_number,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s
0,L_E_1,I,64,64,0.46875,0.43750,1.807114,1.777725,1.779743,1.766910,1.817928,0.582000,0.576469,0.568376,0.595625,-0.072214,-0.123581,4,1.789615,1.765397,1.814165
1,L_E_1,M,64,64,0.46875,0.56250,1.866421,1.823345,1.810256,1.812035,1.877731,0.610226,0.593468,0.594533,0.625919,0.085471,-0.249771,3,1.840848,1.812185,1.869964
2,L_E_1,P,64,64,0.40625,0.53125,1.906837,1.880968,1.869511,1.866466,1.921339,0.637018,0.625677,0.623149,0.650886,0.167803,-0.354075,2,1.890833,1.864791,1.917239
3,L_E_1,R,64,64,0.53125,0.34375,2.201796,2.065394,2.095478,2.082286,2.184905,0.753816,0.739781,0.732642,0.774990,-0.228475,-0.635302,1,2.125094,2.080570,2.170570
4,L_E_10,I,64,64,0.40625,0.43750,2.396017,1.963664,1.990096,2.004236,2.355445,0.750792,0.688182,0.699634,0.801951,-0.014558,-0.569093,1,2.118678,2.013015,2.229887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,N_E_8,R,64,64,0.43750,0.56250,2.150770,1.970635,1.861604,1.910510,2.210895,0.694765,0.621438,0.640933,0.748597,0.143791,-0.350229,2,2.003238,1.898251,2.114032
140,N_E_9,I,64,64,0.50000,0.40625,2.896768,2.791573,2.399711,2.514839,3.173502,0.975815,0.875336,0.892580,1.059049,-0.058621,0.154670,1,2.653328,2.441421,2.883628
141,N_E_9,M,64,64,0.46875,0.46875,2.543844,2.398058,2.158315,2.154949,2.786953,0.849694,0.769238,0.781744,0.917645,0.015255,0.170330,2,2.338931,2.185279,2.503387
142,N_E_9,P,64,64,0.53125,0.43750,2.200259,2.314515,2.150948,2.156968,2.357806,0.800797,0.765908,0.762055,0.839539,-0.077008,0.060989,3,2.227316,2.142675,2.315300
143,N_E_9,R,64,64,0.40625,0.53125,2.054661,2.146185,1.950324,1.989754,2.211093,0.724667,0.667995,0.681278,0.768057,0.047459,-0.013095,4,2.064044,1.976401,2.155573

## 14. Success-rate, answer-duration, and fatigue/learning analysis

This section tests the requested psychophysics-only questions:

- Does answer duration (`time_to_answer`) relate to success?
- Does success go up or down over the session (learning vs tiredness/fatigue proxy)?
- Are the effects visible within each participant/finger and across participants?

Because no subjective tiredness scale is present in `answers.csv`, tiredness is operationalized conservatively as trial order, elapsed time, and first-vs-second-half changes.

In [273]:
success_time_fatigue = pf.compute_success_time_fatigue(combined_success_trials, ["subject_id", "finger_condition"])

success_summary_by_subject_finger = success_time_fatigue["summary"]
success_trend_slopes_by_subject_finger = success_time_fatigue["slopes"]
success_by_reaction_time_bin = success_time_fatigue["reaction_time_bins"]
success_by_order_bin = success_time_fatigue["order_bins"]
fatigue_first_second_summary = success_time_fatigue["first_second"]
between_subject_success_time_stats = success_time_fatigue["between_subjects"]
success_summary_by_subject = success_time_fatigue["subject_summary"]

pf.save_csv(success_summary_by_subject, OUTPUT_ROOT, "success_summary_by_subject.csv")
pf.save_csv(success_summary_by_subject_finger, OUTPUT_ROOT, "success_summary_by_subject_finger.csv")
pf.save_csv(success_trend_slopes_by_subject_finger, OUTPUT_ROOT, "success_trend_slopes_by_subject_finger.csv")
pf.save_csv(success_by_reaction_time_bin, OUTPUT_ROOT, "success_by_reaction_time_bin.csv")
pf.save_csv(success_by_order_bin, OUTPUT_ROOT, "success_by_order_bin.csv")
pf.save_csv(fatigue_first_second_summary, OUTPUT_ROOT, "fatigue_first_second_summary.csv")
pf.save_csv(between_subject_success_time_stats, OUTPUT_ROOT, "between_subject_success_time_stats.csv")

print("Participant-level success summary")
display(success_summary_by_subject)
print("Within participant/finger success trend slopes: positive=success improves, negative=success decreases")
display(success_trend_slopes_by_subject_finger)
print("First vs second half fatigue/learning proxy")
display(fatigue_first_second_summary)
print("Between-participant duration/time statistics")
display(between_subject_success_time_stats)

Participant-level success summary

,subject_id,subject_group_label,n_trials,n_data_points,success_rate,success_rate_ci95_lower,success_rate_ci95_upper,mean_reaction_time,median_reaction_time,reaction_time_ci95_lower,reaction_time_ci95_upper,mean_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,session_duration_min,mean_abs_stiffness_delta,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s
0,L_E_1,other,256,256,0.812500,0.760197,0.855563,1.916200,1.864899,1.892270,1.940130,0.645765,0.634338,0.657192,62.273045,37.5,1.907446,1.885773,1.929367
1,L_E_10,other,256,256,0.812500,0.760197,0.855563,1.991296,1.892819,1.933783,2.048809,0.673385,0.654461,0.692309,56.520598,37.5,1.960863,1.924105,1.998324
2,L_E_11,other,256,256,0.718750,0.660752,0.770280,2.351671,2.118362,2.256305,2.447037,0.818945,0.788782,0.849108,80.278058,37.5,2.268106,2.200714,2.337561
3,L_E_12,other,256,256,0.878906,0.833243,0.913365,2.066896,2.002182,2.029866,2.103926,0.718308,0.704066,0.732550,67.943181,37.5,2.050961,2.021957,2.080380
4,L_E_14,other,256,256,0.722656,0.664830,0.773899,2.076768,1.964511,1.993271,2.160265,0.711375,0.691555,0.731195,46.663964,37.5,2.036790,1.996819,2.077562
5,L_E_15,other,256,256,0.730469,0.673002,0.781121,2.471305,2.278803,2.390735,2.551875,0.881471,0.857261,0.905680,57.790664,37.5,2.414448,2.356698,2.473614
6,L_E_16,other,256,256,0.648438,0.588147,0.704339,2.153545,2.058420,2.100879,2.206212,0.752138,0.732201,0.772076,46.120512,37.5,2.121532,2.079654,2.164254
7,L_E_17,other,256,256,0.816406,0.764422,0.859035,2.107745,2.005069,2.059415,2.156075,0.733531,0.715920,0.751143,69.619694,37.5,2.082421,2.046068,2.119420
8,L_E_18,other,256,256,0.738281,0.681195,0.788322,2.463830,2.237280,2.356893,2.570766,0.870539,0.843602,0.897476,52.548685,37.5,2.388197,2.324726,2.453402
9,L_E_19,other,256,256,0.519531,0.458493,0.579992,2.134921,2.007748,2.083246,2.186597,0.743682,0.723916,0.763447,62.809944,37.5,2.103666,2.062495,2.145659
10,L_E_2,other,256,256,0.957031,0.924708,0.975840,2.080102,2.045888,2.056538,2.103667,0.728487,0.717809,0.739165,54.472472,37.5,2.071944,2.049937,2.094186
11,L_E_3,other,256,256,0.753906,0.697645,0.802660,2.190184,2.046024,2.128390,2.251977,0.765261,0.743257,0.787265,50.099540,37.5,2.149555,2.102772,2.197378
12,L_E_4,other,256,256,0.777344,0.722492,0.823995,2.108929,1.940001,2.038684,2.179173,0.719974,0.693966,0.745982,77.021541,37.5,2.054380,2.001639,2.108511
13,L_E_5,other,256,256,0.851562,0.802824,0.889906,2.027688,1.953375,1.993428,2.061947,0.699730,0.685911,0.713549,59.293493,37.5,2.013209,1.985581,2.041222
14,L_E_6,other,256,256,0.707031,0.648547,0.759394,2.074734,2.032881,2.040532,2.108937,0.721764,0.706551,0.736976,60.607454,37.5,2.058060,2.026989,2.089608
15,L_E_7,other,256,256,0.886719,0.842043,0.919960,2.005809,1.931853,1.974152,2.037467,0.689059,0.675098,0.703020,55.279814,37.5,1.991840,1.964226,2.019843
16,L_E_8,other,256,256,0.714844,0.656679,0.766656,1.822286,1.797952,1.804995,1.839576,0.597344,0.588418,0.606269,42.702907,37.5,1.817285,1.801136,1.833578
17,L_E_9,other,256,256,0.882812,0.837636,0.916669,1.979324,1.901161,1.933270,2.025379,0.668924,0.649589,0.688258,56.632631,37.5,1.952135,1.914754,1.990246
18,N_E_1,other,256,256,0.816406,0.764422,0.859035,2.163881,1.859726,2.020031,2.307732,0.712528,0.677351,0.747706,75.726228,37.5,2.039140,1.968656,2.112149
19,N_E_11,other,256,256,0.203125,0.158399,0.256630,2.733077,2.305296,2.482495,2.983659,0.932497,0.894739,0.970254,68.643718,37.5,2.540845,2.446698,2.638615
20,N_E_12,other,256,256,0.757812,0.701771,0.806231,2.103966,1.901073,2.041402,2.166529,0.721188,0.696589,0.745786,53.274563,37.5,2.056875,2.006896,2.108099
21,N_E_13,other,256,256,0.894531,0.850898,0.926499,1.860984,1.833166,1.817067,1.904901,0.604100,0.581754,0.626445,48.553039,37.5,1.829605,1.789174,1.870948
22,N_E_14,other,256,256,0.890625,0.846463,0.923236,2.026585,1.985700,1.974739,2.078431,0.693681,0.676147,0.711215,50.105218,37.5,2.001067,1.966287,2.036463
23,N_E_15,other,256,256,0.753906,0.697645,0.802660,1.953227,1.871978,1.917189,1.989264,0.661507,0.647103,0.675912,48.088022,37.5,1.937711,1.909999,1.965824
24,N_E_16,other,256,256,0.710938,0.652610,0.763028,2.212629,2.000692,2.143320,2.281937,0.769270,0.743452,0.795088,53.247419,37.5,2.158191,2.103183,2.214637
25,N_E_17,other,256,256,0.531250,0.470110,0.591466,2.083442,2.017327,2.033012,2.133872,0.721171,0.703118,0.739224,41.179542,37.5,2.056840,2.020041,2.094309
26,N_E_18,other,256,256,0.914062,0.873317,0.942565,2.051939,1.857372,1.984026,2.119852,0.693351,0.667841,0.718862,59.112103,37.5,2.000409,1.950023,2.052097
27,N_E_19,other,256,256,0.757812,0.701771,0.806231,1.811418,1.711579,1.719465,1.903371,0.570230,0.549842,0.590617,40.383103,37.5,1.768673,1.732980,1.805102
28,N_E_2,other,256,256,0.675781,0.616209,0.730156,2.257993,2.154322,2.205741,2.310244,0.801811,0.783601,0.820021,53.621567,37.5,2.229574,2.189341,2.270547
29,N_E_3,other,256,256,0.902344,0.859814,0.932976,2.196799,2.008707,2.124150,2.269449,0.758985,0.731605,0.786364,48.753318,37.5,2.136106,2.078413,2.195400
30,N_E_4,other,256,256,0.863281,0.815794,0.900027,1.966513,1.885296,1.904007,2.029018,0.659168,0.639329,0.679008,53.162148,37.5,1.933184,1.895208,1.971920
31,N_E_5,other,256,256,0.816406,0.764422,0.859035,1.932744,1.777798,1.849139,2.016349,0.629827,0.604842,0.654813,53.909850,37.5,1.877286,1.830963,1.924782
32,N_E_6,other,256,256,0.867188,0.820139,0.903379,1.956643,1.882042,1.906433,2.006854,0.653355,0.631119,0.675591,56.085871,37.5,1.921978,1.879713,1.965193
33,N_E_7,other,256,256,0.906250,0.864297,0.936191,2.384527,2.098210,2.289481,2.479572,0.835274,0.806201,0.864346,69.505895,37.5,2.305445,2.239385,2.373453
34,N_E_8,other,256,256,0.863281,0.815794,0.900027,2.114321,1.893328,2.028715,2.199927,0.713258,0.683472,0.743045,68.588753,37.5,2.040629,1.980742,2.102327
35,N_E_9,other,256,256,0.781250,0.726655,0.827529,2.418233,2.140789,2.294065,2.542400,0.837743,0.805375,0.870112,69.192234,37.5,2.311146,2.237535,2.387177

Within participant/finger success trend slopes: positive=success improves, negative=success decreases

,subject_id,finger_condition,n_trials,n_data_points,success_rate,success_rate_ci95_lower,success_rate_ci95_upper,median_reaction_time,reaction_time_ci95_lower,reaction_time_ci95_upper,mean_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,success_vs_order_slope,success_vs_order_p_value,success_vs_order_spearman_r,success_vs_order_spearman_p,success_vs_order_direction,success_vs_global_order_slope,success_vs_global_order_p_value,success_vs_global_order_spearman_r,success_vs_global_order_spearman_p,success_vs_global_order_direction,success_vs_elapsed_slope,success_vs_elapsed_p_value,success_vs_elapsed_direction,success_vs_reaction_time_slope,success_vs_reaction_time_p_value,success_vs_reaction_time_spearman_r,success_vs_reaction_time_spearman_p,success_vs_reaction_time_direction,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s
0,L_E_1,I,64,64,0.890625,0.791011,0.946000,1.779743,1.766910,1.817928,0.582000,0.568376,0.595625,0.174519,0.195461,0.163958,0.195461,up_weak,0.739629,0.195461,0.163958,0.195461,up_weak,0.893841,0.170262,up_weak,-0.298911,0.436703,-0.177508,0.160543,down_weak,1.789615,1.765397,1.814165
1,L_E_1,M,64,64,0.859375,0.753835,0.924215,1.810256,1.812035,1.877731,0.610226,0.594533,0.625919,-0.108173,0.473347,-0.091241,0.473347,down_weak,-0.458448,0.473347,-0.091241,0.473347,down_weak,-0.566357,0.408463,down_weak,-0.027901,0.933270,-0.074210,0.560040,flat,1.840848,1.812185,1.869964
2,L_E_1,P,64,64,0.781250,0.665670,0.864978,1.869511,1.866466,1.921339,0.637018,0.623149,0.650886,0.103846,0.562972,0.073658,0.562972,up_weak,0.440110,0.562972,0.073658,0.562972,up_weak,0.182804,0.764557,up_weak,-1.016788,0.028896,-0.210742,0.094615,down_p_lt_0.05,1.890833,1.864791,1.917239
3,L_E_1,R,64,64,0.718750,0.598658,0.814068,2.095478,2.082286,2.184905,0.753816,0.732642,0.774990,-0.173077,0.374514,-0.112876,0.374514,down_weak,-0.733516,0.374514,-0.112876,0.374514,down_weak,-0.758355,0.356726,down_weak,0.443858,0.103946,0.244564,0.051459,up_weak,2.125094,2.080570,2.170570
4,L_E_10,I,64,64,0.765625,0.648665,0.852502,1.990096,2.004236,2.355445,0.750792,0.699634,0.801951,0.333173,0.066740,0.230623,0.066740,up_weak,1.412019,0.066740,0.230623,0.066740,up_weak,1.289883,0.046929,up_p_lt_0.05,-0.171919,0.020732,-0.156744,0.216126,down_p_lt_0.05,2.118678,2.013015,2.229887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,N_E_8,R,64,64,0.843750,0.735717,0.912853,1.861604,1.910510,2.210895,0.694765,0.640933,0.748597,0.204808,0.191516,0.165396,0.191516,up_weak,0.867995,0.191516,0.165396,0.191516,up_weak,0.839968,0.177821,up_weak,-0.189311,0.010673,-0.223634,0.075670,down_p_lt_0.05,2.003238,1.898251,2.114032
140,N_E_9,I,64,64,0.828125,0.717866,0.901224,2.399711,2.514839,3.173502,0.975815,0.892580,1.059049,-0.246635,0.129168,-0.191688,0.129168,down_weak,-1.045261,0.129168,-0.191688,0.129168,down_weak,-0.558050,0.206645,down_weak,-0.132724,0.000092,-0.337416,0.006399,down_p_lt_0.05,2.653328,2.441421,2.883628
141,N_E_9,M,64,64,0.812500,0.700254,0.889355,2.158315,2.154949,2.786953,0.849694,0.781744,0.917645,-0.020192,0.905299,-0.015169,0.905299,flat,-0.085577,0.905299,-0.015169,0.905299,down_weak,-0.049091,0.955796,down_weak,-0.077834,0.041842,-0.153861,0.224795,down_p_lt_0.05,2.338931,2.185279,2.503387
142,N_E_9,P,64,64,0.765625,0.648665,0.852502,2.150948,2.156968,2.357806,0.800797,0.762055,0.839539,-0.073558,0.689477,-0.050917,0.689477,down_weak,-0.311745,0.689477,-0.050917,0.689477,down_weak,-0.461728,0.646805,down_weak,-0.305774,0.018565,-0.272554,0.029340,down_p_lt_0.05,2.227316,2.142675,2.315300
143,N_E_9,R,64,64,0.718750,0.598658,0.814068,1.950324,1.989754,2.211093,0.724667,0.681278,0.768057,-0.429808,0.024868,-0.280308,0.024868,down_p_lt_0.05,-1.821566,0.024868,-0.280308,0.024868,down_p_lt_0.05,-2.585553,0.023508,down_p_lt_0.05,0.114755,0.368107,0.015050,0.906041,up_weak,2.064044,1.976401,2.155573

First vs second half fatigue/learning proxy

,subject_id,finger_condition,mean_reaction_time_first_half,mean_reaction_time_second_half,n_trials_first_half,n_trials_second_half,success_rate_first_half,success_rate_second_half,success_rate_second_minus_first,fatigue_direction,reaction_time_second_minus_first
0,L_E_1,I,1.807114,1.777725,32,32,0.84375,0.93750,0.09375,up_weak,-0.029389
1,L_E_1,M,1.866421,1.823345,32,32,0.90625,0.81250,-0.09375,down_weak,-0.043076
2,L_E_1,P,1.906837,1.880968,32,32,0.78125,0.78125,0.00000,flat,-0.025869
3,L_E_1,R,2.201796,2.065394,32,32,0.78125,0.65625,-0.12500,down_weak,-0.136402
4,L_E_10,I,2.396017,1.963664,32,32,0.65625,0.87500,0.21875,up_weak,-0.432353
...,...,...,...,...,...,...,...,...,...,...,...
139,N_E_8,R,2.150770,1.970635,32,32,0.81250,0.87500,0.06250,up_weak,-0.180135
140,N_E_9,I,2.896768,2.791573,32,32,0.87500,0.78125,-0.09375,down_weak,-0.105195
141,N_E_9,M,2.543844,2.398058,32,32,0.78125,0.84375,0.06250,up_weak,-0.145786
142,N_E_9,P,2.200259,2.314515,32,32,0.78125,0.75000,-0.03125,down_weak,0.114256
143,N_E_9,R,2.054661,2.146185,32,32,0.84375,0.59375,-0.25000,down_weak,0.091525

Between-participant duration/time statistics

                                            analysis  n_subjects     slope  linear_p_value  spearman_r  spearman_p       direction
0      between_subject_success_vs_mean_reaction_time          36 -0.353711        0.002023   -0.333891    0.046572  down_p_lt_0.05
1    between_subject_success_vs_median_reaction_time          36 -0.474881        0.004713   -0.364924    0.028643  down_p_lt_0.05
2    between_subject_success_vs_session_duration_min          36  0.000035        0.988179    0.142802    0.406062            flat
3  between_subject_success_vs_mean_abs_stiffness_...          36       NaN             NaN         NaN         NaN         unknown

## 15. Finger identity across time and finger appearance order

This section addresses two additional time questions:

1. **Between fingers across time:** compare index/middle/ring/pinky success trajectories across normalized time within each finger's trials.
2. **Appearance of fingers:** compare the first, second, third, and fourth finger encountered in each participant session, independent of the anatomical finger identity.

Outputs include subject-level slopes, group time-bin curves by finger, the finger-order matrix for every participant, and paired contrasts between fingers/appearance positions.

In [274]:
import importlib
pf = importlib.reload(pf)

finger_time_appearance = pf.compare_fingers_over_time_and_appearance(combined_success_trials)

finger_time_subject_summary = finger_time_appearance["subject_finger_summary"]
finger_time_group_bins = finger_time_appearance["group_finger_time_bins"]
finger_time_subject_bins = finger_time_appearance["subject_finger_time_bins"]
finger_appearance_order_summary = finger_time_appearance["appearance_order_summary"]
finger_by_appearance_order = finger_time_appearance["finger_by_appearance_order"]
finger_order_matrix = finger_time_appearance["finger_order_matrix"]
finger_time_slope_summary = finger_time_appearance["finger_slope_summary"]
stiffness_time_slope_summary = finger_time_appearance.get("stiffness_slope_summary", pd.DataFrame())
finger_time_slope_contrasts = finger_time_appearance["finger_slope_contrasts"]
finger_appearance_order_contrasts = finger_time_appearance["appearance_order_contrasts"]

pf.save_csv(finger_time_subject_summary, OUTPUT_ROOT, "finger_time_subject_summary.csv")
pf.save_csv(finger_time_group_bins, OUTPUT_ROOT, "finger_time_group_bins.csv")
pf.save_csv(finger_time_subject_bins, OUTPUT_ROOT, "finger_time_subject_bins.csv")
pf.save_csv(finger_appearance_order_summary, OUTPUT_ROOT, "finger_appearance_order_summary.csv")
pf.save_csv(finger_by_appearance_order, OUTPUT_ROOT, "finger_by_appearance_order.csv")
pf.save_csv(finger_order_matrix, OUTPUT_ROOT, "finger_order_matrix.csv")
pf.save_csv(finger_time_slope_summary, OUTPUT_ROOT, "finger_time_slope_summary.csv")
pf.save_csv(stiffness_time_slope_summary, OUTPUT_ROOT, "stiffness_time_slope_summary.csv")
pf.save_csv(finger_time_slope_contrasts, OUTPUT_ROOT, "finger_time_slope_contrasts.csv")
pf.save_csv(finger_appearance_order_contrasts, OUTPUT_ROOT, "finger_appearance_order_contrasts.csv")

print("Finger order matrix: which finger appeared 1st/2nd/3rd/4th for each participant")
display(finger_order_matrix)
print("Group success by finger and normalized within-finger time bin")
display(finger_time_group_bins)
print("Finger appearance-order summary")
display(finger_appearance_order_summary)
print("Finger time-slope summary")
display(finger_time_slope_summary)
print("Success slope by stiffness")
display(stiffness_time_slope_summary)
print("Paired contrasts between finger time slopes")
display(finger_time_slope_contrasts)
print("Paired contrasts between appearance-order success rates")
display(finger_appearance_order_contrasts)

Finger order matrix: which finger appeared 1st/2nd/3rd/4th for each participant

   subject_id appearance_1_finger appearance_2_finger appearance_3_finger appearance_4_finger
0       L_E_1                   R                   P                   M                   I
1      L_E_10                   I                   M                   P                   R
2      L_E_11                   P                   I                   R                   M
3      L_E_12                   R                   P                   M                   I
4      L_E_14                   M                   R                   I                   P
5      L_E_15                   I                   M                   P                   R
6      L_E_16                   P                   I                   R                   M
7      L_E_17                   R                   P                   M                   I
8      L_E_18                   M                   R                   I                   P
9      L_E_19                   R                   P                   M                   I
10      L_E_2                   P                   I                   R                   M
11      L_E_3                   P                   I                   R                   M
12      L_E_4                   P                   I                   R                   M
13      L_E_5                   R                   P                   M                   I
14      L_E_6                   M                   R                   I                   P
15      L_E_7                   P                   I                   R                   M
16      L_E_8                   R                   P                   M                   I
17      L_E_9                   M                   R                   I                   P
18      N_E_1                   M                   R                   I                   P
19     N_E_11                   M                   R                   I                   P
20     N_E_12                   I                   M                   P                   R
21     N_E_13                   P                   I                   R                   M
22     N_E_14                   R                   P                   M                   I
23     N_E_15                   M                   R                   I                   P
24     N_E_16                   I                   M                   P                   R
25     N_E_17                   P                   I                   R                   M
26     N_E_18                   R                   P                   M                   I
27     N_E_19                   R                   P                   M                   I
28      N_E_2                   R                   P                   M                   I
29      N_E_3                   I                   M                   P                   R
30      N_E_4                   M                   R                   I                   P
31      N_E_5                   P                   I                   R                   M
32      N_E_6                   P                   I                   R                   M
33      N_E_7                   R                   P                   M                   I
34      N_E_8                   M                   R                   I                   P
35      N_E_9                   I                   M                   P                   R

Group success by finger and normalized within-finger time bin

,finger_condition,within_finger_time_bin,n_subjects,total_trials,n_data_points,mean_success_rate,median_success_rate,sem_success_rate,success_rate_ci95_lower,success_rate_ci95_upper,mean_reaction_time,median_reaction_time,sem_reaction_time,reaction_time_ci95_lower,reaction_time_ci95_upper,mean_log_reaction_time,log_reaction_time_ci95_lower,log_reaction_time_ci95_upper,mean_within_finger_order_fraction,geomean_reaction_time_s,reaction_time_log_ci95_lower_backtransformed_s,reaction_time_log_ci95_upper_backtransformed_s
0,I,1,36,288,288,0.756944,0.7500,0.037909,0.682642,0.831247,2.211760,2.049621,0.064187,2.085954,2.337567,0.761122,0.716398,0.805845,0.055556,2.140676,2.047047,2.238587
1,I,2,36,288,288,0.802083,0.8750,0.028771,0.745693,0.858474,2.142064,1.941752,0.061873,2.020792,2.263336,0.730808,0.687082,0.774534,0.182540,2.076758,1.987906,2.169581
2,I,3,36,288,288,0.760417,0.7500,0.032034,0.697630,0.823203,2.123574,1.968835,0.060283,2.005419,2.241728,0.727822,0.684837,0.770806,0.309524,2.070565,1.983448,2.161508
3,I,4,36,288,288,0.788194,0.8750,0.034076,0.721405,0.854984,2.161035,1.940917,0.063540,2.036497,2.285573,0.738390,0.688746,0.788034,0.436508,2.092564,1.991217,2.199068
4,I,5,36,288,288,0.756944,0.7500,0.034122,0.690066,0.823823,2.126990,1.979553,0.065312,1.998979,2.255002,0.722384,0.678700,0.766068,0.563492,2.059337,1.971313,2.151291
5,I,6,36,288,288,0.795139,0.8125,0.026889,0.742436,0.847842,2.071157,1.951467,0.053747,1.965814,2.176500,0.703498,0.663340,0.743655,0.690476,2.020808,1.941265,2.103610
6,I,7,36,288,288,0.760417,0.7500,0.030446,0.700742,0.820091,2.099730,1.927076,0.047155,2.007305,2.192154,0.719010,0.679249,0.758771,0.817460,2.052400,1.972396,2.135650
7,I,8,36,288,288,0.753472,0.8125,0.039681,0.675698,0.831246,2.009304,1.902979,0.033846,1.942967,2.075641,0.684450,0.654027,0.714873,0.944444,1.982680,1.923270,2.043926
8,M,1,36,288,288,0.763889,0.7500,0.036180,0.692977,0.834801,2.231659,2.006013,0.074407,2.085822,2.377496,0.763455,0.712934,0.813977,0.055556,2.145677,2.039968,2.256865
9,M,2,36,288,288,0.725694,0.7500,0.033341,0.660347,0.791042,2.224434,1.967821,0.124767,1.979890,2.468977,0.739904,0.692760,0.787048,0.182540,2.095734,1.999227,2.196901
10,M,3,36,288,288,0.750000,0.7500,0.037268,0.676955,0.823045,2.072429,1.963995,0.045816,1.982630,2.162229,0.712177,0.672824,0.751531,0.309524,2.038425,1.959764,2.120243
11,M,4,36,288,288,0.798611,0.8125,0.027403,0.744901,0.852321,2.094988,1.962953,0.049427,1.998110,2.191865,0.716553,0.677425,0.755681,0.436508,2.047363,1.968801,2.129061
12,M,5,36,288,288,0.819444,0.8750,0.033572,0.753643,0.885246,2.075624,1.946210,0.044569,1.988269,2.162980,0.709424,0.671373,0.747475,0.563492,2.032820,1.956923,2.111661
13,M,6,36,288,288,0.756944,0.7500,0.033014,0.692238,0.821651,2.032208,1.916776,0.037887,1.957950,2.106467,0.693733,0.658856,0.728610,0.690476,2.001172,1.932581,2.072198
14,M,7,36,288,288,0.722222,0.7500,0.031541,0.660402,0.784042,2.080875,1.925598,0.042215,1.998133,2.163616,0.710990,0.674031,0.747950,0.817460,2.036007,1.962130,2.112665
15,M,8,36,288,288,0.774306,0.8125,0.033341,0.708958,0.839653,2.073524,1.926554,0.042288,1.990640,2.156409,0.710688,0.674801,0.746575,0.944444,2.035390,1.963641,2.109761
16,P,1,36,288,288,0.781250,0.8750,0.032419,0.717709,0.844791,2.193910,2.066878,0.052034,2.091923,2.295897,0.763318,0.722133,0.804504,0.055556,2.145384,2.058820,2.235587
17,P,2,36,288,288,0.746528,0.7500,0.033588,0.680696,0.812359,2.186097,2.002727,0.049067,2.089927,2.282268,0.756432,0.719778,0.793086,0.182540,2.130660,2.053977,2.210206
18,P,3,36,288,288,0.770833,0.8750,0.035739,0.700785,0.840882,2.100122,1.979748,0.036142,2.029284,2.170961,0.722793,0.694333,0.751253,0.309524,2.060179,2.002374,2.119654
19,P,4,36,288,288,0.805556,0.8125,0.029649,0.747443,0.863668,2.121877,1.941625,0.064458,1.995539,2.248215,0.722233,0.679597,0.764868,0.436508,2.059025,1.973082,2.148711
20,P,5,36,288,288,0.795139,0.8125,0.029104,0.738095,0.852183,2.073667,1.980998,0.038377,1.998448,2.148886,0.711743,0.679216,0.744271,0.563492,2.037541,1.972330,2.104907
21,P,6,36,288,288,0.774306,0.8750,0.035502,0.704721,0.843890,2.050294,1.964458,0.037023,1.977729,2.122859,0.702009,0.670027,0.733991,0.690476,2.017802,1.954290,2.083379
22,P,7,36,288,288,0.763889,0.7500,0.030610,0.703894,0.823884,2.022631,1.949196,0.032093,1.959729,2.085533,0.692057,0.662125,0.721989,0.817460,1.997821,1.938909,2.058524
23,P,8,36,288,288,0.805556,0.8750,0.033940,0.739034,0.872077,2.107791,1.915668,0.045693,2.018233,2.197349,0.721056,0.684087,0.758026,0.944444,2.056605,1.981962,2.134058
24,R,1,36,288,288,0.767361,0.7500,0.031162,0.706284,0.828438,2.276907,2.067218,0.072315,2.135169,2.418645,0.791441,0.743673,0.839208,0.055556,2.206573,2.103648,2.314533
25,R,2,36,288,288,0.784722,0.8750,0.036123,0.713922,0.855522,2.214476,2.015948,0.067588,2.082003,2.346950,0.758554,0.713279,0.803829,0.182540,2.135187,2.040672,2.234080
26,R,3,36,288,288,0.760417,0.7500,0.034638,0.692527,0.828307,2.113900,2.011340,0.039671,2.036145,2.191654,0.731298,0.699437,0.763159,0.309524,2.077776,2.012618,2.145042
27,R,4,36,288,288,0.777778,0.8750,0.033076,0.712949,0.842607,2.109309,2.006877,0.041871,2.027241,2.191376,0.728550,0.694639,0.762460,0.436508,2.072073,2.002986,2.143543
28,R,5,36,288,288,0.777778,0.8125,0.032699,0.713688,0.841868,2.168158,2.009111,0.071671,2.027682,2.308633,0.736415,0.694107,0.778724,0.563492,2.088436,2.001920,2.178691
29,R,6,36,288,288,0.770833,0.7500,0.032466,0.707199,0.834467,2.085063,1.985928,0.043886,1.999047,2.171079,0.715127,0.681914,0.748341,0.690476,2.044447,1.977659,2.113491
30,R,7,36,288,288,0.798611,0.8125,0.026010,0.747631,0.849591,2.091473,1.965182,0.049147,1.995146,2.187801,0.713246,0.675150,0.751341,0.817460,2.040603,1.964327,2.119841
31,R,8,36,288,288,0.777778,0.8750,0.034182,0.710780,0.844775,2.032661,1.971465,0.029395,1.975046,2.090276,0.696986,0.670140,0.723833,0.944444,2.007693,1.954511,2.062323

Finger appearance-order summary

,finger_appearance_order,n_subjects,fingers_observed,mean_success_rate,median_success_rate,sem_success_rate,success_rate_ci95_lower,success_rate_ci95_upper,mean_reaction_time,median_reaction_time,sem_reaction_time,reaction_time_ci95_lower,reaction_time_ci95_upper,mean_success_slope,sem_success_slope
0,1,36,"I,M,P,R",0.758681,0.773438,0.023246,0.713118,0.804243,2.293635,2.097944,0.041629,2.212042,2.375228,0.009455,0.030592
1,2,36,"I,M,P,R",0.775608,0.796875,0.025441,0.725744,0.825471,2.121238,2.007670,0.034422,2.053770,2.188705,0.012380,0.026011
2,3,36,"I,M,P,R",0.786458,0.812500,0.022289,0.742772,0.830145,2.057980,1.922964,0.038410,1.982697,2.133264,0.034375,0.026732
3,4,36,"I,M,P,R",0.772135,0.789062,0.027223,0.718778,0.825493,1.999608,1.863535,0.030463,1.939900,2.059316,-0.026723,0.026855

Finger time-slope summary

,finger_condition,n_subjects,n_data_points,mean_success_rate,median_success_rate,sem_success_rate,success_rate_ci95_lower,success_rate_ci95_upper,mean_success_slope,median_success_slope,sem_success_slope,success_slope_ci95_lower,success_slope_ci95_upper,mean_reaction_time_slope,median_reaction_time_slope,sem_reaction_time_slope,reaction_time_slope_ci95_lower,reaction_time_slope_ci95_upper
0,I,36,2304,0.771701,0.812500,0.023559,0.725525,0.817878,-0.015224,-0.041827,0.029803,-0.073638,0.043190,-0.184291,-0.133029,0.048648,-0.279641,-0.088940
1,M,36,2304,0.763889,0.804688,0.025438,0.714031,0.813747,0.002885,-0.027404,0.027297,-0.050618,0.056387,-0.185919,-0.081640,0.089464,-0.361268,-0.010571
2,P,36,2304,0.780382,0.789062,0.024931,0.731517,0.829247,0.025962,0.020192,0.024619,-0.022292,0.074215,-0.149023,-0.115537,0.040925,-0.229236,-0.068811
3,R,36,2304,0.776910,0.789062,0.024671,0.728555,0.825265,0.015865,-0.005769,0.028923,-0.040824,0.072555,-0.224309,-0.198085,0.057367,-0.336748,-0.111870

Success slope by stiffness

   comparison_value  n_subjects  n_trials  mean_success_rate  mean_success_slope  median_success_slope  sem_success_slope  success_slope_ci95_lower  success_slope_ci95_upper
0              25.0          36      1152           0.917535            0.011086              0.000000           0.022502                 -0.033019                  0.055191
1              40.0          36      1152           0.881944            0.006965              0.000000           0.040478                 -0.072372                  0.086302
2              55.0          36      1152           0.801215            0.022093             -0.000378           0.043741                 -0.063638                  0.107825
3              70.0          36      1152           0.660590           -0.004993              0.003610           0.055242                 -0.113267                  0.103280
4             100.0          36      1152           0.653646            0.074521              0.101867           0.056327                 -0.035880                  0.184921
5             115.0          36      1152           0.723090            0.026209              0.032706           0.052603                 -0.076892                  0.129311
6             130.0          36      1152           0.765625            0.036298              0.057542           0.048245                 -0.058263                  0.130859
7             145.0          36      1152           0.782118           -0.001183             -0.031187           0.046568                 -0.092457                  0.090090

Paired contrasts between finger time slopes

,contrast,metric,n_paired_subjects,mean_difference,median_difference,sem_difference,difference_ci95_lower,difference_ci95_upper,t_stat,p_value
0,I_minus_M,success_vs_within_finger_time_slope,36,-0.018109,-0.027404,0.034695,-0.086111,0.049893,-0.521947,0.604995
1,I_minus_P,success_vs_within_finger_time_slope,36,-0.041186,-0.029567,0.036853,-0.113418,0.031046,-1.117569,0.271364
2,I_minus_R,success_vs_within_finger_time_slope,36,-0.031090,-0.051202,0.040629,-0.110723,0.048543,-0.765207,0.449278
3,M_minus_P,success_vs_within_finger_time_slope,36,-0.023077,-0.041106,0.034712,-0.091113,0.044959,-0.664810,0.510529
4,M_minus_R,success_vs_within_finger_time_slope,36,-0.012981,0.028846,0.040185,-0.091744,0.065782,-0.323025,0.748599
5,P_minus_R,success_vs_within_finger_time_slope,36,0.010096,-0.033173,0.035236,-0.058967,0.079159,0.286529,0.776162

Paired contrasts between appearance-order success rates

               contrast        metric  n_paired_subjects  mean_difference  median_difference  sem_difference  difference_ci95_lower  difference_ci95_upper    t_stat   p_value
0  appearance_1_minus_2  success_rate                 36        -0.016927          -0.015625        0.009811              -0.036156               0.002302 -1.725355  0.093284
1  appearance_1_minus_3  success_rate                 36        -0.027778          -0.007812        0.012153              -0.051597              -0.003958 -2.285714  0.028440
2  appearance_1_minus_4  success_rate                 36        -0.013455          -0.023438        0.017343              -0.047447               0.020537 -0.775811  0.443072
3  appearance_2_minus_3  success_rate                 36        -0.010851           0.000000        0.009760              -0.029981               0.008279 -1.111731  0.273832
4  appearance_2_minus_4  success_rate                 36         0.003472           0.007812        0.012637              -0.021297               0.028241  0.274758  0.785117
5  appearance_3_minus_4  success_rate                 36         0.014323           0.015625        0.013386              -0.011913               0.040559  1.070002  0.291942

## 16. Article-inspired figures adapted to this experiment: skin stretch and XY probing

The eLife article includes perception panels (psychometric curves, PSE, JND) and force/trajectory-style panels. For this experiment, the relevant substitutions are:

- **No grip force:** use the recorded skin-stretch gain/condition in **mm/m** and a skin-stretch command proxy, not grip force.
- **Probing from center in the XY plane:** use `object_x, object_y` from `tracking.csv` relative to screen center `(320, 240)`.
- **Article-style perception:** keep psychometric curves, PSE, JND, subject lines, and group average/dotted summary styling.

Important distinction: `motor_response_analisys_servo` is a separate hardware check/calibration for motor command response. This psychophysics notebook keeps the main analysis on the experiment variables that participants experienced: skin-stretch mm/m, XY probing from center, time, success, and finger/order effects.

In [275]:
article_style_figure_paths, article_style_figure_manifest = pf.save_article_style_psychophysics_figures(
    OUTPUT_ROOT,
    combined_success_trials,
    psychometric_input_by_subject_finger,
    pse_jnd_by_subject_finger,
    finger_time_subject_summary,
    finger_appearance_order_summary,
    finger_by_appearance_order,
    preferred_subject=None,
    fig_dpi=FIG_DPI,
)
print(f"Saved {len(article_style_figure_paths)} article-style psychophysics figures")
display(article_style_figure_manifest)

Saved 8 article-style psychophysics figures

                                              figure selected_typical_subject                                 style_source
0  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
1  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
2  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
3  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
4  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
5  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
6  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted
7  c:\Users\user\BIO MEDICAL ROBOTICS Dropbox\Eli...                           Farajian_Nisky_eLife_52653_Figure_7_adapted

## 17. Saved output tree

The final cell writes the requested architecture under `RUN_OUTPUT_ROOT`:

- group/all outputs under `results/<DATA_SELECTION>/`, for example `results/L_E/`
- subject outputs as sibling folders, for example `results/L_E_1/`, `results/L_E_2/`, `results/L_E_3/`, ...

Subject folders contain only subject-meaningful plots. The group folder contains one all-level plot set under figures/all with individual subjects faded in the background where relevant.

## Psychometric fit conventions, PSE band-pass, and figure encodings

**Symmetric delta axis.** All psychometric curves use the signed difference `G_comparison - G_standard` on the x-axis, centred on 0 (comparison == standard) and drawn symmetric over the full tested range (delta -80..+80, i.e. comparison 5..165 around the standard 85).

**PSE band-pass (LPF + HPF) for the group analysis.** A per-subject/finger fit is included in the *group* analysis only when its PSE lies inside the reliable stimulus band **25..145** (delta +/-60). Out-of-band or un-estimated PSE fits are kept and still drawn as individual curves, but are flagged (`pse_in_valid_band`, `excluded_from_group_analysis`, `group_exclusion_reason`) and **excluded from every group-level aggregation/comparison** (`compute_experiment_group_comparisons`). JND is not band-filtered.

**Unreliable CIs.** Degenerate fits (e.g. railed lapse rate, near-flat slope) can produce PSE/JND bootstrap CIs that run far outside the tested range. On the individual curves these CIs are **clipped to the +/-80 axis and labelled "CI unreliable"** so the figure stays readable; the raw values remain in the saved tables.

**Workspace shading (group per-finger curves).** Background individual curves are shaded by workspace: **L workspace in a darker shade, N workspace in a lighter shade** (see legend).

**Pilot exclusion.** Pilot/protocol subjects (`*_P`, i.e. L_P/N_P) are pilot data, not experiment results, so they are excluded from every group-level fit (subject-pooled, per-finger, all-pooled) AND from the group-curve backgrounds; together with the band-pass-disqualified subjects they never enter the group analysis. They still appear as individual per-subject curves.

In [ ]:
# Group comparisons for the active (pooled) selection; reused by the main tree.
psychophysics_group_comparisons = pf.save_experiment_group_comparison_outputs(
    OUTPUT_ROOT,
    combined_success_trials,
    pse_jnd_by_subject_finger=pse_jnd_by_subject_finger,
    pse_jnd_subject_pooled=pse_jnd_subject_pooled,
)
motor_control_method_references = pf.motor_control_method_references()
pf.save_csv(motor_control_method_references, OUTPUT_ROOT, "motor_control_method_references.csv")


def _filter_to_group(frame, code):
    """Rows whose subject_id belongs to experiment-group ``code`` (e.g. 'L_E')."""
    if frame is None:
        return frame
    if frame.empty or "subject_id" not in frame.columns:
        return frame.iloc[0:0].copy()
    keep = frame["subject_id"].astype(str).map(lambda s: pf.subject_group_code(s) == code)
    return frame[keep].copy()


def _save_analysis_tree(out_root, selection, clean_sub, success_sub, flagged_sub, qc_sub,
                        psy_by_sf, fits_by_sf, aggs, group_comparisons):
    return pf.save_selected_analysis_tree(
        out_root,
        selection,
        clean=clean_sub,
        flagged=flagged_sub,
        success_trials=success_sub,
        qc_summary=qc_sub,
        psychometric_input_by_subject_finger=psy_by_sf,
        pse_jnd_by_subject_finger=fits_by_sf,
        psychometric_input_group_by_finger=aggs["psychometric_input_group_by_finger"],
        pse_jnd_group_by_finger=aggs["pse_jnd_group_by_finger"],
        psychometric_input_group_all_pooled=aggs["psychometric_input_group_all_pooled"],
        pse_jnd_group_all_pooled=aggs["pse_jnd_group_all_pooled"],
        order_effects_summary=aggs["order_effects_summary"],
        order_effects_binned=aggs["order_effects_binned"],
        success_time_fatigue=aggs["success_time_fatigue"],
        finger_time_appearance=aggs["finger_time_appearance"],
        psychophysics_group_comparisons=group_comparisons,
        fig_dpi=FIG_DPI,
    )


# For the combined L_N_E cohort, also emit a full standalone group analysis for
# each sub-cohort (L_E, N_E) as sibling folders -- identical to running each on
# its own -- in addition to the pooled L_N_E tree written below.
_subgroup_trees = []
if pf.normalize_data_selection(DATA_SELECTION) == "L_N_E":
    for _code in pf.GROUP_SELECTIONS["L_N_E"]:  # ("L_E", "N_E")
        _clean_sub = _filter_to_group(combined_clean_trials, _code)
        if _clean_sub.empty:
            print(f"No {_code} subjects in this run; skipping {_code} tree.")
            continue
        _success_sub = _filter_to_group(combined_success_trials, _code)
        _flagged_sub = _filter_to_group(combined_flagged_trials, _code)
        _psy_sub = _filter_to_group(psychometric_input_by_subject_finger, _code)
        _fits_sub = _filter_to_group(pse_jnd_by_subject_finger, _code)
        _qc_sub = pf.make_qc_summary(_clean_sub, _flagged_sub)
        _aggs = pf.compute_psychophysics_group_aggregates(
            _clean_sub, _success_sub, _psy_sub, _fits_sub, psignifit_available=PSIGNIFIT_AVAILABLE
        )
        _work = OUTPUT_BASE / f"_working_{_code}"
        pf.reset_output_root(_work)
        _grp_cmp = pf.save_experiment_group_comparison_outputs(
            _work,
            _success_sub,
            pse_jnd_by_subject_finger=_fits_sub,
            pse_jnd_subject_pooled=_aggs["pse_jnd_subject_pooled"],
        )
        _out = OUTPUT_BASE / _code
        pf.reset_output_root(_out)
        _save_analysis_tree(_out, _code, _clean_sub, _success_sub, _flagged_sub, _qc_sub,
                            _psy_sub, _fits_sub, _aggs, _grp_cmp)
        try:
            pf._rmtree_windows_retry(_work)
        except OSError:
            pass
        _subgroup_trees.append(_out)
        print(f"Saved standalone sub-cohort tree: {_out}")

# Main (pooled) tree for the active selection. For L_N_E this is the combined
# L_E + N_E pooled analysis; for any other selection it is the only tree.
analysis_tree_manifest = pf.save_selected_analysis_tree(
    RUN_OUTPUT_ROOT,
    DATA_SELECTION,
    clean=combined_clean_trials,
    flagged=combined_flagged_trials,
    success_trials=combined_success_trials,
    qc_summary=qc_summary,
    psychometric_input_by_subject_finger=psychometric_input_by_subject_finger,
    pse_jnd_by_subject_finger=pse_jnd_by_subject_finger,
    psychometric_input_group_by_finger=psychometric_input_group_by_finger,
    pse_jnd_group_by_finger=pse_jnd_group_by_finger,
    psychometric_input_group_all_pooled=psychometric_input_group_all_pooled,
    pse_jnd_group_all_pooled=pse_jnd_group_all_pooled,
    order_effects_summary=order_effects_summary,
    order_effects_binned=order_effects_binned,
    success_time_fatigue=success_time_fatigue,
    finger_time_appearance=finger_time_appearance,
    psychophysics_group_comparisons=psychophysics_group_comparisons,
    fig_dpi=FIG_DPI,
    write_subjects=not bool(_subgroup_trees),
)

print(f"Saved requested output tree for {DATA_SELECTION}: {RUN_OUTPUT_ROOT}")
if _subgroup_trees:
    print("Sub-cohort trees:", _subgroup_trees)
print("Group figures:", RUN_OUTPUT_ROOT / "figures")
print("Group CSVs:", RUN_OUTPUT_ROOT / "csv")
print("Subject folders:", [OUTPUT_BASE / pf.sanitize_name(s) for s in selected_subject_ids])
print("Tree manifest:", RUN_OUTPUT_ROOT / "analysis_tree_manifest.csv")
display(analysis_tree_manifest.head(80))

print("N_E / L_E / L_P / N_P psychophysics group summary where available")
for key in [
    "psychophysics_trial_group_metric_summary",
    "psychophysics_protocol_group_metric_summary",
    "psychophysics_analysis_scope_metric_summary",
]:
    if key in psychophysics_group_comparisons and not psychophysics_group_comparisons[key].empty:
        print(key)
        display(psychophysics_group_comparisons[key].head(80))

print("Motor-control / psychophysics method references saved for later citation")
display(motor_control_method_references[["citation_key", "year", "title", "doi", "analysis_use"]])

working_manifest = pf.analysis_manifest(OUTPUT_ROOT)
display(working_manifest)

if not KEEP_WORKING_OUTPUTS and OUTPUT_ROOT.exists():
    # Robust removal: the intermediate scratch folder can hold a transient
    # Windows/Dropbox file lock. Retry, and never fail the run over scratch.
    try:
        pf._rmtree_windows_retry(OUTPUT_ROOT)
        print("Removed intermediate working folder:", OUTPUT_ROOT)
    except OSError as exc:
        print("Left intermediate working folder in place (locked):", OUTPUT_ROOT, "->", exc)

## Interpretation notes

- `PSE` is the physical comparison value where `P(response_comparison_greater) = 0.5`.
- `JND = (x75 - x25) / 2`, in the same units as the stimulus values.
- `farajian_style_input_by_subject_finger.csv` mirrors the Farajian/Nisky perception scripts: stimulus difference, number of comparison-stiffer responses, and total repetitions.
- `correct_response` is the success variable: 1 means the physically stiffer stimulus was selected, 0 means it was not.
- `success_vs_order_slope > 0` suggests improvement/learning over the session; `< 0` suggests possible fatigue or decline. Treat this as a proxy because no direct subjective tiredness rating is present in `answers.csv`.
- `success_vs_reaction_time_slope` and `success_by_reaction_time_bin.csv` show whether longer answer duration is associated with better or worse success.
- `finger_time_group_bins.csv` compares success across normalized time within each finger, enabling direct index/middle/ring/pinky time-course comparison.
- `finger_appearance_order_summary.csv` compares the 1st/2nd/3rd/4th finger encountered in a participant session, which tests whether finger appearance/order itself matters.
- `finger_order_matrix.csv` records which anatomical finger appeared in each order position for every participant.
- Review `fit_warning`, `qc_warnings`, `combined_flagged_trials.csv`, and the per-subject trend tables before interpreting results.
- `motor_response_analisys_servo` is treated as a separate hardware calibration/check, not mixed into the main psychophysics variables.
- Rows excluded from fitting are preserved for audit; no raw data files are modified.

- All psychophysics group outputs now include the requested scopes when available: protocol/group (`N_E`, `L_E`, `L_P`, broad `N/L/P/E`, and all participants), participant, finger, stiffness/comparison value, success/failure, sex, age group, and workspace (`N` 40x50 cm; `L` 60x60 cm).
- `comparison_over_standard`, `signed_delta_over_standard`, and `abs_delta_over_standard` normalize analog stiffness values to the trial standard while preserving original values; workspace columns document the original physical space and do not alter stimulus units.
- Scope-summary plots use faded raw/background values plus the summary bar/point so every value remains transparent behind the group statistic.
- `psychophysics_factor_statistics.csv` is an ANOVA-style screening table. For binary repeated 2AFC trials, treat it as descriptive evidence; for manuscript-level inference prefer planned psychometric model comparisons or mixed/repeated-measures models with participant as a repeated/random factor.
- `motor_control_method_references.csv` lists the motor-control and haptic psychophysics articles used to guide the analysis additions and citation trail.